### ISSUE TITLE
Exposing two internal functions

### ISSUE THREAD

**Issue by andrewthad** [yesodweb/yesod#1002]
Could the functions `subHelper` and `stripHandlerT` be exposed? I occasionally build subsites without using yesod's routing TH (to get non-monomorphic routes), and I have copied these functions out into my project because they're so dang helpful for this. My current solution works fine, but I think that it would be nice to not have duplicated code in my project.

**Comment by snoyberg** [comment]
Yes, I'm good with that. Can you send a PR?

**Comment by andrewthad** [comment]
https://github.com/yesodweb/yesod/pull/1003

**Comment by andrewthad** [comment]
The PR is ready
