### ISSUE TITLE
Scaffolding uses deprecated getAuthId

### ISSUE THREAD

**Issue by pseudonom** [yesodweb/yesod#1009]
`yesod init` with `yesod-bin 1.4.9.2` produces scaffolding which defines `getAuthId`. The [documentation](http://haddock.stackage.org/nightly-2015-06-09/yesod-auth-1.4.5/Yesod-Auth.html#v:getAuthId) indicates that this is deprecated.

**Comment by snoyberg** [comment]
This should be an easy fix in the scaffolding. Interested in sending a PR?

**Comment by pseudonom** [comment]
Sure.
