### ISSUE TITLE
Generalize `runDb` type signature

### ISSUE THREAD

**Issue by pseudonom** [yesodweb/yesod#1010]
I have an API subsite which is an instance of `YesodPersist` (the master site is not). When I try to use `runDB` in a subsite handler I get the error:

```
Expected type: HandlerT API (HandlerT master IO) (Key Foo)
  Actual type: HandlerT API IO (Key Foo)
```
.

The only solution I've found is to replace (`YesodDB` type synonym expanded for symmetry):
```haskell
runDB :: ReaderT (YesodPersistBackend site) (HandlerT site IO) a -> HandlerT site IO a 
```
with
```haskell
runDB :: (MonadResourceBase m) => 
         ReaderT (YesodPersistBackend site) (HandlerT site m) a -> HandlerT site m a
```

**Comment by snoyberg** [comment]
It sounds like you just need to use a custom function in your subsite instead of using the `YesodPersist` typeclass. Is there a reason that won't work?

**Comment by pseudonom** [comment]
Yes, it does work; it's what I'm doing. Is there a reason not to generalize the type class signature? Just trying to maintain simplicity?

**Comment by snoyberg** [comment]
Correct, a generalization would make error messages more confusing for the
common case.

**Comment by pseudonom** [comment]
Okay, thanks.
