### ISSUE TITLE
Support for stack in yesod-bin

### ISSUE THREAD

**Issue by drwebb** [yesodweb/yesod#1015]
I've been hacking on porting yesod-bin to use use stack instead of cabal, and getting stuck pretty early on. Currently `cabal configure` is called in order to specify the wrapped GHC version. 

https://github.com/drwebb/yesod/commit/af0ec46476937a71a8765261d6f7dbc892529301

It would be nice to have this feature in my yesod projects, so I'm asking for any thoughts on implementation.

**Comment by snoyberg** [comment]
There's work ongoing for a GSoC for the yesod-devel replacement, which will hopefully not be shackled to cabal. It's probably not worth trying to fix yesod-bin right now.

**Comment by drwebb** [comment]
Alright, when I first looked over at the code it looked a lot easier than it actually probably is. Closing the request.
