### ISSUE TITLE
stack exec -- yesod devel

### ISSUE THREAD

**Issue by legrostdg** [yesodweb/yesod#1018]
Not sure if the issue is in yesod-bin or in stack, but after building a yesod based project and installing yesod-bin with stack, I can't run "yesod devel":

    $ stack exec -- yesod devel
    Yesod devel server. Press ENTER to quit
    Application can be accessed at:
    
    http://127.0.0.1:3000
    https://127.0.0.1:3443
    If you wish to test https capabilities, you should set the following variable:
      export APPROOT=https://127.0.0.1:3443
    
    cabal: Use of GHC's environment variable GHC_PACKAGE_PATH is incompatible with
    Cabal. Use the flag --package-db to specify a package database (it can be used
    multiple times).

**Comment by snoyberg** [comment]
It's a problem in Cabal, in that it won't recognize the `GHC_PACKAGE_PATH` environment variable, and yesod devel which uses cabal. The proper solution will be to move yesod devel off of cabal, which will hopefully be part of the current GSoC project to move over to ide-backend. In the meanwhile, unfortunately yesod devel is not compatible with stack, at least not directly as we'd like.

**Comment by legrostdg** [comment]
Is there a workaround? I noticed the same problem with propellor https://propellor.branchable.com, which I guess won't be updated to ide-backend...

https://github.com/haskell/cabal/pull/2270 may be a fix?

**Comment by snoyberg** [comment]
It depends on what you mean by "workaround." You can use `env` to disable the GHC_PACKAGE_PATH environment variable (and we can provide a flag to `exec` to automate that). But in the case of yesod devel, that will mean you end up not having the packages in scope.

Another possibility would be to tweak `yesod devel` to parse GHC_PACKAGE_PATH, turn it into command line parameters for cabal, and unset the environment variable. Which presumably is what cabal should be doing anyway. propellor could do the same thing.

**Comment by legrostdg** [comment]
closed by a7cccf2a7c5df8b26da9ea4fdcb6bac5ab3a3b75
Thanks!

**Comment by snoyberg** [comment]
You're fast, the blog post isn't even out yet!

**Comment by geraldus** [comment]
Oh, cool, thanks!  Now I can use `stack` (:

**Comment by legrostdg** [comment]
@snoyberg you are the fast one!

I just updated my yesod git clone by chance and noticed the latest commit :).

**Comment by tfiala** [comment]
I seem to be hitting this issue with 'stack exec -- yesod test':

```
stack exec -- yesod test
cabal: Use of GHC's environment variable GHC_PACKAGE_PATH is incompatible with
Cabal. Use the flag --package-db to specify a package database (it can be used
multiple times).
```

I've got ```stack exec -- yesod devel``` working just fine.  Is this likely the same instance of the problem solved here for the devel command?

**Comment by snoyberg** [comment]
I wouldn't bother using `yesod test` with stack, just use `stack test`.

**Comment by tfiala** [comment]
Ah, thanks!  I am new to both Haskell and stack, and didn't even know 'stack test' was an option.  I'm just getting started with the 2nd ed book and it pointed to stack.
