### ISSUE TITLE
add how to install with stack to README.md, and other docs.

### ISSUE THREAD

**Issue by danthedeckie** [yesodweb/yesod#1021]
Given that stack is getting quite a lot of press right now, and many people are recommending getting started with haskell now that cabal-hell is supposedly dying, and that yesod is the best known and strongest web framework/system for haskell, it'd be really great if there was a very simple getting started "how should your stack.yaml file look like to get going with the example code in our tutorials" section.

In the **Installation and isolation** section, which version of yesod should the *extra-deps:* be there? Or should one use yesod-bin?  Are there other packages I need to add?

**Comment by snoyberg** [comment]
The problem right now is that `yesod devel` still requires cabal, though we're planning on getting away from that ASAP. The future of yesod is definitely with stack, we just need to get the devel server issue sorted out first.

I'd happily accept a PR that explains this.

**Comment by snoyberg** [comment]
This should be ready soon based on the new stack support in yesod devel. After some testing time for the community, I'm going to update the docs (likely next Sunday).

**Comment by cdepillabout** [comment]
This would be great!

**Comment by snoyberg** [comment]
I've updated the content on yesodweb.com and the README. The website is having trouble refreshing right now, but the new content can be viewed on the Github repo until then.
