### ISSUE TITLE
typo: applyng

### ISSUE THREAD

**Issue by agreif** [yesodweb/yesod#1024]
Hi,

here is a small typo "applyng" should be "applying"
all occurrences are found with:
https://github.com/yesodweb/yesod/search?utf8=%E2%9C%93&q=applyng

Alex.

**Comment by creichert** [comment]
`hsfiles/` contains auto-generated code from the yesod/yesod-scaffold. If you're up for it, you can submit pull requests for the typos (which would be preferred over issues).

**Comment by agreif** [comment]
created a pull request.

ALex.
