### ISSUE TITLE
typo: authenitcation

### ISSUE THREAD

**Issue by agreif** [yesodweb/yesod#1025]
Hi,
here is another typo:
https://github.com/yesodweb/yesod/search?utf8=%E2%9C%93&q=authenitcation

please make a comment if I should stop reporting obvious typos.
I find them by occasion while reading the generated code.

thanks,
ALex.

**Comment by creichert** [comment]
@agreif you should fix them if you can. You can even edit the code in the github interface. Any typos in hsfiles should be fixed on the postgres branch of the scaffold:

https://github.com/yesodweb/yesod-scaffold/tree/postgres

**Comment by creichert** [comment]
Fixing typos and requesting to have typos fixed is perfectly okay in my book. It helps improve the overall quality of the project and helps newcomers to this code base become acquainted.

**Comment by agreif** [comment]
and it proves that newcomers are really reading comments, thus they are valuable :)

**Comment by agreif** [comment]
typo already fixed in postgres branch
issue can be closed.

ALex.
