### ISSUE TITLE
Even better logging of SQL messages

### ISSUE THREAD

**Issue by andrewthad** [yesodweb/yesod#1026]
I have, on a previous occassion, opened a thread about [better logging of SQL](https://github.com/yesodweb/yesod/issues/939) in yesod. But, I just thought of a way to make it even better. Right now, the messages look like this:

    [Debug#SQL] SELECT "id", "vacation", "office365_user", "completed" FROM "office365_calendar_queue_job" WHERE ("completed"=?); [PersistBool False] @(<unknown>:<unknown> <unknown>:0:0)

Cool, sort of. In a suggestion I made to [ditch the source location](https://github.com/yesodweb/yesod/issues/939#issuecomment-75793415), I failed to realize that `logDebugN` uses the awful-looking `<unknown>` string and `0` line, which is annoying to see appended to the end of every line. What I want to see instead is this:

    [Debug#SQL] SELECT "id", "vacation", "office365_user", "completed" FROM "office365_calendar_queue_job" WHERE ("completed"=?); [PersistBool False]

Notice how there isn't any trailing garbage. My thought is that I can just change `defaultMessageLoggerSource` to target messages that are from source `"SQL"` and then **not** display the extra stuff at the end for those messages. I will end up needing to change `formatLogMessage` as well (but that should be fine because it isn't exported). Basically, what I want to ask is: Does this seem agreeable? If so, I can do it and put up a PR.

**Comment by gregwebs** [comment]
That seems like an obvious improvement to me. But implementation-wise it would be better to not look at the log level but instead to look at whether or not there is actually location information.

**Comment by andrewthad** [comment]
Unfortunately, `monadLoggerLog` expects a `Loc`, not a `Maybe Loc`, and `Loc` looks like this:

    data Loc
      = Loc { loc_filename :: String
      , loc_package  :: String
      , loc_module   :: String
      , loc_start    :: CharPos
      , loc_end      :: CharPos }

So, there is no where to concretely say "This information does not exist". I wish that this situation were different, but changing anything there would definitely not be worth it. So, I'll interpret your suggestion to mean "check to see if `loc_filename` is `"<unknown>"`, which could be a better approach. Seems a little hacky though.

**Comment by andrewthad** [comment]
@gregwebs Also, just to clarify, my suggestion is to examine `LogSource` to make the decision, not `LogLevel`:

    messageLoggerSource :: site
                        -> Logger
                        -> Loc -- ^ position in source code
                        -> LogSource
                        -> LogLevel
                        -> LogStr -- ^ message
                        -> IO ()

**Comment by gregwebs** [comment]
yes, the hacky approach, or changing the type to a Maybe would be preferable over analyzing the source. Persistent probably should be including line numbers and probably isn't just to avoid a template-haskell dependency.

**Comment by andrewthad** [comment]
It originally did include line numbers. At my suggestion, Michael [got rid of them](https://github.com/yesodweb/yesod/issues/939#issuecomment-75793415) because it doesn't make  sense to have every SQL log to tell users about the same line in `persistent`. I'll wait a few days to see if there's any other feedback, and then I'll proceed with the approach that uses `loc_filename`. Thanks for your feedback.

**Comment by snoyberg** [comment]
Go for the hacky approach. There's 0 benefit to including the location information in the log, since it's the location information inside the persistent library, not your own code.

**Comment by andrewthad** [comment]
Ah, just who I was waiting for.

**Comment by snoyberg** [comment]
Heh, I forgot that @andrewthad kicked that off in the first place ;)

**Comment by snoyberg** [comment]
(Ssh... I'm not really here)

**Comment by andrewthad** [comment]
PR is up. https://github.com/yesodweb/yesod/pull/1027

**Comment by snoyberg** [comment]
PR is merged, closing. Thanks!
