### ISSUE TITLE
Unable to run yesod devel with stack

### ISSUE THREAD

**Issue by reneklacan** [yesodweb/yesod#1028]
Hi,

Sorry for asking such a basic question, I was googling and found this https://github.com/commercialhaskell/stack/issues/153 for example but wasn't able to solve my problem anyway.

I have fresh install of stack and eveything is working great except `yesod devel`

First thing I tried to run `stack exec yesod -- devel` but I got

```
yesod: cabal: createProcess: runInteractiveProcess: exec: does not exist (No such file or directory)
```

I tried `stack install yesod` to install it globally and do `yesod devel` but got same error.

So I installed cabal by running `stack install cabal-install`

Then when I tried to run `yesod devel` I got

```
Resolving dependencies...
Configuring cars-0.0.0...
cabal: At least the following dependencies are missing:
aeson >=0.6 && <0.9,
classy-prelude >=0.10.2,
... (list of all packages)
```

Even tried to run `cabal install --enable-tests . --max-backjumps=-1 --reorder-goals` but it didn't change anything...

I am running out of ideas so can you give me any hint how to solve it because workflow "stack build" and "stack exec some_yesod_app" after every change is killing me.

Thanks

Rene

**Comment by snoyberg** [comment]
Can you try the instructions at
http://www.yesodweb.com/blog/2015/06/stack-support-yesod-devel ?

**Comment by reneklacan** [comment]
Thanks for blazingly fast answer, going to try it immediately

**Comment by reneklacan** [comment]
After running `stack exec yesod -- devel` I got error:

```
cabal: Use of GHC's environment variable GHC_PACKAGE_PATH is incompatible with
Cabal. Use the flag --package-db to specify a package database (it can be used
multiple times).
```

My env:

```
➜  stack --version
Version 0.1.1.0, Git revision 91fe70306f51eb3d68667a0d6e09a7d7ebbeb2b6

➜  cabal --version
cabal-install version 1.18.1.0
using version 1.18.1.5 of the Cabal library

➜  cat ~/.stack/global/stack.yaml
flags: {}
packages: []
extra-deps:
- hfsevents-0.1.5
resolver: lts-2.16
```

**Comment by snoyberg** [comment]
This is a feature in the newest yesod-bin. Did you install the newest version as per the blog post (`stack build yesod-bin-1.4.11`)? What's the output of `stack exec -- yesod --version`?

**Comment by reneklacan** [comment]
You are right. Sorry, Thank you very much. You are my hero! Have a nice evening!

**Comment by snoyberg** [comment]
Afternoon actually, I'm in California as of yesterday ;)

**Comment by reneklacan** [comment]
Have a nice afternoon then :D

**Comment by bitemyapp** [comment]
I'm getting this error, but I have version `1.4.17.1` in my snapshot. Any idea what might be doing on?

Also weirdly, this isn't working:

```
$ stack exec -- yesod --version
Invalid option `--version'
```

**Comment by MaxGabriel** [comment]
Needs to be `yesod version`
```
Max@maximilians-mbp ~/D/i/i/Heyzap> yesod version
yesod-bin version: 1.4.17.1
```

**Comment by bitemyapp** [comment]
@MaxGabriel well, same issue remains.

**Comment by snoyberg** [comment]
Just to confirm the report, you're saying you get the exact same `createProcess` error message reported above?

```
yesod: cabal: createProcess: runInteractiveProcess: exec: does not exist (No such file or directory)
```

**Comment by mrkkrp** [comment]
I'm running into the same issue now. @bitemyapp, how did you resolve this?

**Comment by mrkkrp** [comment]
For others: you need to install `cabal`, these days I use stack and forgot about Cabal.

**Comment by RobertFischer** [comment]
I am getting this in a brand new `yesod-simple` project.

```
robert@rcf-dell:~/wkdir/blogging$ ./script/server 
++ dirname ./script/server
+ HEREDIR=./script
+ cd ./script/..
+ stack build yesod-bin
+ export APPROOT=https://localhost:3443
+ APPROOT=https://localhost:3443
+ stack exec -- yesod devel
Yesod devel server. Type 'quit' to quit
Application can be accessed at:

http://localhost:3000
https://localhost:3443
If you wish to test https capabilities, you should set the following variable:
  export APPROOT=https://localhost:3443

yesod: cabal: createProcess: runInteractiveProcess: exec: does not exist (No such file or directory)
robert@rcf-dell:~/wkdir/blogging$ stack exec yesod version
yesod-bin version: 1.4.18.7
```

If I visit `localhost:3000`, it just keeps saying that my application hasn't been built and refreshing.

**Comment by snoyberg** [comment]
Looks like @mrkkrp's comment applies (need to install cabal). However, if you modify your `stack.yaml` to include:

```
extra-deps:
- yesod-bin-1.5.1
```

Then `stack build yesod-bin` and `stack exec -- yesod devel` will use the newer devel server that does not depend on cabal, and overall works more reliably. See: http://www.yesodweb.com/blog/2016/11/new-yesod-devel-server

**Comment by RobertFischer** [comment]
@snoyberg -- I very much appreciate the quick response. Loving Yesod overall, BTW. After years of being stuck in Java/JS in a web world dominated by Ruby, Yesod is a breath of fresh air.

For the record, I also had to add these to my `extra-deps` list in `stack.yaml`:
```
- say-0.1.0.0
- typed-process-0.1.0.0
```
(But the error message was very helpful in pointing that out.)

If you want to replicate the original problem, the following commands (taken from `history`) do it reliably:
```
 2182  mkdir ~/tmp
 2183  cd ~/tmp/
 2185  stack new demo yesod-simple
 2187  cd ./demo/
 2189  stack setup
 2190  stack install yesod-bin
 2193  stack exec -- yesod devel
```

**Comment by snoyberg** [comment]
Cool, glad it's working. I've slated yesod-bin-1.5.1 to be included in the
next LTS releases so that all of this will happen automatically in the
future.

**Comment by tdimiduk** [comment]
I'm getting this error with yesod-bin-1.5.1 (lts-8.0), fresh scaffolded yesod-sqlite. 

$ stack exec -- yesod version                                                                                                                 
yesod-bin version: 1.5.1

$ stack exec -- yesod devel
Yesod devel server. Enter 'quit' or hit Ctrl-C to quit.
Application can be accessed at:

http://localhost:3000
https://localhost:3443
If you wish to test https capabilities, you should set the following variable:
  export APPROOT=https://localhost:3443

yesod: stack: startProcess: runInteractiveProcess: exec: does not exist (No such file or directory)

---
I have also installed yesod-bin through nix (I am running NixOS), and that version will run, but gives me the application hasn't been built page

$ yesod version
yesod-bin version: 1.5.1

**Comment by vandenoever** [comment]
I have the same issues as @tdimiduk.
```bash
$ stack exec -- yesod version
yesod-bin version: 1.5.2.2
$ stack --nix exec -- yesod devel
Yesod devel server. Enter 'quit' or hit Ctrl-C to quit.
Application can be accessed at:

http://localhost:3000
https://localhost:3443
If you wish to test https capabilities, you should set the following variable:
  export APPROOT=https://localhost:3443

yesod: stack: startProcess: runInteractiveProcess: exec: does not exist (No such file or directory)
```

So stack does not find stack.  strace shows that stack looks for stack in many places but not in the `PATH` directories.

**Comment by vandenoever** [comment]
Here's a line from `strace` that shows the problem. There are about 20 of these lines where stack looks for stack in different places:
```
[pid 24492] execve("/nix/store/5cpnwwnasypdi7p0av6qbaf52y99gmdz-xz-5.2.2-bin/bin/stack", ["stack", "build", "--fast", "--file-watch", "my-project:lib", "--exec", "/home/oever/.stack/snapshots/x86"..., "--flag", "my-project:dev", "--flag", "my-project:library-only"], [/* 52 vars */]) = -1 ENOENT (No such file or directory)
```

**Comment by vandenoever** [comment]
Here is a workaround:
```bash
cp $(type -P stack) .stack-work/install/x86_64-linux-nix/lts-8.8/8.0.2/bin/
```
Now `stack exec -- yesod devel` runs fine with the workaround.

**Comment by tdimiduk** [comment]
Thanks, that workaround does solve the problem for me for now.

**Comment by mmzx** [comment]
After suggestion from @vandenoever, yesod devel works.
Some details: ./.stack-work/install/x86_64-linux-nix/lts-10.5/8.2.2/bin/ .

**Comment by adparker** [comment]
Just FYI, I ran into this problem too, as posted by @vandenoever, and their solution fixed it:  copying `stack` to `.stack-work/...`.  I'm on `yesod` version `1.6.0.3`. 

Should we reopen this issue, as I'm sure others are still running into it.
