### ISSUE TITLE
Can't compile yesod-websockets examples.

### ISSUE THREAD

**Issue by Elektroingenieur** [yesodweb/yesod#1031]
My versions:

     ghc 7.8.3
     wai-websockets-3.0.0.6
     websockets-0.9.5.0
     websockets-snap-0.9.2.0
     yesod-websockets-0.2.1.1

### /yesod/yesod-websockets/chat.hs    
    chat.hs:27:22:
    Couldn't match type ‘HandlerSite
                           (ReaderT
                              Network.WebSockets.Connection.Connection (HandlerT App IO))’
                  with ‘App’
    Expected type: ReaderT
                     Network.WebSockets.Connection.Connection (HandlerT App IO) App
      Actual type: ReaderT
                     Network.WebSockets.Connection.Connection
                     (HandlerT App IO)
                     (HandlerSite
                        (ReaderT
                           Network.WebSockets.Connection.Connection (HandlerT App IO)))
    In a stmt of a 'do' block: App writeChan <- getYesod
    In the expression:
      do { sendTextData
             ("Welcome to the chat server, please enter your name." :: Text);
           name <- receiveData;
           sendTextData $ "Welcome, " <> name;
           App writeChan <- getYesod;
           .... }
    Failed, modules loaded: Yesod.WebSockets.

### /yesod/yesod-websockets/sample.hs  
    sample.hs:15:1:
    Couldn't match type ‘[Char]’
                  with ‘Data.ByteString.Internal.ByteString’
    Expected type: Network.HTTP.Types.Method.Method
      Actual type: [Char]
    In the pattern: "GET"
    In a case alternative:
        "GET"
          -> yesodRunner getHomeR env6378_ag3S (Just HomeR) req6378_ag3T
    In the expression:
      case Network.Wai.Internal.requestMethod req6378_ag3T of {
        "GET"
          -> yesodRunner getHomeR env6378_ag3S (Just HomeR) req6378_ag3T
        _ -> yesodRunner
               (badMethod >> (return ())) env6378_ag3S (Just HomeR) req6378_ag3T }
    Failed, modules loaded: Yesod.WebSockets.

### /yesod/yesod-websockets/chat-with-timeout-control.hs
    chat-with-timeout-control.hs:27:22:
    Couldn't match type ‘HandlerSite
                           (ReaderT Network.WebSockets.Connection.Connection Handler)’
                  with ‘App’
    Expected type: ReaderT
                     Network.WebSockets.Connection.Connection Handler App
      Actual type: ReaderT
                     Network.WebSockets.Connection.Connection
                     Handler
                     (HandlerSite
                        (ReaderT Network.WebSockets.Connection.Connection Handler))
    In a stmt of a 'do' block: App writeChan <- getYesod
    In the expression:
      do { sendTextData
             ("Welcome to the chat server, please enter your name." :: Text);
           name <- receiveData;
           sendTextData $ "Welcome, " <> name;
           App writeChan <- getYesod;
           .... }
    Failed, modules loaded: Yesod.WebSockets.

**Comment by Elektroingenieur** [comment]
My versions:

     ghc 7.8.3
     wai-websockets-3.0.0.6
     websockets-0.9.5.0
     websockets-snap-0.9.2.0
     yesod-websockets-0.2.1.1

**Comment by gregwebs** [comment]
These are probably out of sync with recent changes. Would be great if you can make some updates

**Comment by creichert** [comment]
I'm pushing an update for `sample.hs` but I can't reproduce the issue in
`chat.hs` yet.

**Comment by creichert** [comment]
What version of yesod-core do you have installed?

With the same configuration, I am able to load all the modules:

```
$ ghc-pkg -V
GHC package manager version 7.8.3

$ cabal exec -- ghc-pkg list | grep websockets
    wai-websockets-3.0.0.6
    websockets-0.9.5.0
    yesod-websockets-0.2.1.1


$ cabal repl
Prelude> :l chat-with-timeout-control.hs 
[1 of 2] Compiling Yesod.WebSockets ( Yesod/WebSockets.hs, interpreted )
[2 of 2] Compiling Main             ( chat-with-timeout-control.hs, interpreted )
Ok, modules loaded: Yesod.WebSockets, Main.
Prelude> :l chat.hs
[1 of 2] Compiling Yesod.WebSockets ( Yesod/WebSockets.hs, interpreted )
[2 of 2] Compiling Main             ( chat.hs, interpreted )
Ok, modules loaded: Yesod.WebSockets, Main.
Prelude> :l sample.hs 
[1 of 2] Compiling Yesod.WebSockets ( Yesod/WebSockets.hs, interpreted )
[2 of 2] Compiling Main             ( sample.hs, interpreted )
Ok, modules loaded: Yesod.WebSockets, Main.
```

**Comment by creichert** [comment]
What version of `yesod-core` do you have installed?

With the same configuration, I am able to load all the modules:

```
$ ghc-pkg -V
GHC package manager version 7.8.3

$ cabal exec -- ghc-pkg list | grep websockets
    wai-websockets-3.0.0.6
    websockets-0.9.5.0
    yesod-websockets-0.2.1.1


$ cabal repl
Prelude> :l chat-with-timeout-control.hs 
[1 of 2] Compiling Yesod.WebSockets ( Yesod/WebSockets.hs, interpreted )
[2 of 2] Compiling Main             ( chat-with-timeout-control.hs, interpreted )
Ok, modules loaded: Yesod.WebSockets, Main.
Prelude> :l chat.hs
[1 of 2] Compiling Yesod.WebSockets ( Yesod/WebSockets.hs, interpreted )
[2 of 2] Compiling Main             ( chat.hs, interpreted )
Ok, modules loaded: Yesod.WebSockets, Main.
Prelude> :l sample.hs 
[1 of 2] Compiling Yesod.WebSockets ( Yesod/WebSockets.hs, interpreted )
[2 of 2] Compiling Main             ( sample.hs, interpreted )
Ok, modules loaded: Yesod.WebSockets, Main.
```

**Comment by Elektroingenieur** [comment]
Sorry for the late reply. I have reinstalled all packages using 'stack' and successfuly compiled all 3 examples. When run, however, sample.hs produces an error when I click `send another message` button.

    # stack runghc sample.hs 
    18/Jul/2015:01:50:51 +0800 [Info#yesod-core] Application launched @(yesod-core-1.4.12:Yesod.Core.Dispatch ./Yesod/Core/Dispatch.hs:148:11)
    127.0.0.1 - - [18/Jul/2015:01:52:59 +0800] "GET / HTTP/1.1" 200 - "" "Mozilla/5.0 (X11; Linux x86_64; rv:31.0) Gecko/20100101 Firefox/31.0 Iceweasel/31.4.0"
    127.0.0.1 - - [18/Jul/2015:01:52:59 +0800] "GET / HTTP/1.1" 500 - "" "Mozilla/5.0 (X11; Linux x86_64; rv:31.0) Gecko/20100101 Firefox/31.0 Iceweasel/31.4.0"

    18/Jul/2015:01:52:59 +0800 [Error#yesod-core] Exception from Warp: CloseRequest 1001 "" @(yesod-core-1.4.12:Yesod.Core.Dispatch ./Yesod/Core/Dispatch.hs:175:23)

My versions:

    # stack exec -- ghc-pkg list | grep websockets
    wai-websockets-3.0.0.6
    websockets-0.9.5.0
    yesod-websockets-0.2.1.1

    # stack exec -- ghc-pkg list | grep yesod
    yesod-core-1.4.12
    yesod-websockets-0.2.1.1

**Comment by Elektroingenieur** [comment]
I suspect something's wrong about `toWidget [julius| .... |]`
I changed it with this debug code, The browser doesnt hangs.

        toWidget
            [julius|
              var url = document.URL,
                  conn;
              url = url.replace("http:", "ws:").replace("https:", "wss:");
              conn = new WebSocket(url);

              conn.onmessage = function(e) {
                console.log(e.data);
              };
           |]

As long as the issue is not on the server side. I consider this issue fixed.

**Comment by creichert** [comment]
At a glance, I'm not exactly sure what the issue is but if you figure out the exact cause feel free to put in a PR on the example code. Thanks!
