### ISSUE TITLE
Enable stack with "yesod keter"

### ISSUE THREAD

**Issue by chreekat** [yesodweb/yesod#1039]
Starting a ticket to discuss implementation. There is more than one way to do this. What does everyone prefer?

1. Clobber all cabal-install support: Use the Stack, Luke
2. Make stack another option alongside [--dev|-d]
3. Make stack the *default*, with fallback options for cabal/-dev
4. Others?

**Comment by chreekat** [comment]
I'm going to start working on implementing 3 by way of implementing 1.

**Comment by snoyberg** [comment]
How about: if stack.yaml exists, use stack by default, otherwise use cabal.
