### ISSUE TITLE
Yesod in a post Stackage/LTSHaskell/Stack world...

### ISSUE THREAD

**Issue by cies** [yesodweb/yesod#1043]
I'm tracking Stackage's nightlies now with [lambdacms](https://github.com/lambdacms/lambdacms) now. And I must say that Stackage and Stack are a great improvement to the overall simplicity of getting started.

Sometimes (when bumping the nightly I'm tracking) I need to bump some upper bounds in the cabal file, now I'm tempted to completely remove version constraints from the cabal file's dependecies section. Is this a good idea? I cannot imagine someone would like to do Yesod development without `stack`, now that it is here.

And would it be possible to use a program local to the application instead of `stack exec -- yesod devel`, preferably requiring less keystrokes?

**Comment by gregwebs** [comment]
If you are the distributor of lambdacms then you definitely want to maintain a cabal file with bounds.
If you are just a user and you are happy with stack and stackage then you can just get rid of bounds since you are pegging everything

**Comment by cies** [comment]
Hi @gregwebs, thanks for your answer...

> If you are the distributor of lambdacms then you definitely want to maintain a cabal file with bounds.

But this is only for those using LambdaCms without stack, right?

Just realized this question is much better suited for the mailing list. Sorry for that, please close it.

**Comment by gregwebs** [comment]
If someone is a stack user but wants to start changing a lot of dependencies (they want to add packages not on the version of stack you are using, having bounds in the cabal file could be very helpful to them.
