### ISSUE TITLE
yesod init start page mentions incorrect test file location

### ISSUE THREAD

**Issue by thomasdziedzic** [yesodweb/yesod#1049]
After running ```yesod init``` and visiting the newly generated site, I see:

> And last but not least, Testing. In tests/main.hs you will find a test suite that performs tests on this page. You can run your tests by doing:

It mentions ```tests/main.hs``` but instead, I have ```test/Spec.hs```.

**Comment by MaxGabriel** [comment]
Good catch; I think it was changed to Spec.hs about 9 months ago. Would you be interested in sending a PR to the postgres branch of the yesod-scaffold repo? It looks like [this line](https://github.com/yesodweb/yesod-scaffold/blob/424a958aca2c0d367ab5c7829a52656ee144f013/templates/homepage.hamlet#L39) needs updating.

**Comment by thomasdziedzic** [comment]
Hmm, I'm not too sure about the yesod-scaffold repo, but I thought I would only have to change the lines at:

```
[thomas@Thomas-Dziedzics-MacBook-Pro yesod]$ git grep tests/main.hs
yesod-bin/hsfiles/mongo.hsfiles:  <li> And last but not least, Testing. In <em>tests/main.hs</em> you will find a #
yesod-bin/hsfiles/mysql.hsfiles:  <li> And last but not least, Testing. In <em>tests/main.hs</em> you will find a #
yesod-bin/hsfiles/postgres-fay.hsfiles:  <li> And last but not least, Testing. In <em>tests/main.hs</em> you will find a #
yesod-bin/hsfiles/postgres.hsfiles:  <li> And last but not least, Testing. In <em>tests/main.hs</em> you will find a #
yesod-bin/hsfiles/simple.hsfiles:  <li> And last but not least, Testing. In <em>tests/main.hs</em> you will find a #
yesod-bin/hsfiles/sqlite.hsfiles:  <li> And last but not least, Testing. In <em>tests/main.hs</em> you will find a #
```

**Comment by creichert** [comment]
The files are auto-generated from the yesod-scaffold repository. You
should check out the yesod-scaffold postgres branch and make the edit in
the single source file. It will be merged into yesod-bin in the next
release.

Here is a direct link to the branch: https://github.com/yesodweb/yesod-scaffold/blob/postgres/templates/homepage.hamlet#L39

**Comment by thomasdziedzic** [comment]
Thanks, I was a bit confused on why I had to touch another repository and send my changes against a non-master branch. Opened the PR.

**Comment by creichert** [comment]
Yea, it's a bit confusing but thanks for the contribution!
