### ISSUE TITLE
Stack install failing

### ISSUE THREAD

**Issue by chadbrewbaker** [yesodweb/yesod#1052]
./stack-0.1.2.0-x86_64-osx  install yesod-bin
Using resolver: lts-2.21 from global config file: /Users/crb002/.stack/global/stack.yaml
While constructing the BuildPlan the following exceptions were encountered:

--  Failure when adding dependencies:    
      hfsevents: needed (>=0.1.3), latest is 0.1.5, but not present in build plan
    needed for package: fsnotify-0.1.0.3

--  While attempting to add dependency,
    Could not find package hfsevents in known packages

--  Failure when adding dependencies:    
      fsnotify: needed (>=0.0 && <0.3), latest is 0.2.1, but couldn't resolve its dependencies
    needed for package: yesod-bin-1.4.13.1

Recommended action: try adding the following to your extra-deps in /Users/crb002/.stack/global/stack.yaml
- hfsevents-0.1.5

You may also want to try the 'stack solver' command

**Comment by mgsloan** [comment]
Looks like it's using your global stack.yaml.  Maybe try with [the one in the yesod repo](https://github.com/yesodweb/yesod/blob/master/stack.yaml)?

**Comment by snoyberg** [comment]
This was a problem with the way Stackage snapshots were being generated, see:

https://github.com/commercialhaskell/stack/issues/594

If you run `stack install --resolver nightly-2015-08-05 yesod-bin`, it should work. We'll be rolling out a new LTS release with this fix very soon.

**Comment by chadbrewbaker** [comment]
```bash
stack --resolver nightly-2015-08-07 install  yesod-bin --install-ghc
```
That seems to work. Thanks!
