### ISSUE TITLE
Move Yesod cookbook away from wiki 

### ISSUE THREAD

**Issue by psibi** [yesodweb/yesod#1070]
Based on this: http://www.yesodweb.com/blog/2015/08/thoughts-on-documentation

I would recommend moving cookbook either to a new repository or under this repository. (Although, I would prefer it to move under a new repository as Yesod already has quite a number of directories under it).

What are others opinion on this ?

**Comment by creichert** [comment]
I don't have any objections to this, but aren't the wikis already a
standalone git repository? I understand michael's blog post and I agree
but Github wikis already seem to support the functionality of a repo.

git clone git@github.com:yesodweb/yesod.wiki


On Sun, Sep 06 2015, Sibi <notifications@github.com> wrote:
> Based on this: http://www.yesodweb.com/blog/2015/08/thoughts-on-documentation
>
> I would recommend moving cookbook either to a new repository or under this repository. (Although, I would prefer it to move under a new repository as Yesod already has quite a number of directories under it).
>
> What are others opinion on this ?
>
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/yesodweb/yesod/issues/1070

--
Christopher Reichert
irc: creichert
gpg: C81D 18C8 862A 3618 1376  FFA5 6BFC A992 9955 929B

**Comment by psibi** [comment]
@creichert Thanks, I know they already are git repository. I'm just suggesting it move it as a new repository so that contributions are done via pull requests for raising the trust level.

**Comment by creichert** [comment]
On Mon, Sep 07 2015, Sibi <notifications@github.com> wrote:
> @creichert Thanks, I know they already are git repository. I'm just suggesting it move it as a new repository so that contributions are done via pull requests for raising the trust level.
>

Good point, no objections here.


-- 
Christopher Reichert
gpg: C81D 18C8 862A 3618 1376  FFA5 6BFC A992 9955 929B

**Comment by gregwebs** [comment]
Please do!

**Comment by psibi** [comment]
@gregwebs Can you create an appropriate repository for that (since you have the needed privileges) ?

**Comment by gregwebs** [comment]
ok, there is a yesod-cookbook repo now.

**Comment by psibi** [comment]
I have migrated the existing cookbook to the repository. If you are ok with that, then I would go and put new links in the yesod wiki page (for the cookbook) and also the message that the cookbook has moved to the repository (so that new contributions don't end up there).

**Comment by gregwebs** [comment]
Thanks! I just had 1 question about the directory naming: https://github.com/yesodweb/yesod-cookbook/issues/1

**Comment by psibi** [comment]
@gregwebs Renamed it. Let me know if you have anything else in mind. If not, I will patch the user facing Yesod website and the old cookbook with link to the new path.

**Comment by gregwebs** [comment]
That's it. Thanks a lot!
