### ISSUE TITLE
identifyForm mishandles empty forms

### ISSUE THREAD

**Issue by edgmnt** [yesodweb/yesod#1072]
Looks like identifyForm simply removes fields of a form to make it missing. However, for already-empty forms, that's a noop, so they wrongly pass validation successfully.

The usecase seems pretty legitimate to me, e.g. delete actions on a particular route (which need no parameters). Of course, one can always work around it by providing a different route and handler for each form.

**Comment by meteficha** [comment]
So after [`eraseParams`](https://github.com/yesodweb/yesod/blob/master/yesod-form/Yesod/Form/Functions.hs#L346) we also need to discard their `FormResult` and manually return `FormMissing`?

**Comment by jprider63** [comment]
I just ran into this bug. I've created a pull request which should fix it.
