### ISSUE TITLE
Latest Yesod fails to build

### ISSUE THREAD

**Issue by tebello-thejane** [yesodweb/yesod#1075]
So the following happened today after running `cabal update`:

```
Resolving dependencies...
cabal: Could not resolve dependencies:
trying: yesod-1.4.2 (user goal)
trying: aeson-0.10.0.0 (dependency of yesod-1.4.2)
trying: monad-control-1.0.0.4 (dependency of yesod-1.4.2)
trying: yesod-form-1.4.4.1 (dependency of yesod-1.4.2)
trying: persistent-2.2 (dependency of yesod-form-1.4.4.1)
trying: yesod-persistent-1.4.0.3 (dependency of yesod-1.4.2)
next goal: persistent-template (dependency of yesod-persistent-1.4.0.3)
rejecting: persistent-template-2.1.3.4 (conflict: aeson==0.10.0.0,
persistent-template => aeson>=0.7 && <0.10)
rejecting: persistent-template-2.1.3.3, 2.1.3.2, 2.1.3.1, 2.1.3 (conflict:
aeson==0.10.0.0, persistent-template => aeson>=0.7 && <0.9)
rejecting: persistent-template-2.1.1 (conflict: persistent==2.2,
persistent-template => persistent>=2.1 && <2.1.3)
rejecting: persistent-template-2.1.0.1 (conflict: aeson==0.10.0.0,
persistent-template => aeson>=0.7 && <0.9)
rejecting: persistent-template-2.1 (conflict: monad-control==1.0.0.4,
persistent-template => monad-control>=0.2 && <0.4)
rejecting: persistent-template-2.0.8, 2.0.7, 2.0.5, 2.0.4, 2.0.3.2, 2.0.3.1,
2.0.3, 2.0.2.2, 2.0.2.1, 2.0.2, 2.0.1.1, 2.0.1, 2.0.0.3, 2.0.0.2, 2.0.0.1,
2.0.0, 1.3.2.2, 1.3.2.1, 1.3.1.4, 1.3.1.3, 1.3.1.2, 1.3.1.1, 1.3.1, 1.3.0,
1.2.0.6, 1.2.0.5, 1.2.0.4, 1.2.0.3, 1.2.0.2, 1.2.0.1, 1.2.0, 1.1.3.1, 1.1.3,
1.1.2.5, 1.1.2.4, 1.1.2.3, 1.1.2.2, 1.1.2.1, 1.1.2, 1.1.1, 1.1.0, 1.0.0.2,
1.0.0.1, 1.0.0, 0.9.0.2, 0.9.0.1, 0.9.0, 0.8.2, 0.8.1.2, 0.8.1.1, 0.8.1,
0.8.0, 0.7.0, 0.6.3.1, 0.6.3, 0.6.2, 0.6.1, 0.5.1, 0.5.0.1, 0.5.0 (conflict:
yesod-persistent => persistent-template>=2.1 && <2.2)
Backjump limit reached (change with --max-backjumps).
```

Looks like `persistent-template` might be misbehaving? Although I'm not sure why it's insisting on `aeson==0.10.0`...

**Comment by psibi** [comment]
@tebello-thejane What steps did you follow to install it ? The official recommended way of installing it is using [stack](http://www.yesodweb.com/page/quickstart).

**Comment by cosmo0920** [comment]
`aeson-0.10.0.0` has been released three days ago and persistent-template has the version constraint `aeson < 0.10.0`. This constraints causes installation failure.
Did you try `stack`? The official installation description using this tool.

**Comment by tebello-thejane** [comment]
I did ``cabal update && cabal fetch yesod``, using a clean GHC with ``cabal install`` version 1.22.4.0.

Has the ``yesod`` team given up on supporting ``Cabal-install``? I see the stackage LTS resolver is a rather old 2.17.

**Comment by snoyberg** [comment]
You can use cabal, at your own peril. In this case: there's no bug at all coming from Yesod, it's just that the dependency solver gave up. You need to pass it `--reorder-goals --max-backjumps=-1`.

You mean the resolver in the stack.yaml file? Yes, I've still been building with LTS 2.17, there's nothing wrong with it. When I want to test something newer, I use `--resolver ...`.

**Comment by tebello-thejane** [comment]
Takes almost 5 minutes for ``cabal`` to solve the dependencies properly.

So... you have officially given up support for ``cabal`` now?

I have a feeling this can be mitigated by adding bounds for ``aeson``, though, or (much easier) relaxing the upper-bound on ``persistent-template`` (it builds perfectly fine with ``aeson-0.10.0.0`` -- I checked). But it won't be necessary if you've decided not to support ``cabal`` anymore.

**Comment by tebello-thejane** [comment]
Nah. ``persistent-template`` tests fail on the new ``aeson``.

**Comment by snoyberg** [comment]
You should report this as a bug to the cabal team, 5 minutes to find a build plan should be considered a bug.

It's not clear what you mean by "not to support cabal anymore." I don't recommend cabal anymore to anyone. Even before stack existed, the recommendation was always "use Stackage Nightly or LTS Haskell." If you're able to make that work: great. We're not doing anything to prevent Yesod from working with cabal, but there are clearly serious bugs in cabal still preventing it from working correctly.

**Comment by MaxGabriel** [comment]
Re: persistent-template tests: this is caused by a breaking change made in Aeson 0.10 

This is being tracked at: https://github.com/bos/aeson/issues/287, https://github.com/bos/aeson/issues/83, and yesodweb/persistent#465

**Comment by tolysz** [comment]
There is no breaking change :) with the patch: https://github.com/bos/aeson/pull/326
Yesod and all packages are fine.

**Comment by StevenXL** [comment]
Given the comment from @tolysz (and the age fo this issue), seems like this is appropriate to close.
