### ISSUE TITLE
Wish: Somehow Yesod and GHC communicate to deal with new static files better

### ISSUE THREAD

**Issue by wolftune** [yesodweb/yesod#1080]
If I add a static file, I need StaticFiles.hs to recompile. _Ideally_ somehow the system would know that if a compile error occurs on a StaticR item, then, it makes sense to either try recompiling StaticFiles.hs right away or at least to provide an error that say "if you just added this static file, try touching StaticFiles.hs to get it to recompile".

On a side idea, perhaps there could be a `yesod new-static` command that would just be an alias for `touch Settings/StaticFiles.hs` or otherwise do the necessary steps so that it works.

I suppose a full clean, a la `stack clean` is the proper way to do this today, but it just seems there should be a smooth way to handle adding static files that doesn't seem so opaque.

If nobody has good ideas about how to improve this, I understand just closing it as "wishful thinking".

**Comment by jezen** [comment]
> If nobody has good ideas about how to improve this, I understand just closing it as "wishful thinking".

Nothing came of this in four years, so will close this issue.
