### ISSUE TITLE
ghc.exe: could not execute

### ISSUE THREAD

**Issue by wismill** [yesodweb/yesod#1082]
Hi there, I followed the [quickstart instructions](http://www.yesodweb.com/page/quickstart) on Windows but I keep having the following error:

```
stack : my-project-0.0.0: build
Preprocessing library my-project-0.0.0...
In-place registering my-project-0.0.0...
Preprocessing executable 'my-project' for my-project-0.0.0...
Linking .stack-work\dist\d96ab9d9\build\my-project\my-project.exe ...
ghc.exe: could not execute: C:\Users\user123\AppData\Local\Programs\stack\x86_64-windows\ghc-7.10.2\lib/../mingw/bin/gcc.exe
--  While building package my-project-0.0.0 using:
      C:\Users\user123\AppData\Roaming\stack\setup-exe-cache\setup-Simple-Cabal-1.22.4.0-x86_64-windows-ghc-7.10.2.exe --builddir=.stack-work\dist\d96ab9d9\ build lib:my-project 
exe:my-project --ghc-options " -ddump-hi -ddump-to-file"
    Process exited with code: ExitFailure 1
```

I get the same issue with the templates yesod-hello-world, yesod-simple, yesod-sqlite but not yesod-minimal.

My configuration:
- Windows 7 64 bit
- stack 1.5 (b7673fb03b714b5d16a3e778917946ad9cc7ac5f)
- resolver: lts-3.8

**Comment by snoyberg** [comment]
This looks like the standard file path issues on Windows. Have a look at

https://www.fpcomplete.com/blog/2015/08/stack-ghc-windows#workaround--shorter-paths

**Comment by wismill** [comment]
I have defined STACK_ROOT=C:\stack but I still have the same issue. But ghc is located in `%LOCALEAPPDATA%\Programs\stack\x86_64-windows\ghc-7.10.2` that looks quite a long path.

How can I change it?

**Comment by snoyberg** [comment]
It's far more likely to be the linker arguments than the path to GHC itself. You can install GHC manually (or just copy that directory elsewhere) and put it on the PATH to test, but that's likely what you'll find. You can also try putting your project directory higher on the filesystem.

As you can see from that blog post, I sent some patches to GHC to get this problem resolved properly, which will hopefully be released in the next few weeks as GHC 7.10.3.

**Comment by wismill** [comment]
Many thanks! I will wait for the next GHC version. I try hard but it is really demotivating to work with Haskell on Windows. Windows is unfortunately not an option at my work.

May I suggest you to include your advices from fpcomplete to the [documentation of Stack](https://github.com/commercialhaskell/stack/blob/master/doc/install_and_upgrade.md#windows)?

**Comment by snoyberg** [comment]
I didn't put it there since this is hopefully just a temporary workaround.
However, I'd accept a PR adding this advice.

**Comment by wismill** [comment]
PR: https://github.com/commercialhaskell/stack/pull/1111
