### ISSUE TITLE
Feature request: Get rid of cabal-install

### ISSUE THREAD

**Issue by cblp** [yesodweb/yesod#1084]
at least in presence of `stack`.

**Comment by snoyberg** [comment]
I don't understand what this issue means, can you clarify?

**Comment by cblp** [comment]
Yesod (particularly, `yesod devel` command) needs `cabal` tool (package `cabal-install`) installed to rebuild a project. On the other hand, the preferred way to use Yesod is with `stack` utility, which is a full replacement of `cabal-install`, and it also can rebuild a project. So there is no real need in `cabal-install`.

**Comment by snoyberg** [comment]
The `yesod devel` workflow is being replaced by `wai-devel`, which is why we aren't pursuing this right now.

**Comment by cblp** [comment]
Thank you!
