### ISSUE TITLE
Routes with Maybe

### ISSUE THREAD

**Issue by Daniel-Diaz** [yesodweb/yesod#1087]
I wanted this feature some time ago, and now I just found another case where I want it. I will explain it with an example:

Suppose I want the user to _optionally_ input a piece of a path, then I would write the following line in my route file:

```
/foo/#(Maybe Int)/bar FooBarR GET
```

Now the user can go either to ``/foo/203/bar`` or to ``/foo/-/bar``. The following function will handle the user request:

``` haskell
getFooBarR :: Maybe Int -> Handler Html
getFooBarR mint = ...
```

Note that the choice for ``-`` to mean ``Nothing`` was arbitrary and it can be any other symbol that makes sense.

I have looked at the code and it wasn't trivial enough to me to brave myself into writing the patch. I found a little confusing the route parsing code. Maybe I was just looking at the wrong place. I might try again in the future, but right now I have other things to do.

I don't even know if there is interest in having this feature, or maybe if this feature already exists! In any case, I decided to open the issue here since at least I myself have interest.

**Comment by gregwebs** [comment]
Can you create a type alias for `Maybe Int` and use that?

**Comment by Daniel-Diaz** [comment]
@gregwebs What is used to read the value from the route? The ``Read`` instance?

**Comment by gregwebs** [comment]
To/FromPathPiece

**Comment by Daniel-Diaz** [comment]
Thanks! Found it thanks to that!

https://github.com/yesodweb/path-pieces/blob/master/Web/PathPieces.hs#L23

That ``Maybe`` instance was not what I was looking for, but I can make my own type and write my own instance, so no big deal. This is awesome. So my last question would be, if I create a type, and I make it instance of that class, will I be able to use it from the routes file? If this is the case (as I suspect), this issue can be closed.

Thanks!

**Comment by MaxGabriel** [comment]
Yep, you can use it from the routes file. Here's a quick implementation of what I think you're looking for:

```haskell
newtype OptInteger = OptInteger { unOptInteger :: Maybe Integer } deriving (Eq, Show, Read)

instance PathPiece OptInteger where
    fromPathPiece t = Just $ OptInteger $ readMay t
    toPathPiece optInteger = case unOptInteger optInteger of
        Just i -> T.pack $ show i
        Nothing -> "-"

mkYesodData "App" $(parseRoutesFile "config/routes")
```

And in the routes file:

```
/foo/#OptInteger FooR GET
```
