### ISSUE TITLE
Is there something like admin panel for Yesod?

### ISSUE THREAD

**Issue by mrkkrp** [yesodweb/yesod#1088]
Hello,

First of all, thank you for this framework, I'm currently reading so-called “Yesod Book” and it's amazing so far. I especially like the idea of leveraging Haskell strong type system to check urls, etc. at compile time. The idea with widgets also looks promising. Thank you, @snoyberg for this marvel. I initially wanted to use Python/Django for my web-application, but now I think I will try to write it using Yesod.

Now, to the point of this issue. In Django (and other web frameworks), there are admin panel, so you can edit/create/delete model objects using the web interface. This is quite convenient in some cases. Is there something similar for Yesod? I've searched table of contents of the “Yesod Book”, but I couldn't find anything like this. [Haskellers site](https://github.com/snoyberg/haskellers) has templates related to administration, does it mean that I need to write something for administration on per-project basis?

**Comment by gregwebs** [comment]
No, not officially. There are some projects out there that provide some functionality like this though

**Comment by mrkkrp** [comment]
@gregwebs, What do you use yourself?

**Comment by gregwebs** [comment]
Custom code

**Comment by mrkkrp** [comment]
So, as I understand if there are third-party solutions and Yesod doesn't provide the official one, it means that authors of the project think that it's unnecessary or not exactly right conceptually to have admin panel in the project. Can someone explain rationale for this decision?

**Comment by gregwebs** [comment]
You are assuming a lot!

I would love to be able to offer an admin subdirectory in the scaffolding

**Comment by mrkkrp** [comment]
@gregwebs, So... why not just write it then?

**Comment by mrkkrp** [comment]
I mean if you personally don't have time, there should be quite a few enthusiastic people with sufficient skill and understanding of how Yesod works. Their code can be corrected if necessary and included in Yesod. I myself would do it, but I need to learn a lot before I can contribute to the project.

**Comment by mrkkrp** [comment]
@gregwebs, Nevermind, there are obviously other obstacles I don't know of. Thanks for your response.

**Comment by gregwebs** [comment]
general purpose Admins are generally most useful when first starting. Eventually they need so much customization that you are better off just rolling your own. So I personally don't have much use for them but would be willing to include it in Yesod. First step would be looking into existing efforts.

**Comment by mrkkrp** [comment]
@gregwebs, I reopen this then. Tell me if I can help somehow. I could check out already existing solutions. Well, that's not much, I'm still reading Yesod book and playing around :-)

**Comment by gregwebs** [comment]
yep, trying out the existing solutions is the best approach.

These are what show up on the [wiki](https://github.com/Tener/yesod-vend/blob/master/src/Yesod/VEND.hs) but you might also try googling and browsing hackage

* https://github.com/tlaitinen/yesod-dsl
* https://github.com/Tener/yesod-vend/blob/master/src/Yesod/VEND.hs

**Comment by gregwebs** [comment]
https://github.com/jairoGilC/Yesod-CRUD-Generator

**Comment by mrkkrp** [comment]
https://github.com/yairchu/yesod-admin-crud

**Comment by mrkkrp** [comment]
There are a lot of them. When official one is missing everyone comes up with his/her own :-)

**Comment by mrkkrp** [comment]
This https://github.com/tlaitinen/yesod-dsl looks like too radial approach to include it in scaffolded site, IMHO. The rest of them are not widely used according to number of GitHub “stars” and downloads on Hackage.

**Comment by Miguelme** [comment]
I think this would be a great add-on to yesod. It helps a lot!

**Comment by chreekat** [comment]
There are a few CRUD plugins that might be similar to what you want:
hackage.haskell.org/packages/search?terms=Crud

**Comment by jezen** [comment]
I think this would be a great addition to the project, but the best place to start discussion would be over a pull request. As this issue has been inactive for a few years, I will close it.
