### ISSUE TITLE
request: improved flexibility for `yesod add-handler`

### ISSUE THREAD

**Issue by wolftune** [yesodweb/yesod#1097]
If a project decides to move or rename the Application.hs file or the Handler/ directory (for example, into a src/ directory), it would be ideal if `yesod add-handler` could have some sort of settings file that would tell it to use the correct location for the files it looks for.

Secondly, it would be ideal if it could be optionally set to put the new handler entries in alphabetical order instead of at the end of the list.

Sure, it's easy enough to do all this manually. But improving this tool would just be a nice convenience if it's easy enough. And it would make it easier for more novice contributors to set up routes and pages even if they don't themselves understand Yesod well yet.

**Comment by jezen** [comment]
Doesn’t seem like there is enough need for this. I’ll close this issue.
