### ISSUE TITLE
Missing convenience function for custom status code + JSON return type

### ISSUE THREAD

**Issue by bitemyapp** [yesodweb/yesod#1101]
Ended up using sendResponseStatus + toJSON, but the lack of obvious apparent way to `returnJson` with a different status code can get new people turned around.

Snap avoids this by having the ability to set status codes inside MonadSnap, like so:

```
modifyResponse $ setResponseStatus 500 "Internal Server Error"
```

Then you can just `>>` that with your JSON return.

While technically this is accommodated with `sendResponseStatus` via `ToTypedContent`, it's not going to be obvious to new people that all they have to do is wrap their value in `toJSON`. I realize you don't want to make one-off concretions of `sendResponseStatus` for each return type, but something like "return status 201 + JSON" is going to be pretty common for anyone wanting to make a REST API in Yesod.

Only thing I could find via Googling that came close to documenting how this worked was [Brisbin's handy blog post](https://pbrisbin.com/posts/writing_json_apis_with_yesod/), but even that doesn't specifically address returning JSON (only Text values).

**Comment by gregwebs** [comment]
Yeah, Right now error handling is too hard-coded.
I have been meaning to commit some code I created for dealing with this.

@snoyberg what do you think?


``` haskell
module ApiError
  ( ApiError(..)
  , send
  , sends
  , messageAndErrors
  ) where

import ClassyPrelude
import Yesod hiding (Unauthorized)
import Network.HTTP.Types
import FrontRow.Helpers.Error
import qualified Data.Aeson.Types as A

type Handler a = forall site.  (YesodPersist site, Yesod site)
              => HandlerT site IO a

data ApiError
  = Forbidden (Maybe Text) -- ^ 403
  | Unauthorized           -- ^ 401
  -- Keep this open so that it is easy to defined error types where they are used
  -- for type-safety, none of the ApiError constructors should have a ToJSON instance
  | forall err. (Eq err, Show err, ToJSON err) => BadRequest err

instance Show ApiError where
  show Unauthorized    = "Unauthorized"
  show (Forbidden msg) = "Forbidden " <> (unpack $ fromMaybe "" msg)
  show (BadRequest e)  = "BadRequest " <> show e

-- Hacky, but only used in tests
instance Eq ApiError where
  Unauthorized    == Unauthorized    = True
  (Forbidden msg1) == (Forbidden msg2) = msg1 == msg2
  -- using ToJSON (we could be slighly hackier and use Show) is pretty hacky
  -- but this is only needed for testing purposes
  (BadRequest e1) == (BadRequest e2) = toJSON e1 == toJSON e2
  _ == _ = False

-- | every top-level constructor corresponds to an HTTP error code
toErrorStatus :: ApiError -> Status
toErrorStatus (Forbidden _)  = forbidden403
toErrorStatus Unauthorized   = unauthorized401
toErrorStatus (BadRequest _) = badRequest400

send :: ApiError -> Handler a
send e = sends [e]

sends :: [ApiError] -> Handler a
-- TODO: change this to be different from forbidden
sends [] = errorM "ApiError sends: No errors given"
sends es = do
  errJson <- mapM badJSON es
  sendResponseStatus badRequest400
                     $ object ["errors" .= errJson]
  where
    badJSON :: ApiError -> Handler Value
    badJSON Unauthorized =
      sendResponseStatus (toErrorStatus Unauthorized)
      -- TODO: should be differnt from Forbidden
      $ object $ messageAndErrors "unauthorized"
    badJSON f@(Forbidden msg) =
      sendResponseStatus (toErrorStatus f)
      -- TODO: change from unauthorized to "Permission Denied"
      $ object $ messageAndErrors (fromMaybe  "unauthorized" msg)
    badJSON (BadRequest e) = return $ toJSON e

-- maintain backwards compatibility with existing Yesod JSON errors
-- and forwards compatibility with FrontRow error type
messageAndErrors :: Text -> [(Text, Value)]
messageAndErrors msg =
  [ "message" .= msg
  , "errors"  .= [msg]
  ]

```

**Comment by gregwebs** [comment]
Here is some validation code that uses this

``` haskell
-- | Run validation.  Returns result on success, short-circuits
-- into a 4XX response on failure.
runValidation :: (input -> Validation [ApiError] validated) -> input -> Handler validated
runValidation validate input =
  case validate input of
    Success x  -> return x
    Failure es -> Error.sends es >> errorM "runValidation: response already sent"

-- | Like 'runValidation', but incorporates 'returnJson'.
sendValidation :: ToJSON validated => Validation [ApiError] validated -> Handler Value
sendValidation v = case v of
  Success x  -> returnJson x
  Failure es -> Error.sends es >> errorM "sendValidation: response already sent"

-- | For the purposes of sending a JSON response,
-- it is fine to have an InvalidRequest wrapping an ApiError:
-- it will get unwrapped when converted to JSON
failure :: forall e a. (Show e, Eq e, ToJSON e) => e -> Validation [ApiError] a
failure e = Failure [Error.BadRequest e]

forbidden :: Text -> Validation [ApiError] a
forbidden msg = Failure [Error.Forbidden $ if null msg then Nothing else Just msg]
```

**Comment by gregwebs** [comment]
And some code that uses the validation code

```
data FooError
  = FooNotEmpty
  | FooIsBar
  deriving (Eq, Show)
deriveToJSON ''FooError

validateFooIsEmpty :: [Entity Foo] -> Validation [ApiError] ()
validateFppIsEmpty = flip unless (failure FooNotEmpty) . null
```

**Comment by snoyberg** [comment]
@bitemyapp this looks like a misunderstanding, you can use `sendResponseStatus` on a JSON value. Perhaps you'd like to send a doc patch to make that clearer?

**Comment by snoyberg** [comment]
@gregwebs I'm not following the new API you're proposing, or how it would address Chris's problem, but it seems like a much simpler solution is possible.

**Comment by gregwebs** [comment]
The actual problem I am addressing is that Yesod's existing helpers such as `invalidArgs` make it impossible to send back structured JSON.
The code demonstrates using `sendResponseStatus`, but it also shows how to start creating a uniform higher-level API on top of it, which is something that Yesod should be providing.

**Comment by snoyberg** [comment]
My only opinion at this point is that including discussion of this change
on the current issue is confusing

**Comment by gregwebs** [comment]
@snoyberg fair enough.

However, using Yesod as an API server will always be confusing as long as there isn't a single easy way to send back structured responses that is consistently used in the book and documentation, so my opinion is that adding a line of documentation about `sendResponseStatus` is good but won't really addresses the underlying issue.

@bitemyapp I think the Snap API you have shown is bad because it allows for the response status to be modified multiple times. If you are setting the status that should be done together with setting the result and that should immediately send a response. So the current `sendResponseStatus` seems better to me.

**Comment by bitemyapp** [comment]
>@bitemyapp I think the Snap API you have shown is bad because it allows for the response status to be modified multiple times.

I don't disagree.

>If you are setting the status that should be done together with setting the result and that should immediately send a response. So the current sendResponseStatus seems better to me.

Fine by me.

>However, using Yesod as an API server will always be confusing as long as there isn't a single easy way to send back structured responses that is consistently used in the book and documentation

I agree there.

>@bitemyapp this looks like a misunderstanding, you can use sendResponseStatus on a JSON value. Perhaps you'd like to send a doc patch to make that clearer?

The point is that the typeclass obfuscates that all they need to do is apply `toJSON` to their value in order to have something they can send.

![screenshot from 2015-11-24 13-18-56](https://cloud.githubusercontent.com/assets/320177/11377869/edb2c9a0-92ad-11e5-88dd-94d995f19b81.png)

Have a look at that instance list (keep in mind, this assumes they even got as far as figuring out it was `ToTypedContent` and found the Haddocks)

What says the word "JSON"? It's not the thing they want. What they want is to return a `Value` but only practiced Haskellers are going to know `Value` is what they want that in order to `a -> Value` they need to use `toJSON`.

**Comment by snoyberg** [comment]
I think I see what you're saying, you want the `toJSON` part to be applied for the user because otherwise, it's not obvious how to get to a `ToTypedContent` instance. I hadn't understood that at first.

I'm OK with functions is similar to `returnJson` but for `sendResponseStatus` to be added to `Yesod.Core.Json`. Want to send a PR for such an addition?

**Comment by bitemyapp** [comment]
@snoyberg I'm happy to PR it - any opinions on nomenclature? Do we want to keep it constrained to JSON for now since that's the most common thing?

**Comment by snoyberg** [comment]
Since the PR is about to be merged, closing.

**Comment by jezen** [comment]
Just want to say: you guys are awesome for taking the time to think about this from the perspective of a newbie, and for discussing this in the open 💖

**Comment by bitemyapp** [comment]
For anyone that runs into this, but for `Handler Html`, and is stuck:

I did something like this to return an error page that uses `defaultLayout` with the appropriate status code:

```haskell
response <- defaultLayout bodyWidget
sendResponseStatus status response
```

My brain had gotten fixated on the idea that `defaultLayout` somehow short-circuited or finalized the response --- it does not. Thank you @snoyberg for getting me unstuck on this.
