### ISSUE TITLE
Don't recompile some files

### ISSUE THREAD

**Issue by mrkkrp** [yesodweb/yesod#1106]
I'm suing Flycheck (Emacs package) and it temporarily creates files named `flycheck_*.hs` when I visit Haskell source files. When I run `stack exec -- yesod devel` it compiles/recompiles them all the time. I don't like this. Is there some way to specify which files shouldn't cause recompilation, i.e. something like `.gitignore` for `yesod devel`?

**Comment by MaxGabriel** [comment]
I believe `wai-devel` allows more control over what files are compiled, and the author designed it with emacs/vim temporary files in mind. I haven't tried it out since it was in beta, personally, but I think some people are using it in place of `yesod devel`.

**Comment by geraldus** [comment]
@mrkkrp the easient solution is to set `flycheck-temp-prefix` to something like `.flycheck_` -- `yesod devel` ignores files starting with period.

**Comment by mrkkrp** [comment]
@geraldus, Perfect, thanks!
