### ISSUE TITLE
Compiling scaffolded site with nightly-2015-11-25 doesn't pass type-check

### ISSUE THREAD

**Issue by mrkkrp** [yesodweb/yesod#1108]
I started with `yesod-prostgres` template. Next, I specified resolver `nightly-2015-11-25` because it contains update of one package that I really want to use. I don't know if this is related, but to compile the scaffolded site with this resolver I had to drop upper bound for `yesod-test` package (was `< 1.5.0`) because version of `yesod-test` in that resolver is 1.5.0.1.

Now when I run `stack test` on tests from scaffolded site I get type error:

```
/home/mark/projects/programs/reproducing-that-disaster/test/Handler/HomeSpec.hs:7:5:
Couldn't match type ‘(site0, wai-3.0.4.0:Network.Wai.Middleware)’
               with ‘App’
Expected type: hspec-core-2.2.0:Test.Hspec.Core.Spec.Monad.SpecM
                 App ()
  Actual type: SpecWith
                 (Arg
                    (Control.Monad.Trans.State.Lazy.StateT
                       (YesodExampleData site0) IO ()))
In a stmt of a 'do' block:
  it "loads the index and checks it looks right"
  $ do { get HomeR;
         statusIs 200;
         htmlAllContain "h1" "Welcome to Yesod";
         request
         $ do { setMethod "POST";
                setUrl HomeR;
                .... };
         .... }
In the second argument of ‘($)’, namely
  ‘do { it "loads the index and checks it looks right"
        $ do { get HomeR;
               statusIs 200;
               .... };
        it "leaves the user table empty"
        $ do { get HomeR;
               statusIs 200;
               .... } }’
In the expression:
  withApp
  $ do { it "loads the index and checks it looks right"
         $ do { get HomeR;
                statusIs 200;
                .... };
         it "leaves the user table empty"
         $ do { get HomeR;
                statusIs 200;
                .... } }
```

I only can say that this is some sort of package incompatibility. I don't have enough knowledge of Yesod-ecosystem yet to tell how to work around this issue.

What is causing this and can I make it work using the same resolver?

**Comment by gregwebs** [comment]
you need to use the newer version of yesod-test (put it in extra-deps in stack.yaml)

**Comment by mrkkrp** [comment]
But `nightly-2015-11-25` I'm using provides `yesod-test-1.5.0.1`. How can I use something newer than that? This is the most recent version of that package: https://hackage.haskell.org/package/yesod-test.

**Comment by gregwebs** [comment]
ahh, sorry, I didn't look at this closely enough. Are you using a recently generated scaffold or an older one?

**Comment by mrkkrp** [comment]
Recently generated, but I've edited it. I removed some upper bounds, in other cases I set higher lower bounds. Here it is, actually: https://github.com/svod-music/svod/blob/master/svod.cabal.

**Comment by mrkkrp** [comment]
So thought that if I use the same resolver all those packages should play nicely together. In fact all of them should be of the latest versions, so this thing should not happen.

**Comment by gregwebs** [comment]
You just need the latest version of the scaffold: https://github.com/yesodweb/yesod-scaffold/blob/postgres/test/TestImport.hs

**Comment by mrkkrp** [comment]
That works. I wonder how it's possible that I got obsolete scaffold when I run it just yesterday. I thought it's downloaded “on demand”, i.e. when you choose to create new project from template (`stack new template-name`) you always get the latest files…

**Comment by gregwebs** [comment]
@snoyberg I really have no idea how this stuff works, I just push to the postgres branch. Do you know why this isn't working?

**Comment by snoyberg** [comment]
There's no automated deployment. We need to merge, build, and then copy the
resulting files to the stack-templates repo. I'll write up the
documentation on how all of this works. Once that happens, would you be
able to try running through the steps to confirm the documentation is
complete?

**Comment by snoyberg** [comment]
Documentation added to: https://github.com/yesodweb/yesod-scaffold/commit/119976b42efadc537626914382e05b73a2903883

**Comment by mrkkrp** [comment]
I think this is resolved now, so I close it.
