### ISSUE TITLE
yesod-bin and stack don't apply settings.yaml changes on rebuild

### ISSUE THREAD

**Issue by YoEight** [yesodweb/yesod#1109]
Greetings,

consider those settings in `settings.yaml`

```yaml
port:           "_env:PORT:3000"
approot:        "_env:APPROOT:http://localhost:3000"
```
if I change `port` to `4000` like this:

```yaml
port:           "_env:PORT:4000"
approot:        "_env:APPROOT:http://localhost:4000"
```

and proceeding with `stack build && stack exec yesod devel`,

`yesod-devel` keeps lauching the app on port `3000`

```
yoeight@haestrom corecursion-net [master] $ stack exec yesod devel
Yesod devel server. Type 'quit' to quit
Application can be accessed at:

http://127.0.0.1:3000
https://127.0.0.1:3443
If you wish to test https capabilities, you should set the following variable:
  export APPROOT=https://127.0.0.1:3443
```
stack: Version 0.1.8.0, Git revision e33dd995e292efcf8ee42e1e4c649b96232abf2e (2603 commits) x86_64

ghc: 7.10.2

yesod-bin:  1.4.14

Thanks for your time.

**Comment by snoyberg** [comment]
The port that `yesod devel` listens to needs to be specified on the command
line, not in the settings.yml file. For more information, see:

    stack exec -- yesod devel --help

**Comment by YoEight** [comment]
I really didn't know that. Thanks for the quick answer
