### ISSUE TITLE
support for serving xhtml

### ISSUE THREAD

**Issue by vandenoever** [yesodweb/yesod#1111]
It would be nice if Yesod could server XHTML with mime-type application/xhtml+xml.
This is a requirement in certain environments where HTML is not permitted.

**Comment by snoyberg** [comment]
Hamlet supports switching to XHTML rendering, and Yesod supports both
setting arbitrary content types and using alternative HTML rendering
systems if desired. Can you clarify what support you're looking for from
Yesod on this?

**Comment by vandenoever** [comment]
I'd like to know how I can get yesod to sent application/xhtml+xml when from e.g. 
  getHomeR :: Handler Html
I grepped the code for that mimetype but did not find it. It would be nice to set it as the mimetype for Handler Html in the entire server.

**Comment by snoyberg** [comment]
With Haskell's type system, that can't be done. But if you create a newtype
wrapper `newtype Xhtml = Xhtml Html`, you could create appropriate
`ToTypedContent` instances for that.

On Thu, Dec 3, 2015 at 10:45 AM, Jos van den Oever <notifications@github.com

**Comment by vandenoever** [comment]
Thanks! I'll give it a go.

**Comment by vandenoever** [comment]
This works fine.

```
{-# LANGUAGE GeneralizedNewtypeDeriving #-}

xhtmlType :: ByteString
xhtmlType = "application/xhtml+xml"
newtype Xhtml = Xhtml Html deriving ToContent
instance HasContentType Xhtml where
    getContentType _ = xhtmlType
instance ToTypedContent Xhtml where
    toTypedContent = TypedContent xhtmlType . toContent

getHomeR :: Handler Xhtml
getHomeR = do
    xhtml =<< defaultLayout $ do
        [whamlet|
            <p>Hello XHTML</p>
        |]
    return $ Xhtml xhtml
```

**Comment by snoyberg** [comment]
Can this issue be closed?

**Comment by vandenoever** [comment]
yes, issue was with the user

**Comment by snoyberg** [comment]
No problem, glad we could figure it out. If you're so interested, this
would be a good topic for a short Yesod cookbook snippet (
https://github.com/yesodweb/yesod-cookbook).

**Comment by vandenoever** [comment]
Good idea. I just created a pull request. https://github.com/yesodweb/yesod-cookbook/pull/3
