### ISSUE TITLE
Select multiple files field

### ISSUE THREAD

**Issue by daniot** [yesodweb/yesod#1113]
Hello, i use fileAFormReq  to get a FileInfo , but what i want to have is a multiple files field that ruturns something like [FileInfo].
I'm new to use Yesod and Haskell, if you have a little example, that could help me a lot.
Thank you very much

**Comment by snoyberg** [comment]
There's no support for this currently, I think we'd need to add a new function:

```haskell
filesAFormReq :: (MonadHandler m, RenderMessage (HandlerSite m) FormMessage)
               => FieldSettings (HandlerSite m) -> AForm m [FileInfo]
```

The implementation should be fairly straightforward based on the `fileAFormReq` function. Would you be interested in taking a stab at a PR on such an addition?

**Comment by daniot** [comment]
i would like to, but i just start to work with haskell in last few days. So could you help me please

**Comment by cutsea110** [comment]
It desirable to increse the input fields as required.

**Comment by snoyberg** [comment]
@daniot I'd recommend:

* Copy the current code from yesod-form into your project
* Make sure that it compiles (may need to add some import statements)
* Add the `multiple` attribute
* Modify the type signature to reflect multiple files
* Fix the code so that it compiles

**Comment by cutsea110** [comment]
I've succeed this just now.
Is this ugly?
----
filesField :: (Monad m, RenderMessage (HandlerSite m) FormMessage) => Field m [FileInfo]
filesField = Field
  { fieldParse = \_ files -> return $
      case files of
        [] -> Right Nothing
        fs@(_:_) -> Right $ Just fs
  , fieldView = \id' name attrs _ isReq -> do
     toWidget [hamlet|
                 <input name=#{name} *{attrs} type=file :isReq:required>
               |]
     toWidget [julius|
               $(function(){
                    $("input[name="+#{toJSON name}+"]")
                    .on("change", function() {
                       var file = this.files[0];
                       if (file != null) {
                         $(this).clone(true).insertAfter(this);
                       }
                    });
               })
               |]
  , fieldEnctype = Multipart
  }

**Comment by snoyberg** [comment]
It's not ugly, and if it works, seems fine (though I haven't tested it). You should ensure though that jQuery is in scope.

**Comment by cutsea110** [comment]
I've modified the implementation.
This filesField take one argument, which means url of jquery.js.
And, this works on my application. 

```.hs
filesField :: (Monad m, RenderMessage (HandlerSite m) FormMessage) =>
              Either (Route (HandlerSite m)) Text -> Field m [FileInfo]
filesField jqueryJs = Field
  { fieldParse = \_ files -> return $
      case files of
        [] -> Right Nothing
        fs@(_:_) -> Right $ Just fs
  , fieldView = \id' name attrs _ isReq -> do
     addScriptEither jqueryJs
     toWidget [hamlet|
                 <input name=#{name} *{attrs} type=file multiple :isReq:required>
               |]
     toWidget [julius|
               $(function(){
                    $("input[name="+#{toJSON name}+"]")
                    .on("change", function() {
                       var fileInputs = $("input[name="+#{toJSON name}+"]").length,
                           fileSelects = $("input[name="+#{toJSON name}+"]")
                                         .map(function(){return this.files[0]}).length;
                       if (fileInputs <= fileSelects) {
                         $(this).clone(true).insertAfter(this);
                       }
                    });
               })
               |]
  , fieldEnctype = Multipart
  }
```

**Comment by andrew-lei** [comment]
It seems a minor modification to `Yesod.Form.Fields.fileAFormOpt` should work? Works for me at least. The differences are returning `[FileInfo]` vs `Maybe FileInfo`, adding the `multiple` attribute to the input tag, grabbing the whole list in the `Just` case rather than only the head, and otherwise returning an empty list. Should I send a PR?

```haskell
fileAFormMult :: MonadHandler m
             => FieldSettings (HandlerSite m)
             -> AForm m [FileInfo]
fileAFormMult fs = AForm $ \(master, langs) menvs ints -> do
    let (name, ints') =
            case fsName fs of
                Just x -> (x, ints)
                Nothing ->
                    let i' = incrInts ints
                     in (pack $ 'f' : show i', i')
    id' <- maybe newIdent return $ fsId fs
    let (res, errs) =
            case menvs of
                Nothing -> (FormMissing, Nothing)
                Just (_, fenv) ->
                    case Map.lookup name fenv of
                        Just fi -> (FormSuccess fi, Nothing)
                        _ -> (FormSuccess [], Nothing)
    let fv = FieldView
            { fvLabel = toHtml $ renderMessage master langs $ fsLabel fs
            , fvTooltip = fmap (toHtml . renderMessage master langs) $ fsTooltip fs
            , fvId = id'
            , fvInput = [whamlet|
$newline never
<input type=file name=#{name} ##{id'} *{fsAttrs fs} multiple>
|]
            , fvErrors = errs
            , fvRequired = False
            }
    return (res, (fv :), ints', Multipart)
```

**Comment by jezen** [comment]
There is code here if anyone wants to take the initiative to open a PR. I'll close this issue for now though.
