### ISSUE TITLE
SqlError when compiling

### ISSUE THREAD

**Issue by ptkato** [yesodweb/yesod#1114]
I'm trying to compile a project, but it's throwing a SQL error when doing so:

```
The code threw an exception : SqlError: SqlError {sqlState = "42P01", sqlExecStatus = FatalError, sqlErrorMsg = "relation \"image\" does not exist", sqlErrorDetail = "", sqlErrorHint = ""}
```

It started to happen after I reset the database on Heroku, before that, it worked fine.
The structure in Foundation.hs:

```
share [mkPersist sqlSettings, mkMigrate "migrateAll"] [persistLowerCase|
    Event
        title Text
        message Textarea
        image ImageId Maybe
        date UTCTime default=now()
        deriving Show
    Image
        fileinfo Text
        description Text
        date UTCTime default=now()
        deriving Show
|]
```

I'm a bit confused, because I'm not used to Yesod and this error just appeared from the void.

**Comment by creichert** [comment]
Are you running migrations when you app starts up? (in the scaffold: https://github.com/yesodweb/yesod-scaffold/blob/postgres/Application.hs#L76)

What commands does Heroku run when resetting the database?

**Comment by ptkato** [comment]
I'm not using the scaffolded site, I dunno if it's the same, but as I posted, I'm using `mkMigrate "migrateAll"`.

To reset Heroku, I did in through the web interface on Heroku site. I also tried to reset the credentials, but didn't work.

**Comment by gregwebs** [comment]
Not a lot of information here. A starting point is looking at the schema in postgres

**Comment by jezen** [comment]
Not much information here, and this is old, so I will close this.
