### ISSUE TITLE
Cannot override default rendering of messages

### ISSUE THREAD

**Issue by mrkkrp** [yesodweb/yesod#1117]
Possibly related to #363. It seems that it's not possible to override default rendering of messages. In scaffold, I set:

```haskell
instance RenderMessage App FormMessage where
  renderMessage _ _ = russianFormMessage
```

This should make all form messages to be in Russian no matter what (note the second argument, it's ignored, that should mean that no matter what language is requested, result will be the same).

It doesn't work, I get “Please fill out this field.” message when I play with forms.

Next we can write:

```haskell
instance RenderMessage App FormMessage where
  renderMessage _ _ = const "Boo!"
```
or even

```haskell
instance RenderMessage App FormMessage where
  renderMessage _ _ = error "Hey! I'm an error!"
```

There is no error ever reported. So this instance doesn't mean anything at all. How to make it work?

**Comment by snoyberg** [comment]
The message you refer to is part of `AuthMessage,` not `FormMessage`. You need to change how you render both of those.

**Comment by mrkkrp** [comment]
Now with (couldn't find `russianAuthMessage`):

```haskell
instance RenderMessage App FormMessage where
  renderMessage _ _ = error "Hey, I'm error!"

instance RenderMessage App AuthMessage where
  renderMessage _ _ = error "Hey, I'm error!"
```

Still the same result. I think I should tell you more about my use-case. It's a form and the message is certainly displayed client-side, Yesod book says that some Java Script is generated to improve experience with forms, so I think it's part of it (although I didn't dig into that). The form has `areq emailField` and other required fields. When I try to submit empty form they all are highlighted and balloon appears near email field with that message.

**Comment by mrkkrp** [comment]
Maybe this is out of Yesod control. I experimented with browser language settings but they have no effect.

**Comment by mrkkrp** [comment]
Do these messages affect client-side interactions or are they only used to render incorrectly filled form after submission (Django does it this way, if I remember correctly)? If the latter, it explains this thing.

**Comment by mrkkrp** [comment]
All right, looking at HTML output I can see that this is vanilla thing. This is browser's way to support [`required`](http://www.w3schools.com/tags/att_input_required.asp) attribute on `input` field, Yesod has nothing to do with it. I had to setup Russian locale to check this out.
