### ISSUE TITLE
Expected in: flat namespace [Persisting enum]

### ISSUE THREAD

**Issue by ericshortcut** [yesodweb/yesod#1121]
I was trying to persist a Enum datatype and I've got the following error. 
<command line>: can't load .so/.DLL for: /path/to/project/dist/build/libHShelloworld-0.0.0-EF8MR1cMFcW3wMyLFX9tHK-ghc7.10.2.dylib (dlopen(/path/to/project/dist/build/libHShelloworld-0.0.0-EF8MR1cMFcW3wMyLFX9tHK-ghc7.10.2.dylib, 5): Symbol not found: _burgazuEF8MR1cMFcW3wMyLFX9tHK_ImportziBillingStatus_Open_closure
  Referenced from: /path/to/project/dist/build/libHShelloworld-0.0.0-EF8MR1cMFcW3wMyLFX9tHK-ghc7.10.2.dylib
  Expected in: flat namespace
 in /path/to/project/dist/build/libHShelloworld-0.0.0-EF8MR1cMFcW3wMyLFX9tHK-ghc7.10.2.dylib)
Exit code: ExitFailure 1

**Comment by ericshortcut** [comment]
I found out that my datatype was not listed on cabal file. I hope it helps other devs :)

library
     exposed-modules: Package.MyModule

**Comment by snoyberg** [comment]
FYI, Stack detects and warns about this situation.

Any reason to keep the issue open?

**Comment by MaxGabriel** [comment]
I've updated the [section of the wiki](https://github.com/yesodweb/persistent/wiki/Persistent-entity-syntax#sum-types) on using Sum Types with Persistent to mention adding the new module to your Cabal file. The added portion is:

> Note: If you created a new module, make sure add it to the exposed-modules section of your Cabal file.

**Comment by ericshortcut** [comment]
Solved, not important anymore :)
