### ISSUE TITLE
Editing Julius template doesn't start recompilation

### ISSUE THREAD

**Issue by mrkkrp** [yesodweb/yesod#1126]
The title says it. In `templates` directory I have `foo.hamlet` and `foo.julius`. I use them via `$(widgetFile "foo")`. Script itself works, but when I edit it I need to manually start recompilation every time, Yesod devel doesn't do it (at the same time editing of `foo.hamlet` starts recompilation normally).

**Comment by mrkkrp** [comment]
I'm not sure but it seems like Julius templates don't need recompilation, at least during development. Some clarification would be appreciated.

**Comment by snoyberg** [comment]
This is by design. Julius templates have an auto reload feature in them
which is used by the scaffolding

**Comment by mrkkrp** [comment]
Thank you.
