### ISSUE TITLE
Yesod devel tries do read global files when run via stack exec

### ISSUE THREAD

**Issue by mrkkrp** [yesodweb/yesod#1127]
I have GHC installed globally (it's 7.10.3 after recent update, I'm on Arch Linux) and stack. My understanding is that stack should take care of GHC version so it always matches version that's used by resolver. My Yesod project uses resolver that works with 7.10.2. Here is some output (run inside project root directory):

```
$ which ghc
/usr/bin/ghc
$ ghc --version
The Glorious Glasgow Haskell Compilation System, version 7.10.3
$ stack exec -- ghc --version
The Glorious Glasgow Haskell Compilation System, version 7.10.2
$ stack exec -- yesod devel
Yesod devel server. Type 'quit' to quit
Application can be accessed at:

http://127.0.0.1:3000
https://127.0.0.1:3443
If you wish to test https capabilities, you should set the following variable:
  export APPROOT=https://127.0.0.1:3443

…

Rebuilding application... (using cabal)
yesod: /usr/lib/ghc-7.10.2/settings: openFile: does not exist (No such file or directory)
```

Yesod tries to access global files of GHC 7.10.2 which now don't exist. As a result, I cannot run development server. Is this Yesod's behavior correct? Since I run it via Stack, shouldn't it use GHC that Stack setups for it?

**Comment by snoyberg** [comment]
It's possible you compiled the `yesod` executable itself with a different GHC version. I'd recommend running `stack build yesod-bin` and trying again.

**Comment by mrkkrp** [comment]
That works, thank you!
