### ISSUE TITLE
yesod-core-1.4.18 test suite failure

### ISSUE THREAD

**Issue by bergmark** [yesodweb/yesod#1128]
```
Failures:

  test/RouteSpec.hs:306:
  1) overlap checking detects overlaps in a hierarchy
       expected: [("FooSlashNestedR","")]
        but got: [("FooSlashNestedR","FooR/FooNestedR")]

Randomized with seed 714907749
```

This comes from the nightly build, not sure how serious it is. I might let it fail for now since we might exclude a lot of packages otherwise.

**Comment by snoyberg** [comment]
Mistake on my part, I included some code that wasn't actually in the repo. Should be fixed now.
