### ISSUE TITLE
`stack build` uses different environment to `stack exec yesod devel`

### ISSUE THREAD

**Issue by silky** [yesodweb/yesod#1130]
i am using a local version of `yesod-form`. in my `stack.yml` i have (essentially):

````
# Local packages, usually specified by relative directory name
packages:
- '.'
- ext/yesod-form

# Packages to be pulled from upstream that are not in the resolver (e.g., acme-missiles-0.3)
extra-deps:
- yesod-form-1.4.7
````

where 1.4.7 is my own new version of this library. let's say i've added a new function `foo`.

`stack build` works fine and life is good, no compile errors when i reference this new `foo` function in my code.

but if i do `stack exec yesod devel` it doesn't compile. now, `stack exec yesod devel` uses cabal, and in my cabal file it's perhaps important to note that i do *not* require `yesod-form == 1.4.7`, i leave it open at any yesod-form version. so it happens that in my global cabal database i have an earlier version of yesod-form; so *that* is the one that is picked up by `devel`s `cabal build`, and the build fails, and so `stack exec yesod devel` fails.

if i pin to version 1.4.7 in my cabal file, then `stack exec yesod devel` works fine.

my question is: is this expected behaviour? i was a bit surprised; but some other threads (https://github.com/yesodweb/yesod/issues/1018) make me think that maybe i shouldn't expect this to work perfectly anyway.

what's the advice here? should i remove my global installation and be happy? is it a bug that can be fixed? or should i just have to put proper bounds in my cabal file?

thanks for any tips!

**Comment by snoyberg** [comment]
It's not really clear what exactly is going on here, especially with your references to "global." If you actually have versions of yesod-form installed in your global package database, that's a bad idea, and I'd recommend removing it.

I don't quite understand how you can be requiring a specific version of yesod-form, but not need to have that package referenced in your cabal file.

**Comment by silky** [comment]
okay, i guess this is just my misunderstanding.

when i run `stack exec -- ghc-pkg list` i get

````
09:20 AM noon ∈ high5-web@master>stack exec -- ghc-pkg list
/usr/local/lib/ghc-7.10.2/package.conf.d
   [...]
/home/noon/.stack/snapshots/x86_64-linux/lts-3.13/7.10.2/pkgdb
   [...]
   yesod-form-1.4.5
   [...]
/home/noon/dev/thing-app/thing-web/.stack-work/install/x86_64-linux/lts-3.13/7.10.2/pkgdb
   [...]
   yesod-form-1.4.7
````

so indeed i *don't* have a yesod-form in my global db, but one clearly comes from lts-3.13 (which is what my stack.yaml specifies).

i guess my confusion is that `stack build` works fine; it's only `yesod devel` that breaks (because yesod devel does a cabal build at some point). i.e. i don't really need to "fix" anything here if i don't ever run `yesod devel`.

when running `stack exec -- cabal build --verbose=2` i see something like

````
/home/noon/.stack/snapshots/x86_64-linux/lts-3.13/7.10.2/bin/yesod-ghc-wrapper [...] yesod-form-1.4.5-268c6c6c9012366cc7d1c72e6000e195 
````

so whatever it is that picks that version of yesod-form is what's causing me grief. it probably makes sense that the smallest version that matches the bounds in my cabal file is chosen, so i guess that explains it?

am i still misunderstanding something? is it just an accident that this works at all for `stack build`?

**Comment by snoyberg** [comment]
It sounds like cabal is making different guesses about which packages to
use versus Stack. I'd recommend adding the necessary build dependencies to
your cabal file.
