### ISSUE TITLE
Long compiles

### ISSUE THREAD

**Issue by DaveCTurner** [yesodweb/yesod#1131]
I've a Yesod site with about 170 routes and I'm starting to have real trouble with the length of time it takes to recompile the site after minor changes. Anything that touches `Foundation` or one of its dependencies seems to cause all the Template Haskell (i.e. all the handlers) to be rebuilt when running `stack test` or similar. I'm running with `-O0 -fomit-interface-pragmas` but even so the compile and run cycle is now many minutes long due to the unnecessary TH recompilation.

Note that running with `stack exec yesod devel` seems much more intelligent about what to recompile and generally does the right thing. That's fine for exploratory work but not much good for writing tests.

Is this recompilation expected behaviour or am I missing something? Any other hints about how to make recompiles faster? I'd normally try and rationalise the inter-module dependencies to reduce the number of things that depended on unstable interfaces but because everything in Yesod has to go through `Foundation` I'm struggling to see how the usual techniques apply here.

**Comment by gregwebs** [comment]
You can try to remove code from Foundation and make more code less dependent on it. The best approach is to use ghci with the approach that exists in the DevelMain.hs file.

**Comment by DaveCTurner** [comment]
Thanks, Greg. Not sure how much more I can take out of `Foundation` - it needs to have the definition of `App` which, in turn, has to depend on the whole model doesn't it?

However, the pointer to `DevelMain.hs` is helpful. At the moment we're running Selenium-style tests by starting and stopping the service as a separate process (hence the need for a recompile), but it looks from that as if (with a bit of a rethink) we could get the Selenium tests running from within GHCI.
