### ISSUE TITLE
Build error in yesod-core 1.4.18 and 1.4.18.1

### ISSUE THREAD

**Issue by nek0** [yesodweb/yesod#1134]
when trying to build a project of mine with cabal (I know I shouldn't, but I haven't made a transition yet) I get the following compile error:

```
Yesod/Core/Dispatch.hs:195:7:
    Not in scope: ‘Network.Wai.Handler.Warp.warpVersion’
    Perhaps you meant one of these:
      data constructor ‘Network.Wai.Handler.Warp.FileInfo’ (imported from Network.Wai.Handler.Warp),
      data constructor ‘Network.Wai.Handler.Warp.BadFirstLine’ (imported from Network.Wai.Handler.Warp),
      ‘Network.Wai.Handler.Warp.run’ (imported from Network.Wai.Handler.Warp)
```

Can somebody look into this?

**Comment by snoyberg** [comment]
There's a minor regression in Warp it seems, and was discussed on the
mailing list. Solutions:

* Add a warp < 3.2 in your .cabal file
* Use Stack

**Comment by nek0** [comment]
thanks a lot.
