### ISSUE TITLE
Cannot run quickstart app. Error: "yesod: /usr/local/haskell/ghc-7.10.3-x86_64/lib/ghc-7.10.3/settings: openFile: does not exist (No such file or directory)"

### ISSUE THREAD

**Issue by x-ji** [yesodweb/yesod#1135]
Sorry if this is a dumb question. I'm new to Yesod and stack. I initiated the quickstart project per the instructions on the website, however, after I run `stack exec -- yesod devel`, everything seems to be fine, except for the last line in the console: `yesod: /usr/local/haskell/ghc-7.10.3-x86_64/lib/ghc-7.10.3/settings: openFile: does not exist (No such file or directory)`. Then, whenever I try to connect to localhost://3000, I get "the Application isn't built. we'll keep trying to refresh every second.", with no extra output being shown on the console.

I have no idea why it seems to be trying to access a file that doesn't exist. I don't have any ghc installation at `/usr/local/haskell` now, and the 7.10.3 version of ghc should have been installed locally into the project directory via `stack build`. The only reason I can think of is I indeed previously installed ghc 7.10.3 via Haskell Platform https://www.haskell.org/platform/#linux-generic to `/usr/local/haskell`. However, I already tried to delete everything that comes with this installation, including this folder and all the symlinks it created in the /usr/local/bin folder. So it's likely that there is still some (global) configuration file remaining in my system that says ghc 7.10.3 is installed at `/usr/local/haskell/ghc-7.10.3-x86_64/lib/ghc-7.10.3/`, however I'm at a loss as of where to find this configuration file and change it. Any idea? I understand I should have used stack from the beginning and not installed Haskell Platform on my system, but I didn't know.

- System: Ubuntu 14.04 64-bit.
- Stack: version `Version 1.0.0, Git revision 3bc26237b5b3c387b8fd564459ea4dd88fd58b30 (2939 commits) x86_64`/
- Yesod: yesod-bin version: 1.4.16.1

**Comment by snoyberg** [comment]
Where does your `yesod` binary come from? Did you compile it with Haskell Platform, or with Stack? What does `which yesod` say? Does running `stack build yesod-bin` and then `stack exec yesod devel` have any impact?

**Comment by x-ji** [comment]
I think I installed yesod after I deleted Haskell Platform and installed Stack. `which yesod` reports `~/.local/bin/yesod`. The command didn't seem to make any changes.

I think the global stack ghc on my system is 7.10.2 (using resolver lts-3.19). However, when I initiated a project using `stack new projectName yesod-postgres`, there was a dependency in the template `yesod-postgres` which required ghc 7.10.3, so it downloaded ghc 7.10.3 using resolver `nightly-2015-12-24`. Not sure if this has anything to do with the issue.

**Comment by snoyberg** [comment]
It does. Please follow the instructions in the quickstart guide exactly.
You need to run:

    stack build yesod-bin && stack exec yesod devel

This will ensure you're using a consistent GHC version throughout the devel
server and your project.

**Comment by x-ji** [comment]
I noticed that for some reason the resolver version was `nightly-2015-12-24` in the project. After I changed it to `lts-3.21` and executed `stack build yesod-bin && stack exec yesod devel`, it worked.

Then I tried to replicate the process outlined in the quickstart guide, and here is what happened:

`stack new testProject yesod-sqlite`

```
Downloading template "yesod-sqlite" to create project "testProject" in testProject/ ...
Writing default config file to: /home/jx/Projects/testProject/stack.yaml
Basing on cabal files:
- /home/jx/Projects/testProject/testProject.cabal

Checking against build plan lts-3.21

* Build plan did not match your requirements:
    yesod-test version 1.4.4 found
    - testProject requires >=1.5.0.1 && <1.6


Checking against build plan lts-3.19

* Build plan did not match your requirements:
    yesod-test version 1.4.4 found
    - testProject requires >=1.5.0.1 && <1.6


Checking against build plan nightly-2015-12-24
Selected resolver: nightly-2015-12-24
Wrote project config to: /home/jx/Projects/testProject/stack.yaml
```

So that is to say it automatically chose the nightly build plan, which uses ghc 7.10.3, because of `yesod-test`.

Then I `cd` into the folder and executed `stack install yesod-bin cabal-install --install-ghc`:

```
Copying from /home/jx/.stack/snapshots/x86_64-linux/nightly-2015-12-24/7.10.3/bin/cabal to /home/jx/.local/bin/cabal
Copying from /home/jx/.stack/snapshots/x86_64-linux/nightly-2015-12-24/7.10.3/bin/yesod to /home/jx/.local/bin/yesod
Copying from /home/jx/.stack/snapshots/x86_64-linux/nightly-2015-12-24/7.10.3/bin/yesod-ar-wrapper to /home/jx/.local/bin/yesod-ar-wrapper
Copying from /home/jx/.stack/snapshots/x86_64-linux/nightly-2015-12-24/7.10.3/bin/yesod-ghc-wrapper to /home/jx/.local/bin/yesod-ghc-wrapper
Copying from /home/jx/.stack/snapshots/x86_64-linux/nightly-2015-12-24/7.10.3/bin/yesod-ld-wrapper to /home/jx/.local/bin/yesod-ld-wrapper

Copied executables to /home/jx/.local/bin:
- yesod-ld-wrapper
- yesod-ghc-wrapper
- yesod-ar-wrapper
- yesod
- cabal
```

Then I ran `stack build`:

```
testProject-0.0.0: configure
Configuring testProject-0.0.0...
testProject-0.0.0: build
Preprocessing library testProject-0.0.0...
[ 1 of 10] Compiling Model            ( Model.hs, .stack-work/dist/x86_64-linux/Cabal-1.22.5.0/build/Model.o )
[ 2 of 10] Compiling Settings         ( Settings.hs, .stack-work/dist/x86_64-linux/Cabal-1.22.5.0/build/Settings.o )
[ 3 of 10] Compiling Settings.StaticFiles ( Settings/StaticFiles.hs, .stack-work/dist/x86_64-linux/Cabal-1.22.5.0/build/Settings/StaticFiles.o )
[ 4 of 10] Compiling Import.NoFoundation ( Import/NoFoundation.hs, .stack-work/dist/x86_64-linux/Cabal-1.22.5.0/build/Import/NoFoundation.o )
[ 5 of 10] Compiling Foundation       ( Foundation.hs, .stack-work/dist/x86_64-linux/Cabal-1.22.5.0/build/Foundation.o )

Foundation.hs:8:1: Warning:
    The import of ‘Yesod.Auth.Message’ is redundant
      except perhaps to import instances from ‘Yesod.Auth.Message’
    To import instances alone, use: import Yesod.Auth.Message()
[ 6 of 10] Compiling Import           ( Import.hs, .stack-work/dist/x86_64-linux/Cabal-1.22.5.0/build/Import.o )
[ 7 of 10] Compiling Handler.Common   ( Handler/Common.hs, .stack-work/dist/x86_64-linux/Cabal-1.22.5.0/build/Handler/Common.o )
[ 8 of 10] Compiling Handler.Home     ( Handler/Home.hs, .stack-work/dist/x86_64-linux/Cabal-1.22.5.0/build/Handler/Home.o )
[ 9 of 10] Compiling Handler.Comment  ( Handler/Comment.hs, .stack-work/dist/x86_64-linux/Cabal-1.22.5.0/build/Handler/Comment.o )
[10 of 10] Compiling Application      ( Application.hs, .stack-work/dist/x86_64-linux/Cabal-1.22.5.0/build/Application.o )
In-place registering testProject-0.0.0...
Preprocessing executable 'testProject' for testProject-0.0.0...
[1 of 1] Compiling Main             ( app/main.hs, .stack-work/dist/x86_64-linux/Cabal-1.22.5.0/build/testProject/testProject-tmp/Main.o )
Linking .stack-work/dist/x86_64-linux/Cabal-1.22.5.0/build/testProject/testProject ...
testProject-0.0.0: copy/register
Installing library in
/home/jx/Projects/testProject/.stack-work/install/x86_64-linux/nightly-2015-12-24/7.10.3/lib/x86_64-linux-ghc-7.10.3/testProject-0.0.0-6x22vsWfBy3DTNSeGlEhCy
Installing executable(s) in
/home/jx/Projects/testProject/.stack-work/install/x86_64-linux/nightly-2015-12-24/7.10.3/bin
Registering testProject-0.0.0...
```

Then finally `stack exec yesod devel`:

```
Yesod devel server. Type 'quit' to quit
Application can be accessed at:

http://localhost:3000
https://localhost:3443
If you wish to test https capabilities, you should set the following variable:
  export APPROOT=https://localhost:3443

Resolving dependencies...
Configuring testProject-0.0.0...
Forcing recompile for ./Model.hs because of config/models
Forcing recompile for ./Foundation.hs because of config/routes
Forcing recompile for ./Foundation.hs because of templates/default-layout-wrapper.hamlet
Forcing recompile for ./Foundation.hs because of templates/default-layout.hamlet
Forcing recompile for ./Handler/Home.hs because of templates/homepage.hamlet
Forcing recompile for ./Handler/Home.hs because of templates/homepage.julius
Forcing recompile for ./Handler/Home.hs because of templates/homepage.lucius
Rebuilding application... (using cabal)

Foundation.hs:8:1: Warning:
    The import of ‘Yesod.Auth.Message’ is redundant
      except perhaps to import instances from ‘Yesod.Auth.Message’
    To import instances alone, use: import Yesod.Auth.Message()
yesod: /usr/local/haskell/ghc-7.10.3-x86_64/lib/ghc-7.10.3/settings: openFile: does not exist (No such file or directory)
```

If I change the resolver to another nightly, say `nightly-2016-01-07`, the same thing happens.

However if I change it to `lts-3.21`, it worked. No problem with `yesod-test` is reported either.

**Comment by snoyberg** [comment]
I'm not sure what the files are, but it doesn't appear that you have
something left over from a previous install. Perhaps if you wipe out your
~/.ghc and ~/.cabal directories it will work. But I'm not sure what we can
change in Yesod to deal with this.

**Comment by x-ji** [comment]
Deleting those directories didn't work, but deleting everything installed by `stack` and reinstalling `stack` worked. Still not sure what happened. Anyways, thanks for your time and help.

**Comment by pbrisbin** [comment]
Hi @snoyberg I seem to be experiencing a _very_ similar issue and I'd rather not do the "delete and start over" thing without first understanding why this is happening.

I'm on Arch and up until recently was letting stack use system GHC. However, I've now switched away from that. I've:

- Set the configuration

  ```
  % grep ghc ~/.stack/config.yaml
  system-ghc: false
  install-ghc: true
  ```

- Removed my system installed stuff

  ```
  % pacman -Qs ghc cabal
  % ls -l ~/.ghc
  ls: cannot access '/home/patrick/.ghc': No such file or directory
  % ls -l ~/.cabal
  total 4
  -rw-r--r-- 1 patrick patrick 4058 Apr  3 12:36 config
  ```

- Installed yesod-bin via stack

  ```
  % which yesod 
  /home/patrick/.stack/bin/yesod
  % stack exec which yesod
  /home/patrick/.stack/snapshots/x86_64-linux/lts-5.11/7.10.3/bin/yesod
  % stack build yesod-bin
  (does nothing because i've done it already)
  ```

And yet,

```
% stack exec yesod devel
Yesod devel server. Type 'quit' to quit
Application can be accessed at:

http://localhost:3000
https://localhost:3443
If you wish to test https capabilities, you should set the following variable:
  export APPROOT=https://localhost:3443

Warning: The package list for 'hackage.haskell.org' does not exist. Run 'cabal
update' to download it.
Resolving dependencies...
Configuring tee-io-0.0.0...
Rebuilding application... (using cabal)
yesod: /usr/lib/ghc-7.10.3/settings: openFile: does not exist (No such file or directory)
```

Can you please tell me what to look at next to figure out what's going on?

Unfortunately, I don't actually use `yesod devel` all that much -- my workflow is primarily test-driven, so I can't say for sure what action I took that caused this to break. I know it was working before, but I can't say for certain if it broke before, after, or exactly when I made the explicit step to start using a `--no-system-ghc`-based workflow.

**Comment by pbrisbin** [comment]
I tried a version of the "delete and try again" approach:

```
stack clean --full
rm ~/.stack/bin/yesod*
find ~/.stack -name "yesod-bin*" -exec rm -rf {} +
stack install yesod-bin
(did re-configure, re-build)
stack build && stack exec yesod devel
```

Same error.

I pretty sure that the yesod binary that just built should not know anything about a local GHC installation: it was built just now, by stack, using the `--no-system-ghc` configuration, and I have no ghc on my system (or any stale `/usr/lib/ghc-*` directories). It compiled and installed fine, and even runs fine. It just has the wrong settings path...

**Comment by snoyberg** [comment]
At the time you installed GHC via Stack, did you still have the system GHC
installed? Can you grep in your ~/.stack for your old GHC directory? I
wonder if the GHC installation somehow hard coded a directory.

**Comment by pbrisbin** [comment]
> At the time you installed GHC via Stack, did you still have the system GHC installed?

It's possible. I'd imagine that happened implicitly the first time I did something after setting the `use-system-ghc: false` configuration? It's possible I didn't yet actually remove the system package at that time.

> Can you grep in your ~/.stack for your old GHC directory? I wonder if the GHC installation somehow hard coded a directory

There are no results for the complete string `/usr/lib/ghc-7.10.3/settings`. But here are the results for `/usr/lib/ghc-7.10.3`: http://sprunge.us/cVcb

**Comment by snoyberg** [comment]
It does seem like a (reasonable) case of some paths getting hard-coded to the original GHC location. I'm not really sure what yesod-bin, Stack, or GHC could do differently in this case.

**Comment by pbrisbin** [comment]
It seems to me that you're saying having stack install GHC while a system GHC exists won't work. If that's true, I think a documentation update and/or an explicit check-error in stack would be appropriate. If that's not true, then I still don't know what I've done wrong, but am OK not taking up more of your time on it if you believe there's no bug here.

Any thoughts on what I should do now? Anything less nuclear than `rm -rf ~/.stack`? Can I tell stack to re-install 7.10.3? I imagine that would require also re-installing everything built by it so far.

**Comment by snoyberg** [comment]
What I think happened here is that some of the packages were installed with the system-global GHC, and that's now gone. Those binary installed packages are now corrupted and need to be deleted (which is the behavior I'm saying seems reasonable). I could be mistaken on the details though since I've been unable to reproduce this.

**Comment by pbrisbin** [comment]
I see. So even though the error seems to come from the `yesod` binary, which I know for sure was compiled just now by the stack-installed GHC, packages on which it depends may have been installed previously by a system GHC and that's the cause.

**Comment by snoyberg** [comment]
That's my guess (and it really is only a guess).
