### ISSUE TITLE
yesod dislikes unicode letters in static file names

### ISSUE THREAD

**Issue by knupfer** [yesodweb/yesod#1136]
having a file like /static/img/mühlen.jpg becomes a StaticR img_m_hlen_jpg, albeit the 'ü' would be a valid letter

**Comment by snoyberg** [comment]
Coming up with a proper whitelist for this is complicated, and making a change at this point will break existing sites. I'd accept a PR though that makes the whitelisting rules configurable.

**Comment by knupfer** [comment]
I'm working on a PR. But why would a proper whitelist be difficult? Wouldn't it boil down to Data.Char.isAlphaNum? This get's all valid identifiers excluding identifiers with apostrophe (sensible to exclude that one in file names).

**Comment by snoyberg** [comment]
Perhaps I'm over thinking it. If the functions from Data.Char match up with
the Haskell spec, it could be trivial. But we still need this to be
configurable to avoid breakage in existing code.

**Comment by knupfer** [comment]
They match up, I looked in the report. The only ugly thing at the moment would be when someone begins the directory name with an uppercase letter: static/Img/foo.jpg becomes  _Img_foo_jpg. Perhaps we should warn a usage like that, or canonicalize on lowecase?

**Comment by knupfer** [comment]
Lowercasing wouldn't help against static/123/foo.txt

**Comment by jezen** [comment]
This issue is inactive, so I will close it.
