### ISSUE TITLE
staticFiles should warn about unused statics

### ISSUE THREAD

**Issue by knupfer** [yesodweb/yesod#1137]
Albeit irrelevant from the perspective of type-safty, this would tremendously help to keep a site nice and clean.

**Comment by snoyberg** [comment]
This is not possible: staticFiles provides the identifiers and exports them to other modules, and has no idea if those modules use them or not. This is a general issue with detecting unused functions in a multi-module project.

**Comment by knupfer** [comment]
I've hacked something together. It is just a draft but works with my page flawlessly.
https://github.com/knupfer/yesod-test-static

**Comment by snoyberg** [comment]
Can you clarify your approach here? I'm not sure what you're attempting to
do, or how you determine that a file is stale.

**Comment by knupfer** [comment]
It converts every filepath from a file in the static dir into the string which would be used to reference this file in code and searches for that string in the codebase (in all .hs, .hamlet, .cassius, .julius, .lucius). It searches for example "css_bootstrap_css" and errors when it isn't found.

**Comment by gregwebs** [comment]
Neat! But won't this be brittle?

**Comment by silky** [comment]
yeah as-is it's definitely brittle and prone to false positives and false negatives; certainly fine for something ad-hoc, but not good for inclusion into yesod itself imo.

**Comment by gregwebs** [comment]
I think having this as a task that could be run occasionally could be a good default. That task could look at all non-binary files since it wouldn't be run very often.

**Comment by snoyberg** [comment]
That sounds good to me Greg.

**Comment by knupfer** [comment]
False negatives are actually very unlikely (only if you've got unused haskell functions which use the static) but false positives are common place when using css packages like bootstrap, because they don't use typesafe urls to point to the static, this behaviour can be seen in the scaffolded site. Because of that, my mockup exports a customizeable whitelist.
In the next days, I'll deuglify my code (it's inefficient and to much IO) and extend the reach to check as well if shakespeartemplates are stale.

**Comment by knupfer** [comment]
Thinking a bit, it generates also false negatives when someone writes for example css_bootstrap_css in plain text in an hamlet and when it's an infix of another static. Both cases are unlikely to happen, but at least the latter can be taken care of easily.

**Comment by paul-rouse** [comment]
I think it is worth pointing out that static files do not need to be known at compile time.  URLs can be built dynamically with the `StaticRoute` constructor, for example using data from a configuration file.  This is exactly what I do with around 1000 images which have their own, separate build process - and that would give a lot of false positives!

Nice idea for simpler cases, though!

**Comment by jezen** [comment]
Discussion here is inactive, so I will close this issue.
