### ISSUE TITLE
yesod neither compresses nor caches favicon.ico

### ISSUE THREAD

**Issue by knupfer** [yesodweb/yesod#1138]
albeit it's just a bit (1.4k vs 1.1k), sites like webpagetest complain about it.

**Comment by snoyberg** [comment]
Perhaps you want to send a PR to wai-extra?
https://github.com/yesodweb/wai/blob/master/wai-extra/Network/Wai/Middleware/Gzip.hs#L59

**Comment by snoyberg** [comment]
Also, you can send a PR to yesod for adding caching to getFaviconR.

**Comment by knupfer** [comment]
Fixed both
