### ISSUE TITLE
Cannot add/remove/reorder fields in a form

### ISSUE THREAD

**Issue by DaveCTurner** [yesodweb/yesod#1139]
... in between creating the form and submitting it.

We have a form where the fields it contains depend on the server-side state. However, if a user gets the form, then the state changes in a way that removes one of the fields from subsequently rendered forms, and _then_ the user submits the form then the data ends up in the wrong fields.

Sounds decidedly nontrivial to fix given how it works under the hood, and we're going to work around it simply by having the different forms post back to different URLs (there aren't _that_ many permutations in our case) but figured it was worth raising anyway.

**Comment by snoyberg** [comment]
What about just manually setting `fsName` for each field?

**Comment by DaveCTurner** [comment]
That's also possible, but breaks the nice compositionality you get from being able to use the same field more than once.

**Comment by jezen** [comment]
This seems pretty specific to the OP's project and it's not clear what the best way forward is or even if this is actually an issue, so I'll close this.
