### ISSUE TITLE
consider hashing every static, not only css

### ISSUE THREAD

**Issue by knupfer** [yesodweb/yesod#1140]
At the moment, something like static/img/logo.jpg get's only an etag, from a performance perspective it would be better to put the hash of the file in the name and set expire max.
This would avoid a http request (which are very detrimental for performance) for every cached img. In this case omission of the etag would be sensible.
Additionally, this would be more consistent and make it a sensible base to implement serving automatically device specific resolutions of images (via srcset).

**Comment by snoyberg** [comment]
I don't think this is an accurate assessment of the current functionality.

**Comment by knupfer** [comment]
With which point do you disagree? At least the part of the http request is to my knowledge correct.

**Comment by snoyberg** [comment]
If you use `StaticR img_logo_jpg`, it should include the hash in the query string, fixing the problem you're bringing up. I'm not sure if there's something more complicated that you're looking for.

**Comment by knupfer** [comment]
Ok sorry for the noise, I've read some articles about the unreliability of querystrings, but these articles are quite outdated.

**Comment by gregwebs** [comment]
Thanks for taking a close look at the static assets serving
