### ISSUE TITLE
sendStatusJSON yields type m a, but should be m b since it short-circuits

### ISSUE THREAD

**Issue by Dridus** [yesodweb/yesod#1142]
I think it's just a typo. The signature of `sendStatusJSON` is:

```haskell
sendStatusJSON :: (MonadHandler m, ToJSON a) => H.Status -> a -> m a
```

which would seem to imply it gives you back the thing you gave it, but in fact it short circuits. I'm thinking it's just a typo to have used `a` twice.

`sendResponseStatus` is correctly typed to give you whatever you want since it never produces it, and that's why it compiled

**Comment by snoyberg** [comment]
Sounds correct, interested in sending a PR to fix that?

**Comment by Dridus** [comment]
I would be honored. #1143

**Comment by snoyberg** [comment]
Awesome, I'll merge that PR once Travis gives it the green light. Meanwhile, closing this issue.
