### ISSUE TITLE
yesod devel returns 500 errors after first compile, but not subsequent compiles

### ISSUE THREAD

**Issue by snoyberg** [yesodweb/yesod#1146]
Not sure exactly what's going on here. It seems that when using `yesod devel`, the application it's running returns 500 "something went wrong" error messages the first time the application is compiled. Once I make a code change, future updates make the response work correctly. This doesn't seem to be a problem with Yesod-the-library or the app being tested, but with how it's being run.

I've only noticed this with GHC 7.10.3, may be a recent change in the compiler.

**Comment by snoyberg** [comment]
I'm no longer able to reproduce this, will reopen if it happens again.

**Comment by dariooddenino** [comment]
@snoyberg I've been experiencing this for the past few months. Other than changing a file, hitting enter on the terminal to force a rebuild fixes it.
During these months I have updated stack, ghc, and yesod multiple times but nothing changed.
