### ISSUE TITLE
GoogleEmail authentication broken

### ISSUE THREAD

**Issue by mrP0tat0Head** [yesodweb/yesod#1150]
The authentication example from yesodweb doesn't work for GoogleEmail. The link to google's openid service seems broken. I get an 404 for this url: 

https://github.com/yesodweb/authenticate/blob/ed55c336a2526c5e7b134869a84a61f9758be139/authenticate/Web/Authenticate/OpenId/Providers.hs#L17

Here is the error as plain text.
http://lpaste.net/150364

**Comment by mrP0tat0Head** [comment]
Am I right that the openid 2 authentication code has to be [migrated to OpenID Connect](https://developers.google.com/identity/protocols/OpenID2Migration)?

**Comment by silky** [comment]
yeah, you want to use `GoogleEmail2` from here, say - https://github.com/yesodweb/yesod/blob/master/yesod-auth/Yesod/Auth/GoogleEmail2.hs

**Comment by snoyberg** [comment]
I've added deprecation warnings to the relevant functions/modules. The example on the website was also recently updated to use Yesod.Auth.GoogleEmail2.

**Comment by snoyberg** [comment]
Thanks for the report, can you confirm that the website updates hit the example you were referring to?

**Comment by mrP0tat0Head** [comment]
Thanks for the fix it works perfectly! You just made an newbie lucky :smile:

**Comment by snoyberg** [comment]
Awesome
