### ISSUE TITLE
"Cookbook file upload saving files to server" isn't compiled

### ISSUE THREAD

**Issue by amitaibu** [yesodweb/yesod#1152]
Trying to copy/ paste [this coobook](https://github.com/yesodweb/yesod/wiki/Cookbook-file-upload-saving-files-to-server), I'm getting the following error upon `stack runhaskell Example.hs`

```
Example.hs:17:1:
    Can't make a derived instance of ‘PathPiece (Key Image)’:
      ‘PathPiece’ is not a derivable class
      Try GeneralizedNewtypeDeriving for GHC's newtype-deriving extension
    In the newtype instance declaration for ‘Key’
```

**Comment by gregwebs** [comment]
Can you fix it on the wiki? It probably just needs that extension

**Comment by psibi** [comment]
@amitaibu Note that cookbook has move to https://github.com/yesodweb/yesod-cookbook . I will update each page in the old wiki to reflect this as this is causing confusion to several peoples.

**Comment by amitaibu** [comment]
:+1:
