### ISSUE TITLE
Configurable `config/` directory

### ISSUE THREAD

**Issue by vlatkoB** [yesodweb/yesod#1154]
Currently, `config/` is hardcoded in several places, and to use different configurations, one must rename/relink current `config/`. 
It would be good to be able to specify `config/` directory (i.e. in `configDir` variable), that would be honoured by yesod, and `yesod keter`.

Maybe something like this:
```
/config
  selectedConfig.cfg  # location and filename are hardcoded. Its content i.e. config1
   /config1
      settings.yml
      keter.yml
        ...
   /config2
  ...
 ```

`selectedConfig.cfg` file is read first, and `configDir` variable is set to that value. If `selectedConfig.cfg` or directory it points to doesn't exist, or some other error occur, `configDir` is set to `config/`, as is hardcoded now, so it would be backward compatible, and yet provide flexibility.

I think the approach with `selectedConfig.cfg` file would be better that specifying config directory on command line. All info is on disk, and easy to share/configure/document. 
However, having both would be even better.

This would be very useful to ease the testing on different environments, sharing with team members, having same site customized to certain topics, clients, locations, ...

What do you think?

**Comment by snoyberg** [comment]
Can you specify where `config/` is hard-coded in libraries? That would make this discussion much more concrete.

**Comment by vlatkoB** [comment]
These are just grep results for "config/":
./yesod-bin/AddHandler.hs:    modify "config/routes" $ fixRoutes name pattern methods
./yesod-bin/Keter.hs:        let yml = "config/keter.yml"
./yesod-bin/Keter.hs:        return $ if ymlExists then yml else "config/keter.yaml"
./yesod/Yesod/Default/Handlers.hs:getFaviconR = sendFile "image/x-icon" "config/favicon.ico"
./yesod/Yesod/Default/Handlers.hs:getRobotsR = sendFile "text/plain" "config/robots.txt"
./yesod/Yesod/Default/Config.hs:    , csFile = \_ -> return "config/settings.yml"
./yesod/Yesod/Default/Config2.hs:configSettingsYml = "config/settings.yml"

**Comment by snoyberg** [comment]
Going through those:

1. There's no reasonable way I can see to configure the location of the keter.yaml file: it has to be an agreed-upon file path for all applications and the Keter application itself. So I don't see that changing.
2. For AddHandler: there are actually a number of hard-coded paths in that command. So allowing modification of just the config directory and not the rest would be a bit strange
3. The Handlers.hs should probably just be deprecated; I don't think anyone's using them
4. Config.hs is superceded by Config2.hs

So IMO, the only real location worth discussing is in Config2.hs. But that's just a string that's used as a default value in the scaffolding, and which can be overridden. And replacing one hard-coded path (config/settings.yml) with a new hard-coded path (config/selectedConfig.cfg) doesn't seem to gain anything to me, unless I'm missing something here.

**Comment by vlatkoB** [comment]
I see your points. 

1.  You're absolutely right here for deployment, it must be a fixed location. But for preparing a bundle there can be a way. But this one is easily solved by scripting.

What do you think about defining a standard customizable IO function for config directory in Yesod? Library authors and users will have a common place to put settings. 
Does that make more sense?

**Comment by snoyberg** [comment]
The settings file is just a recommendation that comes from the scaffolding,
and can easily be bypassed completely, its location changed, etc. The
standard way within the config file for changing specific settings is by
setting environment variables. If there's a straightforward way to achieve
what you're looking for, I'm not opposed, but IMO this is already a solved
problem, at least for the cases I've seen.

**Comment by vlatkoB** [comment]
OK, thanks for discussion. I'll implement the solution I have in mind, and if it's any good, I'll reopen this.
