### ISSUE TITLE
"Defined but not used" warnings from Yesod TH

### ISSUE THREAD

**Issue by tomkludy** [yesodweb/yesod#1160]
I am getting the following warning with "-Wall" option:

```
/Users/tomkludy/Haskell/proxy-rendezvous/src/Proxy/Rendezvous.hs:75:1: Warning:
    Defined but not used: type constructor or class ‘Widget’

/Users/tomkludy/Haskell/proxy-rendezvous/src/Proxy/Rendezvous.hs:75:1: Warning:
    Defined but not used: ‘resourcesApp’
```

The referenced line is:

```
mkYesod "App" [parseRoutes|
/#CustId/#Endpoint ListenR GET
|]
```

I don't use widgets or resources in my app...  Is there a way to suppress or eliminate these warnings?

Thanks!

**Comment by snoyberg** [comment]
The easiest way is to explicitly export `Widget` from the module where you
call `mkYesod`.

**Comment by MaxGabriel** [comment]
Closing; this sounds resolved
