### ISSUE TITLE
XML returning Handler UX/API doesn't make a ton of sense

### ISSUE THREAD

**Issue by bitemyapp** [yesodweb/yesod#1162]
While collaborating with a coworker, this is what we arrived at for a handler returning XML:

```haskell
getJobFeedR :: Handler RepXml
getJobFeedR = return $ repXml $ renderText def $  Document undefined (formatItemsToXML []) []
```

Now I have a hypothesis as to why we're doing it this way, but it does seem a bit strange that we have to lose the XML information by turning it into text in order to return XML which is structured data.

Hypothesis: so that any XML library could work - not just xml-conduit.

Am I close? Have we missed something?

Sorry for the hassle.

**Comment by bitemyapp** [comment]
This bit acted as a red herring in the process of figuring this out as well:

```haskell
provideRep
  :: (Monad m, HasContentType a) =>
     m a
     -> Control.Monad.Trans.Writer.Lazy.Writer
          (Data.Monoid.Endo [ProvidedRep m]) ()
```

**Comment by snoyberg** [comment]
It's just to avoid having a dependency on xml-conduit I believe. Having an
instance for that package's Document type wouldn't prevent using another
XML representation with Yesod as well, much like how lucid can be used with
Yesod.

**Comment by bitemyapp** [comment]
Well there's definitely nothing to object to in what you've said. Just feels weird to have to do the bouncing back and forth yourself. I'll stew on it and let the code proliferate a bit before I say more unless someone has something to add. Reopen later if I do.

**Comment by bitemyapp** [comment]
Thank you as always!
