### ISSUE TITLE
Can yesod handle a massive commercial site?

### ISSUE THREAD

**Issue by JohnReedLOL** [yesodweb/yesod#1163]
Dear yesod,

I was wondering if you could handle a massive commercial website.

SoundCloud and AirBnB use Rails, LinkedIn uses Play framework, PayPal uses Node.js. Seeing big companies use a framework is very reassuring, but what was built with yesod? http://lambdacms.org/ ? That's hardly a PayPal, AirBnB, or SoundCloud.

Is yesod fit to handle a website like SoundCloud or PayPal?

On that note, can I deploy yesod in such a way that it can quickly and automatically expand to withstand huge, unexpected onslaughts of traffic? I'm talking from a few thousand users streaming content and interacting with the server to hundreds of thousands of users and then back down to a few thousand in a matter of hours?

p.s. I don't care that much about performance because IO is the bottleneck, I care about scalability.

**Comment by MaxGabriel** [comment]
I think this was addressed on the Yesod google group, so I'm closing.
