### ISSUE TITLE
I18N - Message interpolation used, but no message renderer provided

### ISSUE THREAD

**Issue by felipexpert** [yesodweb/yesod#1171]
I followed the instructions from the wiki about how to add I18N feature to the scaffold, but I get the following exception in my handler:
    
    Rebuilding application... (using cabal)

    Handler/Conf.hs:41:9:
        Exception when trying to run compile-time code:
          Message interpolation used, but no message renderer provided
        Code: Language.Haskell.TH.Quote.quoteExp
                hamlet
                "\n\
                \<div ng-controller=ConfController>\n\
                \  <p>\n\
                \    test: {{test}}\n\
                \  <p>\n\
                \    _{MsgWelcome}\n"
    Build failure, pausing...

**Comment by snoyberg** [comment]
Please include a code snippet or a link to the code you're trying to follow. Most likely you're using `hamlet` instead of `ihamlet`, though.

**Comment by felipexpert** [comment]
I solved it sometime ago... If I remember well, it was the problem indeed. Thank you!

**Comment by snoyberg** [comment]
Closing as resolved
