### ISSUE TITLE
Mozilla's Persona will shut down in November 2016

### ISSUE THREAD

**Issue by geraldus** [yesodweb/yesod#1173]
Just a reminder

**Comment by snoyberg** [comment]
Thanks for the reminder. I've deprecated the module and removed its usage in the scaffolding. Any other changes you can think of?

**Comment by geraldus** [comment]
Hmm… I can't remember anything worthwhile at this moment.  I run into some minor issues related to authentication in general when integrated LambdaCms in my project, and they are more LambdaCms specific rather than Yesod.

**Comment by jezen** [comment]
This appears to be resolved by the two commits above, so I will close this issue.
