### ISSUE TITLE
Aeson - requireJsonBody

### ISSUE THREAD

**Issue by felipexpert** [yesodweb/yesod#1177]
I have the following JSON

    {"data": {...}}

`{...}` represents a model. This model already is an instance of FromJSON...

Now look at this:

    putMyEntityR :: Handler ()
    putMyEntityR = do
      (Entity id _) <- (...) -- getting id
      (Object o) <- requireJsonBody'
      -- I want to get the "data" attribute inside and and
      -- make `myEntity`
      -- runDB $ replace id myEntity
      sendResponseStatus status204 ("UPDATED" :: Text)

    parseJsonBody' :: (MonadHandler m) => m (J.Result Value)
    parseJsonBody' = do
        eValue <- rawRequestBody $$ runCatchC (sinkParser JP.value')
        return $ case eValue of
            Left e -> J.Error $ show e
            Right value -> J.Success value

    -- | Same as 'parseJsonBody', but return an invalid args response on a parse
    -- error.
    requireJsonBody' :: (MonadHandler m) => m Value
    requireJsonBody' = do
        ra <- parseJsonBody'
        case ra of
            J.Error s -> invalidArgs [pack s]
            J.Success a -> return a

I have made my own version of requireJsonBody (requireJsonBody')
How can I get `MyEntity` from `o`, using my FromJSON instance??

**Comment by felipexpert** [comment]
Is there any more standard way to do it, following this line of resolution? Other way I have done is to just create a Wrapper and implement another version of FromJSON, but I would need to make it frequently, and I think it is not a "Haskell like" way of doing things... I would like any useful suggestion.

**Comment by MaxGabriel** [comment]
I'm having some trouble understanding your comment, even knowing about your [Stackoverflow question](http://stackoverflow.com/questions/35816074/haskell-yesod-extracting-a-object-inside-a-json-before-converting-it-to-a-mode). 

Is your question how to go from a Persistent `Key` + record to an Entity? If so, use the `Entity` constructor. Here's some example usage from the REPL:

```
ghci > :t Entity
Entity
  :: PersistEntity record => Key record -> record -> Entity record
ghci > import Database.Persist.Sql (toSqlKey)
ghci > Entity (toSqlKey 1) (User {userIdent="", userPassword=Nothing})
Entity {entityKey = UserKey {unUserKey = SqlBackendKey {unSqlBackendKey = 1}}, entityVal = User {userIdent = "", userPassword = Nothing}}
```

**Comment by felipexpert** [comment]
Sorry, but not actually... I have an entity, which already is a `FromJSON` instance. From my frontend I receive this entity wrapped like this: `{ "data": (myEntity ...) }` (this is a JSON representation)

That means that I have a json, with a `data` attribute, and this `data` attribute refer to myEntity`s from Yesod. That's ok, so... I could write a FromJSON instance for this wrapper, using my already defined FromJSON from `myEntity`. But I would like to do differently, I want to just use `requestJsonBody'` I have defined which returns a `Value`, and take the `data` stuff from that `Value`, and use my `FromJSON` implementation to actually convert this `Object` I have caught inside the wrapping JSON which came from client. Is is clear?

**Comment by MaxGabriel** [comment]
Hey @felipexpert, I think I understand the issue better—it's just the same as your StackOverflow question, right? Here's how I implemented it for an `Entity` named `Comment`.

First in your Handler:

```haskell
postDataCommentR :: Handler Value
postDataCommentR = do
  value <- requireJsonBody' -- Parse request body into Value
  commentJson <- requireJsonKey "data" value -- Lookup a key from the Value
  comment <- (requireJsonParse commentJson :: Handler Comment) -- Parse the Value into a comment record

  insertedComment <- runDB $ insertEntity comment
  returnJson insertedComment
```

This part is just what you wrote for `parseJsonBody'` and `requireJsonBody'`:

```haskell
import qualified Data.Aeson as J
import qualified Data.Aeson.Parser as JP
import Data.Conduit.Attoparsec (sinkParser)

-- Written by you
parseJsonBody' :: (MonadHandler m) => m (J.Result Value)
parseJsonBody' = do
    eValue <- rawRequestBody $$ runCatchC (sinkParser JP.value')
    return $ case eValue of
        Left e -> J.Error $ show e
        Right value -> J.Success value

-- | Same as 'parseJsonBody', but return an invalid args response on a parse
-- error.
requireJsonBody' :: (MonadHandler m) => m Value
requireJsonBody' = do
    ra <- parseJsonBody'
    case ra of
        J.Error s -> invalidArgs [pack s]
        J.Success a -> return a
```

These are some helper functions I wrote for the code above:

```haskell
-- Written by me
requireJsonParse :: (MonadHandler m, FromJSON a) => Value -> m a
requireJsonParse v = case J.fromJSON v of
  J.Error s -> invalidArgs [pack s]
  J.Success a -> return a

requireJsonKey :: (MonadHandler m) => Text -> Value -> m Value
requireJsonKey key jObject@(Object hashMap) = case lookup key hashMap of
                                    Nothing -> invalidArgs ["Couldn't find a value when looking up the key " <> key <> " in the object: " <> (pack (show jObject))]
                                    Just v -> return v
requireJsonKey key invalid = invalidArgs ["When looking up the key " <> key <> ", expected an object but got a " ++ (pack (show invalid))]
```

Does that answer your question?

**Comment by felipexpert** [comment]
Yes, you answered my question completely. Thank you very much.

**Comment by MaxGabriel** [comment]
Cool, good luck with your app!
