### ISSUE TITLE
Yesod-1.4.2 run as a fastcgi app failed

### ISSUE THREAD

**Issue by uuhan** [yesodweb/yesod#1179]
Recently I upgraded my web appcation to the new version yesod of version 1.4.2 . My web app run as a fastcgi app by lighttpd, throuth toWaiApp function  and run function provided by wai-handler-fastcgi .

But It Failed to run ( could be successfully spawned, but turned into a zombie process once visited the uri) .
After doing some tests, I found the funtion toWaiApp was not suitable for this work anymore. I can only use the toWaiAppPlain function.  ** toWaiApp with wai-handler-fastcgi seems buggy  **

import Network.Wai.Handler.FastCGI (run)
instance Yesod App
...
toWaiApp App >>= run   ( BUGGY)
toWaiAppPlain App >>= run ( Works )

So, is it normal ?

**Comment by snoyberg** [comment]
That seems to be a bad interaction with one of the middlewares. Can you test out which middleware causes the problem?

**Comment by uuhan** [comment]
@snoyberg I downgraded the wai and wai-handler-fastcgi to 3.0.5.0 and 3.0.0, It worked well. I  want to fingure out the problem cause the failure.  It may take me some hours or even days  ╮(￣⊿￣")╭ .
But, I think there is something may "break the world" inside the newest wai package. I make the postgrest prorject into a fastcgi app through the same method, It also failed to run. ( Not using the toWaiApp, but a pure wai application with wai-handler-fastcgi)

**Comment by uuhan** [comment]
@snoyberg 
Well, finally I known what is wrong with the old wai-extra package.
Fastcgi is just a frontend of the cgi protocal, roughly. But It was deficult to debug fastcgi.
After your reply of this issue: **[https://github.com/yesodweb/yesod/issues/1186]**
The fastcgi (as a frontend of cgi) problem is caused by the  same issue. Now, my project runs well as expected.

Thank you so much : )
