### ISSUE TITLE
Is there any support for forms with different methods than GET and POST?

### ISSUE THREAD

**Issue by mrkkrp** [yesodweb/yesod#1184]
I want to use PATCH to partially edit a resource. HTML forms however only allow GET or POST. In RoR for example, [you can specify any method to use](http://guides.rubyonrails.org/form_helpers.html#how-do-forms-with-patch-put-or-delete-methods-work-questionmark) with form but if it's not GET or POST, then POST is specified and hidden field `_method` is created with real method there. Server then deals with that POST request as needed. In there similar machinery or any support for HTTP methods other than GET and POST in forms in Yesod?

**Comment by snoyberg** [comment]
Exact same thing works in Yesod by default (via a middleware), just use something like `<form action=@{SomeRouteR}?_method=PATCH>`.

**Comment by mrkkrp** [comment]
That's just great, thanks for your reply!
