### ISSUE TITLE
Yesod Tests addToken could use a nicer error

### ISSUE THREAD

**Issue by bitemyapp** [yesodweb/yesod#1185]
Getting 

```
There was no response, you should make a request
```

Because you forgot to `GET` before using `addToken` in a POST is misery itself.

**Comment by snoyberg** [comment]
Do you have a recommendation for clearer text on this?

**Comment by bitemyapp** [comment]
"You tried using `addToken`, we can only get the CSRF token if you made a GET request to a page that includes a form, but we couldn't see a previous request in `StateThingy`."

First pass. How? My guess - have addToken register an addendum/context in the same state thingy. I've only looked at the code for a few hours though.

Let me know if this sounds reasonable/doable at all. It could be expanded to other actions that also trigger `withResponse`.

**Comment by snoyberg** [comment]
I'm not sure if modifying `addToken` is necessary, but having a version of `withResponse` that takes a more meaningful error message seems like it would address this case and similar ones.
