### ISSUE TITLE
Run subsite widgets with mainsite widgets

### ISSUE THREAD

**Issue by mchaver** [yesodweb/yesod#1204]
I have a yesod site called `MainWebsite` with a single page angular front end app. I want to make it depend on yesod subsite package called `SubWebsite` which will provide pieces for the angular front end. In the `MainWebsite` I have a widget that looks like this.  

```
mainJSFile :: Widget
mainJSFile = do
  aMainWebsiteWidget
  bMainWebsiteWidget
  aSubWebsiteWidget
```
If the widget in `SubWebsite` looks like this then this works out fine, because it really has no dependency on anything `SubWebsite`, it's a WidgetT for an arbitrary site:
```
aSubWebsiteWidget = toWidget [julius|
  // js code
|]
```
but that's not really interesting because I want it the JS to make ajax calls to routes in `SubWebsite` so it should really look like this, but it changes the type signature: 
```
aSubWebsiteWidget = do
  toParent <- getRouteToParent
  toWidget [julius|
  // ajax query to @{toParent SubWebsiteQuery}
|]
```
Now there is a problem with the `mainJSFile` code. All of the widgets from `MainWebsite` look like `Widget` or `WidgetT MainWebsite IO ()` and `aSubWebsiteWidget` looks like `aSubWebsiteWidget :: (MonadWidget (HandlerT SubWebsite (HandlerT SubWebsite IO))) => HandlerT SubWebsite (HandlerT SubWebsite IO) ()`. It gets HandlerT because of `getRouteToParent`.

I thought `handlerToWidget` might help but that just wraps the original type in `WidgetT` and I'm not sure how to get that to work with the `MainWebsite` widgets. Also `widgetToParentWidget` seems to give a WidgetT wrapped in HandlerT and I'm not sure how to get it out. 

Any ideas how to get `aSubWebsiteWidget` running with the `MainWebsite` widgets? This might be a good addition to the Yesod Cookbook.

Edit: here's my current work around. It is not ideal because it puts a burden of knowing the correct route in the Main package and makes the sub package code less readable

```
aSubWebsiteWidget route = toWidget [julius|
  @{route}
|]
```

```
mainJSFile :: Widget
mainJSFile = do
  aSubWebsiteWidget (SubsiteR SubWebsiteQuery)
```

**Comment by snoyberg** [comment]
The only way to get this to work is to pass in your `Route child -> Route parent` wrapper manually. The reason is that there's no way for the system to figure out which subsite it's talking about. A simple case to demonstrate that would be when you have two of the same subsite in an app, e.g.:

```
/foo FooR Subsite getFoo
/bar BarR Subsite getBar
```

If you then include a `WidgetT site IO ()` from the `Subsite` package, there's no way to know if the generated route should start with `/foo` or `/bar`. So you can define your widget as something like:

```haskell
aSubsiteWidget :: (Route Subsite -> Route site) -> WidgetT site IO ()
aSubsiteWidget toParent = toWidget [julius|@{toParent SubWebsiteQuery}|]
```

And then use it as:

```haskell
mainJSFile :: Widget
mainJSFile = aSubWebsiteWidget SubsiteR
```

If desired, you could define a typeclass for providing that route wrapper so you don't need to pass it in at every call site, but that will necessarily limit you to one instance of that subsite per app (which is probably fine).

**Comment by mchaver** [comment]
What would the route wrapping type class look like?

Another related question. Is it possible to call a handler from `SubWebsite` in `MainWebsite`? Or is this the same issue as above?

```
getSubWebsiteHomeR :: SomeYesodTypeClass master => HandlerT SubWebsite (HandlerT master IO) Html
getSubWebsiteHomeR = do
  [whamlet|
<div>Hello
|]
```

```
getMainWebsiteHomeR :: Handler Html
getMainWebsiteHomeR = do
  x <- getSubWebsiteHomeR
  [whamlet|
<div>
  ^{x}
|]
```

**Comment by snoyberg** [comment]
The typeclass might be:

```haskell
class HasSubWebsite master where
    fromSubWebsiteRoute :: Route SubWebsite -> Route master
```

This is the same issue as above; you need to define your `Handler` function as something like:

```haskell
someHandler :: SubWebsite -> HandlerT master IO a
```

**Comment by mchaver** [comment]
Sorry to bother you again. I thought I would be able to figure it out by looking around the source code and learning more about Yesod Monad Transformers, but I am still struggling to figure out what the type class instance would like for those two functions.

**Comment by snoyberg** [comment]
As a hint in the right direction, consider that, in the scaffolded site, StaticR is a constructor in the master site that converts a sub route into a master route. You'll have something similar in your case.
