### ISSUE TITLE
yesod-test function(byLabel, etc) don't escape newline

### ISSUE THREAD

**Issue by ncaq** [yesodweb/yesod#1207]
yesod-test function(byLabel, etc) don't escape ';'(semicolon)

I use ';' `elem` Text to byLabel, then http post params was broken.

Of course, I can use `decodeUtf8 $ urlEncode True $ encodeUtf8`.
But, Should I write `decodeUtf8 $ urlEncode True $ encodeUtf8` always?

Do you know smart solution?

**Comment by snoyberg** [comment]
I do not understand this question, can you clarify? FWIW, a semicolon is a valid query string separator character, if that's relevant.

**Comment by ncaq** [comment]
Sorry, I was wrong.
I don't escape character to newline. not semicolon.

**Comment by snoyberg** [comment]
I don't understand the question

**Comment by ncaq** [comment]
I could not tell you what I wanted to say because my English ability was not available.
ByLabel is also going to be deprecated and I will close this issue.
