### ISSUE TITLE
Trouble with inner select with limit

### ISSUE THREAD

**Issue by felipexpert** [yesodweb/yesod#1217]
There is some time I am trying to solve a problem, and I posted a question on StackOverflow to get some clarity, but until the time noone did post any help there. Please, someone, read this question: http://stackoverflow.com/questions/36665736/yesod-esqueleto-how-can-i-express-selects-with-inner-pagination

**Comment by jezen** [comment]
Looks like the question on SO has an answer, so I will close this.
