### ISSUE TITLE
Application binary looks for templates/*.lucius files in production

### ISSUE THREAD

**Issue by narendraj9** [yesodweb/yesod#1220]
I have followed the instructions in the deployment chapter of yesod book. But to make it work correctly I have to manually copy the templates/ folder to the same directory as static/. I am wondering why the contents of those files were not included during compile time.

**Comment by snoyberg** [comment]
You're most likely not compiling with production settings. How exactly are
you compiling the binary?

**Comment by narendraj9** [comment]
stack exec yesod keter

And I would like to know where keter gets the information about postgres.

Thanks,

Narendra Joshi

**Comment by snoyberg** [comment]
Try doing a `stack clean` first, though no guarantees. Have a look in the
Settings.hs and config/settings.yml for information on settings, the
scaffolded site is self documenting.

**Comment by narendraj9** [comment]
I tried doing stack clean it didn't work. I could not understand how the
DEVELOPMENT flag is passed to stack but it seems `yesod keter ` doesn't
pass it while `yesod devel` does. Can you provide links of some
settings.yml and keter.yml in production.

Thanks,
Narendra Joshi

**Comment by snoyberg** [comment]
Both of these are available in the standard scaffolding.

**Comment by narendraj9** [comment]
I have tried almost everything. But I need to copy the templates folder along with the binary for the site to work. I don't know why stack isn't building for production. I think I will have to try to go back to cabal. Here is the repo:https://github.com/narendraj9/hledger-serve

**Comment by narendraj9** [comment]
And updating the static files doesn't seem to cause new files to be sent to clients as is explained in the book. Can you think of any reasons? The static file is added as with `addScript`.

**Comment by snoyberg** [comment]
Do you get this behavior with a freshly scaffolded site? What version of
Stack an are you using?

**Comment by silky** [comment]
@narendraj9 how exactly are you running `keter`? as far as i can see you haven't removed a key line from this file: https://github.com/narendraj9/hledger-serve/blob/ff1b1dd24f4526fb595058b7da96507f8412aa70/webservice/config/keter.yml so, with that keter.yml, `stack exec -- yesod keter` will just fail immediately.

if i actually edit that file to set `user-edited: true`, change it to be able to find the binary, *and* correct this line - https://github.com/narendraj9/hledger-serve/blob/master/webservice/Settings.hs#L68 - to be `False` (i'm not sure why you changed that?), then when i run `stack exec -- yesod keter`, and copy the resulting webservice.keter into my `/opt/keter/incoming` folder everything works as expected; i.e. i can access content from the `/static` path ...

**Comment by narendraj9** [comment]
I was using `stack exec yesod keter` instead of `stack exec -- yesod
keter`. I don't know what difference it would make. I changed that value to
`True` so that I could have more detailed logs even in production as I was
only able to see the http request headers otherwise. With keter this works,
but keter wasn't working as expected. I will try again now. Thanks for
taking the time :)

**Comment by narendraj9** [comment]
No, I haven't tried it with a freshly scaffolded site.

**Comment by silky** [comment]
fyi, the `--` won't make a functional difference here; it's just used to ensure that we no longer pass any subsequent options to `stack` but to whatever sub-command we are `exec`ing.

http://unix.stackexchange.com/questions/11376/what-does-double-dash-mean-also-known-as-bare-double-dash

**Comment by jezen** [comment]
Looks like this is not actually an issue, so I’ll close this.
