### ISSUE TITLE
Yesod.Auth.Email.verifyR leaks verification key ids.

### ISSUE THREAD

**Issue by chreekat** [yesodweb/yesod#1221]
E.g. http://localhost:3000/auth/page/email/verify/3/f22uWzaa7s2aqxV8Id1Hz3cs

Here, `/3/` is the verification key id.

I would expect the verification url to _only_ use the key itself.

I note that `verifyR` already has a `FIXME` comment. :) Maybe this is what it refers to?

I guess fixing this will require adding a new method to the YesodAuthEmail typeclass, in order to work backwards from just the key itself.

**Comment by snoyberg** [comment]
I'm ambivalent about this one. Leaking the key ID is not a major issue IMO.
That said, if someone wants to take a stab at this, I'll happily review.

**Comment by chreekat** [comment]
Actually, it might be particularly harmless once keys are deleted in #1222.
I'll think about how much i really care about this issue...
On Apr 21, 2016 11:15 PM, "Michael Snoyman" <notifications@github.com>
wrote:

I'm ambivalent about this one. Leaking the key ID is not a major issue IMO.
That said, if someone wants to take a stab at this, I'll happily review.

On Thu, Apr 21, 2016 at 11:25 PM Bryan Richter <notifications@github.com>
wrote:

> E.g.
> http://localhost:3000/auth/page/email/verify/3/f22uWzaa7s2aqxV8Id1Hz3cs
>
> Here, /3/ is the verification key id.
>
> I would expect the verification url to *only* use the key itself.
>
> I note that verifyR already has a FIXME comment. :) Maybe this is what it
> refers to?
>
> I guess fixing this will require adding a new method to the YesodAuthEmail
> typeclass, in order to work backwards from just the key itself.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/yesodweb/yesod/issues/1221>
>

—
You are receiving this because you authored the thread.
Reply to this email directly or view it on GitHub
<https://github.com/yesodweb/yesod/issues/1221#issuecomment-213277826>

**Comment by chreekat** [comment]
I still think it's a good idea to fix this some day, but I don't think it's high enough priority for me to do it now.

I can't tell how/if these issues are organized, so I'm not sure if I should keep this open, or how you'd like to deal with it. I'm fine with closing it though.

**Comment by felixSchl** [comment]
The way it could be done is encrypting the verification id in the verification key - is that a reasonable approach?

**Comment by StevenXL** [comment]
We tried to address this but found that the required changes were too high a cost given the small benefit. Please see discussion in #1557.
