### ISSUE TITLE
Yesod cache busting not working

### ISSUE THREAD

**Issue by narendraj9** [yesodweb/yesod#1224]
I modified files in /static directory, touched Settings/StaticFiles.hs, deployed with `stack exec -- yesod keter`. But the files being used have the same etags parameter.

**Comment by 2piix** [comment]
Yup, me too.  yesod-bin-1.5.2.6 here, running in a stack environment too.

Heck, I even made a new repo for my yesod project and built against that.  Whatever is going on is happening in some global cache.

**Comment by snoyberg** [comment]
This sounds like the issue reported in https://github.com/yesodweb/yesod/issues/1551.

**Comment by narendraj9** [comment]
I filed this issue long time ago. I am no longer aware of the progress/status. Hence, closing this one.
