### ISSUE TITLE
'yesod keter' terminating on dist/build/Project/Project not existing

### ISSUE THREAD

**Issue by pharpend** [yesodweb/yesod#1228]
Hello there,

```
$ stack --version
Version 1.0.4.3, Git revision db1afb275ebd64016e8ef0db122f0f03da9e5906 (3242 commits) x86_64
```

My application is using Stackage LTS 5.15.

I am trying to create a keter bundle for my application.

I ran `stack exec -- yesod keter`, and uploaded the `.keter` file to my server, got the same issue with a truncated tar archive as <https://github.com/yesodweb/yesod/issues/996>.

I looked closely at the output of `stack exec -- yesod keter`, and this popped up at the end:

```
WARNING: Installation path /home/pete/src/zuzero/zzps/dist/bin not found on the PATH environment variable
yesod: dist/build/zzps/zzps: getFileStatus: does not exist (No such file or directory)
```

I tried the suggested solution there, and `stack install`ed the newest `yesod-bin`, but I still get the error running just plain `yesod keter`.

Thanks in advance.

**Comment by snoyberg** [comment]
You need to update your `exec` value in `config/keter.yml` to contain `../dist/bin/zzps` instead. I'm going to update the scaffold with more information on this.

**Comment by pharpend** [comment]
> You need to update your `exec` value in `config/keter.yml` to contain
> `../dist/bin/zzps` instead. I'm going to update the scaffold with more
> information on this.

Thanks! That seemed to fix it.

Peter Harpending
