### ISSUE TITLE
Sending an Email

### ISSUE THREAD

**Issue by Miguelme** [yesodweb/yesod#1235]
I was wondering if this is a functionality you have in mind because it would be great if the framework allowed the mail sending. What could be a workaround for this ?

**Comment by psibi** [comment]
> What could be a workaround for this ? 

http://stackoverflow.com/a/22540909/1651941
https://github.com/yesodweb/yesod/wiki/Sending-email

**Comment by jezen** [comment]
There are quite a few approaches to sending email from a Yesod app. A couple that I use are AWS SES, and also using an external email service by sending HTTP requests to it. Since this is a solved problem, I will close this issue.
