### ISSUE TITLE
Yesod.Auth.Email use of unsafePerformIO

### ISSUE THREAD

**Issue by chreekat** [yesodweb/yesod#1245]
I know "unsafe" means "to be used with care". It would give me some peace of mind if someone could provide justification (perhaps via a comment at [the use site](https://github.com/yesodweb/yesod/blob/5342f891f39f1088049436a38ec51aca52a5e032/yesod-auth/Yesod/Auth/Email.hs#L713)) to indicate that care *has* been taken. I, for one, am not familiar enough with the semantics to know how this works in the face of multithreading and so on.

**Comment by bobjflong** [comment]
I believe the usage is per this idiom: https://wiki.haskell.org/Top_level_mutable_state

Discussion in the original PR: https://github.com/yesodweb/yesod/pull/1011#issuecomment-111516864

**Comment by chreekat** [comment]
Thanks @bobjflong!

Sorry for commit spam, I force-pushed some commits referencing this.
