### ISSUE TITLE
isAuthorized not working with defaultCsrfMiddleware

### ISSUE THREAD

**Issue by agreif** [yesodweb/yesod#1246]
I found the following behaviour:

if I use 'defaultCsrfMiddleware' in Foundation.hs, then the 'isAuthorized' function is not called, or does not work as expected

what I did (LTS-6.6):

stack new my-project7 yesod-sqlite

in Foundation.hs use `defaultCsrfMiddleware` and `isAuthorized` returns always `Unauthorized`

    yesodMiddleware = defaultCsrfMiddleware
    ...
    -- Routes not requiring authentication.
    -- isAuthorized (AuthR _) _ = return Authorized
    -- isAuthorized FaviconR _ = return Authorized
    -- isAuthorized RobotsR _ = return Authorized
    -- Default to Authorized for now.
    isAuthorized _ _ = return $ Unauthorized "not authorized"

I would expect that all pages return a 403 Forbidden, but this is not the case. I can still browse all pages.
This seems to be a problem with defaultCsrfMiddleware, or do I misunderstand something?

BTW With the defaultYesodMiddleware it works fine.

thanks,
Alex.

**Comment by snoyberg** [comment]
Minimal repro:

```haskell
{-# LANGUAGE OverloadedStrings     #-}
{-# LANGUAGE QuasiQuotes           #-}
{-# LANGUAGE TemplateHaskell       #-}
{-# LANGUAGE TypeFamilies          #-}
import           Yesod

data HelloWorld = HelloWorld

mkYesod "HelloWorld" [parseRoutes|
/ HomeR GET
|]

instance Yesod HelloWorld where
    yesodMiddleware = defaultCsrfMiddleware
    isAuthorized _ _ = return $ Unauthorized "not authorized"

getHomeR :: Handler Html
getHomeR = defaultLayout [whamlet|Hello World!|]

main :: IO ()
main = warp 3000 HelloWorld
```

I'm not familiar with `defaultCsrfMiddleware` myself. I'll try to poke at this, but if someone else gets to it, please speak up :)

**Comment by MaxGabriel** [comment]
Oh, that's my bad. I had always done `defaultYesodMiddleware . defaultCsrfMiddleware`. The implementation of `defaultCsrfMiddleware` needs to be changed to call the handler like `defaultYesodMiddleware`, right? Something like:

```
defaultCsrfMiddleware :: Yesod site => HandlerT site IO res -> HandlerT site IO res
defaultCsrfMiddleware handler = do
    defaultCsrfSetCookieMiddleware
    defaultCsrfCheckMiddleware
    handler
```

**Comment by snoyberg** [comment]
Either that or we make a doc fix for this. I'm ambivalent on which approach
makes more sense.

**Comment by MaxGabriel** [comment]
I'd expect the CSRF middleware to have the same behavior as the other middlewares, `defaultYesodMiddleware` and `sslOnlyMiddleware`, so making the change in the code seems preferable to me. Could that be a breaking change for some people?

**Comment by snoyberg** [comment]
It's a gray area. I'd say it's acceptable to make the change in a minor
release together with a notification sent to the mailing list. Alternative:
deprecate the current function and create a new function with the given
behavior.

**Comment by MaxGabriel** [comment]
Ok, I'll test this fix and submit a PR tonight.

**Comment by MaxGabriel** [comment]
Wait, I think I was completely misunderstanding this issue the whole time. I thought there was some sort of bug with `defaultCsrfMiddleware` that was breaking authorization that I couldn't wrap my head around. Really the only issue `isAuthorized` is only called by `defaultYesodMiddleware`. In that case I think a doc fix is the much better move, to say that you should use both. I don't see a reason why `defaultCsrfMiddleware` should duplicate the `isAuthorized` behavior.

**Comment by snoyberg** [comment]
SGTM
