### ISSUE TITLE
CSRF failures due to duplicate XSRF-TOKEN values

### ISSUE THREAD

**Issue by bitemyapp** [yesodweb/yesod#1247]
![screenshot from 2016-07-08 13-09-39](https://cloud.githubusercontent.com/assets/320177/16697027/45545982-450d-11e6-9cba-915edac6fef7.png)

Presently, what you see in the screenshot will work because the XSRF-TOKEN values are the same, however if they differ, you'll get that CSRF token middleware error we all know and love.

I do not know how two different XSRF tokens were generated (no repro), but it's not clear to me why there isn't a single XSRF token for the `/` path which covers requests being made from other pages anyway.

I read this thread: https://github.com/yesodweb/yesod/issues/1016

It did not clear up for me why there should be multiple `X-XSRF-TOKEN` values in the cookies.

AFAICT, this code is responsible for the duplicates: 
https://github.com/yesodweb/yesod/blob/8bbe91cbfe68a87735f91251c91535abeb40ad9d/yesod-core/Yesod/Core/Handler.hs#L858-L859

Some snippets:

```haskell
addHeader :: MonadHandler m => Text -> Text -> m ()
addHeader a = addHeaderInternal . Header (encodeUtf8 a) . encodeUtf8

setCookie :: MonadHandler m => SetCookie -> m ()
setCookie = addHeaderInternal . AddCookie

-- | Internal use only, not to be confused with 'setHeader'.
addHeaderInternal :: MonadHandler m => Header -> m ()
addHeaderInternal = tell . Endo . (:)

tell :: MonadHandler m => Endo [Header] -> m ()
tell hs = modify $ \g -> g { ghsHeaders = ghsHeaders g `mappend` hs }

data GHState = GHState
    { ghsSession :: SessionMap
    , ghsRBC     :: Maybe RequestBodyContents
    , ghsIdent   :: Int
    , ghsCache   :: TypeMap
    , ghsCacheBy :: KeyedTypeMap
    , ghsHeaders :: Endo [Header]
    }
```

**Comment by bitemyapp** [comment]
This prevents duplicates but the paths do change as you shuffle about. I don't know how acceptable a solution it is but it should at least prevent the CSRF failures we had.

https://github.com/bitemyapp/yesod/commit/5e4cefc9ad3880258d9685849dea1f9ea0daf768

**Comment by MaxGabriel** [comment]
Oh, I didn't think about specifying the path when I implemented this. I haven't researched it yet, but

> a single XSRF token for the / path which covers requests being made from other pages...

sounds good to me

**Comment by bitemyapp** [comment]
@MaxGabriel by solution doesn't currently do that, but I could modify it. I don't really understand what place duplicate cookie values or mostly duplicate ones with different paths are even supposed to mean here. I'd like to understand the problem a bit more first before doing more.

**Comment by MaxGabriel** [comment]
Here's my guess of what's going on:

1. When the [cookie is set](https://github.com/yesodweb/yesod/blob/8bbe91cbfe68a87735f91251c91535abeb40ad9d/yesod-core/Yesod/Core/Handler.hs#L1371-L1377) by the middleware, its path defaults to the current path of the request.
2. Based on [a StackOverflow answer](http://stackoverflow.com/a/13801330/1176156), cookies are uniqued by (domain, name, path), so there can be multiple cookies with the same name I guess. This is the relevant part of [RFC 2965](http://www.ietf.org/rfc/rfc2965.txt):

    >  3.3.3  Cookie Management  If a user agent receives a Set-Cookie2
   response header whose NAME is the same as that of a cookie it has
   previously stored, the new cookie supersedes the old when: the old
   and new Domain attribute values compare equal, using a case-
   insensitive string-compare; and, the old and new Path attribute
   values string-compare equal (case-sensitive).

3. When the Javascript looks up the cookie by name, it's probably getting the older cookie with the incorrect CSRF token value. It then sends the wrong CSRF token to the server, which the server rejects.

**Comment by MaxGabriel** [comment]
Hm, I'm having trouble reproing getting the CSRF token for a path like "/signup", not sure why.

**Comment by bitemyapp** [comment]
@MaxGabriel We have GHCJS code talking to the backend, did you try performing a CSRF secured AJAX call?

**Comment by MaxGabriel** [comment]
Yes, using the comment AJAX text field that comes with the scaffolding. I can see the XSRF token in the headers of that POST request, too.

**Comment by MaxGabriel** [comment]
Ok got it, wasn't thinking that the path needed to be something like:

```
localhost:3000/foo/bar
```

for the cookie path to be `foo`. Working on a fix
