### ISSUE TITLE
setting Content-Type for json-API

### ISSUE THREAD

**Issue by agreif** [yesodweb/yesod#1251]
for an application I plane to use the json-api. In the specs (http://jsonapi.org/format/#content-negotiation-servers) is required that the server returns `Content-Type: application/vnd.api+json` 
In case I have a handler with the following

```
getFriendsR :: Handler Value
getFriendsR = do
    setHeader "Content-Type" "application/vnd.api+json"
    -- build result
    returnJson result
```

then my response contains two `Content-Type` declarations in the form, that does not seem to be correct:

```
Access-Control-Allow-Origin:http://localhost:3000/friends
Content-Type:application/json; charset=utf-8
Content-Type:application/vnd.api+json
Date:Tue, 26 Jul 2016 19:57:28 GMT
Server:Warp/3.2.7
Set-Cookie:_SESSION=B4Q....k2UcgOKbtAUslT6BqAJuo0HA=; Path=/; Expires=Tue, 26-Jul-2016 21:57:28 GMT; HttpOnly
Transfer-Encoding:chunked
Vary:Accept, Accept-Language
```

what is the best way in a JSON response to use my custom `Content-Type`?

thanks,
Alex.

**Comment by snoyberg** [comment]
The easiest is probably to use `TypedContent` explicitly, which will allow you to specify a mime type. Another possibility is to define a `newtype` wrapper with its own `ToTypedContent` instance.

**Comment by jezen** [comment]
The `TypedContent` approach is definitely the right one here; it works very well. I’ll close this.
