### ISSUE TITLE
boolField should use a <fieldset> to group the radio buttons

### ISSUE THREAD

**Issue by enolan** [yesodweb/yesod#1252]
Presently, a `boolField` outputs HTML like this:
```html
<div class="required ">
  <label for="hident5">Are you a computer programmer?</label>
  <input id="hident5-yes" name="f4" value="yes" type="radio">
  <label for="hident5-yes">Yes</label>
  <input id="hident5-no" name="f4" value="no" type="radio">
  <label for="hident5-no">No</label>
</div>
```
Since no element actually has the id "hident5", the label for the field isn't attached to anything. This is "wrong" in an aesthetic/semantic web sense, makes it a bit harder to find the buttons when using webdriver and supposedly is bad for screen readers. I've never used a screen reader so I don't know if that one is actually a problem. According to [this SO answer](http://stackoverflow.com/a/13273841/1686629), you're supposed to use `fieldset` to group form controls and a `label` can be attached to exactly one control. Here's what I think it should output:
```html
<fieldset class="required ">
  <legend>Are you a computer programmer?</legend>
  <input id="hident5-yes" name="f4" value="yes" type="radio">
  <label for="hident5-yes">Yes</label>
  <input id="hident5-no" name="f4" value="no" type="radio">
  <label for="hident5-no">No</label>
</fieldset>
```

I can write a PR for this.

**Comment by snoyberg** [comment]
SGTM, PR would be great!

**Comment by enolan** [comment]
I spent some time on this. Turns out `<fieldset>` and `<legend>` have severe restrictions on how you can apply CSS to them and I'd be sacrificing the appearance of the page just to make my testing code slightly simpler. Doesn't seem like a good idea anymore.
