### ISSUE TITLE
Html tag 'optgroup' in 'selectField'

### ISSUE THREAD

**Issue by skvl** [yesodweb/yesod#1253]
Hello.

I'd like to add a select field populated from database in which entries are grouped. Currently I use 'BootstrapBasicForm'.

What is the simplest way to do that?

Thanks!

**Comment by schoettl** [comment]
I need also this grouped select field (for my [instrument model selection](https://ziach.intensovet.de/nn2gs#einstellungen)) and I want to use AForms, no InputForms. See [\<optgroup>](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/optgroup).

I'd write a function `selectFieldGrouped` and `selectFieldGroupedList` (similar to [selectField](https://hackage.haskell.org/package/yesod-form-1.6.7/docs/Yesod-Form.html#v:selectFieldList)).

Would a PR for this be accepted?

The API could be

```
selectFieldGroupedList
  :: (Eq a, RenderMessage site FormMessage, RenderMessage site msg, RenderMessage grp FormMessage)
  => [(grp, [(msg, a)])]
  -> Field (HandlerFor site) a

selectFieldGrouped
  :: (Eq a, RenderMessage site FormMessage, RenderMessage grp FormMessage)
  => HandlerFor site [(grp, OptionList a)]
  -> Field (HandlerFor site) a 
```

An alternative for the second one would be:
```
data OptionList a
  = OptionList
    { olOptions :: [Option a]
    , olReadExternal :: Text -> Maybe a
    }
  | OptionListGrouped
    { … }
```

But then the code for the existing `selectField` must be changed and a lot of helpers (e.g. `mkOptionList`) must be added.

What do you think?

**Comment by snoyberg** [comment]
I'm open to such an addition.
