### ISSUE TITLE
Attach data to request

### ISSUE THREAD

**Issue by lippling** [yesodweb/yesod#1254]
I've written an auth plugin, that decrypts and validates the signature of a token (must be run in `HandlerT`). Later, I want to access the token in `HandlerT`.
I don't want to decrypt and validate the token a second time, so what is the best approach to "attach" data to a request (without using cookies)?

**Comment by snoyberg** [comment]
I think you want to use the `cached` function: https://www.stackage.org/haddock/lts-6.10/yesod-core-1.4.22/Yesod-Core-Handler.html#v:cached. Check out the implementation of `defaultMaybeAuthId` (https://www.stackage.org/haddock/nightly-2016-08-02/yesod-auth-1.4.13.3/src/Yesod.Auth.html#defaultMaybeAuthId) for an example usage, via `cachedAuth`.

**Comment by lippling** [comment]
Thanks a lot. I don't know why I missed that. I stumbled across vault, but I was not sure how to use it in Yesod.
It works perfectly.

**Comment by nhooyr** [comment]
This should be closed?

**Comment by snoyberg** [comment]
Good catch, thanks.
