### ISSUE TITLE
How to render routes to static files in a widget?

### ISSUE THREAD

**Issue by mrkkrp** [yesodweb/yesod#1260]
Hi, some time passed since I touched Yesod and maybe this is simple thnig to ask, but I don't seem to get it.

I'm writing a widget that will use a static file (an image). Then I want to use the widget on my site. The code is as following:

```haskell
myWidget :: WidgetT site IO ()
myWidget = do
  render <- getUrlRender
  [whamlet|
$newline never
<img src="#{render img_markdown_mark_svg}" title="With markdown support">
With markdown support
|]
```

The type `WidgetT site IO ()` seems to be too general. The fact that I render this `img_markdown_mark_svg` route (generated by the template haskell helper) makes the type to be rather `WidgetT Static IO ()` which on one hand makes sense because we use a route that belongs to `Static` site, but on the other hand when I use this inside of another widget that deals with `App` site I'm getting “cannot match `App` with `Static`”, which also makes sense.

My question is how do I render routes to static files in widgets that should work with `App` site, or what type should `myWidget` have so I can use it in something like this:

```haskell
-- | Markdown-aware description field.

descriptionField
  :: ( MonadHandler m
     , RenderMessage (HandlerSite Handler) FormMessage )
  => Attrs             -- ^ Attributes
  -> Text              -- ^ Label of the field
  -> Maybe Text        -- ^ Default value
  -> Checker m (SomeMessage (HandlerSite m)) Text -- ^ 'Checker' monoid
  -> AForm m Text
descriptionField = markdownField MarkdownFieldSettings
  { mfsEditingTabLabel = "Edit"
  , mfsPreviewTabLabel = "Preview"
  , mfsAppendix        = myWidget
  , mfsAutoResizing    = True }
```

(This a sort of short cut to Yesod applicative forms but its type should give you a hint what sort of type mismatch I'm running into. I'm willing to change `m` to `Handler`, but apprently it does not want `HandlerSite Handler ~ App`, but only `Static`.)

**Comment by mrkkrp** [comment]
My current understanding is that it is not possible because to render static routes one needs `getStatic` or `appStatic` from the `App` (foundation) type which is available only in handlers. So static routes can be rendered only handlers.

**Comment by snoyberg** [comment]
I think the answer to your question is to pass in a function of type `Route Static -> Route site`, and then you can use that inside your function. The caller would then pass in (in the example of the scaffolded site) `StaticR`.

**Comment by mrkkrp** [comment]
Yeah, I think that would work. Thanks, @snoyberg!
