### ISSUE TITLE
Yesod cache does not store nested cached action results

### ISSUE THREAD

**Issue by CthulhuDen** [yesodweb/yesod#1266]
I am talking about per-request cache (`Yesod.Core.Handler.cached`).

When [`cached'](https://github.com/yesodweb/yesod/blob/master/yesod-core/Yesod/Core/Handler.hs#L997) executes action which also calls `cached`, outer `cached` will override new cache entries having been created during inner `cached` invocations. I suggest merging cached types map instead of overwriting it [here](https://github.com/yesodweb/yesod/blob/master/yesod-core/Yesod/Core/Handler.hs#L1006).

**Comment by snoyberg** [comment]
SGTM. Want to send a PR?
