### ISSUE TITLE
Adding a new handler adds it under wrong stanza

### ISSUE THREAD

**Issue by amitaibu** [yesodweb/yesod#1273]
Adding a new handler

![yesod-scaffold-build_ _amitai_amitais-macbook-pro_ _zsh_ _111x28](https://cloud.githubusercontent.com/assets/125707/18176816/0087091e-7080-11e6-947b-f001c8c077e8.jpg)

Results with the handler registered under the `test-suite` stanza 

![yesod-scaffold-build_cabal_ __library_webserver_documents_haskell_yesod-scaffold-build](https://cloud.githubusercontent.com/assets/125707/18176804/f6a32c2a-707f-11e6-9f99-1bea65c051c2.jpg)

**Comment by snoyberg** [comment]
Thanks, should be fixed in newest yesod-bin (1.4.18.3).

**Comment by amitaibu** [comment]
Thanks. Small question, how do I see if this is published already?  I tried to `stack build yesod-bin` but I still see the old behavior.

**Comment by snoyberg** [comment]
You'd have to tell it an exact version, by default it will just use the package version in your snapshot. Try `stack build yesod-bin-1.4.18.3` or add that to your `extra-deps` in stack.yaml.

**Comment by amitaibu** [comment]
Will do, thanks!

**Comment by amitaibu** [comment]
Sorry, I'm getting this:

```
$ stack build yesod-bin-1.4.18.3
Didn't see yesod-bin-1.4.18.3 in your package indices.
Updating and trying again.
Fetching package index ...remote: Counting objects: 1, done.
remote: Total 1 (delta 0), reused 1 (delta 0), pack-reused 0
Unpacking objects: 100% (1/1), done.
Fetched package index.    
The following package identifiers were not found in your indices: yesod-bin-1.4.18.3
Possible candidates: yesod-bin-1.4.0, yesod-bin-1.4.0.1, yesod-bin-1.4.0.2, yesod-bin-1.4.0.3, yesod-bin-1.4.0.4, yesod-bin-1.4.0.5, yesod-bin-1.4.0.6, yesod-bin-1.4.0.7, yesod-bin-1.4.0.8, yesod-bin-1.4.0.9, yesod-bin-1.4.1, yesod-bin-1.4.1.1, yesod-bin-1.4.1.2, yesod-bin-1.4.2, yesod-bin-1.4.3, yesod-bin-1.4.3.1, yesod-bin-1.4.3.2, yesod-bin-1.4.3.3, yesod-bin-1.4.3.4, yesod-bin-1.4.3.5, yesod-bin-1.4.3.6, yesod-bin-1.4.3.7, yesod-bin-1.4.3.9, yesod-bin-1.4.3.10, yesod-bin-1.4.3.11, yesod-bin-1.4.4, yesod-bin-1.4.5, yesod-bin-1.4.5.1, yesod-bin-1.4.6, yesod-bin-1.4.7, yesod-bin-1.4.7.1, yesod-bin-1.4.7.2, yesod-bin-1.4.8, yesod-bin-1.4.9, yesod-bin-1.4.9.1, yesod-bin-1.4.9.2, yesod-bin-1.4.10, yesod-bin-1.4.11, yesod-bin-1.4.12, yesod-bin-1.4.13, yesod-bin-1.4.13.1, yesod-bin-1.4.13.2, yesod-bin-1.4.13.3, yesod-bin-1.4.14, yesod-bin-1.4.15, yesod-bin-1.4.16, yesod-bin-1.4.16.1, yesod-bin-1.4.17, yesod-bin-1.4.17.1, yesod-bin-1.4.18, yesod-bin-1.4.18.1, yesod-bin-1.4.18.2.
```

**Comment by snoyberg** [comment]
You'll need to wait about an hour got the indices to update.
