### ISSUE TITLE
Yesod - Running DB actions inside a subsite handler

### ISSUE THREAD

**Issue by psibi** [yesodweb/yesod#1277]
What is the proper way to run database query inside a subsite handler ?

Assuming, I have a subsite handler like this:

``` haskell
postProblemR :: Yesod master => HandlerT ApiSub (HandlerT master IO) TypedContent
postProblemR = do
  liftIO $ print "hello"
  insertedComment <- lift $ runDB $ insert undefined
  selectRep $ do
    provideRep $ return $ object
                   [ "name" .= name
                   , "age" .= age]
      where
        name = "Sibi" :: Text
        age = 28 :: Int
```

Note that `ApiSub` is just `data ApiSub = ApiSub`. If I remove the line `insertedComment <- lift $ runDB $ insert undefined`, it compiles well.

The actual compile error message:

```
    Couldn't match expected type ‘PersistEntityBackend val0’
                with actual type ‘YesodPersistBackend master’
    The type variable ‘val0’ is ambiguous
    Relevant bindings include
      postProblemR :: HandlerT ApiSub (HandlerT master IO) TypedContent
        (bound at Api.hs:33:1)
    In the second argument of ‘($)’, namely ‘insert undefined’
    In the second argument of ‘($)’, namely ‘runDB $ insert undefined’
    In a stmt of a 'do' block:
      insertedComment <- lift $ runDB $ insert undefined
```
How to approach this ?

**Comment by snoyberg** [comment]
This is just an issue of GHC not knowing the type of `val`, and therefore not knowing what backend to use. If you put in a concrete value instead of `undefined`, you'll likely get a much more informative error message, presumably telling you that you need to add a constraint like:

    YesodPersistBackend master ~ PersistEntityBackend YourConcreteType

**Comment by psibi** [comment]
What should be `YourConcreteType` ? Should it be the name of the persistent Entity ?

I did something like this and ran into some new error messages:

```
postProblemR :: (Yesod master, YesodPersistBackend master ~ PersistEntityBackend User) => HandlerT ApiSub (HandlerT master IO) TypedContent
postProblemR = do
  insertedComment <- lift $ runDB $ insert (User "gfgsgs" Nothing)
  liftIO $ print (insertedComment)
  selectRep $ do
    provideRep $ return $ object
                   [ "name" .= name
                   , "age" .= age]
      where
        name = "Sibi" :: Text
        age = 28 :: Int
```
The error messages were:

```
    Could not deduce (YesodPersist master)
      arising from a use of ‘runDB’
    from the context (Yesod master,
                      YesodPersistBackend master ~ PersistEntityBackend User)
      bound by the type signature for
                 postProblemR :: (Yesod master,
                                  YesodPersistBackend master ~ PersistEntityBackend User) =>
                                 HandlerT ApiSub (HandlerT master IO) TypedContent
      at Api.hs:33:17-139
 ```

So, I added the constraint ` YesodPersist master ` to the type signature and my error message was reduced to this:

``` shell
/home/sibi/github/startupmafia-yesod/Api.hs:67:26:
    Couldn't match expected type ‘SqlBackend’
                with actual type ‘YesodPersistBackend master’
    Relevant bindings include
      yesodSubDispatch :: Yesod.Core.Types.YesodSubRunnerEnv
                            ApiSub (HandlerSite (HandlerT master IO)) (HandlerT master IO)
                          -> Application
        (bound at Api.hs:67:5)
    In the expression: helper_ao8n
    In the expression:
      let
        helper_ao8n
          = inner_ao8m
          where
              inner_ao8m env2542_ao8j req2542_ao8k
                = ...
                where
                    ...
      in helper_ao8n
    In an equation for ‘yesodSubDispatch’:
        yesodSubDispatch
          = let
              helper_ao8n
                = inner_ao8m
                where
                    ...
            in helper_ao8n
```

I tried various variations on this, but was unable to proceed from it.

**Comment by snoyberg** [comment]
It could be some persistent entity, but given that you're using the SQL backend, you can just add:

```haskell
YesodPersistBackend master ~ SqlBackend
```

**Comment by psibi** [comment]
Unfortunately, I get the same error on adding it. I did try adding this previously. Note that the Handler is of a subsite.

```
[ 7 of 12] Compiling Api              ( Api.hs, .stack-work/dist/x86_64-linux/Cabal-1.22.5.0/build/Api.o )

/home/sibi/github/startupmafia-yesod/Api.hs:66:26:
    Couldn't match expected type ‘SqlBackend’
                with actual type ‘YesodPersistBackend master’
    Relevant bindings include
      yesodSubDispatch :: Yesod.Core.Types.YesodSubRunnerEnv
                            ApiSub (HandlerSite (HandlerT master IO)) (HandlerT master IO)
                          -> Application
        (bound at Api.hs:66:5)
    In the expression: helper_ao6J
    In the expression:
      let
        helper_ao6J
          = inner_ao6I
          where
              inner_ao6I env8275_ao6F req8275_ao6G
                = ...
                where
                    ...
      in helper_ao6J
    In an equation for ‘yesodSubDispatch’:
        yesodSubDispatch
          = let
              helper_ao6J
                = inner_ao6I
                where
                    ...
            in helper_ao6J

```

**Comment by chreekat** [comment]
Here's a full working example, fwiw:

    postResetPassphraseR
        :: ( Yesod master
           , AuthMaster master
           , YesodPersistBackend master ~ SqlBackend
           , YesodPersist master
           , RenderMessage master FormMessage
           )
        => HandlerT AuthSite (HandlerT master IO) Html
    postResetPassphraseR = do
        ((res, _), _) <- lift $ runFormPost (renderDivs credentialsForm)
        formResult
            (\c@Credentials{..} -> do
                mu <- lift (runDB (getBy (UniqueUsr (fromAuth credsIdent))))
                lift $ sendAuthEmail credsIdent =<< maybe
                    (pure BadPassReset)
                    (const $ VerifyPassReset . verifyToken
                        <$> runDB (priviligedProvisionalUser c))
                    mu
                redirectParent VerifyAccountR)
            res

This subsite has knowledge of the Persist'd types (like `UniqueUsr` here), but nothing more. `AuthMaster` doesn't add any constraints. So that means all that matters for `runDB` in this case is `Yesod master`, `YesodPersistBackend master ~ SqlBackend`, and `YesodPersist master`.

**Comment by psibi** [comment]
@chreekat 

I have all the three constrains and I'm getting the same error  I have mentioned above. This is my code for reference:

```
postProblemR :: (Yesod master, 
                 YesodPersistBackend master ~ SqlBackend,
                 YesodPersist master) => HandlerT ApiSub (HandlerT master IO) TypedContent
postProblemR = do
  insertedComment <- lift $ runDB $ insert (User "gfgsgs" Nothing)
  selectRep $ do
    provideRep $ return $ object
                   [ "name" .= name
                   , "age" .= age]
      where
        name = "Sibi" :: Text
        age = 28 :: Int
```
I have a feeling I'm doing something else wrong.

**Comment by chreekat** [comment]
Is the ` ~ ` failing because the types actually don't match? Is your master's site backend really `SqlBackend`? I mean, that's probably a dumb question, but it's my only guess.

**Comment by snoyberg** [comment]
@psibi The error seems to be coming from a totally different function:

```
yesodSubDispatch :: Yesod.Core.Types.YesodSubRunnerEnv
                            ApiSub (HandlerSite (HandlerT master IO)) (HandlerT master IO)
                          -> Application
```

It seems like something a bit more complicated is going on here, at least based on the error messages.

**Comment by psibi** [comment]
Thanks everyone. I resolved it. I also had to add the constraints for the instance `YesodSubDispatch` in subsite. That was not very obvious from the error messages. Phew! I will make sure to add an example of this in a cookbook.
