### ISSUE TITLE
yesod-bin: devel cannot satisfy -package-id main

### ISSUE THREAD

**Issue by spl** [yesodweb/yesod#1284]
I'm upgrading an application from lts-5.16 (GHC 7.10.3) to lts-7.1 (GHC 8.0.1), and I'm seeing the following error when running `yesod devel`:

```
<command line>: cannot satisfy -package-id main
    (use -v for more information)
```

I ran `yesod -v devel`, and, indeed, I see a `-package-idmain` tacked on to the `runghc` command.

I thought it might be due to the upgrade of `yesod-bin` from 1.4.18.1 to to 1.4.18.3, but I tried 1.4.18.1 with the new application version, and it gave me the same problem.

A diff of the `runghc` command string of the two versions of my application appears mostly as expected (changes in version numbers) except for one odd difference. In the old version, there is `-package-keyworkf_0ceLnjmRnbSBeWHnCnoeyy`, but in its place in the new version appears `-package-idmain`.

There are a number of differences between the two versions of the application; however, nothing in the changes of the `.cabal` or `stack.yaml` would appear to cause this. They are all dependency version changes or `extra-deps` changes.

**Comment by spl** [comment]
I wonder if this could be related to the GHC 8.0 changes: 833e74e797a2785b757a903347affe26ef760a5a. cc @erikd

**Comment by spl** [comment]
Also, that difference I mentioned above appears as the last argument to `runghc` before `devel.hs`.

**Comment by spl** [comment]
If I'm reading the order of the list items from 833e74e797a2785b757a903347affe26ef760a5a correctly, seems like the reason for the `-package-key` vs `-package-id` difference is due to this change:

```diff
+#if __GLASGOW_HASKELL__ >= 800
+    packageString flags = "-package-id" ++ Module.unitIdString flags
+#elif __GLASGOW_HASKELL__ == 710
     packageString flags = "-package-key" ++ Module.packageKeyString flags
 #else
     packageString flags = "-package-id" ++ Module.packageIdString flags ++ "-inplace"
```

**Comment by spl** [comment]
So it appears that `"main"` is the `Module.unitIdString`, but I have no idea where it's coming from.

Just reading the following from [`Module.hs`](https://github.com/ghc/ghc/blob/ca8c0e279a87d93c1fb10460c24ef35a9080238f/compiler/basicTypes/Module.hs):

1. UnitId: A ComponentId + a mapping from hole names (ModuleName) to Modules.
2. When Backpack is not being used, UnitId = ComponentId.
3. ComponentId: An opaque identifier provided by Cabal, which should uniquely identify such things as the package name, the package version, the name of the component, the hash of the source code tarball, the selected Cabal flags, GHC flags, direct dependencies of the component.  These are very similar to InstalledPackageId, but an 'InstalledPackageId' implies that it identifies a package, while a package may install multiple components with different 'ComponentId's.
4. Same as Distribution.Package.ComponentId.

**Comment by spl** [comment]
I'm using `Cabal` and `cabal-install` versions 1.24, in case that makes a difference.

**Comment by erikd** [comment]
I see the error:
```
<command line>: cannot satisfy -package-id main
    (use -v for more information)
```
if I'm building in a cabal sandbox and I switch from say ghc-7.10 to ghc-8.0. The solution is usually to do `cabal clean`.

**Comment by spl** [comment]
@erikd: Thanks. I'm glad you could reproduce it. Is there something `yesod-bin` could do to prevent this?

I tried `cabal clean`, and it didn't work.

I'm working in a `stack` project. I'm actually doing `stack exec -- yesod devel`. I already tried `stack clean` without luck. I'll try `rm -rf .stack-work` now, make everything rebuild, and try again.

**Comment by erikd** [comment]
I didn't reproduce, I've just seen it before, and it wasn't anything yesod related, just using cabal sandboxes and switching between compiler versions.

**Comment by spl** [comment]
@erikd: Ah, okay. Thanks.

**Comment by snoyberg** [comment]
Due to https://ghc.haskell.org/trac/ghc/ticket/12130, I'm not even able to
build the scaffolded site on GHC 8.0.1, so haven't hit this at all. Do you
have a repo this can be reproed with?

**Comment by spl** [comment]
@snoyberg:

> Due to https://ghc.haskell.org/trac/ghc/ticket/12130, I'm not even able to build the scaffolded site on GHC 8.0.1, so haven't hit this at all.

I ran into that one, too. For each module where the error occurred, I added:

```haskell
{-# LANGUAGE NoDisambiguateRecordFields #-}
{-# LANGUAGE NoRecordWildCards #-}
```
and removed any uses of record wildcards. That seems to have fixed the compilation errors.

> Do you have a repo this can be reproed with?

Unfortunately, no. It's a large proprietary app.

Also, my rebuild just completed after `rm -rf .stack-work`. The problem still exists.

**Comment by snoyberg** [comment]
OK, those language pragmas fix the issue with GHC 8, I can try to repro this.

It's tempting to remove the cabal-install dependency right now too.

**Comment by snoyberg** [comment]
Apparently the `-package-id` is no longer `main`, but would instead need to be something like `scaffold-0.0.0-7HrhUjYJCUj9s1CVz0vsT8`. I don't know why this changed.

**Comment by spl** [comment]
@snoyberg:

> Apparently the -package-id is no longer main, but would instead need to be something like scaffold-0.0.0-7HrhUjYJCUj9s1CVz0vsT8.

Yep, that's what I would expect, too.

**Comment by snoyberg** [comment]
@erikd It appears that the usage of `unitIdString` here isn't giving us the data we need. Do you have any idea if a function like `packageKeyString :: UnitId -> String` still exists in GHC 8.0?

**Comment by spl** [comment]
https://github.com/ghc/ghc/blob/ca8c0e279a87d93c1fb10460c24ef35a9080238f/compiler/basicTypes/Module.hs#L169-L173 :

```haskell
-- PackageKey: This is what we used to call UnitId.  We ditched
-- "Package" from the name when we realized that you might want to
-- assign different "PackageKeys" to components from the same package.
-- (For a brief, non-released period of time, we also called these
-- UnitKeys).
```

**Comment by spl** [comment]
https://github.com/ghc/ghc/blob/876b00ba25a615423f48b0cf9d443a9fd5dbd6f4/compiler/main/Packages.hs#L1458-L1461 :

```haskell
unitIdPackageIdString :: DynFlags -> UnitId -> Maybe String
unitIdPackageIdString dflags pkg_key
    | pkg_key == mainUnitId = Just "main"
    | otherwise = fmap sourcePackageIdString (lookupPackage dflags pkg_key)
```

Perhaps that is where the `"main"` is coming from?

**Comment by snoyberg** [comment]
Ooh, that's promising.

**Comment by spl** [comment]
And here `unitIdPackageIdString` is used for pretty-printing in `Module.hs`:

https://github.com/ghc/ghc/blob/876b00ba25a615423f48b0cf9d443a9fd5dbd6f4/compiler/basicTypes/Module.hs#L423-L431

**Comment by spl** [comment]
https://github.com/ghc/ghc/blob/876b00ba25a615423f48b0cf9d443a9fd5dbd6f4/compiler/basicTypes/Module.hs#L493-L496 :

```haskell
-- | This is the package Id for the current program.  It is the default
-- package Id if you don't specify a package name.  We don't add this prefix
-- to symbol names, since there can be only one main package per program.
mainUnitId      = fsToUnitId (fsLit "main")
```

**Comment by snoyberg** [comment]
It seems like it might be possible to just leave off this `main` argument entirely and get this to work, though I'm not sure why. I'm having success on my machine at least. @spl could you try out 69f0711 from the 1284-yesod-bin-ghc-8 branch?

**Comment by spl** [comment]
@snoyberg: Yep, that works here.

Could it be that it's able to find the other modules in the main package somehow?

**Comment by snoyberg** [comment]
I just realized that `-hide-all-packages` isn't turned on, which would explain it. In reality, given a Stack use case, almost all of this complication around getting the right set of packages is unnecessary, since Stack will provide a consistent package set in the databases. This really is agitating towards a massive simplification of `yesod devel` to take advantage of this, but perhaps for now simply releasing the small change I made makes sense.

**Comment by spl** [comment]
Agreed. Thank you very much for your help.

**Comment by vandenoever** [comment]
I'm seeing this issue with cabal 1.24.0.0 and yesod-bin 1.4.18.6.
The server that shows "The application isn’t built" is started, but after building `<command line>: cannot satisfy -package-id main`' is shown.

The commandline for `runghc` ends with `-package-idmain app/devel.hs`. (shown by `yesod devel -v`).

The `runghc` command can be run by hand without the `-package-idmain`, however this exits immediately.

**Comment by vandenoever** [comment]
It looks like 1284-yesod-bin-ghc-8 was not merged.

**Comment by snoyberg** [comment]
Doh, good catch. Hopefully 1.4.18.7 should do it.

**Comment by vandenoever** [comment]
Yep, now it's fixed. Thanks!

**Comment by snoyberg** [comment]
People here may be interested in this commit:

83d3a12a23c2d6c3a11fb469b90264990fbb1203

and this comment:

https://github.com/yesodweb/yesod/issues/1304#issuecomment-262495905
