### ISSUE TITLE
yesod-static doesn't obey Authentication

### ISSUE THREAD

**Issue by psibi** [yesodweb/yesod#1286]
Having something like this as an instance of `Yesod App`, doesn't really work in case of static pages:

```
instance Yesod App where
    ....
    isAuthorized (AuthR _) _ = return Authorized
    isAuthorized _ _ = return AuthenticationRequired
```

Basically, I want static pages which is properly authenticated.

**Comment by snoyberg** [comment]
Hmm... this is tricky. Authentication is handled by `yesodMiddleware`, which currently does not apply to subsites. I can see a few options here:

1. Apply is to subsites
2. Add a new method controlling subsite middlewares, and include auth there
3. Special-case adding subsite auth in

I'm not sure what makes sense, or if there are other options.

**Comment by psibi** [comment]
For my custom subsites, I make authentication work like this: https://github.com/psibi/yesod-rest/blob/6fad7a933bbb4dfe6cb470ff6a39c85975c6141f/Api.hs#L18

I haven't looked the codebase of yesod-static yet, but can't a similar method be used here ?

**Comment by snoyberg** [comment]
I think that the yesod-static subsite is different, in that it's actually calling out to a WAI application. Here's the relevant instance: https://www.stackage.org/haddock/lts-7.4/yesod-static-1.5.0.5/src/Yesod.Static.html#line-173

**Comment by psibi** [comment]
Ah right. I would still like to have at-least one method of having an authenticated subsite using `yesod-static`.

**Comment by snoyberg** [comment]
I'm open to the idea of modifying the static subsite to be inline with the example you gave. Want to give it a shot?

**Comment by psibi** [comment]
I looked on the codebase and was not able to figure out much. Would be interested to see your patch or can you point me what to do ?

**Comment by snoyberg** [comment]
I wasn't sure what to do either, I thought you had an idea based on your
patch. I can look into it later this week.

**Comment by snoyberg** [comment]
Alright, I've pushed a commit to 1286-yesod-static-apply-middleware which seems to work. Before deciding if it's a good idea to merge (it's a slightly breaking change), can you confirm that it works as expected for you?

**Comment by psibi** [comment]
Thanks, this works just as expected!
