### ISSUE TITLE
InternalError isn't very structured, can't generalize JSON API compatibility

### ISSUE THREAD

**Issue by bitemyapp** [yesodweb/yesod#1289]
Currently having a problem where I'd like to abide by http://jsonapi.org/format/ in the `errorHandler`, but `InternalError` contains a `Text`, not something structured.

I _think_ the most general way to handle this is to make the parameters to the data constructors associated types with defaults.

The below is the sort of thing I'm talking about, that JSON is what I'm limited to with the current `Text` value.

![screenshot from 2016-10-27 14-33-03](https://cloud.githubusercontent.com/assets/320177/19782352/1fdf13a2-9c53-11e6-8310-f944324a95c7.png)

Have I missed something that would help with what I want to do, or is a change like I've described above needed?

**Comment by snoyberg** [comment]
I think this is just handling things at the wrong layer. Why not catch
exceptions in your Handler and generate the desired output? InternalError
is intended as a last resort.

**Comment by psibi** [comment]
@snoyberg Is catching by `SomeException` the recommended method in the handler or is there some other way ?

**Comment by snoyberg** [comment]
Yes, on the caveat that you do so with something like [safe-exceptions](https://haskell-lang.org/library/safe-exceptions) to avoid catching async exceptions (like the slowloris protection exceptions).

**Comment by bitemyapp** [comment]
@snoyberg I certainly could do that, I was trying to avoid relying on middleware or a manually injected helper when there's already a handler for this in the Yesod class.

If that was the authorial intent, I'll close this issue.
