### ISSUE TITLE
No packages found ... "hsc2hs" executable

### ISSUE THREAD

**Issue by alx741** [yesodweb/yesod#1299]
I'm following: http://www.yesodweb.com/page/quickstart,  but completely unable to use Yesod at all. 

In step `4. Build libraries: stack build`  I get:

> No packages found in snapshot which provide a "hsc2hs" executable, which is a build-tool dependency of "skein"
> Missing build-tools may be caused by dependencies of the build-tool being overridden by extra-deps.
> This should be fixed soon - see this issue https://github.com/commercialhaskell/stack/issues/595
> While constructing the build plan, the following exceptions were encountered:
> Plan construction failed.

I've tried removing `~/.cabal`, `~/.stack` , the `stack` tool, and basically starting everything from scratch with fresh installations but the problem persists, so I assume this is a bug, presumably on *Yesod* but could it be on *Stack* (?).

Trying `stack exec -- yesod devel` produces an infinite loop of:

> cabal: At least the following dependencies are missing:
> classy-prelude >=0.10.2,
> classy-prelude-conduit >=0.10.2,
> classy-prelude-yesod >=0.10.2,
> data-default -any,
> hjsmin >=0.1 && <0.3,
> monad-logger ==0.3.*,
> persistent >=2.0 && <2.7,
> persistent-sqlite >=2.1.1 && <2.7,
> persistent-template >=2.0 && <2.7,
> safe -any,
> yesod >=1.4.3 && <1.5,
> yesod-auth >=1.4.0 && <1.5,
> yesod-core >=1.4.17 && <1.5,
> yesod-form >=1.4.0 && <1.5,
> yesod-static >=1.4.0.3 && <1.6
> Resolving dependencies...
> Configuring yesod-0.0.0...

I've tried a couple months ago and I've desisted because of the exact same problem, tried again today with the hope it would be fixed but it's still the same.

Using Archlinux and *Stack*  version 1.2.0-11 (from Arch repos).

Sorry if I'm missing something obvious.

**Comment by snoyberg** [comment]
Thanks for the report, and sorry for the inconvenience.

Can you include the generated stack.yaml file?

**Comment by alx741** [comment]
> Can you include the generated stack.yaml file?

Sure:
stack.yaml: http://pastebin.com/VTyzwv7Z
yesod.cabal: http://pastebin.com/D0Mqb7WX

**Comment by snoyberg** [comment]
Alright, that looks fine. Can you try running the following and pasting the output?

```
stack build hsc2hs -v
stack build -v
```

**Comment by alx741** [comment]
`stack build hsc2hs -v`  http://pastebin.com/mQdELM9D
`stack build -v` http://pastebin.com/3fB4C50s

**Comment by snoyberg** [comment]
Doh, I remember this now. We need a better error message.

Try again with a different project name. yesod is the name of a library
you're depending on, which confuses Stack. I'll try to make the error
message better later today.

**Comment by alx741** [comment]
Oh!! that made it!

Should have `ctrl+c` , `ctrl+v`-ed the commands from the quickstart guide. Sorry about that and thanks a lot! now It works, no bug there apparently 😄

**Comment by snoyberg** [comment]
It looks like Stack HEAD already gives a better error message:

```
Error: While constructing the build plan, the following exceptions were encountered:

Dependency cycle detected in packages:
    [yesod,classy-prelude-yesod,yesod]
```

**Comment by finlaydotb** [comment]
I just got bit by this! 😅. As someone who is beginning with Haskell, the error message is still not helpful 😅
