### ISSUE TITLE
widgetToPageContent support the option to have julius files generate a script tag with crossorigin attribute

### ISSUE THREAD

**Issue by sbditto85** [yesodweb/yesod#1300]
Disclosure: I'm a Haskell and Yesod noob.

It would be nice to have the script tag generated when calling widgetToPageContent have the option to have attributes or be able to at least pass a crossorigin value.

Having my scripts load on a different sub domain prevents me from seeing the full error details when using window.onerror, if setup properly having a crossorigin="anonymous" allows me to then see those error details.

if https://github.com/yesodweb/yesod/blob/master/yesod-core/Yesod/Core/Class/Yesod.hs#L573 (<script src="#{s}">) were to be changed to allow it to have a crossorigin attribute that would be awesome.

I may try and hack a PR together, but not sure I could do this in an optimal way.

Thanks!

**Comment by snoyberg** [comment]
I think one of the Attrs variants of addScript, like addScriptRemoteAttrs,
will do what you're looking for. Check out:

https://www.stackage.org/lts-7.9/hoogle?q=addScript&package=yesod-core

**Comment by sbditto85** [comment]
It appears that I left out some details of what I'm trying to do.

For example, using the `yesod-mysql` template from stack, if I wanted to have the script tag generated from having the `homepage.julius` have attributes how would I do it? I thought that `addScriptAttrs` and `addScriptRemoteAttrs` only worked on "other" js files? From what little I know of  the code the previously mentioned link to the `regularScriptLoad` portion in the `widgetToPageContent` function is the only way to modify that particular script tag for the defaultLayout.

Happy to be corrected otherwise :)

P.S. thank you for your hard work and wonderful framework, without which I don't think I'd be able to convince my work to let me use Haskell.

**Comment by snoyberg** [comment]
You're right about that: the functions I mentioned will only work for separate scripts, not for those generated from `addJulius`. That would require a modification to yesod-core.

I'm a bit out of the loop on this though. Can you explain why you'd need to set crossorigin for these scripts? My understanding what that this is only relevant for scripts coming from a different domain name.

**Comment by sbditto85** [comment]
I'll tell you a generic version of my situation.

I used `urlRenderOverride` to set the `StaticR` base URL to be `static.domain.com` and the website is served under `www.domain.com`. I have multiple JS files in the `./static/scripts/` directory that are included using `addScriptAttrs` and then I have a `.julius` file that is generating a script with some values inserted. In one of the JS scripts I have something similar to the following code:

```
window.onerror = senderror;
function senderror() {
    var argsStr = JSON.stringify(Array.from(arguments));
    var url = "/error/record";
    var data = {
        errorMessage: arguments[0],
        errorJsonString: argsStr
    };
    var request = new XMLHttpRequest();
    request.open('POST', url, true);
    request.send(JSON.stringify(data));
}
```

Since the generated script tag has the domain `static.domain.com` without the `crossorigin` tag it would receive the message "Script error." for EVERY js error that occurred that wasn't blessed via the `Access-Control-Allow-Origin: *` header being returned when requesting the script. The only way to have the [wai-cors cors middleware](http://hackage.haskell.org/package/wai-cors-0.2.5/docs/Network-Wai-Middleware-Cors.html#v:simpleCors) actually add that Header is to have the `Origin` request header set, which in Chrome _seems_ to only be set when it is a completely different domain or if you have the `crossorigin` attribute set. Since I'm merely using a subdomain I would need to set the `crossorigin` attribute so that the `Origin` request header is set which then causes `Access-Control-Allow-Origin` response header to be returned and I am able to receive the _actual js error_ instead of the generic message.

I'm still rather new to this so if there is something I am misunderstanding I'd happily make adjustments, but having the `crossorigin` attribute does make things work.

**Comment by snoyberg** [comment]
Cool, thanks for clarifying. Do you want to take a stab at a PR for this
feature then?

**Comment by sbditto85** [comment]
I'd be happy to, though I'm open to suggestions on the best way to implement this.

I assume we would want to be able to set it to either not show or have the value "anonymous" or "use-credentials" based on [MDN](https://developer.mozilla.org/en-US/docs/Web/HTML/CORS_settings_attributes) ... or maybe it should just be a `[(Text, Text)]` like the `Attrs` functions?

What would be the best way to get that information? Get it from something like `jsLoader` maybe called `jsCors`? or is there a way to have a per julius file script tag designation? Have it passed into the `widgetToPageContent` function?

I was leaning to the function in the Yesod type class but was not sure if adding to that class was frowned upon.

**Comment by snoyberg** [comment]
I'd totally agree with a new method in the Yesod typeclass, seems straightforward. And having `[(Text, Text)]` would be the right thing IMO. If it can be generalized to some kind of function that modifies values, I'm also cool with that, but offhand I don't see any such generalization.

**Comment by sbditto85** [comment]
#1308 addresses and fixes the issue.
