### ISSUE TITLE
yesod-auth: Add new json handlers for the Email module

### ISSUE THREAD

**Issue by psibi** [yesodweb/yesod#1303]
Right now, all the handlers in the [Yesod.Auth.Email](https://www.stackage.org/haddock/lts-7.9/yesod-auth-1.4.13.5/Yesod-Auth-Email.html) module is tied up with Shakespeare. Working with that when all you can do is communicate using JSON is a pain. I'm proposing to add additional handlers and routes for JSON specifically. This is something I specifically need for [yesod-rest](https://github.com/psibi/yesod-rest) project.

I will create a PR, if there is no opposition.

**Comment by snoyberg** [comment]
No opposition from me, that's for sure. +1
