### ISSUE TITLE
yesod devel fails when using GHC 8

### ISSUE THREAD

**Issue by SamDM** [yesodweb/yesod#1304]
Using lts-7.9 with the `yesod-simple` template works (i.e. it compiles, after some changes, see [this issue](https://ghc.haskell.org/trac/ghc/ticket/12130) and [this diff](https://gist.github.com/SamDM/9d49b8481e11239f98793f0228446bea)). That is, `stack build` and `stack test` work as they should.

Unfortunately, `stack exec -- yesod devel` does not. It gives the following error:
```
app/devel.hs:2:1: error:
Failed to load interface for ‘Application’
It is a member of the hidden package ‘yesodGhc8-0.0.0@yesodGhc8-0.0.0-50I4TO8rJLD744gHxjnYos’.
It is a member of the hidden package ‘yesodGhc8-0.0.0@yesodGhc8-0.0.0-GxI8989ntrHKHxlvhuMbCe’.
```
I did check that I am using the correct yesod binary:
```
$ stack exec which
/home/sam/.stack/snapshots/x86_64-linux/lts-7.9/8.0.1/bin/ye‌​sod
````

See also the original Stackoverflow question [here](http://stackoverflow.com/q/40697684/2496293).

**Comment by snoyberg** [comment]
I tweaked the title to hopefully make this more obvious to other people wanting to report this (I know someone commented about it on Twitter or Reddit, I just don't remember who right now).

This looks related to #1284. I thought we had this fixed, but apparently not.

IMO, it's high time to do a fairly substantial rewrite of `yesod devel`, to do something more simple like call `stack build --fast --file-watch package-name:lib --exec launch-dev-server`. It's not quite that simple, and will certainly break some existing workflows, but I think the reduced complexity in yesod-bin would be worth it.

**Comment by snoyberg** [comment]
Alright, I've just pushed a commit to 1304-stack-based-devel which will hopefully work much nicer. Would you mind giving it a shot? You should:

* Clone this repo and check out the 1304-stack-based-devel branch
* Run `stack install yesod-bin` inside the repo
* Run `yesod devel` (_not_ `stack exec yesod devel`) inside your project

It's working so far for me, but I'd appreciate some initial feedback from someone else before going to the wider community with this.

**Comment by SamDM** [comment]
Hi, I gave it a try and `yesod devel` seems to work again.

There is another issue however, and I'm not sure if it is related to yesod itself. I used to be able to launch the REPL with `stack exec cabal repl` and now I get this issue:

    Package has never been configured. Configuring with default flags. If this
    fails, please run configure manually.
    cabal: Use of GHC's environment variable GHC_PACKAGE_PATH is incompatible with
    Cabal. Use the flag --package-db to specify a package database (it can be used
    multiple times).

When I run the 'old' version of yesod again (i.e. `stack exec yesod devel`, which of course fails after it is done compiling my application) and then run `stack exec cabal repl` , I am able launch my application from the REPL.

Anyway, thx for your incredibly fast feedback on this issue :)

**Comment by snoyberg** [comment]
I'm shocked that `stack exec cabal repl` ever worked: cabal really doesn't like the `GHC_PACKAGE_PATH` environment variable. Any reason not to use `stack ghci`?

**Comment by SamDM** [comment]
The reason I used it is [this wiki page](https://github.com/yesodweb/yesod/wiki/ghci). This page is referenced to from `app/DevelMain.hs` (at lines 28-29).

Anyhow, `stack ghci` works, so everything I need is working with GHC 8 now. I do get a ton of warnings though:

    * * * * * * * *
    Warning: There are cabal settings for this project which may prevent GHCi from loading your code properly.
    In some cases it can also load some projects which would otherwise fail to build.
    
    -XNoImplicitPrelude will be used, but GHCi will likely fail to build things which depend on the implicit prelude.
    It is specified for:
        pkb:lib
    But not for: 
        pkb:exe:pkb
    
    -XTemplateHaskell will be used, but it may cause compilation issues due to different parsing of '$' when there's no space after it.
    It is specified for:
        pkb:lib
    But not for: 
        pkb:exe:pkb
    
    -XQuasiQuotes will be used, but it may cause parse failures due to a different meaning for list comprehension syntax like [x| ... ]
    It is specified for:
        pkb:lib
    But not for: 
        pkb:exe:pkb
    
    -XOverloadedStrings will be used, but it can cause type ambiguity in code not usually compiled with it.
    It is specified for:
        pkb:lib
    But not for: 
        pkb:exe:pkb
    
    -XTypeFamilies will be used, but it implies -XMonoLocalBinds, and so can cause type errors in code which expects generalized local bindings.
    It is specified for:
        pkb:lib
    But not for: 
        pkb:exe:pkb
    
    -XGADTs will be used, but it implies -XMonoLocalBinds, and so can cause type errors in code which expects generalized local bindings.
    It is specified for:
        pkb:lib
    But not for: 
        pkb:exe:pkb
    
    To resolve, remove the flag(s) from the cabal file(s) and instead put them at the top of the haskell files.
    
    It isn't yet possible to load multiple packages into GHCi in all cases - see
    https://ghc.haskell.org/trac/ghc/ticket/10827
    * * * * * * * *

Despite these warnings, I have not yet noticed any problems :)

**Comment by snoyberg** [comment]
Thanks for reporting, I think we can fix that in the scaffolding. Glad it's working now for you, and thanks for testing. Mind if we close this and follow up in the PR itself?

**Comment by snoyberg** [comment]
@MaxGabriel Do you think that the [ghci wiki page](https://github.com/yesodweb/yesod/wiki/ghci) could be changed to just `stack ghci`? Would there be any downsides?

**Comment by SamDM** [comment]
As far as I'm concerned, this issue can be closed.

**Comment by SamDM** [comment]
Maybe one of should explain the temporary workaround on the stackoverflow question? I can do it if you want but then you won't get any credit for it. Let me know.

**Comment by snoyberg** [comment]
Go for it, I'd be much obliged!

**Comment by tolysz** [comment]
`yesod devel` how does it know where `ghc` is?

**Comment by snoyberg** [comment]
Which version of `yesod-bin` are you using (check by running `yesod version`)? Can you try upgrading to 1.5.1?

**Comment by tolysz** [comment]
It was more about ghc (`8.0.2`) and it does not fully work if the resolver is not build exactly for the compiler.

It works fine without changing compiler (modulo having to use modified `shakespeare`  which exports Text.Css (Block(..))` so the tycon Block is visible and TH does not panic)

**Comment by AshtonKem** [comment]
I'm seeing this issue on NixOs, but unfortunately the workaround of just using ```yesod devel`` won't work for me because Stack manages the environment on NixOs.

Is there a fix for this that doesn't require me abandon stack?

**Comment by snoyberg** [comment]
Have you tried the latest version 1.5?

**Comment by AshtonKem** [comment]
With 1.5.1 I get the following output:

``` 
Yesod devel server. Enter 'quit' or hit Ctrl-C to quit.
Application can be accessed at:

http://localhost:3000
https://localhost:3443
If you wish to test https capabilities, you should set the following variable:
  export APPROOT=https://localhost:3443

yesod: stack: startProcess: runInteractiveProcess: exec: does not exist (No such file or directory)
```

**Comment by snoyberg** [comment]
And running stack works?

**Comment by AshtonKem** [comment]
Correct. I've been using ```stack install``` and ```stack  exec <appname>``` in the mean time. Just to narrow it down, ```stack exec yesod touch``` also appears to work, so it's something unique to ```stack exec yesod devel```

**Comment by snoyberg** [comment]
That's a pretty big step to take, I'd rather avoid having to set up a VM if I can. I'm pretty sure this is because Stack+Nix plays around with your PATH environment. Can you try running the following:

    $(stack exec which yesod) devel

Also, please include the exact commands you run to generate the output you're posting; there's a difference between `yesod devel` and `stack exec yesod devel`, for instance.

**Comment by AshtonKem** [comment]
Sorry I wasn't clear, all previous output was done through stack.

I'm a little bit confused on what's happening, I upgraded by stack LTS and everything is broken, but in different ways. At the risk of confusing you, I'm going to post the several commands I've tried to get devel to work, along with the output. I'm uncertain which way to run devel is the correct way, so please let me know if you need any more info.

##### ```$(stack exec which yesod) devel```

```
Executable named which not found on path: ["/home/ashton/Documents/gym/.stack-work/install/x86_64-linux-nix/lts-7.19/8.0.1/bin","/home/ashton/.stack/snapshots/x86_64-linux-nix/lts-7.19/8.0.1/bin","/nix/store/kvjkwch6d466xdmrkjzbh1n6vp573sy8-ghc-8.0.1/bin","/nix/store/91gq1r39y4yfv4k95vl9szw1sg7v9rmg-patchelf-0.9/bin","/nix/store/7m2ch0nyd74y3p8qbzrj3rnz7k81i54v-paxctl-0.9/bin","/nix/store/mwncq6kfcl4iyxr74lihr39fdrghp40q-gcc-wrapper-5.4.0/bin","/nix/store/kgczpyfkh9avarbb1xxi2k2jh5ndyzgw-gcc-5.4.0/bin","/nix/store/2mvblw8kq86ncaidjrp3x4rssy1lhlhi-binutils-2.27/bin","/nix/store/bm052v0zqk8w4gvfwqacszb6b9kijcs4-glibc-2.24-bin/bin","/nix/store/lcwdbh37ha51z86c62mm65vbcfc990dd-coreutils-8.25/bin","/nix/store/lcwdbh37ha51z86c62mm65vbcfc990dd-coreutils-8.25/bin","/nix/store/95vfigaqdg8jg5bk961k1x06j86p5fh0-findutils-4.6.0/bin","/nix/store/222s1mvzd1qipjklq13mrhrjgfngq9fd-diffutils-3.5/bin","/nix/store/c6pcdai9nwd2zmcnbz96j239mgs61qxj-gnused-4.2.2/bin","/nix/store/slrbnmc69dly2gf4by296n32ypsccr0f-gnugrep-2.25/bin","/nix/store/x451jk1q0dadjic52qawhnwfv0f4a4sk-gawk-4.1.3/bin","/nix/store/cj0zinnakxj5zd3fw8050l0ng5mlrwm5-gnutar-1.29/bin","/nix/store/c5y9w08xkiz6kvnscpjv3205gyr6iybz-gzip-1.8/bin","/nix/store/hia247wa09mffcyp66412zg8gliqyw91-bzip2-1.0.6.0.1-bin/bin","/nix/store/zklahbvk9idyjqn6qf667ac1n63yf3s8-gnumake-4.2.1/bin","/nix/store/gabjbkwga2dhhp2wzyaxl83r8hjjfc37-bash-4.3-p48/bin","/nix/store/krskgwnnd18c6wzfwnf0clqqdirpkl1h-patch-2.7.5/bin","/nix/store/5cpnwwnasypdi7p0av6qbaf52y99gmdz-xz-5.2.2-bin/bin"]
devel: command not found
```


##### ```stack exec yesod devel```

```
Yesod devel server. Enter 'quit' or hit Ctrl-C to quit.
Application can be accessed at:

http://localhost:3000
https://localhost:3443
If you wish to test https capabilities, you should set the following variable:
  export APPROOT=https://localhost:3443

yesod: stack: startProcess: runInteractiveProcess: exec: does not exist (No such file or directory)
```

In this case the process immediately exits.

##### ```yesod devel```

```
ExitSuccess
Type help for available commands. Press enter to force a rebuild.
Starting devel application
Devel application launched: http://localhost:3000
devel.hs: bind: resource busy (Address already in use)
```

This one confuses me the most. The devel application starts correctly serves the "Application Isn't Built Yet" on port 3000, but nothing I do will cause it to serve my application. Triggering a build manually (enter or tying "build") sometimes triggers compilation output on the terminal, but my compiled code is never served on port 3000.

**Comment by snoyberg** [comment]
Let's focus on that last one. The 3000 port is being successfully bound, but the application's random port assigned by `yesod devel` cannot be bound. There's no obvious reason for this. I'd recommend:

* Adding some debug into to `devel.hs` in your site
* Running with `yesod devel --disable-reverse-proxy` to see if it behaves differently

**Comment by mrkgnao** [comment]
@snoyberg 
I was in the exact same situation. `yesod devel --disable-reverse-proxy` worked for me, too: maybe it's something about the default NixOS firewall/network configuration?

Meanwhile, I can now get started with the Yesod book! :)

**Comment by marchgithub** [comment]
Can we reopen this for the other issue described here, which was `stack exec -- yesod devel` returning the error below?

```yesod: stack: startProcess: runInteractiveProcess: exec: does not exist (No such file or directory)```
