### ISSUE TITLE
Julius: commented out code tirgger errors

### ISSUE THREAD

**Issue by alx741** [yesodweb/yesod#1322]
I have a new scaffolded project where the only change is the `getHomeR` resource:

```Haskell
getHomeR :: Handler Html
getHomeR =
        setTitle "Welcome To Yesod!"
        $(widgetFile "homepage")
```

Commenting out Hamlet and Lucius code that uses the `commentFormId`, `commentTextareaId` and `aDomId` variables (present in the original `getHomeR`) interpolation works fine, but for the Julius code it needs to be removed, if it is only commented out it will trigger:

```
Forcing recompile for ./Handler/Home.hs because of templates/homepage.hamlet
Forcing recompile for ./Handler/Home.hs because of templates/homepage.julius
Forcing recompile for ./Handler/Home.hs because of templates/homepage.hamlet
Rebuilding application... (using cabal)

Handler/Home.hs:30:11:
    Not in scope: ‘aDomId’
    In the splice: $(widgetFile "homepage")

Handler/Home.hs:30:11:
    Not in scope: ‘commentFormId’
    In the splice: $(widgetFile "homepage")

Handler/Home.hs:30:11:
    Not in scope: ‘commentTextareaId’
    In the splice: $(widgetFile "homepage")

Handler/Home.hs:30:11:
    Not in scope: ‘commentListId’
    In the splice: $(widgetFile "homepage")
Build failure, pausing...
```

I suppose it's a bug to take commented out Julius code into account for that verification, although there may be a reason for it (?)

**Comment by snoyberg** [comment]
This is the way Julius is designed: "comments" in Julius are not special, since Julius performs no Javascript parsing. If you leave some content in a comment, it will still be rendered and sent to the client. Therefore, the variables in question must be present.

**Comment by alx741** [comment]
Oh! it take me by surprise, thanks!
