### ISSUE TITLE
Static resource identifiers not being generated

### ISSUE THREAD

**Issue by alx741** [yesodweb/yesod#1323]
Adding a new file to the `static` directory like an image, using it somewhere in a Hamlet template and then re-building triggers an error:

```
Foundation.hs:130:15:
    Not in scope: ‘img_test_png’
    In the splice: $(widgetFile "default-layout")
```

Because there is no resource yet for that file, the only way to force it to generate the identifier is by `touch`ing `Settings.hs` or `Settings/StaticFiles.hs` of course. Maybe `yesod touch` could handle this hassle as well?

**Comment by snoyberg** [comment]
I'd be up for a PR to add support for this to `yesod touch`, though overall I didn't think `yesod touch` was being used much anymore. It would be nice to have some kind of better logic in GHC for this, but it's a truly confounding corner case where there's no obvious way to make the compiler notice this _and_ remain fast.

**Comment by alx741** [comment]
Having `yesod touch` to *touch* `Settings.hs` always may be a bit of a extra overhead that is not always necessary, but in the other hand, it took me a full day of debugging just to find out that the identifiers are not being generated even after stopping `yesod devel` and then `stack clean && stack exec -- yesod touch && stack build` but *touch*ing a settings file is necessary. It's a bit frustrating, and there is no documentation about how to get the identifiers to be generated.

Maybe I got something wrong with my workflow, but it's quit a bit astonishing behavior. Will try to do something with `yesod touch` and see how that works
