### ISSUE TITLE
yesod-persistent-1.4.1.0 compile error

### ISSUE THREAD

**Issue by peti** [yesodweb/yesod#1324]
Citing from http://hydra.nixos.org/build/45109823/nixlog/1/raw:

~~~~
Building yesod-persistent-1.4.1.0...
Preprocessing library yesod-persistent-1.4.1.0...
[1 of 2] Compiling Yesod.Persist.Core ( Yesod/Persist/Core.hs, dist/build/Yesod/Persist/Core.o )

Yesod/Persist/Core.hs:178:26: error:
    Not in scope: type constructor or class ‘PersistUniqueWrite’
    Perhaps you meant ‘PersistUnique’ (imported from Database.Persist)

Yesod/Persist/Core.hs:197:27: error:
    Not in scope: type constructor or class ‘PersistUniqueWrite’
    Perhaps you meant ‘PersistUnique’ (imported from Database.Persist)
~~~~

Maybe the dependency `persistent >=2.1 && <2.7: using persistent-2.2.4.1` is the crux?

**Comment by psibi** [comment]
Yes, that's the problem. But IIRC, yesod-persistent has CPP conditionals handling this.

**Comment by snoyberg** [comment]
It was a bug in a newly added CPP conditional. I've just pushed a fix and uploaded 1.4.1.1 to Hackage.

**Comment by snoyberg** [comment]
@peti Thanks for the report, can you confirm when you've had a chance that this fixes the problem?

**Comment by peti** [comment]
Yes, the new version builds fine. Thank  you very much for the quick fix.

**Comment by snoyberg** [comment]
No problem!
