### ISSUE TITLE
languages does not behave like documented

### ISSUE THREAD

**Issue by akazik** [yesodweb/yesod#1325]
function Yesod.Core.Handler.languages

According to documentation:
- The _LANG get parameter.
- The _LANG cookie.
- The _LANG user session variable.
- Accept-Language HTTP header.

Actual order:
- The _LANG user session variable.
- The _LANG get parameter.
- The _LANG cookie.
- Accept-Language HTTP header.

**Comment by psibi** [comment]
It's implementation was changed recently: https://github.com/yesodweb/yesod/pull/1290

**Comment by akazik** [comment]
Yesod.Core.Handler.getMessageRender does not uses the languages order, maybe the other order.
Why are the two different?

**Comment by snoyberg** [comment]
It looks like a bug. The right thing to do is:

* Modify getMessageRender to use the languages function
* Update the docs to match current behavior

Would you be interested in sending a PR?

**Comment by bermanjosh** [comment]
Just ran into this issue today - @snoyberg just confirming, based on your comment about the correct behavior is what we see `languages` function, **not** the docs / `getMessageRender`, correct?

**Comment by snoyberg** [comment]
Correct, `languages` is the winner in this fight.

**Comment by jezen** [comment]
This issue appears to be resolved by the merged PR, so I will close this.
