### ISSUE TITLE
How to Encrypt All Log Messages?

### ISSUE THREAD

**Issue by civiclabsconsulting** [yesodweb/yesod#1328]
First off, `yesod` is great, thanks for all the hard work that has gone into this project.

I'm having an issue with logging: I'd like to encrypt all the logs as the messages occasionally contain sensitive information.

I wrote some code that creates a custom info logger, but obviously this only works if I explicitly use the `secureLogInfo` function.

```
module Helpers (secureLogInfo) where

import           ClassyPrelude
import           Crypto.Cipher
import qualified Data.ByteString.Char8 as B
import qualified Data.Text.Lazy              as TL
import           Import.NoFoundation         (logInfo, MonadLogger)
import qualified Data.ByteString.Char8 as BC
import           Data.Char (chr)

secureLogInfo :: MonadLogger m => Text -> m ()
secureLogInfo message = $(logInfo) . pack . B.unpack . ecbEncrypt aes128 . padData .
        B.pack $ unpack message
    where
        keyString :: ByteString
        keyString = B.pack "My Secret Key"

        aes128 :: AES128
        aes128 = cipherInit key

        padData :: ByteString -> ByteString
        padData input = input `B.append` padding
            where
                padding = BC.replicate requiredPadding (chr 0)
                requiredPadding =
                    case inputLength `mod` 16 of
                        0 -> 0
                        x -> 16 - x
                inputLength = B.length input

        Right key = makeKey keyString
```

What I need is to have ALL log messages e.g. database, web requests, encrypted. Is it possible to (easily) do this?

**Comment by snoyberg** [comment]
I'd do it outside of your app, by piping stdout and stderr through another
program. That way, even if some other library uses its own output
mechanism, you're covered. It also means your web app doesn't need to hold
an encryption key.

**Comment by civiclabsconsulting** [comment]
@snoyberg Okay - makes total sense. Thanks!

**Comment by snoyberg** [comment]
No problem :)
