### ISSUE TITLE
yesod-auth: Email provider broke after PR #1317

### ISSUE THREAD

**Issue by CthulhuDen** [yesodweb/yesod#1330]
After trying to parse JSON with `parseJsonBody` or `requireJsonBody` request body is consumed so POST parameters cannot be read (look at demo PR #1331), so unconditionally trying to mix processing request as both JSON and url-encoded string breaks things for whatever option was tried second. I suggest modifying code in #1317 so that it checks `Content-Type` first and interprets input in appropriate way (so do not try to parse JSON if it is not `application/json`).

**Comment by psibi** [comment]
What about the other way round ? Try reading some POST parameters and then JSON parsing in request body. Does that work or does it have the same problems ?

**Comment by CthulhuDen** [comment]
It dos have the same problem (this test also fails https://github.com/yesodweb/yesod/pull/1331/files#diff-74a1d7b146223044592d1a02cc246074R33).

**Comment by psibi** [comment]
@CthulhuDen Ah, okay. But this code in Yesod.Auth.Email works for me with the latest library: https://github.com/yesodweb/yesod-cookbook/blob/master/cookbook/yesod-auth-json.md 

Any idea why that works ? The JSON interface should actually not work.

**Comment by CthulhuDen** [comment]
@psibi I may be getting something wrong, but I doubt it can work at all. I was able to use register button and confirmed my email and also use logout link, but nothing else worked: user record is created without password, class method `needOldPassword` overridden to always return True (https://github.com/yesodweb/yesod-cookbook/commit/76ee43bc310de1865865a6f53181f58bd2ddb56a#diff-2ec8e63a30fc040c7268b526e126fef1R155) so I cannot event set my password.

**Comment by CthulhuDen** [comment]
On second thought, asking for POST parameter then parsing as JSON works iff request header "Content-Type" is correctly set to JSON, because in this case WAI does not even try to parse body for input parameters. Perhaps it would be a good idea to make `parseJsonBody` likewise only parse body for correct content-type, or perhaps for any excluding www-form-urlencoded and multipart/form-data.

Ping @snoyberg

**Comment by psibi** [comment]
@CthulhuDen Execute that as a stack script. This is the relevant code I have used at the start of the file:

```
#!/usr/bin/env stack
{- stack
     --resolver lts-6.15
     --install-ghc
     runghc
     --package yesod
     --package yesod-auth-1.4.15
     --package text
     --package http-conduit
     --package persistent
     --package persistent-sqlite
     --package shakespeare
     --package monad-logger
 -}
```
 Then the workflow there is like this:

* Click register button first. In your terminal, you will get a url printed. Go to that particular url to set new passwordl.
* After that you can use the other buttons to do login, set password etc.

The above flow works for me. Can you see if it works for you ?

**Comment by psibi** [comment]
Also change the `needOldPassword` to False.

**Comment by psibi** [comment]
@CthulhuDen I'm agreeing with the fact that the current code needs to be changed so that we read parameters based on the content type. But right now the Email interface is working for me which is confusing me. In fact, we have a internal service running based on the json endpoints of Yesod.Email.

**Comment by CthulhuDen** [comment]
@psibi After changing needOldPassword it will probably work, agreed. So basically JSON flow works (because correct Content-Type prevents WAI from parsing into input fields) but form do not. I think `parseJsonBody` should check Content-Type as I wrote earlier.

**Comment by psibi** [comment]
@CthulhuDen Yeah, I agree. Can you send a PR fixing the module ?

If not, I will fix this by next week.

**Comment by CthulhuDen** [comment]
@psibi If you mean fix in Yesod.Auth.Email, I'm afraid I won't be able to take care of that, and I would like to get some opinions on whether we should fix `parseJsonBody` instead.

**Comment by psibi** [comment]
Okay. :-) Let's wait and see if @snoyberg and others have a opinion on fixing the `parseJsonBody` instead. IMO, if we decide to fix `parseJsonBody` itself - then I think it will break lots of Yesod handlers in the wild.

**Comment by snoyberg** [comment]
I definitely think doing the form parsing before JSON parsing is a good, simple fix here. And we should have a function to parse a JSON body only if the content-type indicates JSON.

As far as changing the behavior of the existing functions? Probably not. I'd be OK with adding a new function, and putting out an email to the Yesod mailing list asking if we should deprecate the old one for confusing behavior.

**Comment by psibi** [comment]
I think right now we are doing the form parsing before JSON parsing. So, we are good there.

>  And we should have a function to parse a JSON body only if the content-type indicates JSON.

I think it would be good to have it. I know I will be using them a lot.

**Comment by CthulhuDen** [comment]
> I think right now we are doing the form parsing before JSON parsing. So, we are good there.

Not in every method, at least not in password setting.

**Comment by snoyberg** [comment]
I've just pushed a commit to master which I believe will address this, but I haven't tested it myself. Can someone who has been working through these issues give it a shot? If I get the thumbs up, I can make a new release of yesod-core and yesod-auth.

**Comment by psibi** [comment]
I will verify it tonight and report back. Thanks for the fix.

**Comment by connrs** [comment]
Hey @snoyberg, thanks for tackling this for us.

I pulled this in to the project I've been working on (as mentioned [in this Google Groups topic](https://groups.google.com/forum/#!topic/yesodweb/Vhm6vqHBqIg)) and can confirm that this certainly resolves the first-time-set-password issue that I'd encountered.

**Comment by snoyberg** [comment]
Awesome, thanks for confirming. Closing with new release to Hackage.
