### ISSUE TITLE
yesod-websockets: Add a way to change `WS.defaultConnectionOptions`

### ISSUE THREAD

**Issue by tolysz** [yesodweb/yesod#1337]
I have been playing with per-message compression with `websockets` ( https://github.com/jaspervdj/websockets/pull/130 ). It is very promising already but: compression is not for everyone.
The good default is to have it disabled: as it uses some additional memory (up to 320k+ due to deflate/inflate buffers).
If someone does not care about having millions of connections but sends some huge amounts of redundant data it helps a lot it is a win.

I was wondering if it would be possible to add some constructor which would allow creating `webSockets` with any `WS.ConnectionOptions`. Thus possibly varying which compression options to offer per request.
Eg. Admin could have it (huge data volume), a user would not (a little data, a huge number of connections).

Maybe something like `webSocketsOptions` and `webSocketsOptionsWith`?

**Comment by snoyberg** [comment]
I'm fine with something like that in principle, want to take a stab at a PR?

**Comment by tolysz** [comment]
Should we re-export `WS.defaultConnectionOptions` and `ConnectionOptions` ?

**Comment by snoyberg** [comment]
Good question. I think it makes sense to do so.

**Comment by snoyberg** [comment]
Handled by #1338
