### ISSUE TITLE
Yesod.Auth: Export credential plugin information from the respective plugin

### ISSUE THREAD

**Issue by psibi** [yesodweb/yesod#1344]
Usecase: I would like to check if someone has login-ed via Google or Facebook and do some activities based on that in the `authenticate` handler.

Right now, I manually check that `credsPlugin` is `googleemail2` and perform those actions. I had to look at the code to find out this. But I think a better solution is to just export that identifier from that module.

I can submit a PR if there is no opposition.

**Comment by snoyberg** [comment]
Sounds good to me 👍
