### ISSUE TITLE
Don't apply CSRF middleware for one particular handler

### ISSUE THREAD

**Issue by psibi** [yesodweb/yesod#1350]
I have the following middleware configuration in Yesod:

```
yesodMiddleware = defaultYesodMiddleware . defaultCsrfMiddleware
```

Now, for one of the routes I don't want to do the csrf check. Is that possible ? Any way of doing this without removing `defaultCsrfMiddleware` and adding csrf individual checks in the handler.

An api like this would be nice:

```
doCsrfCheck (AuthR _) = return True
doCsrfCheck HomeR = return False
```

**Comment by snoyberg** [comment]
I think something like this would work:

```haskell
yesodMiddleware app = do
  mroute <- getCurrentRoute
  let toApply =
        case mroute of
          Just (AuthR _) -> True
          _ -> False
  defaultYesodMiddleware $ (if toApply then defaultCsrfMiddleware else id) app
```

**Comment by psibi** [comment]
Ah, you're right. That's way simple. Thanks.

**Comment by snoyberg** [comment]
No problem, my pleasure :)

**Comment by sbditto85** [comment]
Awesome! I was about to have the same question so thanks.
