### ISSUE TITLE
Proposal: Add a utility function named getPostParams in Yesod.Core.Handler

### ISSUE THREAD

**Issue by psibi** [yesodweb/yesod#1351]
Getting all post parameters is a common thing and I feel such a function should be available. We can indicate in the documentation that for also getting submitted files, one can use the function `runRequestBody` instead. 

It's implementation would be this:

```
getPostParams
  :: MonadHandler m
  => m [(Text, Text)]
getPostParams = do
  reqBodyContent <- runRequestBody
  return $ fst reqBodyContent
```

**Comment by snoyberg** [comment]
I have no problem with that.

**Comment by felipexpert** [comment]
this function was just what I was looking for! good idea
