### ISSUE TITLE
Q: How to add and delete cookie?

### ISSUE THREAD

**Issue by lucklove** [yesodweb/yesod#1352]
I have search all over the yesod book, but it didn't mention how to operate cookie.

**Comment by snoyberg** [comment]
You're probably looking for:

*
https://www.stackage.org/haddock/lts-8.0/yesod-core-1.4.31/Yesod-Core-Handler.html#v:lookupCookie
*
https://www.stackage.org/haddock/lts-8.0/yesod-core-1.4.31/Yesod-Core-Handler.html#v:setCookie

**Comment by lucklove** [comment]
@snoyberg Oh! It's it! Thank you.

**Comment by snoyberg** [comment]
No problem.
