### ISSUE TITLE
yesod-form: textareaField: writeHtmlEscapedChar: '\n' translate to "<br>", but http newline is "\r\n"

### ISSUE THREAD

**Issue by ncaq** [yesodweb/yesod#1354]
[yesod/Fields.hs at master · yesodweb/yesod](https://github.com/yesodweb/yesod/blob/master/yesod-form/Yesod/Form/Fields.hs#L229)
`textareaField` having `writeHtmlEscapedChar` is `'\n'` translate to `"<br>"`, but http newline is `"\r\n"`.
then, html contain junk `\r`.
this is spec? or bug?
I am sorry poor english. thank you.

**Comment by snoyberg** [comment]
Converting a \r\n to <br> in addition to a plain \n makes sense. Interested
in sending a PR?

**Comment by ncaq** [comment]
I'm happy.My thinking is collect.
I'm developing web application by yesod.
I maybe send PR.
