### ISSUE TITLE
Missing '+' in  post param

### ISSUE THREAD

**Issue by Qinka** [yesodweb/yesod#1362]
When running a test suite, I found that the text read from post param lost all '+', but If I just send a useless file in the same request in the test suite, none of '+' was losted.

**Comment by snoyberg** [comment]
Can you provide a reproducing case?

**Comment by Qinka** [comment]
for handler:

```haskell
postPostR :: Handler Text
postRostR = do
  pp <- lookupPostParam "param"
  return $ fromMaybe undefined pp
```

And if I send request with cURL in terminal:
```bash
$ curl -X POST -F "param=a+b"  url/for/post
```
That will return "a+b".

But if I send request, like this:
```bash
$  curl -X POST -d "param=a+b" url/for/post
```
That will just return "a b", and the "plus" is missing.

**Comment by snoyberg** [comment]
Unless I'm misunderstanding you (this is not a complete reproduction), everything is working as expected, as this is how percent encoding works. Please see, for example, https://en.wikipedia.org/wiki/Percent-encoding#The_application.2Fx-www-form-urlencoded_type

**Comment by Qinka** [comment]
That means I need to encoding that thing by myself, and like this:
```bash
$ curl -X POST -d "param=a%2Bb"
```

**Comment by snoyberg** [comment]
Correct.
