### ISSUE TITLE
Question: Is it possible to override the auth route defintions?

### ISSUE THREAD

**Issue by felixSchl** [yesodweb/yesod#1385]
In particular [Routes L20](https://github.com/yesodweb/yesod/blob/b9e57a1a60f6d2b9f1f65d65197eedf52f4e18ab/yesod-auth/Yesod/Auth/Routes.hs) is an eye sore to me. I understand the reason to have a dedicated namespace for plugin routes, but could we not just have reserved route names and plugins would need to work around those? Or, is there a way to have any influence on this downstream? Just personal opinion, but I'd prefer to have `/auth/email/verify` than `/auth/page/email/verify`, especially when making AJAX requests later

**Comment by snoyberg** [comment]
There is no way to change this outside the codebase. If you want, you can run your own fork of the Git repo with the changes you want and add that version to your stack.yaml file.

**Comment by felixSchl** [comment]
Thank you, that answers my question. I'll have to re-consider how important this is to me before going down the fork route :)
