### ISSUE TITLE
Allow specifying layout in defaultErrorHandler

### ISSUE THREAD

**Issue by felixSchl** [yesodweb/yesod#1388]
I would like to use a different layout when handling errors, but I can see no way of doing this currently. One way to get around it which would cause little API breakage would be to add another argument to [`defaultErrorHandler`](https://github.com/yesodweb/yesod/blob/b9e57a1a60f6d2b9f1f65d65197eedf52f4e18ab/yesod-core/Yesod/Core/Class/Yesod.hs#L645) to specify a layout and apply it to the default layout in the type class instance: `errorHandler = defaultErrorHandler defaultLayout`. This way I can bring my own layout  to the table and still benefit from all the other logic that the default error handler brings to the table, such as setting errors, providing json responses and so on.

**Comment by psibi** [comment]
I think a new function should be added in the typeclass which allows passing of custom widget for error handler.

**Comment by snoyberg** [comment]
How about defaultMessageWidget?
https://www.stackage.org/haddock/lts-8.13/yesod-core-1.4.33/Yesod-Core.html#v:defaultMessageWidget

**Comment by jezen** [comment]
This is inactive, so I will close this issue.
