### ISSUE TITLE
Q: Can I configure Yesod.Auth.Email in such a way that a user can register with a password right away?

### ISSUE THREAD

**Issue by Wizek** [yesodweb/yesod#1389]
Can I configure Yesod.Auth.Email in such a way that a user can register with a password right away without having to click the email verification link in the middle of the process?

I'm mainly interested in this for the JSON endpoints, as there will be users who register through a mobile app and there is a break in the middle of their registration flow if they have to (1) register with email only (2) get verification, click link (3) set password on the website (4) go back to mobile app and type in again their email + password to log in finally.

Instead, I'd like to enable the following flow:
(1) register with email and password and immediately get logged in (2b) In the background their email address is still unverified, and they can click the link they got in the mail whenever they want to. While their status is unverified, they can still use some features of their accounts, and restriction of other features is possible by querying for verification status in the database.

**Comment by kk-hainq** [comment]
I'm having the same situation as @Wizek describes here, that the current flow is quite inconvenient for mobile apps.
I think supporting an optional parameter `password` at the register endpoint + a verify-url with custom redirect-link would solve this problem and enable more helpful use cases.

I can work on this if the maintainers think it's a good idea, can anyone confirm?

**Comment by kk-hainq** [comment]
@snoyberg, In case everyone has missed this, can you confirm?

**Comment by snoyberg** [comment]
I have to admit that I haven't looked at this module in a while, and don't use it myself anymore. At a high level, I don't see a problem with it. Maybe @Wizek can weigh in and say if that would address the issue?

**Comment by kk-hainq** [comment]
I see, will work on a PR soon :+1:

**Comment by kk-hainq** [comment]
This should be addressed now, by https://github.com/yesodweb/yesod/pull/1536.

**Comment by snoyberg** [comment]
Good call, thanks!
