### ISSUE TITLE
Extract form field render functions

### ISSUE THREAD

**Issue by felixSchl** [yesodweb/yesod#1390]
Could we extract the form field render functions? The problem that I see currently is that I cannot use any of the preexisting render functions when I work directly with an `MForm`. I think this is a unnecessary restriction, since from what i have seen all they all follow the same pattern: obtain the `(res, views)` tuple and then map over `views`, it's almost like this `(res, widget) <- second someRenderFn <$> aFormToForm aform`. I'd be glad to prepare a PR if I knew it had a chance of making it in.

**Comment by snoyberg** [comment]
I'm not quite sure what the proposal is, but I don't see an inherent
problem with exposing existing functionality under a new name.

**Comment by jezen** [comment]
I’m also not sure what the proposal is. If you’d like to submit a PR it’d be welcome, and that’s definitely a better place for us to review and consider new design ideas anyway. Since this issue is now very old, I will close it.
