### ISSUE TITLE
Request: Release new version of yesod-bin in Hackage

### ISSUE THREAD

**Issue by psibi** [yesodweb/yesod#1396]
The present version in the git repo is 1.5.2.3 which IMO fixes an important issue my teammates have been facing for the past 6 months or so.

I would love to see a new version. The package version and the changelog is already bumped for the new version.

**Comment by snoyberg** [comment]
Good call, thanks for the reminder. Released to Hackage.

**Comment by psibi** [comment]
Thanks!
