### ISSUE TITLE
Julius files and a multi server environment

### ISSUE THREAD

**Issue by sbditto85** [yesodweb/yesod#1400]
Anyone use Yesod in a multi server environment and use Julius to allow data to be inserted into a javascript file to kick the page off, as opposed to having it just use AJAX request to get all the data a SPA might need? 

I’m finding that it creates a tmp file for the Julius file then serves that. The problem i have is without sticky-routing the other servers may have not generated that tmp file yet so it fails to retrieve the JS (sometimes).

I’ve hacked the widgetToPageContent function to allow me to embed the JS directly and that seems to alleviate that problem, but I’m not sure if its a good solution. Is there a better way to approach this problem?

If it makes a difference I'm using keter as a deployment method and the JS to kick off the SPA is not that large.

**Comment by snoyberg** [comment]
The scaffolding overrides the `addStaticContent` method to create these temp files. If you just remove that code, you'll get the behavior I think you're looking for:

https://github.com/yesodweb/yesod-scaffold/blob/1ff16bc6eb781a7e2aa98c218465fb194a5e56f8/Foundation.hs#L150

You could also consider modifying the behavior to write the temp files to a Redis database (or similar) so they're available to all of the nodes.

**Comment by sbditto85** [comment]
Well i feel a little silly not making the connection between the code in `widgetToPageContent` (https://github.com/yesodweb/yesod/blob/52f67fb04bebd050aa27b4a13fe2ca73aedf25f2/yesod-core/Yesod/Core/Class/Yesod.hs#L576) and the `addStaticContent` being a `Nothing`. I knew I was doing something a little off and felt like there should be a way to do what I wanted.

Thanks it works like a charm.

**Comment by snoyberg** [comment]
No problem
