### ISSUE TITLE
Yesod devel no longer recognising app is ready to serve after upgrading to LTS-8.13 from 6.9

### ISSUE THREAD

**Issue by JoeShanahanT** [yesodweb/yesod#1405]
This is going to be a bit vague but I apologise in advance - I'm not sure what code it would be required to share.

Immediately after starting yesod devel, you can go to

    http://mylocalhost/dev/root

.. to see the standard yesod devel building page. Previously, once our app had started, the page would redirect to ` http://mylocalhost/dev/root/login`. This is no longer happening.

Since upgrading to lts-8.13, the yesod devel splash reloads indefinitely. If you manually navigate to

    http://mylocalhost:3000/dev/root/login

.. then the app can be accessed. The following URLs are also not working whereas previously they were:

    http://mylocalhost:3000/dev/root
    http://mylocalhost/dev/root/login

How does yesod devel determine that an app is ready to serve? How do I determine why it is no longer doing so?

My guess is that `Application.hs` doesn't have some required new magic for yesod devel to work - what this magic is I haven't been able to determine.

**Comment by psibi** [comment]
What version of `yesod-bin` are you using ? Try to use the latest one as that fix the "indefinite splash load" error.

**Comment by JoeShanahanT** [comment]
$ stack exec -- yesod version
    Getting project config file from STACK_YAML environment
    yesod-bin version: 1.5.2.2

Building from source appears to have fixed the issue, thanks!

**Comment by psibi** [comment]
Instead of building from source, you can also use the yesod-bin version `1.5.2.3` which is available. Putting that version under `extra-deps` in `stack.yaml` should do the trick.
