### ISSUE TITLE
yesod-test extraction of attributes?

### ISSUE THREAD

**Issue by mwotton** [yesodweb/yesod#1406]
Just trying to confirm my understanding - there doesn't seem to be a way of extracting an attribute using htmlQuery?
```
            matches <- htmlQuery "a#annotation"
```

gives me 

```
["<a href=\"/doc/91/annotations\" id=\"annotation\">Annotations</a>"]
```

where what i really want is to follow the href. If I haven't missed something, perhaps this would be a good addition - something like "clickOn :: Query -> YesodExample site ()", relying on an extra (as yet undesigned) primitive that can access attributes. (There doesn't seem to be anything in CSS syntax proper for extracting attributes, like XPath has - open to suggestions here.)

**Comment by MaxGabriel** [comment]
Just spitballing here, but maybe use [tagsoup](https://www.stackage.org/package/tagsoup) to parse the HTML that `htmlQuery` returns?

**Comment by mwotton** [comment]
That's definitely an option, but I think following a link in a web app is a
pretty basic thing to do, and a test framework ought to make it easy.

**Comment by snoyberg** [comment]
I agree with adding such a function. All of the data should be available
since we've already parsed the HTML. Want to take a stab at a PR for it?

**Comment by mwotton** [comment]
Yep, I'll have a go.

**Comment by mwotton** [comment]
(out of curiosity: why Yesod.Test.TransversingCSS ? What does it mean to transverse?)

**Comment by snoyberg** [comment]
No idea :)
