### ISSUE TITLE
Feature request: Editable file upload field

### ISSUE THREAD

**Issue by amitaibu** [yesodweb/yesod#1411]
We have a file upload input field part of a bigger form. Here are the (simplified) models:

```
Item
    name            Text
    pdfFile         PdfFileId Maybe
    deriving        Show Generic
File
    filename        String
    deriving        Show Generic
```

![localhost_3000_add_item](https://user-images.githubusercontent.com/125707/27346007-54661e26-55f4-11e7-813f-9cc6dbd1f33b.jpg)

That is, an `Item` will reference a `File`. All is fine, until I'd like to `edit` this entity, and the question arises on how should the input field behave.

In Drupal we have something like this:

![edit_article_tes___site-install](https://user-images.githubusercontent.com/125707/27346170-f2892eea-55f4-11e7-8d92-d859164022dd.jpg)

It allows the user to remove the existing file, and re-attach a new one.

**Comment by snoyberg** [comment]
Does this require changes to the generated HTML, or is this handled with Javascript? Are there downsides to adding it to the existing file field code?

**Comment by amitaibu** [comment]
There's actually a bunch of stuff going on, including Ajaxy calls in case you want to attach (i.e. upload the file) ahead of saving the form.

You can actually have a look how it acts by [spinning](https://simplytest.me/project/drupal) up a (free & disposable) Drupal 8 site, and after the quick installation, go to `/node/add/article` where you will have an Image field to experiment with the functionality and behavior. 

> Are there downsides to adding it to the existing file field code?

I think it would make sense to add it to the existing file field code.

**Comment by snoyberg** [comment]
If this is a non-trivial and opinionated piece of Javascript code, then I do not think it should go into the primary `fileField` function. In fact, putting it as a separate package providing an enhanced `fileField` function is probably the best bet.

**Comment by amitaibu** [comment]
Well, I'm not saying we need to copy exactly what Drupal is doing. It can actually be a simpler adaptation. That is, maybe we can provide a simple solution that upon editing existing entity would:

1. Show the currently selected file
1. Have a checkbox/ button to remove/ delete the file and allow re-uploading a new one.

**Comment by snoyberg** [comment]
Generally speaking, the standard field functions avoid introducing special behavior which would be different than the raw HTML fields. I'm OK if we're setting attributes on a field, but adding custom Javascript goes beyond what most users would expect, and is also not something I really think should be maintained in the core library.

**Comment by amitaibu** [comment]
👍 

I'll try to experiment with it outside core, and if you make sense, I'd port the minimal functionality. Thanks for the feedback :)
