### ISSUE TITLE
add-handler is broken since the scaffolding update

### ISSUE THREAD

**Issue by DylanSp** [yesodweb/yesod#1413]
Since the [June 2017 scaffolding update](http://www.yesodweb.com/blog/2017/06/updated-yesod-scaffolding), yesod add-handler is broken. Running it produces this error:

    yesod: Application.hs: openFile: does not exist (No such file or directory)

It looks like yesod-bin/AddHandler.hs hasn't been updated to reference src/Application.hs. Should it be updated, or is add-handler dead, per the discussion on the [scaffolding update's pull request](https://github.com/yesodweb/yesod-scaffold/pull/147)?

**Comment by ricksanchez** [comment]
I hope it will be back as well 😄 it was useful to avoid around 25 tedious keystrokes

**Comment by MaxGabriel** [comment]
I don't think it's intentionally dead. Would you be able to update it in a pull request to handle both the old and the new location?

**Comment by ygottschalk** [comment]
Is that an acceptable solution?

What should be changed / improved?
