### ISSUE TITLE
Can I use virtualbox shared folder as a static route?

### ISSUE THREAD

**Issue by jeiea** [yesodweb/yesod#1419]
I executed yesod devel in virtualbox ubuntu guest of windows host.
I wanted to modify static files on windows host and tried the folowings.
- Creating a symbolic link in the static directory to virtualbox shared folder, e.g. to `/vagrant/static`.
- Modifying config.yml `static-dir` to `/vagrant/static`.

But both made errors. Modifying `static-dir` to `/mnt` worked well, so it seems I can't use virtualbox shared folder with yesod. Can I bypass this?
The followings are errors.
```
-- When I made symbolic link "assets" in static directory
Variable not in scope: assets_hello_json :: Route Static

-- When I modified static-dir to /vagrant/static
src/Settings/StaticFiles.hs:1:1: error:
    Exception when trying to run compile-time code:
      /vagrant/static: getDirectoryContents:openDirStream: does not exist (No such file or directory)
    Code: staticFiles (appStaticDir compileTimeAppSettings)
```

**Comment by snoyberg** [comment]
It's probably just a limitation in the build system. Try a stack clean and
try again.

**Comment by sbditto85** [comment]
FWIW I have all of the files in the /vagrant/[project_name] directory and then ssh into the vagrant box to build while editing on my host (both windows and mac) and it works fine.

Every once and a while things like yesod-devel don't detect changes, but I don't use yesod-devel anymore.

**Comment by jeiea** [comment]
Sorry, the problem was `docker: true` of stack.yaml.
I'll close this issue.
