### ISSUE TITLE
yesod-persistent's persistent version requirement on hackage is confused

### ISSUE THREAD

**Issue by QuLogic** [yesodweb/yesod#1423]
If you look at [the dependencies](https://hackage.haskell.org/package/yesod-persistent-1.4.2/dependencies), it says:
* persistent (>=2.1 && <2.8)
* persistent-template (>=2.1 && <2.8)

but if you look at the [cabal file in the tarball](https://hackage.haskell.org/package/yesod-persistent-1.4.2/src/yesod-persistent.cabal), it says:
```haskell
                   , persistent                >= 2.1      && < 2.7
                   , persistent-template       >= 2.1      && < 2.7
```
Consequently, one cannot build `yesod-persistent-1.4.2` against `persistent-2.7`.

**Comment by snoyberg** [comment]
Hackage revisions allow cabal file metadata to be edited directly on Hackage without a new tarball being generated. Both Stack and cabal-install handle the logic necessary to grab the latest .cabal file. I'm not sure how you're trying to build the package, but using `stack unpack` should work just fine.

**Comment by QuLogic** [comment]
I am building an RPM, which on Fedora is a fairly thin wrapper around cabal/stack, except that network access is not allowed. Thus it must be built from the tarball and has no idea about the Hackage metadata. I've added a patch in the meantime based on 3229b7ad931cfe476c9569439ea7642a836e3467.

**Comment by QuLogic** [comment]
So it turns out we have some internal tools to tweak the dependencies and avoid any network access. It's a bit of a hack, but it's good enough to build things. I'm going to close this since all that's really needed is a new release and I'd guess that'd happen eventually.
