### ISSUE TITLE
Cassius/Lucius changes trigger recompilation

### ISSUE THREAD

**Issue by alx741** [yesodweb/yesod#1425]
When a change is made in a `cassius` or `lucius` file, the change takes effect immediately and can be observed if the page is refresh within <1s after saving the change to the file (time in which `yesod devel` hasn't started recompilation yet). Although the change takes effect, `yesod devel` detects the change in the file system and triggers recompilation of the module that invokes the template file, forcing a ~10s *unnecessary* wait on the `The application isn’t built` page.

After saving the change in the template file, the output of `yesod devel` is:
> [ 9 of 11] Compiling Handler.Home     ( src/Handler/Home.hs, .stack-work/dist/x86_64-linux-nopie/Cabal-1.24.2.0/build/Handler/Home.o ) [templates/homepage.lucius changed]

Followed by usual recompilation output.

A few months ago a change in a `cassius` or `lucius` file didn't use to trigger recompilation (reload mode).
Not sure if this new behavior arises from a yesod-bin, or scaffolding update though.

**Comment by alx741** [comment]
After some catching up with yesod-bin latest changes, I think this behavior emerges from the use of stack's `--file-watch`, which triggers recompilation on *every file change* including `cassius` and `lucius` templates even though is not needed.

**Comment by snoyberg** [comment]
I do not reproduce this. Stack tracks which files to rebuild based on `addDependentFile` usage, which is _not_ used for the reload versions of cassius, lucius, and julius. Are you able to reproduce this with a freshly scaffolded site?

**Comment by alx741** [comment]
Yes, I just created a new instance of the scaffolding with:
```
stack new someyesod yesod-postgres
stack build yesod-bin cabal-install --install-ghc
stack exec -- yesod devel
```
And the recompilation occurs on every `cassius`, `julius` and `lucius` file change. But I'm able to see the changes reflected in the browser if I refresh really fast (before recompilation begins), just as described above.

Does this not happen to you in the scaffolded site? Could it be that I'm doing something wrong but not seeing it (?)

**Comment by psibi** [comment]
@alx741 Curious to know what version of `yesod` are you using. You can run this under your project to get it:

```
 $ stack exec yesod -- version
yesod-bin version: 1.5.2.2
```

**Comment by alx741** [comment]
@psibi 

`stack exec yesod -- version`
> yesod-bin version: 1.5.2.3


`stack --version`
> Version 1.5.0 x86_64
> Compiled with:
> - Cabal-1.24.2.0
> .....

Running Archlinux
`uname -a`
> Linux amy 4.12.3-1-ARCH #1 SMP PREEMPT Sat Jul 22 15:32:02 UTC 2017 x86_64 GNU/Linux

**Comment by alx741** [comment]
Not sure if relevant, but just in case:
`ag -h "addDependent` gave me (in a fresh scaffolded site)

```
.stack-work/dist/x86_64-linux-nopie/Cabal-1.24.2.0/build/src/Handler/Home.dump-hi
384:addDependentFile "templates/homepage.lucius"
385:addDependentFile "templates/homepage.julius"
386:addDependentFile "templates/homepage.hamlet"
387:addDependentFile "templates/homepage.lucius"
388:addDependentFile "templates/homepage.julius"
389:addDependentFile "templates/homepage.hamlet"
```

**Comment by snoyberg** [comment]
What resolver are you using?

**Comment by alx741** [comment]
Have a couple projects, the same behavior occurs in all of them. These are the resolvers I got:
- lts-6.35
- lts-8.13
- lts-8.19
- lts-9.0

**Comment by alx741** [comment]
So I just freshly installed Ubuntu 16.04 in a virtual machine, then tried with a fresh scaffolded site, and observed the same behavior (needless recompilation after `cassius`, `lucius`, `julius` templates changes)

**Comment by alx741** [comment]
So I just freshly installed Ubuntu 16.04 in a virtual machine, then tried with a fresh scaffolded site and observed the same behavior (needless recompilation after `cassius`, `lucius`, `julius` templates changes)

**Comment by snoyberg** [comment]
Unfortunately I don't think I'm going to get to this soon. The most likely
cause is that `addDependentFile` _is_, for some reason, being called for
functions like cassiusFileReload. If you can track that down in the
shakespeare package, that will probably be the appropriate solution here.

**Comment by alx741** [comment]
@snoyberg thanks, I was trying to track it down by understanding how Stack handles that stuff (with little success), will take a look into Shakespeare.
