### ISSUE TITLE
yesod add-handler does not find Application.hs

### ISSUE THREAD

**Issue by jmn** [yesodweb/yesod#1426]
`yesod: Application.hs: openFile: does not exist (No such file or directory)`

**Comment by snoyberg** [comment]
This should be resolved by #1420, which is released as yesod-bin-1.5.2.5. Can you try upgrading and test if the problem persists?

**Comment by jezen** [comment]
It seems likely that the patch resolved the issue. I’ll close this now anyway as it has been inactive for about two years.
