### ISSUE TITLE
yesod devel does not launch the site in WSL when the project is on the NTFS partition

### ISSUE THREAD

**Issue by ygale** [yesodweb/yesod#1428]
When the yesod project is located on the NTFS partition (for example, `/mnt/c/...`) on Ubuntu 16.04 under WSL, the result of running `yesod devel` is:

    Yesod devel server. Enter quit or hit Ctrl-C to quit.
    Application can be accessed at:

    http://localhost:3000
    https://localhost:3443
    If you wish to test https capabilities, you should set the following variable:
      export APPROOT=https://localhost:3443

    ExitSuccess
    Type help for available commands. Press enter to force a rebuild.

In the browser you get the "Application isn't built" screen.

This assumes that the application has already been built, and a working application executable is available in the normal places.

**Comment by psibi** [comment]
What version of `yesod-bin` are you using ?

**Comment by ygale** [comment]
yesod-bin version: 1.5.2.3

**Comment by psibi** [comment]
What happens if you press Enter ?

**Comment by ygale** [comment]
You get this again:

    ExitSuccess
    Type help for available commands. Press enter to force a rebuild.

**Comment by psibi** [comment]
Does anything change on the browser after you press Enter ?

**Comment by ygale** [comment]
No change, you still get "The application isn't built yet" screen.

**Comment by RJFelix** [comment]
I am having the same issue. `yesod-bin version: 1.6.0`

The application runs fine with `stack build`, `stack exec <app name>`.

**Comment by RJFelix** [comment]
That worked.

My project is using the same LTS snapshot `lts-11.5` as the yesod-simple template.

On a lark, I deleted the `yesod-devel` folder in my project... and that fixed it; `stack exec -- yesod devel` works as usual now. Interesting!

Thanks for the help!

**Comment by snoyberg** [comment]
Cool, thanks for confirming.

**Comment by mberlanda** [comment]
Hello, I am experiencing a slightly different issue but I do not want to duplicate too many issues.

In my case the compiler claims the application was built successfully but when I connect to localhost:3000 I see that the application isn't built: https://stackoverflow.com/questions/75944169/yesod-scaffold-returns-error-the-application-isn-t-built

The unit tests work fine and generate a few sqlite files, which are not generated by ´yesod devel´ command.

Is there any additional flag I can use to investigate the issue and have a better understanding of what is not working? Using the verbose flag is not providing insightful details.

**Comment by mberlanda** [comment]
I managed to reply the same command described in the SO outside WSL and everything worked at the first run.
What is not getting prompted in WSL are the lines after Success!
```
Type help for available commands. Press enter to force a rebuild.
Starting devel application
Migrating: CREATE TABLE "user"("id" INTEGER PRIMARY KEY,"ident" VARCHAR NOT NULL,"password" VARCHAR NULL,CONSTRAINT "unique_user" UNIQUE ("ident"))
10/Apr/2023:14:28:16 +0200 [Debug#SQL] CREATE TABLE "user"("id" INTEGER PRIMARY KEY,"ident" VARCHAR NOT NULL,"password" VARCHAR NULL,CONSTRAINT "unique_user" UNIQUE ("ident")); []
Migrating: CREATE TABLE "email"("id" INTEGER PRIMARY KEY,"email" VARCHAR NOT NULL,"user_id" INTEGER NULL REFERENCES "user" ON DELETE RESTRICT ON UPDATE RESTRICT,"verkey" VARCHAR NULL,CONSTRAINT "unique_email" UNIQUE ("email"))
Migrating: CREATE TABLE "comment"("id" INTEGER PRIMARY KEY,"message" VARCHAR NOT NULL,"user_id" INTEGER NULL REFERENCES "user" ON DELETE RESTRICT ON UPDATE RESTRICT)
Devel application launched: http://localhost:3000
10/Apr/2023:14:28:16 +0200 [Debug#SQL] CREATE TABLE "email"("id" INTEGER PRIMARY KEY,"email" VARCHAR NOT NULL,"user_id" INTEGER NULL REFERENCES "user" ON DELETE RESTRICT ON UPDATE RESTRICT,"verkey" VARCHAR NULL,CONSTRAINT "unique_email" UNIQUE ("email")); []
10/Apr/2023:14:28:16 +0200 [Debug#SQL] CREATE TABLE "comment"("id" INTEGER PRIMARY KEY,"message" VARCHAR NOT NULL,"user_id" INTEGER NULL REFERENCES "user" ON DELETE RESTRICT ON UPDATE RESTRICT); []
10/Apr/2023:14:28:44 +0200 [Debug#SQL] SELECT "id", "message", "user_id" FROM "comment" ORDER BY "id"; []
GET /
  Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8
  Status: 200 OK 0.040888s
 ```
 
 Is there any advanced debug flag or logger that I could put in the code to understand what is not working as intended when running from WSL?
