### ISSUE TITLE
yesod-form: remove line break in postHelper function

### ISSUE THREAD

**Issue by waddlaw** [yesodweb/yesod#1430]
It will be always added newline after input tag for token.

```html
<form method="post" action="http://localhost:3000/contact" enctype="application/x-www-form-urlencoded"><input type="hidden" name="_token" value="xxxxxxx">
<div>
<!-- folowing form html -->
```

The cause is [postHelper](https://github.com/yesodweb/yesod/blob/master/yesod-form/Yesod/Form/Functions.hs#L219) function.

```haskell
postHelper form env = do
    req <- getRequest
    let tokenKey = defaultCsrfParamName
    let token =
            case reqToken req of
                Nothing -> Data.Monoid.mempty
                Just n -> [shamlet|<input type=hidden name=#{tokenKey} value=#{n}>|]
```

I think that better behave to add `$newline never` in `shamlet`.

**Comment by snoyberg** [comment]
I'm not opposed to a PR to implement this, but can you clarify if this is actually causing trouble as opposed to being done for aesthetics in the generated HTML?

**Comment by waddlaw** [comment]
@snoyberg 
Sorry for my late reply.
I see. Trouble is nothing at all maybe. But, I think that ugly in my sense.

You think that It is better not to change this behave?
Thank you.

**Comment by snoyberg** [comment]
I'd probably lean towards not bothering with if it isn't causing causing trouble beyond an extra newline character in the HTML itself.

**Comment by waddlaw** [comment]
OK. thanks.
I'll close this issue.
