### ISSUE TITLE
yesod-form: Reduce verbosity using Monadic Forms

### ISSUE THREAD

**Issue by sestrella** [yesodweb/yesod#1431]
Building forms where some fields validations depend on other fields is simple using Monadic Forms, but as the own Yesod website mentioned:

> it does so at the cost of being more verbose.

Some of this verbosity is caused by the need of grouping the `FiedView site` returned by either `mreq` or `mopt`. Also on the other hand, `formToAForm` requires a Monadic Form like `MForm m (FormResult a, [FieldView site])` to able to transform to `AForm m a`. Consider the following scenario:

```hs
formToAForm $ do
  (field1F, field1V) <- mreq textField MsgField1 Nothing
  (field2F, field2V) <- mreq (checkWith field1F textField) MsgField2 Nothing
  (field3F, field3V) <- mreq (checkWith field1F textField) MsgField3 Nothing
  return
    ( MyForm <$> field1F
                     <*> field2F
                     <*> field3F
    , [field1V, field2V, field3V]
    )
```

While the previous example could be refactored to use Applicative Form style, it requires combining the fields in order to be able to run a custom check. Doing that for more than one field that depends on one value is a little bit tricky using Applicative style.

I'll like to propose adding the following variant of a Monadic Form:

```hs
type WForm m a = MForm (WriterT [FieldView (HandlerSite m)] m) a
```

And the correspondent `req` and `opt` functions like:

```hs
wreq :: (...) => Field m a -> FieldSettings site -> Maybe a -> WForm m (FormResult a)

wopt :: (...) => Field m a -> FieldSettings site -> Maybe (Maybe a) -> WForm m (FormResult (Maybe a))

wFormToAForm ::  WForm  m (FormResult a) -> AForm m a
```

The example above then could be rewritten as follows:

```hs
wFormToAForm $ do
  field1F <- wreq textField MsgField1 Nothing
  field2F <- wreq (checkWith field1F textField) MsgField2 Nothing
  field3F <- wreq (checkWith field1F textField) MsgField3 Nothing
  return $
      MyForm <$> field1F
                    <*> field2F
                    <*> field3F
```

I'll be more than happy to submit a PR if this proposal makes sense to the maintainers.

**Comment by snoyberg** [comment]
That looks pretty nifty! Yeah, I think this could be a good addition. Thanks!
