### ISSUE TITLE
Regression:  parseRoutes TH no longer accepts tab indentation

### ISSUE THREAD

**Issue by mounty1** [yesodweb/yesod#1440]
If the routes are indented by one or more tabs, the following error message is produced:

    • Exception when trying to run compile-time code:
        Invalid resource line

When the tabs are replaced with spaces, the code is compled.

I hope, I just hope, that this is an accident, and that Michael has not fallen for the current fascism of forbidding tabs because some people cannot work them.

**Comment by snoyberg** [comment]
I'm not aware of any specific decision to change this. At least, I don't _remember_ any such decision. You say this is a regression: when did it last work?

**Comment by mounty1** [comment]
Last worked about three months ago;  the delay in my response was because I was wanted to bisect down to a more specific time when it went wrong, but am unable to do so.

**Comment by snoyberg** [comment]
I just tested a basic example on my machine which worked fine:

```haskell
{-# LANGUAGE OverloadedStrings     #-}
{-# LANGUAGE QuasiQuotes           #-}
{-# LANGUAGE TemplateHaskell       #-}
{-# LANGUAGE TypeFamilies          #-}
import           Yesod.Core

data HelloWorld = HelloWorld

mkYesod "HelloWorld" [parseRoutes|
	/ HomeR GET
|]

instance Yesod HelloWorld

getHomeR :: Handler Html
getHomeR = defaultLayout [whamlet|Hello World!|]

main :: IO ()
main = warp 3000 HelloWorld
```

Can you provide a minimal reproducing case? Also, please including the exact version you're compiling against. Looking in the latest version of the codebase, there is no way for that specific error message to be generated (the string always contains more characters).

**Comment by mounty1** [comment]
I am sorry Michael but am now, thankfully, unable to reproduce this problem.  Thank you for your prompt attention.
