### ISSUE TITLE
Proposal: Compile-time checking globally loaded scripts for Yesod

### ISSUE THREAD

**Issue by owickstrom** [yesodweb/yesod#1441]
This is more of a feature request/proposal than an issue. Or maybe just a discussion if this should go into Yesod, or in to a separate library. I have done some hacking to try out my ideas, available in this gist: https://gist.github.com/owickstrom/91615af9d0de89cf2107efaa57a8b019. The example does not build on Yesod, just to keep it simple and illustrate the technique. I hope it is clear enough, anyway. :smile: 

## Summary (same as in the gist)

Yesod has powerful features for including dynamic scripts, using widgets. In many cases this is exactly what I want, but in some, I want scripts to be loaded globally in all pages.

The primary motivation for globally loaded scripts, appearing in the `<head>` element in all pages, is for using something like PJAX, possibly together with HTML5 custom elements. I'd like to declare a number of custom elements, and only use HTML markup in the widgets using the custom elements, i.e. no dynamic script tags added to the page by the widgets. By doing so, the PJAX-variant could be much simpler, not having to inject scripts in the page sent in the PJAX response. All custom elements' Javascript would already be loaded, and the DOM insertions of the widget markup would trigger the scripts to run.

A complication with these global scripts are that all _possibly needed scripts have to be loaded_. For this to be statically known, at compile-time, the globally loaded scripts need to represented in types somehow. This demonstration is a dumbed down version of Yesod, just to illustrate the design, and some machinery for associating global scripts with an application (Foundation type).

## Questions/Remarks

* Could this be integrated into Yesod itself, or should it be a separate library? The upside of integrating into Yesod would be not having to remember to also include the `scriptSources (globalScripts app)` in your code.
* It only supports separate data types implementing `ScriptSource`, like `JQuery` and `MyCustomElements` from the example. It would be nice to support Yesod route types and be able to point to static assets, perhaps without the intermediate data type, e.g. `MyCustomElements`.
* There's no support for local declarations of scripts, like `toWidget [hamlet| ... |]`. Not sure if it would be possible to do that using the Symbol kind. Such local scripts would then be globally added to all pages.
* The term "global" might be confusing. What I mean is scripts that are loaded for all pages -- basically a way for widgets and handlers to signal that they require some script be included in the "master" layout.

Any feedback on this would be very welcome! I can try creating a library first, as I need this for a work project, but it would be helpful to get some input before hacking away.

**Comment by owickstrom** [comment]
Just improved the gist a bit, and edited the description for this issue.

**Comment by snoyberg** [comment]
I'm not sure I follow completely what's going on here. It seems like you're trying to get a way so that you can state:

* foo.js depends on bar.js
* bar.js depends on baz.js
* If a widget using bar.js, automatically include baz.js

Which today would be expressible using something like:

```haskell
fooWidget :: Widget
fooWidget = barWidget >> addScript (StaticR foo_js)

barWidget :: Widget
barWidget = bazWidget >> addScriptRemote "http://.../bar.js"

bazWidget :: Widget
bazWidget = addScript (StaticR baz_js)

someWidget :: Widget
someWidget = do
  barWidget
  toWidget [hamlet|<uses-bar-somehow>Hello World!|]
```

**Comment by owickstrom** [comment]
Yes, in regular "full" page renders that would work. But what I'm after is PJAX-rendered partials, i.e. only the inner container HTML, _without any script tags_.

Say I have three global scripts:

``` js
// foo.js
var Foo = document.registerElement('foo');
// bar.js
var Bar = document.registerElement('bar');
// baz.js
var Baz = document.registerElement('baz');
```
And three pages (and that I could use `requireGlobalScript` together with `StaticR`):

``` haskell
fooR :: Handler Html
fooR = do
  requireGlobalScript (StaticR foo_js)
  toWidget [hamlet|<foo>Cool!|]

barR :: Handler Html
barR =  do
  requireGlobalScript (StaticR bar_js)
  toWidget [hamlet|<bar>Neat!|]

bazR :: Handler Html
bazR =  do
  requireGlobalScript (StaticR baz_js)
  toWidget [hamlet|<baz>Swell!|]
```

When doing a full render, of any page, all three scripts would be loaded. When PJAX-requesting any of the pages, only the markup would be sent, e.g. `<baz>Swell!</baz>`, no script tags. All custom elements (in this example) would be registered in all pages, no matter where you "enter" the site.

I realize that this example is quite specific to my use case, so maybe it should be a separate library. If one does not have the specific requirement on avoiding script tags in PJAX responses, using `addScript (StaticR ...)` is probably the way to go.

Thanks for having a look at this!

**Comment by snoyberg** [comment]
I would recommend starting this as a separate library and getting buy in on
it. I still think it may be possible to achieve this somehow using standard
widgets and analyzing the generated Monoid value that has the list of all
scripts, but I don't think I'm fully understanding the use case.

**Comment by owickstrom** [comment]
Sounds good! I'll ping you when and if I get the time to write the library up. :+1: Thanks!
