### ISSUE TITLE
Feature / Question: forcing a protocol in rendered URL

### ISSUE THREAD

**Issue by netom** [yesodweb/yesod#1447]
I'm running a toy site for instant messaging. It uses websockets.

One route in particular (WallR key) handles HTTP and Websocket traffic too, normally it returns some html and JS which in turn connects back on websocket (e.g.: https://donotsavemy.info/wall/thisisthekeyforthemessagewall123).

If I get the URL renderer function, it will always return an URL for the page with the https protocol. This is fine. :)

However, I need a websocket (wss://) url to connect back to the server.

As one can see on the page above, I currently do this by monkey-patching the https://... url from javascript: ...replace(/^http/, "ws") which is I think less than optimal.

Is it possible to get the URL renderer function to use one desired protocol?

If not, where this feature should go? Is this has a place in yesod, or yesod-websockets (to deal with ws/wss urls in particular)?

Thank you,

Tamas

**Comment by snoyberg** [comment]
The best approach I can think of would be to have two separate routes, one for HTTP, and one for WS, and then modify [urlParamRenderOverride](https://www.stackage.org/haddock/lts-9.6/yesod-core-1.4.37/Yesod-Core.html#v:urlParamRenderOverride) to use a different approot for the WS route.

**Comment by netom** [comment]
Thank you for the help @snoyberg, I managed to conjure up a solution for this.
