### ISSUE TITLE
[For all yesodweb projects] Adding an PR/issue template

### ISSUE THREAD

**Issue by MaxGabriel** [yesodweb/yesod#1450]
@snoyberg's [recent blog post](https://www.snoyman.com/blog/2017/10/manipulating-maintainers) has a number of suggestions for improving bug reports:

* "include the error message, full code, OS, compiler version, and other such things"
* Be concise. Start off with the most highly pertinent information. Make it clear what you're trying to do. If you have a 400 line error message, perhaps put it in an lpaste or Gist and link to it.
* Provide a minimal repro.
* Make sure to mention any custom configuration.

A potential way to get these quality bug reports for the yesodweb family of projects would be to have an issue template suggesting what information to include. This is done by creating a .github folder and including an [issue/PR template](https://github.com/blog/2111-issue-and-pull-request-templates) inside it. Rough example of what it would look like:

>Reporting a bug? If relevant, we recommend including:
>
>* Your OS name and version
>* The versions of tools you're using (e.g. `stack`, `yesod` `ghc`).
>* The versions of dependencies you're using
>
>For your convenience, we recommend pasting this script into bash and uploading the output [as a gist](https://gist.github.com/).
>
>```
>command -v sw_vers && sw_vers # OS X only
>command -v uname && uname -a # Kernel version
>command -v stack && stack --version
>command -v stack && stack ghc -- --version
>command -v stack && stack list-dependencies
>command -v yesod && yesod version
>```
>
> Also, is there anything custom or unusual about your setup? i.e. new or prerelease versions of GHC, stack, etc.
>
> Finally, if possible, please reproduce the error in a small script, or if necessary create a new Github repo with the smallest possible reproducing case.

An example of a project using such a template that I liked was Fish shell: https://github.com/fish-shell/fish-shell/issues/new

<hr>

For pull requests, I think almost all first-time contributors to the Yesod family of projects miss one of these things:

1. Updating the changelog
2. Documenting new APIs
3. Adding `@since` declarations

Which requires someone to ask for those changes. This introduces delays into getting PRs merged, wastes peoples time, might make the contributor frustrated that they have to make additional edits, and might make maintainers feel like they're nagging. An easy fix would be having those items as a checklist in the template for PRs like so:

> Before submitting your PR, check that you've
> 
> - [ ] Documented new APIs with Haddock markup
> - [ ] Adding [`@since` declarations](http://haskell-haddock.readthedocs.io/en/latest/markup.html#since) to the Haddock 
>
> After submitting your PR, make a new commit linking to that PR in the Changelog.md file:
> - [ ] Updated the changelog 
>
> Thanks so much for contributing! :)

<hr>

Relevant questions:

1. Do you think this is a good idea?
2. Is there any specific information you think should be included in either the issue or PR templates? Possible examples: Common questions like "Are you using Stack or Cabal?", or recommendations to try Stackoverflow/the Yesod mailing list for help before asking for help via Github issues
3. Is there anything you'd want to avoid in the templates?

This issue is reported to `yesod`, but I think most of this is generic enough to paste into the other yesodweb projects. Possibly specific projects should have some custom information, like the Persistent repo explaining how to create a reproducible test case for Persistent.

**Comment by snoyberg** [comment]
1. YES! This is a great idea.
2. Nothing comes to mind right now, but those are both good examples.
3. Also can't think of anything.

Thanks for bringing this up 👍

**Comment by paul-rouse** [comment]
Yes, I like this - especially the way you have made it light-weight and not too formal-looking!  My only suggestion is that the PR one could give a gentle hint about coming back and checking the integration tests - maybe it's enough to say "Please ask for help if you do not understand any failures in the travis/appveyor tests."

**Comment by psibi** [comment]
One point regarding the issue template - can we ask them to ask support questions in Stackoverflow instead of here ? We can probably add a note that if the Stackoverflow question isn't answered in a week or so, they can ask it here again.

**Comment by MaxGabriel** [comment]
Cool, I implemented this in #1451. It implements by @paul-rouse and @psibi's ideas about the templates as well.
