### ISSUE TITLE
Code of conduct needs work

### ISSUE THREAD

**Issue by spdegabrielle** [yesodweb/yesod#1452]
https://github.com/yesodweb/yesod/blob/master/CODE_OF_CONDUCT.md
It’s good that it has been started. Consider copying a mature code of conduct and establishing appropriate governance to ensure it is enforced.

**Comment by eq** [comment]
I don't see what is wrong with this code of conduct? It's simple, concise, and gets to the point. What's missing here?

**Comment by spdegabrielle** [comment]
I was being polite.

**Comment by snoyberg** [comment]
Please see #1460

**Comment by snoyberg** [comment]
I think the new CoC in #1460 should address this issue, closing. Thanks for the report.
