### ISSUE TITLE
`byLabel` fails if multiple label names start with the given label name

### ISSUE THREAD

**Issue by pythonissam** [yesodweb/yesod#1454]
ex.) Call `byLabel "hobby" "fishing"` and if the form has `<label for="hobby">hobby</label>` and `<label for="hobby2">hobby2</label>`. Then, it fails with `"More than one label contained "` **ALTHOUGH THEIR NAMES ARE DIFFERENT**.

`Yesod.Test.byLabel` calls `nameFromLabel` in its definition. `nameFromLabel` looks up the name of a field based on the contents of the label pointing to it. In its definition, label names which start with `label` are assigned into `mlabel`

```haskell
mlabel = parseHTML body
                $// C.element "label"
                >=> contentContains label

contentContains x c
        | x `T.isInfixOf` T.concat (c $// content) = [c]
        | otherwise = []
```

Then, the definition follows:

```haskell
mfor = mlabel >>= attribute "for"

case mfor of
    for:[] -> do
      let mname = parseHTML body
                    $// attributeIs "id" for
                    >=> attribute "name"
      case mname of
        "":_ -> failure $ T.concat
            [ "Label "
            , label
            , " resolved to id "
            , for
            , " which was not found. "
            ]
        name:_ -> return name
        [] -> failure $ "No input with id " <> for
    [] ->
      case filter (/= "") $ mlabel >>= (child >=> C.element "input" >=> attribute "name") of
        [] -> failure $ "No label contained: " <> label
        name:_ -> return name
    _ -> failure $ "More than one label contained " <> label
```

Here, the first example fails. Apparently, the cause is that we used `T.isInfixOf` in `contentContains` and not only `"hobby"`, but also `"hobby2"` is taken because it contains "hobby" at the beginning.

**Comment by snoyberg** [comment]
It would be great if you could submit a PR adding a failing test case for this. Even better if it includes a fix too of course :) Would you be able to take a stab at the tests?

**Comment by snoyberg** [comment]
Since it's a breaking behavioral change, I'd suggest making a new function, `byLabelExact`. Some people may be relying on the current behavior.

**Comment by MaxGabriel** [comment]
I found the current behavior pretty confusing. Possibly deprecating byLabel, and adding new functions (e.g. byLabelContains/byLabelExact, or something like addParamForLabel/addParamForLabelContains) could be better?

**Comment by snoyberg** [comment]
Sounds reasonable to me.

On Wed, Nov 22, 2017 at 3:07 PM, Maximilian Tagher <notifications@github.com

**Comment by pythonissam** [comment]
@snoyberg I understand. I'll try.

**Comment by pythonissam** [comment]
Being related to this issue, I found another bug in `byLabel` and `fileByLabel`. The bug possibly lead them set values to incorrect labels. I'm not sure whether we should modify them or not because they'll be deprecated and the bug doesn't appear in exact versions of the functions.
