### ISSUE TITLE
`stack exec -- yesod keter` does not respect `--stack-yaml` option

### ISSUE THREAD

**Issue by jezen** [yesodweb/yesod#1472]
I'm using a custom `stack.yaml`, which doesn't include a stanza for Nix. Specifying the custom `stack.yaml` works in all cases I've tried, except for with `yesod keter`.

### Example 1:  With `yesod --help`

This fails as I expect

```
$ stack exec -- yesod --help
Executable named nix-shell not found on path: ["/usr/local/sbin","/usr/local/bin","/usr/sbin","/usr/bin","/sbin","/bin","/usr/games","/usr/local/games"]
```

…And this works as I expect

```
$ stack --stack-yaml stack.production.yaml exec -- yesod --help
Yesod Web Framework command line utility

Usage: yesod [-d|--dev] [-v|--verbose] COMMAND

...etc
```

### Example 2: With `yesod keter`

This fails as I expect

```
$ stack exec -- yesod keter
Executable named nix-shell not found on path: ["/usr/local/sbin","/usr/local/bin","/usr/sbin","/usr/bin","/sbin","/bin","/usr/games","/usr/local/games"]
```

I expect the following to work, but it fails.

```
$ stack --stack-yaml stack.production.yaml exec -- yesod keter
Executable named nix-shell not found on path: ["/root/newbusinessmonitor.co.uk/.stack-work/install/x86_64-linux/lts-9.18/8.0.2/bin","/root/.stack/snapshots/x86_64-linux/lts-9.18/8.0.2/bin","/root/.stack/compiler-tools/x86_64-linux/ghc-8.0.2/bin","/root/.stack/programs/x86_64-linux/ghc-8.0.2/bin","/usr/local/sbin","/usr/local/bin","/usr/sbin","/usr/bin","/sbin","/bin","/usr/games","/usr/local/games"]
```
_I don't know, but it may be interesting that the path described in this failure is not the same as the path described in the previous failure_.

Curiously enough, specifying the custom `stack.yaml` with an environment variable (which I discovered you could do [here](https://github.com/yesodweb/yesod/blob/master/yesod-bin/Keter.hs#L86)), works just fine

```
$ STACK_YAML=stack.production.yaml stack exec -- yesod keter
Getting project config file from STACK_YAML environment
nbm-0.0.0: unregistering (local file changes: app/DevelMain.hs app/main.hs nbm.cabal package.yaml src/Application.hs src/Foundation.hs src/GoCa...)
Building all executables for `nbm' once. After a successful build of all of them, only specified executables will be rebuilt.
nbm-0.0.0: configure (lib + exe)
Configuring nbm-0.0.0...
etc
```

**Comment by snoyberg** [comment]
I don't think there's a way to get `yesod keter` to behave the way you're
hoping, though a PR to take an extra argument for the stack.yaml file would
work. I'd personally just use the environment variable approach.

**Comment by jezen** [comment]
@snoyberg is it actually the case that Stack should be responsible for this, and not Yesod? I am inferring from [this line][0] that running `stack exec` sets `STACK_EXE` in the environment. Could that also mean that using the `--stack-yaml` flag when running Stack could set the `STACK_YAML` environment variable? I don't know whether or not it should work this way.

[0]: https://github.com/yesodweb/yesod/blob/master/yesod-bin/Keter.hs#L85

**Comment by snoyberg** [comment]
Even your statement here is saying that Stack should be responsible, by
setting STACK_YAML. That's certainly one approach that could be taken here,
but the change is still in Stack.

**Comment by jezen** [comment]
@snoyberg Sure, but I didn't know that when I opened this issue.

I'll move this issue over to Stack 🙂
