### ISSUE TITLE
[Suggestion] byLabelContain

### ISSUE THREAD

**Issue by pythonissam** [yesodweb/yesod#1480]
In #1454, we put `byLabel` into deprecated. However, it might be useful when we have labels that are too long to write. Since `byLabel` matches over the prefix of labels, we can shorten their names and pass them to `byLabel`. So I think it's nice if we can rename it as `byLabelContain` and fix existing bugs. Thank you for your consideration.

**Comment by snoyberg** [comment]
No objection with this, interested in sending a PR?

**Comment by pythonissam** [comment]
Yes! I'd love to:)
