### ISSUE TITLE
Error handling as SomeException

### ISSUE THREAD

**Issue by pbrisbin** [yesodweb/yesod#1486]
We're currently incorporating Bugsnag into our application. To do so effectively, we really want to see the application-level errors as a `SomeException`, so we can report them with an accurate `errorClass` and/or take further action such as custom grouping, ignoring, etc based on exception-specific data.

Customizing the `errorHandler` member of `Yesod` only gets access to an already stringified error message in the `InternalError` case, which is not very useful.

Warp's `onException` setting is the interface we're looking for, but it seems application-level exceptions don't make it out here.

I really don't want to resort to wrapping every individual handler body with something.

Am I missing another extension point? If not, would a PR to add one be accepted? If so, any pointers on where or how to do that?

**Comment by snoyberg** [comment]
I think you can use `yesodMiddleware` for this purpose.

**Comment by MaxGabriel** [comment]
My friends are the co-founders of Bugsnag. Tell me how you like it!

**Comment by pbrisbin** [comment]
@snoyberg of course! Thanks for pointing that out, I totally didn't realize there was Yesod middleware too that worked at that level.

@MaxGabriel Bugsnag is definitely the best error-tracker I've used. It's got a great interface, good timeline and user analytics, the grouping is nice and everything's really customizable. I also love tracking app version and marking things as fixed. FWIW, the reporter I'm putting together is here: https://github.com/pbrisbin/bugsnag-reporter

**Comment by MaxGabriel** [comment]
Cool, it’s a much bigger project than I realized @pbrisbin. I’m pretty sure Bugsnag would accept it on their Github if you think it’d get more visibility there
