### ISSUE TITLE
Yesod.Auth.authHttpManager API change

### ISSUE THREAD

**Issue by psibi** [yesodweb/yesod#1489]
In the recent `unliftio` rewrite, there has been API change of `authHttpManager` from

```
authHttpManager :: master -> Manager
```

to

```
authHttpManager :: AuthHandler master Manager
```

Is this an intended change ? I don't see any specific reason why the old API wouldn't work in the new setup.

**Comment by snoyberg** [comment]
It was for a different reason: the original type signature was too restrictive, and didn't allow usage of the new global manager provided by http-client-tls. By having this generalized type signature, we can skip the need to initialize a manager in the foundation data type, simplifying usage of yesod-auth somewhat. Said another way: we now have a useful default implementation.

**Comment by psibi** [comment]
Thanks, that makes it clear. Have opened a PR which will solve similar confusion in future: https://github.com/yesodweb/yesod/pull/1490
