### ISSUE TITLE
staticFiles doesn't close file handles?

### ISSUE THREAD

**Issue by luite** [yesodweb/yesod#149]
On OS X 10.7.1 the default ulimit for open files is rather low (256), this results in this problem compiling my project:
devel.hs: static/jquery-ui-1.9m5/demos/resizable/max-min.html: openBinaryFile: resource exhausted (Too many open files)

**Comment by lippling** [comment]
@snoyberg I think this is still a problem.

```haskell
mkEmbeddedStatic
    False
    "eStatic"
    [ embedDirAt "js" "static/js"
    ]
```

gives

```
Exception when trying to run compile-time code:
      static/js/ace-min/mode-groovy.js: openBinaryFile: resource exhausted (Too many open files)
    Code: mkEmbeddedStatic
            ghc-prim-0.4.0.0:GHC.Types.False
            "eStatic"
            [embedDirAt "js" "static/js"]
```

I'm using yesod-static 1.5.0.3, Mac OS 10.11.6. The `js` folder contains 350 items.

The error goes away with `ulimit -n 8192` in the current terminal.

**Comment by snoyberg** [comment]
https://twitter.com/snoyberg/status/786762554118922240?s=09

Incoming patch to test, once I get back home

**Comment by snoyberg** [comment]
Can you test out https://github.com/yesodweb/yesod/commit/6228ccc351635ea91f9255974f23d83dff7d71bd?

**Comment by lippling** [comment]
Yes, it works now!
Thanks!

**Comment by snoyberg** [comment]
Cool, thanks for confirming. Releasing to Hackage now.
