### ISSUE TITLE
Hyperlinks in lists are leaking

### ISSUE THREAD

**Issue by yohad** [yesodweb/yesod#1491]
Hi,
I have the following hamlet template:
```
[hamlet|
           <html>
             <head>
               <p>Head
             <body>
               <article>
                 <ul>
                   <li><a href=@{HomeR}>Home
                 <p>Content!
           |]
```
which translate to 
```
<html>
  <head></head>
  <body>
    <p>Head</p>
    <article>
      <ul>
        <li><a href="/">Home</a></li>
        <a href="/"></a>
      </ul>
      <a href="/"><p>Content!</p></a>
    </article>
    <a href="/"></a>
  </body>
</html>
```
As you can see, there are hyperlinks in every tag which is quite annoying and not expected.

**Comment by psibi** [comment]
Can  you show a reproducible code for this ? You can use [stack interpreter](https://docs.haskellstack.org/en/stable/GUIDE/#script-interpreter) to give a demo of this problem.

**Comment by snoyberg** [comment]
I'm pretty sure the problem is here:

    <li><a href=@{HomeR}>Home

In Hamlet, only the first tag on a line auto-closes. So you can rewrite this as:

```hamlet
<li>
    <a href="/">Home
```

or

```hamlet
<li><a href=@{HomeR}>Home</a>
```

**Comment by yohad** [comment]
@snoyberg That fixed the error, thanks.
