### ISSUE TITLE
Show actual next to expected in yesod tests

### ISSUE THREAD

**Issue by Qwertie-** [yesodweb/yesod#1495]
In my test I have
` bodyEquals "[{\"name\":\"a\",\"id\":1,\"desc\":null}]"`
and while running the test it fails with the error:
`Expected body to equal [{"name":"a","id":1,"desc":null}] `
That's all fine but after seeing that the next thing I want to know is what was the body if it wasn't that.
Other test systems show the actual next to the expected which saves you having to go back and add a print in to the tests to see what went wrong.

**Comment by Qwertie-** [comment]
For `bodyContains` there might be large responses but I think if you are using `bodyEquals` you are likely testing an API with a fairly small response because you have to fit the body in your test.

**Comment by snoyberg** [comment]
Fair enough. In that case, PR to change the implementation is welcome.

**Comment by StevenXL** [comment]
Closed due to merge of #1525.
