### ISSUE TITLE
Adding `assertFailure` to yesod-test

### ISSUE THREAD

**Issue by pythonissam** [yesodweb/yesod#1496]
[`assertFailure`](https://www.stackage.org/haddock/lts-11.2/HUnit-1.6.0.0/Test-HUnit-Base.html#v:assertFailure) is useful, so I suggest introducing it in `yesod-test`. The implementation would be like this:

```haskell
import qualified Test.HUnit.Base as HUnit (assertFailure)

assertFailure :: HasCallStack => String -> YesodExample site ()
assertFailure = liftIO . HUnit.assertFailure
```

**Comment by snoyberg** [comment]
Seems reasonable to me, want to send a PR?

**Comment by pythonissam** [comment]
Yes. I'd like to :)
