### ISSUE TITLE
[Suggestion] Implement `delete` like `post` or `get`

### ISSUE THREAD

**Issue by pythonissam** [yesodweb/yesod#1498]
There're [`get`](https://www.stackage.org/haddock/lts-11.2/yesod-test-1.6.2/src/Yesod.Test.html#get) and [`post`](https://www.stackage.org/haddock/lts-11.2/yesod-test-1.6.2/src/Yesod.Test.html#post), but there's no `delete`. Why don't we implement the `delete` version of them?

**Comment by snoyberg** [comment]
To be sure we're all on the same page: you're speaking specifically of the `yesod-test` library, right?

**Comment by pythonissam** [comment]
Yes!

**Comment by snoyberg** [comment]
Potential naming conflicts with existing delete and put functions in the ecosystem could be problematic. What about a more general function that takes a ByteString for the request method?

**Comment by pythonissam** [comment]
No objection with that. I'm going to send PR.
