### ISSUE TITLE
loginDest not working in yesod

### ISSUE THREAD

**Issue by MarcCoquand** [yesodweb/yesod#1508]
When trying to set the loginDest it does not work when using the auth-hardcoded package. I tried with the following code:
```
instance YesodAuth App where
    type AuthId App = Text

    -- Where to send a user after successful login
    loginDest :: App -> Route App
    loginDest _ = ProfileR
    -- Where to send a user after logout
    logoutDest :: App -> Route App
    logoutDest _ = HomeR
    -- Override the above two destinations when a Referer: header is present
    redirectToReferer :: App -> Bool
    redirectToReferer _ = True

    authPlugins _ = [authHardcoded]

    authenticate Creds{..} =
        return
        (case credsPlugin of
            "hardcoded" ->
                case lookupUser credsIdent of
                    Nothing -> UserError InvalidLogin
                    Just m  -> Authenticated (sportClubUsername m)
            _ -> UserError InvalidLogin)
```
As you notice from the code, intuitively the user should be taken to ProfileR after login. However it compiles fine but after a login in the user is taken to HomeR instead of ProfileR. Either there is something wrong with the documentation, a bug or I'm missing something. This is after I modified the scaffolded website and changed the normal user Auth to a hardcoded login. There is also a question mark added to the url so it becomes localhost:3000/?

* OS: MacOs High Sierra 10.3
* stack version 1.6.5, using 
- yesod >=1.6 && <1.7
- yesod-core >=1.6 && <1.7
- yesod-auth >=1.6 && <1.7

**Comment by rnons** [comment]
I had this problem as well when using `lts-11.3`. But the problem is gone after upgrading to `lts-11.14`.

**Comment by jezen** [comment]
This issue seems pretty inactive, so I think we can close it.
