### ISSUE TITLE
Expose selectFieldHelper in Yesod/Form/Fields.hs

### ISSUE THREAD

**Issue by pythonissam** [yesodweb/yesod#1521]
I suggest exposing `selectFieldHelper` in [Yesod/Form/Fields.hs](https://github.com/yesodweb/yesod/blob/master/yesod-form/Yesod/Form/Fields.hs#L732-L765). How do you think?

**Comment by snoyberg** [comment]
What's a motivating use case for doing so? That function as it currently stands isn't well documented or particularly pretty. We haven't had a breaking change in it in a long time, but I'd still like to be cautious about exposing ugly functions without a strong motivation.

**Comment by bitemyapp** [comment]
I had to copy and paste selectFieldHelper into a client's codebase recently because it wasn't exported. I can show you if you like.

**Comment by pythonissam** [comment]
@snoyberg As @bitemyapp says, we have to copy and paste this function every time we want to create forms that use other frameworks rather than Bootstrap (i.e. Bulma). This is it.

**Comment by snoyberg** [comment]
OK, in that case, a PR exposing the function and adding a bit of documentation to it would be accepted.

**Comment by pythonissam** [comment]
I understand. I'm working on it:)

**Comment by StevenXL** [comment]
Addressed by #1530.
