### ISSUE TITLE
Setting X-XSS-Protection: 1 in response header by default?

### ISSUE THREAD

**Issue by pythonissam** [yesodweb/yesod#1543]
I suggest setting [X-XSS-Protection: 1](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-XSS-Protection) in HTTP response header by default. With this setting, Yesod can force browsers to enable XSS filtering. I think it allows us to enforce Yesod's security.

Putting `addHeader` into `defaultYesodMiddleware` or modifying stack-template would work.

**Comment by MaxGabriel** [comment]
My understanding is that `1` is the default for all browsers that support it. Though there's a case to be made for using `1; mode=block` instead 

https://blog.innerht.ml/the-misunderstood-x-xss-protection/
https://markitzeroday.com/headers/content-security-policy/2018/02/10/x-xss-protection.html

**Comment by pythonissam** [comment]
Ah, you're right! Yes, `1; mode=block` is what i meant. haha

**Comment by StevenXL** [comment]
Addressed by #1550.
