### ISSUE TITLE
Yesod-1.6 writes URLs in absolute form (with top-level domain)

### ISSUE THREAD

**Issue by leftaroundabout** [yesodweb/yesod#1549]
The same server (in my case right now, [a yeamer presentation](https://github.com/leftaroundabout/beamonad/blob/master/demo/Main.hs)) behaves differently with Yesod-1.4.5 and now Yesod-1.6.0. Namely, URLs that would previously be rendered in domain-relative form, like
```
/changeposition/AQh4nAMAAAAAAQAB/AQRudWxsAIE=
```
now appear in absolute
```
http://localhost:14910/changeposition/AQh4nAMAAAAAAQAB/AQRudWxsAIE=
```
I couldn't find what patch causes this change, and have no idea why this would be done, but it is a big pain when the Yesod program is running behind a reverse proxy. Clearly, `localhost:...` is _not_ the URL I want when accessing the server from the internet!

Why does this happen, and how do I get proper relative URLs in Yesod>=1.6?

**Comment by plaeremans** [comment]
HI @leftaroundabout,

I think I you can change it with the appRoot setting of your Yesod instance:
https://hackage.haskell.org/package/yesod-core-1.6.6/docs/Yesod-Core.html#t:Yesod

> approot :: Approot site 
> 
> An absolute URL to the root of the application. Do not include trailing slash.
> 
> Default value: guessApproot. If you know your application root statically, it will be more efficient and more reliable to instead use ApprootStatic or ApprootMaster. If you do not need full absolute URLs, you can use ApprootRelative instead.
> 
> **Note: Prior to yesod-core 1.5**, the default value was ApprootRelative.

**Comment by leftaroundabout** [comment]
So the relevant commit is be https://github.com/yesodweb/yesod/commit/79aefc694ae2e3eb176dfd26f4e3d83def3d1e12. Thanks. Specifying `approot` manually fixes my problem.
