### ISSUE TITLE
Unable to detect file changes on hamlet templates on stack devel for lts-12.5

### ISSUE THREAD

**Issue by jvliwanag** [yesodweb/yesod#1551]
On a new project initialized with the yesod templates, with the resolver automatically set to lts-12.5, hamlet templates are not watched. That is, running `yesod devel` fails to rebuild the app on changes to the template files.

Tested on both macos 10.13.6 and Ubuntu 18.04.

What worked however is changing the stack resolver from the picked up `lts-12.5` stack resolver to `lts-11.20`.

Running `watched` command from `stack build --file-watch` confirms that the hamlet files are missing when on lts-12.5, but are present on lts-11.20.

**Comment by snoyberg** [comment]
That's most likely a different in how GHC is reporting the watched files in the two different versions. There should be some `.hi-dump` files in your `.stack-work` directory. Can you report whether those files reference your Hamlet files with the two different resolvers?

**Comment by jvliwanag** [comment]
Looks like they point to the same file, but have the 12.5 has an additional hex string.


11.20 (auto build)
Path: `./.stack-work/dist/x86_64-osx/Cabal-2.0.1.0/build/src/Handler/Home.dump-hi`

```
addDependentFile "templates/homepage.hamlet"
54086c982e9b4ed881fcb2d9d3c2aa4d
  $trModule :: GHC.Types.Module
  {- HasNoCafRefs, Strictness: m,
     Unfolding: (GHC.Types.Module
                   Handler.Home.$trModule3
                   Handler.Home.$trModule1) -}
```

12.5 (no auto build)
Path: `./.stack-work/dist/x86_64-osx/Cabal-2.2.0.1/build/src/Handler/Home.dump-hi`

```
addDependentFile "templates/homepage.hamlet" 64b74188b62bac042119e8a0d26c3289
3886f14f725c6b9c0e89769a9758c7a7
  $trModule :: GHC.Types.Module
  {- HasNoCafRefs, Strictness: m,
     Unfolding: (GHC.Types.Module
                   Handler.Home.$trModule3
                   Handler.Home.$trModule1) -}
```

**Comment by ygale** [comment]
I am still experiencing this issue. Perhaps it should be re-opened?

The underlying stack issue is commercialhaskell/stack#4360.

**Comment by ygale** [comment]
The problem was that you also need shakespeare >= 2.0.19, which is only in the latest [LTS 12.14](https://www.stackage.org/lts-12.14). Thanks to @tolysz for pointing that out. You need stack >= 1.9.3 (not yet released) to get @snoyberg's fix, or in the meantime you can build >= 1.9.2 from the [stable branch](https://github.com/commercialhaskell/stack/tree/stable) on github.

I am now convinced that this issue is fixed. Thanks!

**Comment by spacekitteh** [comment]
I'm not. I just updated to 1.9.3, and addDependentFile generates the following error from within GHC:

`*** Core Linted result of Desugar (after optimization):
    *** Deleting temp files:
    Deleting: C:\Users\SPACEK~1\AppData\Local\Temp\ghc3940_0\ghc_1.hscpp C:\Users\SPACEK~1\AppData\Local\Temp\ghc3940_0\ghc_3.hscpp C:\Users\SPACEK~1\AppData\Local\Temp\ghc3940_0\ghc_5.hscpp
    *** Deleting temp dirs:
    Deleting: C:\Users\SPACEK~1\AppData\Local\Temp\ghc3940_0
    C:\Users\spacekitteh: openBinaryFile: permission denied (Permission denied)
`

**Comment by ygale** [comment]
@spacekitteh Could you please post more details? So far I don't see the connection with `addDependentFile`. Thanks!

**Comment by spacekitteh** [comment]
@ygale I just realised I posted this in the yesod tracker, rather than stack. But, when I comment out the addDependentFile line in my TH code, it works; when I leave it in, it gets permission errors.
