### ISSUE TITLE
New version to depend on Persistent 2.9.*

### ISSUE THREAD

**Issue by CaptJakk** [yesodweb/yesod#1552]
I'm running into an issue where I need to get some of the features in persistent 2.9 and I would like to be able to use them. However it looks like yesod depends on yesod-persistent which won't accept bumping to 2.9 without changes to yesod-persistent. What is the process for trying to bump versions? I'd be happy to help if possible, just haven't done this piece before and would appreciate any sort of direction on where to start.

**Comment by bitemyapp** [comment]
I'd invite @snoyberg and @psibi to disagree with me, but the fastest and easiest way to get a change like this out the door for your app is to use `stack.yaml` to pin a forked version that bumps the upper bound.

Cf. https://github.com/lorepub/moot/blob/master/stack.yaml#L3-L14

**Comment by jezen** [comment]
I think the comment above answers the question, so I will close this issue.
