### ISSUE TITLE
Fix warning "Deprecated: "Use runConduit and .|" from websockets examples

### ISSUE THREAD

**Issue by ghost** [yesodweb/yesod#1564]
Hi, when I compile example from websockets (sample.h), I get this warning:

Deprecated: "Use runConduit and .|"

Could you please update websocket examples? Thanks in advance.

**Comment by Elektroingenieur** [comment]
My apologize if I came across unmannerly.

**Comment by psibi** [comment]
I think the message was fine! :+1:

**Comment by Elektroingenieur** [comment]
`Would you like to send a PR fixing it ?` Sorry my understanding of english is bad. I thought it was sarcasm until I googled PR means (bad at github as well). So yes please.
