### ISSUE TITLE
MonadFail HandlerFor

### ISSUE THREAD

**Issue by ocharles** [yesodweb/yesod#1569]
`HandlerFor` is `ReaderT (HandlerData ..) IO`, so I think it should have a `MonadFail` instance where `fail = liftIO . fail`.

**Comment by MaxGabriel** [comment]
```
newtype HandlerFor site a = HandlerFor
    { unHandlerFor :: HandlerData site site -> IO a
    }
    deriving Functor
```

This is unrelated to having a monadfail instance I think, but HandlerFor is no longer ReaderT in recent Yesod versions

**Comment by ocharles** [comment]
Well, morally ReaderT is more what I meant.

**Comment by snoyberg** [comment]
I have misgivings about this. From my perspective, the only real reason for a `MonadFail` typeclass is for the pattern match failure support. And this seems like exactly the kind of thing I _wouldn't_ want to be supported in `do`-notation for `HandlerFor`. (You may claim that this argument applies to `IO` as well. Yes, it would, I'm not happy with `MonadFail IO` either.)

Can you point out a case where you'd want to use this `MonadFail` instance?

**Comment by ocharles** [comment]
We have a few places in our codebase where we do things like

```haskell
Just foo <- getFoo
```

so it's mostly a convenience thing. It's an internal API where error reporting isn't a huge concern ("oops something went wrong" on the client side is fine).

I see where you're coming from, and could understand how this could be rejected too.

**Comment by snoyberg** [comment]
Yeah, this looks like the kind of thing I'd want the compiler to stuff, and force me to through in a `>>= maybe theImpossibleHappened pure` or similar to make it explicit that we're claiming this can never happen.

**Comment by ocharles** [comment]
Alright, let's stick with the status quo (no `MonadFail`). While it's mildly inconvenient, being explicit about these patterns and providing actual errors is better practice anyway.
