### ISSUE TITLE
Double accessing request bodies

### ISSUE THREAD

**Issue by MaxGabriel** [yesodweb/yesod#1572]
We use Yesod/Warp middleware to report exceptions to Bugsnag using [bugsnag-haskell](https://hackage.haskell.org/package/bugsnag-haskell). It would be nice to also send the request body to the exception tracker (if it's of a reasonable size), but my understanding is that all the Yesod functions to access the request body consume it.

As a workaround to this I'm planning on using Yesod's per-request caching, so that calling `customRequireCheckJsonBody` also puts the parsed `Value` in the per-request cache, so that the exception handling code can pull it from there if necessary.

It seems like there isn't a good general way to support double request body reads in Yesod itself, since it exposes many different ways to stream the request body both directly and through helper functions like `requireJsonBody`. Does this seem correct?

Would a PR to add separate get/set functions to the per-request cache (currently there's only a way to read+write from the cache at the same time) be welcome?

**Comment by MaxGabriel** [comment]
My reading of the docs for that function:

> Get the next chunk of the body. Returns empty when the body is fully consumed.

Is that it also consumes the request body.

(That function is pretty dangerous imo—it’s name implies it gets the whole body, and that will work as long as the body is small enough, but will break beyond a certain size)

**Comment by snoyberg** [comment]
On the naming, please see https://github.com/yesodweb/wai/issues/669.

I'm not sure I follow the motivation here, but I don't see a problem with adding separate read/write functions.

**Comment by snoyberg** [comment]
Thanks for the PR 🎆 

Yup, I'm fine with the addition
