### ISSUE TITLE
Google+ API being shut down.

### ISSUE THREAD

**Issue by gleachkr** [yesodweb/yesod#1579]
It sounds as if the Google+ API will be shut down soon, with intermittent failures to the API starting yesterday (Jan 28th) and a complete shut down on March 7th. `Yesod.Auth.GoogleEmail2` is still using Google+ methods, it appears, so I expect this will cause some problems. 

It'd be nice to have a transparent fix (Google suggests moving over to [Google Sign-In](https://developers.google.com/identity/)), or a smooth migration path for users currently authenticating with Google.

**Comment by snoyberg** [comment]
Yes, we need to address this, agreed. If someone would like to take a crack at this, I'd really appreciate this. Otherwise, I'll try to get to it some time before March 7.

**Comment by snoyberg** [comment]
I've successfully moved Haskellers over to the new Google sign-in system using @pbrisbin's instructions in https://github.com/snoyberg/haskellers/commit/f77bba90d9684afb532639c68e64449523992535. Once that blog post is published, I'll link to it from the GoogleEmail2 module and deprecate the module.

**Comment by pbrisbin** [comment]
Published: https://pbrisbin.com/posts/googleemail2_deprecation/
