### ISSUE TITLE
Internal Server Error, when primary key is not found while deserialising resource from URL

### ISSUE THREAD

**Issue by iamsumanth** [yesodweb/yesod#1583]
I have defined my routes and model for the resource House as,

```
House json
    rent Int
    ownerId PersonId
    addressId AddressId
    deriving Show
```
`/houses/#HouseId HouseR DELETE GET`

There are models for Person & Address as well.

Scenario:
`/localhost:3000/houses/beach`.
Expected: 404 (Not Found)
Response: 404 (Not Found)

Scenario:
`/localhost:3000/houses/1`.
Expected: 404 (Not Found)
Response: 500 (Internal Server Error)

At this moment, I haven't posted any house. So the table must be empty.

I have tried posting few houses and when the house is available it returns me the house. But if I ask for a resource which is not yet created. It throws me 500.

Logs:

> [Error#yesod-core] PersistForeignConstraintUnmet "HouseKey {unHouseKey = SqlBackendKey {unSqlBackendKey = 1}}" @(yesod-core-1.6.9-EedMoTMhaOm6LxRYPY9XFs:Yesod.Core.Class.Yesod ./Yesod/Core/Class/Yesod.hs:662:5)

Machine Information:

> https://gist.github.com/iamsumanth/a9bb19e1a705d6e46dbe06d90c26af9b

**Comment by MaxGabriel** [comment]
Yesod itself doesn't do a database query to look for a House with the given `HouseId`. Your code in a Handler must be doing it. Can you share the code for `getHouseR` and `deletegetHouseR`?

**Comment by iamsumanth** [comment]
Ahh, Thank you. I just had a look at my handler and found that, I always expect a house to be present.

getHouseR :: HouseId -> Handler Value
getHouseR houseId = do
  house' <- runDB $ **getJustEntity** houseId
  fmap toJSON (getCompleteHouse house')

I will try using **get404** in place of it.
