### ISSUE TITLE
How to run yesod hello world app with stack ghci?

### ISSUE THREAD

**Issue by bifunctor** [yesodweb/yesod#1584]
Hi all

I've created a yesod project with following command:

stack new yeplay yesodweb/simple  
and I've added a helloworld.hs file to app directory. The app directory contains the following files:

```
~/haskell/yeplay/app$ ls
devel.hs  DevelMain.hs  helloworld.hs  main.hs
```
The helloworld.hs file has the following content:

```
{-# LANGUAGE OverloadedStrings     #-}
{-# LANGUAGE QuasiQuotes           #-}
{-# LANGUAGE TemplateHaskell       #-}
{-# LANGUAGE TypeFamilies          #-}
import           Yesod

data HelloWorld = HelloWorld

mkYesod "HelloWorld" [parseRoutes|
/ HomeR GET
|]

instance Yesod HelloWorld

getHomeR :: Handler Html
getHomeR = defaultLayout [whamlet|Hello World!|]

main :: IO ()
main = warp 3000 HelloWorld  
```
Then I tried to run the file with the command:

```
runhaskell helloworld.hs
Command 'runhaskell' not found, but can be installed with:
sudo apt install ghc 
```

as described in the documentation.

How can I start the app?  

Thanks

**Comment by StevenXL** [comment]
`runhaskell` is a command provided by the `stack` tool (though I have a `runhaskell` binary in my path, I don't know how it got there). Try `stack runhaskell`.
