### ISSUE TITLE
Feature Request: HTTP OPTIONS method support.

### ISSUE THREAD

**Issue by idcm** [yesodweb/yesod#1587]
When I use axios, I find yesod does not support OPTIONS method.  Yesod could have OPTIONS method support and  add some specific examples in cookbook?

The following is what I found using google: 

The Cross-Origin Resource Sharing standard works by adding new HTTP headers that allow servers to describe the set of origins that are permitted to read that information using a web browser. Additionally, for HTTP request methods that can cause side-effects on server's data (in particular, for HTTP methods other than GET, or for POST usage with certain MIME types), the specification mandates that browsers "preflight" the request, soliciting supported methods from the server with an HTTP OPTIONS request method, and then, upon "approval" from the server, sending the actual request with the actual HTTP request method. Servers can also notify clients whether "credentials" (including Cookies and HTTP Authentication data) should be sent with requests.

https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods/OPTIONS

**Comment by MaxGabriel** [comment]
We use the wai-cors package for this at work

**Comment by dmmartinez** [comment]
How is it not supported?

```haskell
commonHeaders :: Handler ()
commonHeaders =
        do
                addHeader "Access-Control-Allow-Origin" "*"
                addHeader "Access-Control-Allow-Headers" "Origin, X-Requested-With, Content-Type, Accept, Authorization, Access-Control-Allow-Origin, Token"
                addHeader "Accept" "application/json, multipart/form-data"

optionsRestGet :: Handler ()
optionsRestGet =
        do
                _ <- commonHeaders
                addHeader "Content-Type" "application/json"
                addHeader "Allow" "GET"
                addHeader "Access-Control-Allow-Methods" "GET"
                return ()
````

**Comment by jezen** [comment]
As demonstrated above (and I double-checked locally), Yesod already supports this.
