### ISSUE TITLE
maximumContentLength can do IO

### ISSUE THREAD

**Issue by geekingfrog** [yesodweb/yesod#1588]
The current type signature for `maximumContentLength` is `site -> Maybe (Route site) -> Maybe Word64`.
I'd like to have the ability to restrict the content length based on a path parameter of the route, so I would need a db lookup.
For example: `/upload/foo` -> 2MB max, but `/upload/bar` -> 10MB max, these mappings are stored in a db.
Is there any workaround I can use for now? Is it something which could be added to the next release?

**Comment by snoyberg** [comment]
We had a similar situation with `shouldLog` in the past, and added a `shouldLogIO` method to the `Yesod` type class to address this. I think we could do the same thing in this case. Would you be interested in taking a stab at such a PR?

For comparison, here's the prior art: https://github.com/yesodweb/yesod/commit/aa5781d4e42f8797ebe2974a6f3cfabe43af4c50
