### ISSUE TITLE
When use "runRequestBody", where is the temp file?

### ISSUE THREAD

**Issue by idcm** [yesodweb/yesod#1590]
When use "runRequestBody", where is the temp file?
I read the source code of it. It seems that temp file should locate at "/tmp" with name  "webencXXXX.buf", but I do not find the temp file in "/tmp". I want to know whether this is normal.

-- | How to store uploaded files.
    --
    -- Default: When the request body is greater than 50kb, store in a temp
    -- file. For chunked request bodies, store in a temp file. Otherwise, store
    -- in memory.
    fileUpload :: site -> W.RequestBodyLength -> FileUpload
    fileUpload _ (W.KnownLength size)
        | size <= 50000 = FileUploadMemory lbsBackEnd
    fileUpload _ _ = FileUploadDisk tempFileBackEnd

tempFileBackEnd :: InternalState -> ignored1 -> ignored2 -> IO S.ByteString -> IO FilePath
tempFileBackEnd = tempFileBackEndOpts getTemporaryDirectory "webenc.buf"

**Comment by snoyberg** [comment]
It depends on the OS you're on and theoretically versions of libraries being used. I don't remember offhand where default paths would be for this file, but you could add a log statement to your Yesod code to print out the full file path if you wanted.
