### ISSUE TITLE
yesod-websockets: sendClose incorrect type

### ISSUE THREAD

**Issue by pbrisbin** [yesodweb/yesod#1599]
I'm using `yesod-websockets-0.3.0.1` and found what I think is a bug in `sendClose`:

Its type is:

```hs
sendClose
  :: (MonadIO m, WS.WebSocketsData a, MonadReader WS.Connection m)
  => a
  -> WebSocketsT m ()
```

Notice it is concretely `WebSocketsT m` with the `MonadReader` constraint on `m`. This seems wrong to me because `WebSocketsT` should provide the `Connection`, not the underlying `m`.

Indeed, this makes it impossible to use in `WebSocketsT Handler` because `Handler` is a `MonadReader` for your `App` type, not a `Connection`. And the other functions of this library have types that I would expect:

```hs
sendTextData
  :: (MonadIO m, WS.WebSocketsData a, MonadReader WS.Connection m)
  => a
  -> m ()
```

Notice the `MonadReader m` and the ultimate effect `m ()`, this means it it can be used as `WebSocketsT Handler` and finds the `Connection` via `WebSocketsT`, as required.

For example, this seemingly correct code does not work:

```hs
someHandler :: Handler ()
someHandler = webSockets someWebSockets

someWebSockets :: WebSocketsT Handler ()
someWebSockets = do
  sendTextData "hello"
  void recieveTextData
  sendClose "goodbye" -- ERROR

-- NB I omitted annotations required to set WebSocketsData a, for clarity of example
```

For example:

```
    • Couldn't match type ‘Yesod.Core.Types.HandlerData App App’
                     with ‘Network.WebSockets.Connection.Connection’
        arising from a functional dependency between:
          constraint ‘MonadReader
                        Network.WebSockets.Connection.Connection (HandlerFor App)’
            arising from a use of ‘sendClose’
          instance ‘MonadReader
                      (Yesod.Core.Types.HandlerData site site) (HandlerFor site)’
```

I created a local `sendClose` with what I think is the correct type:

```hs
sendClose'
    :: (MonadIO m, WebSocketsData a, MonadReader Connection m) => a -> m ()
sendClose' x = do
    conn <- ask
    liftIO $ WS.sendClose conn x
    -- ^ just in-lining the exact same implementation: wrapWS WS.sendClose
```

And it works.

Is there some reason the type is this way, or is this indeed a bug? Happy to PR if you agree it should be fixed. `sendPing` (and perhaps others, I didn't look closely) are also typed this way.

**Comment by snoyberg** [comment]
I think you're right, PR definitely welcome :)
