### ISSUE TITLE
406 Not Acceptable response is not returned

### ISSUE THREAD

**Issue by normenmueller** [yesodweb/yesod#1611]
[My sys info](https://gist.github.com/normenmueller/685755a916a158052dc688e32b0f60ce)

The handler `getHomeR`, as defined in the Developing Web Apps with Haskell and Yesod, 2nd:

```haskell
getHomeR :: Handler TypedContent
getHomeR = selectRep $ do
    provideRep $ return
        [shamlet| <p>Hello, my name is #{name} and I am #{age} years old.|]
    provideRep $ return $ object
        [ "name" .= name
        , "age" .= age
        ]
  where
    name = "Michael" :: Text
    age = 28 :: Int
```

does *not* return 406 Not Acceptable response in case an Http Accept header is present, but does not matches.

```bash
curl http://localhost:3000 --header "accept: application/json"
curl http://localhost:3000 --header "accept: text/html"
curl http://localhost:3000
curl http://localhost:3000 --header "accept: application/xml"
```

The last request should fail.

**Comment by snoyberg** [comment]
Please see discussion in https://github.com/yesodweb/yesod/pull/1540

**Comment by normenmueller** [comment]
@snoyberg So 

> And it seems like a client can always simply check the `content-type` header and decide it doesn't like what's been delivered.
(Cf. https://github.com/yesodweb/yesod/pull/1540#issuecomment-405143962)

is the current behaviour?

**Comment by snoyberg** [comment]
Yes
