### ISSUE TITLE
Dynamic jsAttributes

### ISSUE THREAD

**Issue by jezen** [yesodweb/yesod#1621]
I need to add a `nonce` attribute to the `<script>` tag that's generated by `widgetFile`.

I have noticed that by using the Yesod typeclass method [`jsAttributes`](http://hackage.haskell.org/package/yesod-core-1.6.15/docs/Yesod-Core.html#v:jsAttributes), I can add arbitrary attributes to that `<script>` tag, however I don't see a way to add a randomised per-request value. A nonce (for CSP) _must_ be randomised on every request.

I am happy to do the work of implementing this and sending a PR, but I actually don't really know where to start with this. Ideally I would like to be able to run a `Handler` for every request (like a middleware). In my case, this `Handler` would generate a nonce, store it somewhere (like a TVar, or per-request cache, or anything else), and then return the nonce.

For additional context, I will share how I am currently handling nonces for static files:

```
-- …
import qualified Data.ByteString.Base64        as B64
import           Data.UUID                     (toASCIIBytes)
-- …

generateRequestNonce :: MonadHandler m => m Text
generateRequestNonce = do
  nonces <- cacheGet >>= return . fromMaybe Set.empty
  nonce <- decodeUtf8 . B64.encode . toASCIIBytes <$> liftIO nextRandom
  cacheSet $ Set.insert nonce nonces
  return nonce

addScriptWithNonce :: MonadWidget m => Route (HandlerSite m) -> m ()
addScriptWithNonce route = generateRequestNonce >>= \n ->
  addScriptAttrs route [("nonce", n)]

addScriptRemoteWithNonce :: MonadWidget m => Text -> m ()
addScriptRemoteWithNonce uri = generateRequestNonce >>= \n ->
  addScriptRemoteAttrs uri [("nonce", n)]

```

The added code I am envisioning would look something like

```
instance Yesod App where

  jsAttributesHandler = do
    nonce <- generateRequestNonce
    return [("nonce", nonce)]
```

Does this seem feasible? Or do I have the wrong approach entirely?

**Comment by snoyberg** [comment]
I don't have an opinion on this. I've never heard of this nonce requirement in CSP, and I have no idea what its purpose would be. That said, I don't think `jsAttributes` is intended for truly static files, but rather for widget-generated Javascript files.

**Comment by jezen** [comment]
> I don't have an opinion on this. I've never heard of this nonce requirement in CSP, and I have no idea what its purpose would be.

My understanding is that the _right_ way to implement the `script-src` part of CSP is with the `'strict-dynamic'` directive as opposed to host-based whitelisting. This is described further in [this article](https://websec.be/blog/cspstrictdynamic/).

> That said, I don't think `jsAttributes` is intended for truly static files, but rather for widget-generated Javascript files.

That's correct. In my case, I am easily able to load static JavaScript files and add randomised nonces with the `addScriptWithNonce` and `addScriptRemoteWithNonce` functions above. This works just fine.

The problem is that I am not sure how to add a randomised nonce to the `<script>` tag generated by a widget. If the `jsAttributes` method could run handler code on every request, this would solve my problem. I am not sure if this is possible though, so I am wondering if I have to make some kind of change [somewhere here](https://github.com/yesodweb/yesod/blob/6a7370a9e61ca48787c539842602b161c219e6ba/yesod-core/src/Yesod/Core/Class/Yesod.hs#L561-L570).

**Comment by snoyberg** [comment]
OK, I think I get it now. I'd be OK with the addition of `jsAttributesHandler`. There's similar prior art around `maximumContentLengthIO` and a few other methods.
