### ISSUE TITLE
Support GHC 8.8.1 on stackage

### ISSUE THREAD

**Issue by ygale** [yesodweb/yesod#1637]
Is there a prognosis for when yesod will make it into the nightlies for GHC >= 8.8.1? Is there anything we can do to help? We need to scope our work for the upgrade; an estimated timeline would be helpful. I see that this has been worked on, e.g. #1626. I don't immediately see any other issues that are marked as relevant to the upgrade to GHC 8.8.

We realize that this is a major GHC version bump, so longer lead time is expected.

Thanks!

**Comment by ygale** [comment]
@snoyberg Is this perchance waiting for the rio branch you mentioned in #1602 to land?

**Comment by ygale** [comment]
The switch to RIO would be even more important for us to hear about in advance. It sounds like a great idea - I'm in favor. But it will cause us a huge amount of work, and a fairly long period where we'll be way behind in versions. So it would be very helpful if we could have as much advance warning as possible, and some rough estimate of when it will hit if possible . Thanks.

**Comment by snoyberg** [comment]
No, this is not blocked on RIO. If there's something you need urgently, I'd recommend opening a PR against Stackage or here.

**Comment by simonmichael** [comment]
yesod seems to be in stackage nightly now ?

**Comment by snoyberg** [comment]
Good point.
