### ISSUE TITLE
Mentioning exceptions in `sendStatusJSON` docs

### ISSUE THREAD

**Issue by alexeyzab** [yesodweb/yesod#1639]
Hi!

I've run into an issue at work where I was using `sendStatusJSON` inside `yesod-persistent`'s `runDB $ do` block, which returned the JSON response, but also rolled back all the other database-related functions inside of this transaction.

I know that under the hood `sendStatusJSON` uses `handlerError` which utilizes exceptions for the sake of short-circuiting a `Handler`, but I think it would be helpful to mention that DB actions will be rolled back in the docs, perhaps somewhere in the `Short-circuit responses` section.

Would you accept a PR updating the docs to warn about this?

Thanks!

**Comment by snoyberg** [comment]
Yes, absolutely, thanks!

**Comment by bitemyapp** [comment]
It might be worth just enumerating everything that short-circuits in one place because I think a lot of people don't bother to see how it works under the hood.

**Comment by alexeyzab** [comment]
@bitemyapp that sounds reasonable. It seems like the `Short-circuit responses` section was intended for that maybe? Don't know if it covers everything though.

**Comment by jezen** [comment]
This has been merged, so this issue can be closed. Thanks @alexeyzab!
