### ISSUE TITLE
yesod-test depends on 

### ISSUE THREAD

**Issue by MaxGabriel** [yesodweb/yesod#1644]
yesod-test's test suite is using areqMsg and wreqMsg, e.g.:

https://github.com/yesodweb/yesod/blob/d5f6fbba8bcabd01a64eaf48e140a91bdb69d230/yesod-test/test/main.hs#L501

It looks like these functions were added in yesod-form 1.6.7

https://www.stackage.org/haddock/lts-14.15/yesod-form-1.6.7/Yesod-Form-Functions.html#v:wreqMsg

But yesod-test only has a dependency on:

yesod-form >= 1.6

Fine to just bump the test dependency to >= 1.6.7? Worth hotfixing past versions on Hackage?

cc @sestrella who I think added those functions

**Comment by snoyberg** [comment]
No problem with changing the version bound on GitHub. Could not care less
about monkey patching Hackage 😁

**Comment by jezen** [comment]
Looks like this is in `master`, so this issue can be closed.
