### ISSUE TITLE
requireCheckJsonBody should pay attention to content type

### ISSUE THREAD

**Issue by v0d1ch** [yesodweb/yesod#1648]
When sending the request with content type `application/json` I received status 400 with html in the response body instead of json which made me think that `requireCheckJsonBody` is not paying attention to content types. 

In my opinion it should respond with a body that is consistent with the request content type.

**Comment by snoyberg** [comment]
Sounds like you need to set the `accept` request header to indicate JSON.

**Comment by v0d1ch** [comment]
Yes `addRequestHeader (hAccept, "application/json")` does the correct thing.
Thanks @snoyberg , closing this non-issue now.
