### ISSUE TITLE
Foundation is giving OOM errors with 120 routes, 45 tables and around 250 I18N messages

### ISSUE THREAD

**Issue by ibarrae** [yesodweb/yesod#1651]
Hey folks, more than an issue I would like to receive some help (if possible) because I have the following project overview:
- Around **250** I18N messages
- **120** routes
- **45** tables ~ persist models

With this set-up and by using Circle CI, the build is giving OOM errors when building with `stack build` at it hangs at `Foundation.hs` as you can see below:
```bash
[312 of 445] Compiling Foundation       ( src/Foundation.hs, .stack-work/dist/x86_64-linux/Cabal-2.4.0.1/build/Foundation.o )

--  While building package cerebro-0.0.0 using:
      /root/.stack/setup-exe-cache/x86_64-linux/Cabal-simple_mPHDZzAJ_2.4.0.1_ghc-8.6.3 --builddir=.stack-work/dist/x86_64-linux/Cabal-2.4.0.1 build lib:cerebro exe:cerebro exe:rank exe:read-translation-csv exe:seed exe:sync-p2s exe:write-translations --ghc-options " -ddump-hi -ddump-to-file -fdiagnostics-color=always"
    Process exited with code: ExitFailure (-9) (THIS MAY INDICATE OUT OF MEMORY)
```
As you can see, we know have _445_ modules and I have done the following attempts to fix this issue:
- I have splitted the big "Model" containing all the tables to smaller files, each one with its table. At the moment, `Model.hs` looks like this:
```haskell
module Model 
  ( module Model.Table1
  , module Model.Table2
  ) where

import Model.Table1
import Model.Table2
```

- I have removed almost *300* no longer necessary I18N translations (since I checked the following [issue](https://github.com/yesodweb/yesod/issues/1487))
- I have done the following [workaround](https://github.com/yesodweb/yesod/issues/1348#issuecomment-278601823) for forms with more than 10 fields

Some extra information:
- The current LTS in the CI is 13.11 ~ GHC 8.6.3
- The docker image used to build in the CI is **fpco/stack-build:lts-13.11**
- On my local machine, the outcome from the command `/usr/bin/time -f "mem=%K RSS=%M elapsed=%E cpu.sys=%S .user=%U" stack build` is:
```bash
mem=0 RSS=4402548 elapsed=6:54.16 cpu.sys=12.01 .user=401.93
```

I almost have run out of ideas :disappointed:, maybe any of you folks would have another idea in order to make it build on Circle CI? Thanks for your help and excuse me if this is kind of weird, English is not my main language :smile:

**Comment by eahlberg** [comment]
I remember getting OOM errors on CircleCI a good while ago and using the [jobs flag](https://docs.haskellstack.org/en/stable/yaml_configuration/#jobs) fixed it for me, e.g. `stack build -j1`. However, it was a much smaller project and it slows down the build, but it could be worth a try. 🤷‍♂️

**Comment by ibarrae** [comment]
I tried so, but it still uses more than 4GB to build the project :disappointed: thanks for your help @eahlberg

**Comment by MaxGabriel** [comment]
If Foundation is specifically the problem, maybe try splitting it up? Something like https://github.com/yesodweb/yesod-scaffold/pull/198 maybe

At work we use giant AWS instances to build our project so haven’t run into this.

That said, is this a commercial project? If so can you just pay for more memory from Circle CI? https://circleci.com/docs/2.0/configuration-reference/#resource_class

**Comment by MaxGabriel** [comment]
Also, my guess on the OOM would be a significant amount of generated code is in Foundation. You can compile with `-ddump-splices -ddump-file` (see https://github.com/yesodweb/persistent/blob/master/persistent-template/README.md#development-tips) to see what is generated. This might help give you an idea of what is using all the memory.

**Comment by ibarrae** [comment]
I'll try splitting foundation! Thanks @MaxGabriel, also using the flags you are suggesting :smile:

**Comment by MaxGabriel** [comment]
Any luck @ibarrae ?

**Comment by ibarrae** [comment]
Thanks for the suggestions @MaxGabriel @eahlberg, _splitting Foundation_ did the trick :tada:. I really appreciate your help throughout this issue, and sorry I forgot to get back to you with the good news. I'm closing this now :smile:

**Comment by rudymatela** [comment]
For future reference, more specifically, @ibarrae  split foundation by making each call to `mkMessageFor` in a separate file.  E.g.:

This:

```
module Foundation where

...
mkMessage "App" "messages/general" "en"
mkMessageFor "App" "MyDataType" "messages/..."
mkMessageFor "App" "MyOtherDataType" "messages/..."
mkMessageFor "App" "MyOtherOtherDataType" "messages/..."
...
```

Became this:

```
module Foundation where

import Foundation.Messages.General
import Foundation.Messages.MyDataType
import Foundation.Messages.MyOtherDataType
import Foundation.Messages.MyOtherOtherDataType
```

```
module Foundation.Messages.General where
...
mkMessage "App" "messages/general" "en"
```

```
module Foundation.Messages.MyDataType where
...
import Foundation.Messages.MyDataType
```

etc...
