### ISSUE TITLE
Redundant Constraint on yesodMiddleware

### ISSUE THREAD

**Issue by jkeuhlen** [yesodweb/yesod#1652]
`yesodMiddleware` currently has the following definition: 

```haskell
yesodMiddleware :: ToTypedContent res => HandlerFor site res -> HandlerFor site res
yesodMiddleware = defaultYesodMiddleware
```

`defaultYesodMiddleware :: Yesod site => HandlerFor site res -> HandlerFor site res`

We compile our application with `-Wredundant-constraints` which caused this to bubble up for us. Is there a reason for the `ToTypedContent` constraint on `yesodMiddleware`? It seems to me like it could be safely removed, and is just an artifact left over from previous code. 

Happy to submit a PR removing it if that's the case.

**Comment by snoyberg** [comment]
That seems like a spurious warning. This is a method in a typeclass, and the constraint is there so that those implementing it can rely on the `ToTypedContent` instance.

**Comment by jkeuhlen** [comment]
Wouldn't someone implementing it always be able to add an additional constraint? Or is that not true because it's a typeclass method? 

I figured there was a reason it was there but couldn't figure out why it was needed.

**Comment by snoyberg** [comment]
> Or is that not true because it's a typeclass method?

Correct, you can't add additional constraints on a method when implementing a type class.

**Comment by jkeuhlen** [comment]
Thanks for the explanation!
