### ISSUE TITLE
Remove unnecessary deriving of Typeable

### ISSUE THREAD

**Issue by MaxGabriel** [yesodweb/yesod#1653]
I noticed that the Yesod codebase derives typeable in a few places. Given that since [7.10 Typeable is automatically derived](https://stackoverflow.com/a/32980973/1176156), and Yesod requires > GHC 7.10, Yesod could drop the manual deriving of it. You can find instances of it with the warning `-Wderiving-typeable`. 

I don't think this is super important, but might be a nice issue for a newcomer

**Comment by juanpaucar** [comment]
@MaxGabriel Can I get this issue assigned to me? I'll open a PR shortly

**Comment by MaxGabriel** [comment]
Solved by #1654
