### ISSUE TITLE
Add meta tag helpers

### ISSUE THREAD

**Issue by jezen** [yesodweb/yesod#1659]
In a few of my projects I maintain a module called `Util.Meta` which just contains a bunch of functions [like these][0]. Is there any reason not to bundle these functions with Yesod? If adding these seems reasonable, I'm happy to send a PR.

[0]: https://ersocon.net/blog/2016/10/26/how-to-add-meta-tags-in-yesod

**Comment by snoyberg** [comment]
Seems fine to me, go for it 💪
