### ISSUE TITLE
CSRF token too short ?

### ISSUE THREAD

**Issue by amkhlv** [yesodweb/yesod#1670]
I am auto-generating POST form using `generateFormPost` 
Looking at the generated HTML, it seems that the CSRF token is 10 alphanumeric chars.
This is below some usual recommendations:
https://security.stackexchange.com/questions/6957/length-of-csrf-token
I am slightly worried...

**Comment by snoyberg** [comment]
PR to improve that is certainly welcome.

**Comment by snoyberg** [comment]
Typical way to test something like this is to make a commit, push to your own fork, and add an `extra-dep` to your `stack.yaml` file. However, this one is pretty straightforward. You can probably just open a PR right away. Request though: please add a ChangeLog entry and minor version bump.

**Comment by amkhlv** [comment]
Done

**Comment by snoyberg** [comment]
Addressed by #1672, closing
