### ISSUE TITLE
cannot install Esqueleto in Yesod

### ISSUE THREAD

**Issue by KeesBleijenberg** [yesodweb/yesod#1671]
I'am working on a Yesod project on Linux Mint 19.3 Cinnamon. Ghc version = 8.4.4. Stack version = 2.1.3. 
Until now I did all my db work with Persistent. 
For a feature I need Esquelto. So under dependencies I added in package.yaml esqueleto.
Then I did stack build and I got:
In the dependencies for tbsServer-0.0.0: esqueleto needed, but the stack configuration has no specified version  (latest matching version is 3.3.3.0)
needed since tbsServer is a build target.
Some different approaches to resolving this:
  * Recommended action: try adding the following to your extra-deps in /home/kees/tbsServer/stack.yaml:
- esqueleto-3.3.3.0@sha256:0b9b63f92138310e7d7157bbac2560682082c2d78e1e10aedf6b53738b538d46,5440

I added the line above in package.yaml and did: stack build:
In the dependencies for esqueleto-3.3.3.0:
    persistent-2.8.2 from stack configuration does not match >=2.10.0 && <2.11  (latest matching version is 2.10.5.2)
needed due to tbsServer-0.0.0 -> esqueleto-3.3.3.0

Some different approaches to resolving this:
  * Set 'allow-newer: true' in /home/kees/.stack/config.yaml to ignore all version constraints and build anyway.
  * Recommended action: try adding the following to your extra-deps in /home/kees/tbsServer/stack.yaml:
- persistent-2.10.5.2@sha256:aaa222a48583b22f0af00bb9ee6adc839ec75256b158f38d85c9c2cb68ec6eb4,4740

Error: While constructing the build plan, the following exceptions were encountered:

In the dependencies for tbsServer-0.0.0:
    persistent-2.10.5.2 from stack configuration does not match ==2.8.*  (latest matching version is 2.8.2)
needed since tbsServer is a build target.

In the dependencies for yesod-auth-1.6.5:
    persistent-2.10.5.2 from stack configuration does not match >=2.8 && <2.10  (latest matching version is 2.9.2)
needed due to tbsServer-0.0.0 -> yesod-auth-1.6.5

In the dependencies for yesod-auth-hashdb-1.7.1:
    persistent-2.10.5.2 from stack configuration does not match >=2.1 && <2.10  (latest matching version is 2.9.2)
needed due to tbsServer-0.0.0 -> yesod-auth-hashdb-1.7.1

In the dependencies for yesod-persistent-1.6.0.1:
    persistent-2.10.5.2 from stack configuration does not match >=2.8 && <2.10  (latest matching version is 2.9.2)
needed due to tbsServer-0.0.0 -> yesod-persistent-1.6.0.1

Some different approaches to resolving this:
  * Set 'allow-newer: true' in /home/kees/.stack/config.yaml to ignore all version constraints and build anyway.
  * Recommended action: try adding the following to your extra-deps in /home/kees/tbsServer/stack.yaml:
- persistent-2.8.2@sha256:d6c274b5bc0a003edf13276eee560b81ce239cfc3041e0a620fec7c7f0a8eff8,5064

So I replaced the line 
persistent-2.10.5.2 from stack configuration does not match >=2.8 && <2.10  (latest matching version is 2.9.2)
with 
- persistent-2.8.2@sha256:d6c274b5bc0a003edf13276eee560b81ce239cfc3041e0a620fec7c7f0a8eff8,5064 
and stack says, I have to add
- persistent-2.10.5.2@sha256:aaa222a48583b22f0af00bb9ee6adc839ec75256b158f38d85c9c2cb68ec6eb4,4740

Is this the return of cabal hell? What can I do?

Kees

**Comment by snoyberg** [comment]
Your best bet is to upgrade to a snapshot that already includes esqueleto, such as LTS 15.10. You can see which snapshots include esqueleto on this page: https://www.stackage.org/package/esqueleto/snapshots

**Comment by KeesBleijenberg** [comment]
Thanks for your effort.

I've upgraded to LTS 15.10 but got these errors:

aeson-1.4.7.1 from stack configuration does not match >=0.6 && <1.4  (latest matching version is 1.3.1.1)
classy-prelude-1.5.0 from stack configuration does not match ==1.4.*  (latest matching version is 1.4.0)
classy-prelude-conduit-1.5.0 from stack configuration does not match ==1.4.*  (latest matching version is 1.4.0)
classy-prelude-yesod-1.5.0 from stack configuration does not match ==1.4.*  (latest matching version is 1.4.0)
fast-logger-3.0.1 from stack configuration does not match >=2.2 && <2.5  (latest matching version is 2.4.17)
persistent-2.10.5.2 from stack configuration does not match ==2.8.*  (latest matching version is 2.8.2)
persistent-postgresql-2.10.1.2 from stack configuration does not match ==2.8.*  (latest matching version is 2.8.2.0)
warp-3.3.10 from stack configuration does not match >=3.0 && <3.3  (latest matching version is 3.2.28)
yaml-0.11.3.0 from stack configuration does not match ==0.8.*  (latest matching version is 0.8.32)

In packages.yaml I have:
# Due to a bug in GHC 8.0.1, we block its usage
# See: https://ghc.haskell.org/trac/ghc/ticket/12130
- base >=4.8.2.0 && <4.9 || >=4.9.1.0 && <5
- yesod >=1.6 && <1.7
- yesod-core >=1.6 && <1.7
- yesod-auth >=1.6 && <1.7
- yesod-auth-hashdb
- yesod-static >=1.6 && <1.7
- yesod-form >=1.6 && <1.7
- classy-prelude >=1.4 && <1.5
- classy-prelude-conduit >=1.4 && <1.5
- classy-prelude-yesod >=1.4 && <1.5
- bytestring >=0.9 && <0.11
- text >=0.11 && <2.0
- persistent >=2.8 && <2.9
- persistent-postgresql >=2.8 && <2.9
- persistent-template >=2.5 && <2.9
- template-haskell
- shakespeare >=2.0 && <2.1
- hjsmin >=0.1 && <0.3
- monad-control >=0.3 && <1.1
- wai-extra >=3.0 && <3.1
- yaml >=0.8 && <0.9
- http-client-tls >=0.3 && <0.4
- http-conduit >=2.3 && <2.4
- directory >=1.1 && <1.4
- warp >=3.0 && <3.3
- data-default
- aeson >=0.6 && <1.4
- conduit >=1.0 && <2.0
- monad-logger >=0.3 && <0.4
- fast-logger >=2.2 && <2.5
- wai-logger >=2.2 && <2.4
- file-embed
- safe
- unordered-containers
- containers
- vector
- time
- case-insensitive
- wai
- foreign-store

Why do most packages (but not all) have a version range? Does that range causes trouble while updating to a new LTS? 

Do I have to change the versions above for aeson, classy-prelude, classy-prelude-conduit.... in package.yaml or should I add to stack.yaml:

- aeson-1.3.1.1@sha256:1ab29743b4c4c9be7df57200ed2c8779048adda4cead075944b7b471e93ed4c3,6006
- classy-prelude-1.4.0@sha256:dbc8d87896640138fa45bbedc7c2affab28fda30f2c9bc13b0da2df06909c6bd,1952
- classy-prelude-conduit-1.4.0@sha256:b72754cb1376966eb38d0d0afb1e48395f0d6d3b77a99c656ccfc58fef2ecb91,1607
- classy-prelude-yesod-1.4.0@sha256:2928c99abb90d133d6aff3026a069e1a049471f4c9e017741703f389cc747daf,1334
- fast-logger-2.4.17@sha256:2b2f13d921c57a77115d752f56738b47bff07f9610b2f1018318bfbcae7164fb,2270
- persistent-2.8.2@sha256:d6c274b5bc0a003edf13276eee560b81ce239cfc3041e0a620fec7c7f0a8eff8,5064
- persistent-postgresql-2.8.2.0@sha256:17c2b31ad96cf45f806ced30933c7135d68e6e05a83863c3674c4b2812c95327,1668
- warp-3.2.28@sha256:b32fb8fed7ace4bd206fd897c388c00cdb915ec7e34ee61dc6397d518d9e651c,11186
- yaml-0.8.32@sha256:cb9e788e4c18f3c3579a950c1d53f89efb7e8871f6a00b5fabc37084c05cf04e,5452

**Comment by KeesBleijenberg** [comment]
I've tried the suggestions from stack to insert a few lines in stack.yaml, but I got again a lot of  new errors (version problems).
Is there a good way to upgrade your LTS?

**Comment by snoyberg** [comment]
Yes, the range causes trouble. The short answer to all of this is: try taking the version range off all the dependencies in `package.yaml`, upgrade your LTS, and see if it builds and works correctly.

**Comment by KeesBleijenberg** [comment]
Removing the ranges in package.yaml worked. Thanks

**Comment by snoyberg** [comment]
No problem
