### ISSUE TITLE
DevelMain's update function silently crashes ghci

### ISSUE THREAD

**Issue by Truedrog** [yesodweb/yesod#1673]
* Your OS name and version: Win 10 x64 1909 (OS Build 18363.836)
* The versions of tools you're using: stack 2.3.1, yesod 1.6.0.1
* The versions of dependencies you're using: new scaffolded project (yesod postgres)

Steps to reproduce 

```
stack ghci
DevelMain.update

*do nothing then silently crashes*
```
And it seems that it is crashing on `loadYamlSettings [configSettingsYml] [] useEnv`, but I am not sure.

```
settings <- loadYamlSettings [configSettingsYml] [] useEnv :: IO AppSettings
```
results with the same behavior as running update function.

**Comment by snoyberg** [comment]
Does loading up the `main` function in GHCi work? My best guess is that this is a GHC on Windows bug.

**Comment by Truedrog** [comment]
The main function works OK.

Few observations:
update function works in yesod-simple. But after adding persistent-postgresql dep it breaks loadYamlSettings  (and update function).

**Comment by snoyberg** [comment]
Most likely it's a bad interaction with loading external libraries. Unfortunately I don't have any insight into how best to go about debugging at this point, sorry. I can only give more standard advice: try to pare this down to a more minimal repro.

**Comment by Truedrog** [comment]
https://github.com/Truedrog/reproymlconfig can you try this?

**Comment by snoyberg** [comment]
That's not really what I meant by a minimal repro. In any event, I'm not on a Windows machine, and won't be able to assist with debugging this without more concrete information on what's crashing. Again, my best guess is this is a Windows/GHC bug.
