### ISSUE TITLE
yesod-static: Simple JS concat is not syntactically correct in some cases

### ISSUE THREAD

**Issue by iustin** [yesodweb/yesod#1679]
I'm using LTS 16, so yesod-static version 1.6.0.1.

Reading the code for `combineStatics'`, it looks to me (not familiar with conduit) that with default options, i.e. pass-through js pre- and post-process, it leads to a simple concatenation of all input files.

However, this cannot be relied to generate valid files, in the case of this specific ordering:

* file 1 ends with a single-line comment (e.g. `// end of file 1`) and has no newline at the end
* file 2 starts with a multi-line comment (e.g. `/* start of file 2`)

In this case, a simple 'cat' results in:

```
…
// end of file 1/* start of file 2
* copyright blah blah
*/
```

This file will fail with syntax error at the `* copyright` line.

It is likely possible to workaround this via the pre-post process option, but that seems fragile, as both seem to take the already-concatenanted text, so they have to guess the proper place to insert a newline, which is fragile.

I think that the concatenation should enforce that each of the file ends with a new line, or at least warn about it; this bug only appears in the production, combining deployment, but not in devel, which is fun :)

**Comment by snoyberg** [comment]
Is this something you've actually been affected by? In any event, PR welcome

**Comment by iustin** [comment]
Yes, see the issue I mentioned above. Many of the minification tools remove the final newline, e.g. bootstrap minified bundle triggers this behaviour.

I'd send a PR, but I'm not familiar with Conduit. I'll try to craft something...

**Comment by jezen** [comment]
The way we work around this is by being sure to enclose all scripts in an IIFE, like this:

```
;(function() {
  // your scripts here
})();
```

You could also do this automatically with the pre/post-process system.

This is basically the same as what we were doing in web development 10+ years ago, so this isn't specific to Yesod.

**Comment by jezen** [comment]
I'll close this as I don't think this is a problem specific to Yesod.
