### ISSUE TITLE
File extension for routes file

### ISSUE THREAD

**Issue by MaxGabriel** [yesodweb/yesod#1685]
I saw a VSCode extension with syntax highlighting for Yesod routes https://github.com/e-bigmoon/vscode-language-yesod/blob/master/sample/sample.yesodroutes. It used the file extension `.yesodroutes` for the routes file. I think adopting a specific file extension would be good, so that:

1. It will be easier for people to configure their editors to syntax highlight the file
2. There will be a common name for it that different syntax highlighters can identify

I like their choice of `.yesodroutes`—it's specific and verbose, which I think is completely fine for a file extension that is so rare.

I would propose:

1. Documenting in the Template Haskell route functions that the recommended file extension is `.yesodroutes`, similar to what Persistent does: https://www.stackage.org/haddock/nightly-2020-07-24/persistent-template-2.8.2.3/Database-Persist-TH.html#v:persistManyFileWith
2. Updating the scaffolding to use this new `.yesodroutes` extension

**Comment by MaxGabriel** [comment]
cc @isao-takejib who appears to have worked on the VSCode syntax highlighting for routes

**Comment by snoyberg** [comment]
SGTM
