### ISSUE TITLE
Functions generating Open Graph markup use the wrong attribute

### ISSUE THREAD

**Issue by eahlberg** [yesodweb/yesod#1708]
The functions [setOGType](https://hackage.haskell.org/package/yesod-core-1.6.18.6/docs/Yesod-Core-Widget.html#v:setOGType) and [setOGImage](https://hackage.haskell.org/package/yesod-core-1.6.18.6/docs/Yesod-Core-Widget.html#v:setOGImage) use the `name` attribute (i.e. `<meta name="og:type" >`) but according to the [Open Graph docs](https://opengraphprotocol.org/#types), the `property` attribute should be used, (i.e. `<meta property="og:type" >`).

If you agree with this change, I'll gladly add a PR.

**Comment by snoyberg** [comment]
PR would be great, thank you!
