### ISSUE TITLE
Incorrect module import in docs

### ISSUE THREAD

**Issue by eahlberg** [yesodweb/yesod#1712]
The example for [testSetCookie](https://hackage.haskell.org/package/yesod-test-1.6.10/docs/Yesod-Test.html#v:testSetCookie) imports the [Cookie module](https://hackage.haskell.org/package/cookie-0.4.5/docs/Web-Cookie.html) from `Data.Cookie` when it should be imported from `Web.Cookie`. If you'd like I'll open a PR with the fix.

**Comment by snoyberg** [comment]
That would be great thanks!
