### ISSUE TITLE
Breadcrumbs: Warn against infinite loop

### ISSUE THREAD

**Issue by NorfairKing** [yesodweb/yesod#1727]
Hi! Every once in a while I accidentally make an infinite loop in breadcrumbs, which then locks up my computer entirely.
Is there any chance we could give this code a recursion limit or a loop detector?
https://github.com/yesodweb/yesod/blob/c59993ff287b880abbf768f1e3f56ae9b19df51e/yesod-core/src/Yesod/Core/Class/Breadcrumbs.hs#L28-L31

**Comment by snoyberg** [comment]
Seems OK, PR welcome.
