### ISSUE TITLE
RFC: Signature for isAuthorized is too general

### ISSUE THREAD

**Issue by jezen** [yesodweb/yesod#1732]
Currently, the signature for the [`Yesod.Core.Class.Yesod.isAuthorized`][0] function is too general in that the second argument — the `Bool` — only tells the user whether the request is a read request or a write request.

I think there are a couple of general philosophical reasons why this isn't ideal — namely, _Boolean Blindess_, and _Primitive Obsession_ — but more importantly there is a practical reason why this isn't ideal: the user should be guided to think about how to handle permissions in more granular terms than just reading and writing.

I propose changing the boolean argument to something that carries the HTTP method along with it, but also groups the different HTTP methods by whether they are read or write requests. This would allow the user to specify different permissions logic for different code paths at two different levels of granularity, and it would allow the compiler to encourage the user to think a bit more about the different permission levels for different HTTP methods for a given route.

I suppose this would be a minor breaking change, and would necessitate a version bump to `1.7`.

[0]: https://hackage.haskell.org/package/yesod-core-1.6.20.2/docs/src/Yesod.Core.Class.Yesod.html#isAuthorized

**Comment by snoyberg** [comment]
Since `isAuthorized` already lives in `Handler`, you can access the full `Request` directly, so I think you can achieve what you're looking for without an API change. That's not to discredit your other points, I agree with the philosophical reasons. But I'd rather avoid a breaking change. Perhaps a doc addition explaining how to achieve this would make sense?

**Comment by jezen** [comment]
I never managed to find the time to get around to this, so I'll close this for now.
