### ISSUE TITLE
[Feature request] Export defaultGen

### ISSUE THREAD

**Issue by googleson78** [yesodweb/yesod#1733]
Would it be possible to export `Yesod.Core.Dispatch.defaultGen`? I need this because I'm using a non-standard `YesdorRunnerEnv` and would like to reuse `defaultGen`.

**Comment by snoyberg** [comment]
Seems reasonable, PR welcome. Please include a `@since` comment (since it's newly exposed), changelog entry, and minor version bump. Thanks!
