### ISSUE TITLE
[Auth] yesod-auth-bcrypt link in readme is dead

### ISSUE THREAD

**Issue by smichel17** [yesodweb/yesod#1738]
I get a status 404 at [https://github.com/ollieh/yesod-auth-bcrypt/](https://github.com/ollieh/yesod-auth-bcrypt/). A quick web search found [https://github.com/TobyGoodwin/yesod-auth-bcrypt](https://github.com/TobyGoodwin/yesod-auth-bcrypt) as the fork that seems most up to date. It's still not updated since 2015, but maybe it's simply complete; I'm a newcomer to the Haskell ecosystem, so I don't know the state of most anything.

Along similar lines, I'm not sure who to tell that the `yesod-auth-account` hackage page links to a bitbucket repo which also 404s.

https://github.com/yesodweb/yesod/blob/dfc270b0b2bdcbce13b4c53dbeaf5223b594ed1b/yesod-auth/README.md#L9-L11

**Comment by psibi** [comment]
Thanks for pointing this out! I guess the broken links could be updated to either stackage or hackage link if there is a confusion links.

In general, my recommendation is to rely on the official sources and use this OAuth plugin: https://hackage.haskell.org/package/yesod-auth-oauth2-0.6.3.4

Adding the above link in README would be nice. PR's welcome. :-)
