### ISSUE TITLE
AllocationLimitExceeded isn't caught by yesod to render 500 error page

### ISSUE THREAD

**Issue by jappeace** [yesodweb/yesod#1751]
We want to use allocation limits to ensure our request threads don't misbehave.
Which is explained here: 
+ https://simonmar.github.io/posts/2017-01-24-asynchronous-exceptions.html
+ https://hackage.haskell.org/package/base-4.16.0.0/docs/GHC-Conc-Sync.html#v:enableAllocationLimit

but the default yesod exception handler does not catch this.

Although the FP-complete blog warns against [catching async exceptions](https://www.fpcomplete.com/blog/2018/04/async-exception-handling-haskell/), 
I think for this particular type of exception I'd expect a 500 screen rather then a white screen with AllocationLImitException.

We're currently working around this by rethrowing the async exception into a synchronous one,
and also disabling the allocation limit before throwing 
(otherwise the async exception get's thrown anyway).
```haskell
-- this acts as a yesod middleware
withAllocationLimit' :: (HasCallStack, MonadUnliftIO m) => Int64 -> m a -> m a
withAllocationLimit' limit middle =
  rethrowAllocationAs500 limit $ do
    liftIO $ setLimit limit
    middle

setLimit :: Int64 -> IO ()
setLimit limit = do
  Sync.setAllocationCounter limit
  Sync.enableAllocationLimit

rethrowAllocationAs500 :: MonadUnliftIO m => Int64 -> m a -> m a
rethrowAllocationAs500 limit middle = unsafeAsyncCatch middle (handleAllocationLimt limit)

handleAllocationLimt :: MonadIO m => Int64 -> EUnsafe.AllocationLimitExceeded -> m res
handleAllocationLimt limit exception = do
  liftIO Sync.disableAllocationLimit
  liftIO $ throwIO $ MkAllocationLimitException $ MkAlocExceptionData
    { aleSetLimit = limit
    , aleException = exception
    , aleMsg       = "this means the computation was took "
        <> "to long to finish in an acceptable time frame, make sure there"
        <> " are no bugs and if not increase the limit"
    }

```

**Comment by snoyberg** [comment]
This is a good point, I'm glad you're raising it. It may actually make sense in this case to go even further, and say that error handling at this layer should catch all sync _and_ async exceptions. I can't think of a good reason to let async exceptions propagate in this kind of case, since ultimately Warp will catch and (poorly) handle those anyway. What do you think?

**Comment by jappeace** [comment]
Yes, I think it'd be confusing if the user would see an exception rather then the 500 screen.

At supercede we'd prefer to have the 500 screen because it says we're doing critical maintenance for example which is less confusing for the user.

I'll make a PR for this

**Comment by jappeace** [comment]
I made an implementation that catches async exceptions in here: https://github.com/yesodweb/yesod/pull/1753

**Comment by jappeace** [comment]
I suppose this is solved then.
