### ISSUE TITLE
"Application isn't built" when launching yesod devel

### ISSUE THREAD

**Issue by dariooddenino** [yesodweb/yesod#1755]
Hi,
I've been experiencing this minor annoyance for the past months - if not years.
Basically when I run `stack exec -- yesod devel` I get the "Application isn't built" page until I edit any file.
At that point yesod recompiles and starts working correctly.

Contrary to #1471 I don't get any error message, the terminal looks completely fine.

Right now I'm on Ubuntu 20.04, stack 2.7.5, ghc 9.0.2 and yesod 1.6.1, but, as I wrote, this has happened for a long time with different versions of everything.

A new scaffold project does not give me this problem.

Any idea of how I could debug this? 

Thanks!

**Comment by jezen** [comment]
This isn't exactly an answer to your question, but personally I stopped using `yesod devel` several years ago, and I've just used GHCi directly since. Have you considered just using GHCi directly? Do you know how to do that?

**Comment by dariooddenino** [comment]
@jezen I have tried various times with ghci and ghcid, but they never worked properly for me.
I don't remember the details, but I think it was something about reloads not working reliably or stopping working after a while.

**Comment by schoettl** [comment]
I have good experience with GHCi.

I have a `.ghci` file in the project folder with
```
:set -fobject-code
:l app/DevelMain.hs
update
```

and to reload type:
```
:r
update
```

I have editor key mappings that send those keys to tmux running ghci. The only time it fails for me is maybe when I change model or routes.
