### ISSUE TITLE
yesod-test: testing radio buttons with the same label

### ISSUE THREAD

**Issue by eahlberg** [yesodweb/yesod#1770]
I have a form with multiple radio button sections where the labels of the radio inputs are the same:
```html
<form>
  <div>
    <label for="hident1">How do you rate your stay?</label>
    <div id="hident1">
      <label class="radio" for="hident1-1">
        <div>
          <input id="hident1-1" type="radio" name="f4" value="1" required="required">1
        </div>
      </label>
      <label class="radio" for="hident1-2">
        <div>
          <input id="hident1-2" type="radio" name="f4" value="2" required="required">2
        </div>
      </label>
    </div>
  </div>
  <div>
    <label for="hident2">How do you rate your dinner?</label>
    <div id="hident2">
      <label class="radio" for="hident2-1">
        <div>
          <input id="hident2-1" type="radio" name="f5" value="1" required="required">1
        </div>
      </label>
      <label class="radio" for="hident2-2">
        <div>
          <input id="hident2-2" type="radio" name="f5" value="2" required="required">2
        </div>
      </label>
    </div>
  </div>
</form>
```

Selecting a radio option by using e.g. `byLabelContain "1" "1"` therefore results in `"More than one label contained 1"`. Is there another way to select a label in this case?

**Comment by jezen** [comment]
If the issue is that the content is the same, then one approach might be to actually make the content unique, but then hide that uniqueness with CSS.

Separately, I'm not sure both sets of of radio buttons should have the same value for the `name` attribute.

**Comment by eahlberg** [comment]
@jezen thanks for the response! I think the `name` attribute should be the same (see [mdn](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/radio)). By making the content unique and hiding with CSS, do you mean something like this?
```html
<label><span class="hidden">first</span>1</label>
...
<label><span class="hidden">second</span>1</label>
```

**Comment by jezen** [comment]
Personally, I think the first option is probably the best one. In practice I have found I needed to use monadic forms, with custom markup and custom fields more often than not, so I think having that flexibility is actually better than trying to accommodate the markup that the rendering functions in the `yesod-form` library generates.

**Comment by eahlberg** [comment]
Yeah that's a valid point. I also hit a case where the third option wouldn't suffice so I think the first one is the way to go. I've opened a PR [here](https://github.com/yesodweb/yesod/pull/1781).
