### ISSUE TITLE
Yesod is catching Timeout, which breaks the timeout middleware

### ISSUE THREAD

**Issue by pbrisbin** [yesodweb/yesod#1771]
It seems Yesod is catching the [`Timeout` exception](https://hackage.haskell.org/package/base-4.16.1.0/docs/System-Timeout.html#t:Timeout) used by the standard `timeout` function and turning it into a 500 instead of letting to get back to `timeout`. This means that when we use the [`Timeout` middleware](https://hackage.haskell.org/package/base-4.16.1.0/docs/System-Timeout.html#t:Timeout), instead of getting a 503 as desired, we get see `InternalError "<<timeout>>"` come through as a 500.

## Steps

Given the following executable:

```hs
{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE QuasiQuotes #-}
{-# LANGUAGE TemplateHaskell #-}
{-# LANGUAGE TypeFamilies #-}

module Main where

import Control.Concurrent (threadDelay)
import Data.Maybe (fromMaybe)
import Data.Text (Text)
import Network.HTTP.Types.Status (status200)
import Network.Wai (responseLBS)
import Network.Wai.Handler.Warp as Warp
import Network.Wai.Middleware.Timeout as Middleware
import System.Environment (lookupEnv)
import Text.Read (readMaybe)
import Yesod hiding (respond)

data App = App

mkYesod "App" [parseRoutes|
/ RootR GET
|]

getRootR :: Handler Text
getRootR = do
    liftIO $ threadDelay $ 3 * 1000000
    pure "Hello word\n"

instance Yesod App

simpleApp :: Application
simpleApp _req respond = do
    threadDelay $ 3 * 1000000
    respond $ responseLBS status200 [] "Hello world\n"

main :: IO ()
main = do
    app <- do
        x <- lookupEnv "YESOD"
        if x == Just "1" then toWaiAppPlain App else pure simpleApp

    port <- fromMaybe 3000 . (readMaybe =<<) <$> lookupEnv "PORT"
    Warp.run port $ Middleware.timeout 2 app
```

## Expected behavior

When run using the `simpleApp`, it does as expected (a 503):

```console
stack exec -- timeout-example
```

```console
% curl -D - localhost:3000
HTTP/1.1 503 Service Unavailable
Transfer-Encoding: chunked
Date: Mon, 27 Jun 2022 20:35:32 GMT
Server: Warp/3.3.21
```

## Actual behavior

When run using `App` with yesod, the `Timeout` turns into a 500:

```console
% YESOD=1 stack exec -- timeout-example
27/Jun/2022:16:40:38 -0400 [Error#yesod-core] <<timeout>> @(yesod-core-1.6.23.1-BngrWz5NDXK4xc2KyG7z7M:Yesod.Core.Class.Yesod src/Yesod/Core/Class/Yesod.hs:691:6)
```

```console
% curl -D - localhost:3000
HTTP/1.1 500 Internal Server Error
Date: Mon, 27 Jun 2022 20:40:38 GMT
Server: Warp/3.3.21
Content-Length: 157
Content-Type: text/html; charset=utf-8
Set-Cookie: _SESSION=vYgezGHwk6Qauaj0RdmWc3XmIZh0HaWbZ7phPFzTHrdoLpzE/UrxshoB+rp1pgMbzE5PUMWbb65dIfdCY30rYn9QWkh21VocKCGttI0FAgzT1lH9F4Owj2sWZ/PqFfBq0Daylw0SHfGt230IZZ18oT5je1RR1CGjD00WkZlY3KrUivN0y2E=; Path=/; Expires=Mon, 27-Jun-2022 22:40:36 GMT; HttpOnly
Vary: Accept, Accept-Language
X-XSS-Protection: 1; mode=block

<!DOCTYPE html>
<html><head><title>Internal Server Error</title></head><body><h1>Internal Server Error</h1>
<pre>&lt;&lt;timeout&gt;&gt;</pre>
</body></html>%
```

## Versions

The above does not reproduce in lts-19.0, and appears in lts-19.1. From that, I assumed the bug is in `yesod-core-1.6.22.0`. I eventually found [this code](https://github.com/yesodweb/yesod/compare/yesod-core-1.6.21.0...yesod-core-1.6.22.0#diff-106c156959464ae06ede93a357503f35dea6c3dbdb98438c983e14d0dab72d54R60), which appears kind of intentional.

**Comment by pbrisbin** [comment]
I've found another circumstance in which this has broken our error-handling/reporting:

We see a lot of `InvalidRequest Warp: Client closed connection prematurely` noise starting with this update. Both in our logs and reported to Bugsnag. Warp has always considered this a "normal" exception (and I agree),

![](https://files.pbrisbin.com/screenshots/screenshot.267546.png)

By Yesod taking over and not letting it get to Warp, the `defaultShouldDisplayException` behavior (which we leveraged to keep this noise out of our metrics) no longer works.

**Comment by snoyberg** [comment]
Only thing I can think of is adding a specific list of exceptions inside Yesod that it should not catch and should instead propagate.

**Comment by snoyberg** [comment]
I honestly don't feel great about any of this. Pinging @jappeace. @pbrisbin is raising some valid concerns with the previous async exception behavior change. Here's how I'd summarize the situation:

* Generally, catching an async exception is a bad thing
* However, in the web server context, that's not true. Since each connection is handled by its own green thread, catching those async exceptions and turning them into valid responses to the client makes all the sense in the world.
* The issue here is: who should do the catching?
    * @jappeace wants the catching done by Yesod, since it allows for better error output
    * @pbrisbin wants to rely on WAI middlewares and some of Warp's built-in behavior

I can't really say that either is "more correct" than the other. A configuration option to determine which async exceptions (if any) should be caught by Yesod is the best middle ground I can think of.

**Comment by jappeace** [comment]
Making it configurable would also work for us.
I think we don't want to catch the connection closed exception, but we do want to catch the timeout one.

**Comment by snoyberg** [comment]
Cool. Would one of you be interested in submitting a PR with this kind of change?

**Comment by jappeace** [comment]
yes, I"ll try doing this wensday
