### ISSUE TITLE
Trying to understand apptroot and ApprootStatic

### ISSUE THREAD

**Issue by jfly** [yesodweb/yesod#1792]
(I'm using yesod-core 1.6.24.0)

I'm trying to understand the behavior when I specify something like `approot = ApprootStatic "http://localhost:3000/wiki"`. I've read through [the hackage docs](https://hackage.haskell.org/package/yesod-core-1.6.24.0/docs/Yesod-Core.html#v:approot) and [the yesod book](https://www.yesodweb.com/book/yesod-typeclass#yesod-typeclass_rendering_and_parsing_urls), and *expect* all routes to get prefixed with `/wiki`, and that's sort of half-happening. My urls all appear to be generated as I'd expect, but content isn't actually getting served up where I'd expect.

## Demo

With the following `test.hs` file:

```haskell
{-# LANGUAGE OverloadedStrings     #-}
{-# LANGUAGE QuasiQuotes           #-}
{-# LANGUAGE TemplateHaskell       #-}
{-# LANGUAGE TypeFamilies          #-}
import           Yesod

data HelloWorld = HelloWorld

mkYesod "HelloWorld" [parseRoutes|
/ HomeR GET
/some/path SomePathR GET
|]

instance Yesod HelloWorld where
    approot = ApprootStatic "http://localhost:3000/wiki"

getHomeR :: Handler Html
getHomeR = defaultLayout
    [whamlet|
        <pre>
            HomeR @{HomeR}
            SomePathR @{SomePathR}
    |]

getSomePathR :: Handler Html
getSomePathR = defaultLayout [whamlet|some path!|]

main :: IO ()
main = warp 3000 HelloWorld
```

And a running server:

```
$ runhaskell test.hs
22/Jan/2023:19:27:28 -0800 [Info#yesod-core] Application launched @(yesod-core-1.6.24.0-8Gv4DPUzB40I7pR9a6Te9d:Yesod.Core.Dispatch src/Yesod/Core/Dispatch.hs:178:10)
```

I see that the generated links/urls are definitely prefixed with `/wiki`:

```
$ curl http://localhost:3000
<!DOCTYPE html>
<html><head><title></title></head><body><pre>HomeR http://localhost:3000/wiki/
SomePathR http://localhost:3000/wiki/some/path</pre>
</body></html>%     
```

However, if I try to access `/wiki/` I get this bizarre redirect:

```
$ curl -i http://localhost:3000/wiki/
HTTP/1.1 301 Moved Permanently
Transfer-Encoding: chunked
Date: Mon, 23 Jan 2023 03:28:47 GMT
Server: Warp/3.3.21 + Yesod/1.6.24.0 (core)
Content-Type: text/plain
Location: http://localhost:3000/wiki/wiki
Vary: Accept-Encoding

Redirecting%
```

And if I access `/wiki/some/path`, I get a 404:

```
$ curl -i http://localhost:3000/wiki/some/path
HTTP/1.1 404 Not Found
Date: Mon, 23 Jan 2023 03:29:01 GMT
Server: Warp/3.3.21 + Yesod/1.6.24.0 (core)
Content-Length: 121
Content-Type: text/html; charset=utf-8
Set-Cookie: _SESSION=UiPUt9vwGWZM6LnIx0ZvqZr6FdLcjBjEncb9z8hgGaTShOtNW3/qCysdFAn1hoZjr5WtjR2FJ+MTLKk6XnET6X8bu1Q/K3OlD2j2djfRLWLbec0KC401nz1Gnq1gU8pwuF/iJXx/HAY+wgw/PZrEo/8t7qaKWYcj1rKt3FQnaC2O2eyK7Qc=; Path=/; Expires=Mon, 23-Jan-2023 05:29:01 GMT; HttpOnly
Vary: Accept-Encoding, Accept, Accept-Language
X-XSS-Protection: 1; mode=block

<!DOCTYPE html>
<html><head><title>Not Found</title></head><body><h1>Not Found</h1>
<p>/wiki/some/path</p>
</body></html>%
```

Is this a bug? Or am I just misunderstanding the framework/docs? What I'd have expected:

- `/` to 404
- `/wiki`: I don't know what I'd expect here. Probably redirect to `/wiki/`
- `/wiki/` to serve up `getHomeR`
- /wiki/some/path` to serve up `SomePathR`.

It feels like the url generation code is honoring `approot`, but the actual routing logic is ignoring it.

**Comment by snoyberg** [comment]
> It feels like the url generation code is honoring approot, but the actual routing logic is ignoring it.

That's correct, and it's by design. The route _parsing_ logic is separate. Using `approot` to have a subpath is generally best if you have your site behind some kind of a reverse proxy that rewrites URLs. In your kind of case, I'd recommend prefixing the routes themselves with `/wiki`, otherwise you'll have to play around with things like [`cleanPath`](https://www.stackage.org/haddock/nightly-2023-01-24/yesod-core-1.6.24.0/Yesod-Core.html#v:cleanPath), which is not really intended for this purpose and hard to get right.

**Comment by jfly** [comment]
Ah, ok, good to know, I can definitely rework the routes. (I'm actually not writing a yesod application, I'm just a user of [hledger-web](https://github.com/simonmichael/hledger/tree/master/hledger-web) who wants to host it under a subpath, but I can either fork it or introduce a reverse proxy that rewrites stuff as you suggest).
