### ISSUE TITLE
yesod-form fails to build with transformers >= 0.6

### ISSUE THREAD

**Issue by TeofilC** [yesodweb/yesod#1794]
In transformers-0.6, the `MonadTrans` class was changed to have a quantified constraint:
```
class (forall m. Monad m => Monad (t m)) => MonadTrans t where
...
```

This causes the `MonadTrans AForm` instance to fail.

I feel like there's two solutions:
1. Add a `Monad m => Monad (AForm m)` instance for `AForm` though I feel like there's probably a reason for a lack of one
2. Remove the `MonadTrans` instance

**Comment by snoyberg** [comment]
I think (1) makes sense, but gated via CPP on the version of transformers

**Comment by TeofilC** [comment]
Sure I'll write up a patch next week.
