### ISSUE TITLE
yesod-form: i18n: Add form localization for Romanian language

### ISSUE THREAD

**Issue by ciukstar** [yesodweb/yesod#1800]
Add Romanian language support for form validation error messages.
Thanks.

**Comment by jezen** [comment]
Have you written the translations? Do you need help contributing them?

**Comment by ciukstar** [comment]
> Have you written the translations? Do you need help contributing them?

I have submitted PR #1801 to resolve this issue.

**Comment by ciukstar** [comment]
Resolved by PR #1801
