### ISSUE TITLE
Add getUltDest in the module Yesod.Core.Handler

### ISSUE THREAD

**Issue by ciukstar** [yesodweb/yesod#1831]
Add ```getUltDest``` in the ```module Yesod.Core.Handler```.

```getUltDest``` proves useful in PWA applications for mobile devices, where it can be used for back buttons in Hamlet templates of subsites or shared subpages.

More generally, it is necessary to have some construct (perhaps a stack) to keep track of the URLs crawled to a shared page (resource) in order to return to the starting page.

 ```
 Page_0     Page_1  ...  Page_n
       \    /               |
       Page_01           Page_02
             \         /
             Shared_Page
```

**Comment by jezen** [comment]
> More generally, it is necessary to have some construct (perhaps a stack) to keep track of the URLs crawled to a shared page (resource) in order to return to the starting page.

Is this use case not covered by the `YesodBreadcrumbs` typeclass?

Personally, I'm not averse to exposing another function; it seems relatively minor. But it would be good to better understand the desired design pattern.

**Comment by ciukstar** [comment]
A while ago I tried to use (instantiate) ```YesodBreadcrumbs``` and as far as I remember it doesn't offer what I'm describing. Perhaps I'll try to instantiate it again, which means providing an instance that actually implements the behavior I am asking in this issue. I was hoping someone more experienced would be willing to provide and share an instance of this behavior.

Details: 

Each child page of an application that looks like a native application on mobile devices (PWA, Progressive Web Application) has a “Back” button, which is a link to the previous page from which the user accessed the child page. Everything is fine when there is only one parent page for each child page. The problem occurs when a page can be reached from two or more parent pages. The child page does not know which parent it was accessed from.

For now, for a shared page or a page on a subsite (like ```Yesod.Auth```), I partially solve this problem by using ```setUltDestCurent``` when providing parent page and reading hardcoded ```_ULT``` from the session to link the child page with the parent page.

The scenario becomes more complicated when there are several of these shared pages along a possible path of links:

```
              StartPage
              /        \
    ChildPage_1       ChildPage_2
              \        /
              SharedPage_1
              /        \
    ChildPage_21       ChildPage_22
              \        /
              SharedPage_21
```

Note that this is not the same as using browser history on the client side. From a child page, the user can go to several other pages that are not the parent page, which he must return to by clicking the Back button.

As I see it, the solution is an extension of the "Ultimate Destination" by using a stack of links, also stored in the user's session. The developer uses push to track the path the user follows and pop to indicate the return path. ...Or anything else that solves this problem.

And yes, it's a small problem, but quite annoying when the back button doesn't work properly.

Thanks.

**Comment by ciukstar** [comment]
Use subsites for shared resources
