### ISSUE TITLE
`jsAttributesHandler` only applied to scripts with a src location

### ISSUE THREAD

**Issue by dten** [yesodweb/yesod#1835]
This very much follows on from this other ticket from some years back btw https://github.com/yesodweb/yesod/issues/1621

We are trying to add a CSP nonce value to the script produced by widgets with julius, but the attributes provided by `jsAttributesHandler`
 are only applied if that scripts has a `srcLoc`, which is only possible if `addStaticContent` was used to cache that script somewhere.

The related code is here https://github.com/dten/yesod/blob/master/yesod-core/src/Yesod/Core/Class/Yesod.hs#L596

it looks like this MR was the first to add the attributes to only the ones with a location https://github.com/yesodweb/yesod/pull/1308

So as far as I can see at the moment there's no way to get attributes to the inline script created from julius and so no way to add a csp nonce.

I'm proposing adding the same `jsAttrs` to the inline script also (as the docs seem to claim would happen) and happy to do an MR if that's acceptable. My worry is that would be a change for anyone who was only caching some of the scripts.

**Comment by dten** [comment]
in addition the attributes to not appear to end up on the `<script>` in `<head>` produced from using `toWidgetHead`

**Comment by jezen** [comment]
I can confirm that this works:

```toWidget [julius|alert('!!');|]```

…but this doesn't:

```toWidgetHead [julius|alert('!!');|]```

The framework should make it frictionless to implement an appropriate CSP for any given page, so a pull request to improve this situation is certainly welcome 🙂

**Comment by dten** [comment]
hmm in our project that toWidgt julius does not turn up with jsAttributesHandler's values. I'll try make a small project to demo what I mean

**Comment by jezen** [comment]
That's useful context, and yes, a small demo would be a good idea.

Here are my notes from a few years ago which you may also find useful.

https://jezenthomas.com/2019/09/implementing-csp-in-yesod/

**Comment by dten** [comment]
Yep I actually started from your blog 😊 it was very useful

**Comment by dten** [comment]
@jezen i've written a test that fails to add the attributes to the script

https://github.com/dten/yesod/commit/eca5e5994791c7f43b8c21ad6822815c2e145d80

**Comment by dten** [comment]
and adding the attributes to non-loc scripts fixes it https://github.com/dten/yesod/commit/a1ea911de0c2d13feed74bee190d3e3ee9ece768

**Comment by dten** [comment]
I'm happy to do a PR for this if seems acceptable

**Comment by jezen** [comment]
@dten Of course, that would be welcome.
