### ISSUE TITLE
default-layout.hamlet not being used?

### ISSUE THREAD

**Issue by TheOddler** [yesodweb/yesod#1841]
I'm trying out Yesod, and trying to add a default layout to my website as described [here](https://www.yesodweb.com/book/scaffolding-and-the-site-template#scaffolding-and-the-site-template_defaultlayout). I tried adding `default-layout.hamlet` to my `templates` folder, but it's not being used.

The content of `default-layout.hamlet` is

```hamlet
<h2>Test
```

So I was expecting just all my pages to only show "Test", but it's just still showing my other template files.

My handler for my home page looks like this:

```haskell
getHomeR :: Handler Html
getHomeR = do
  networkInterfaces <- networkInterfacesShortList <$> getsYesod appNetworkInterfaces
  port <- getsYesod appPort
  defaultLayout $(widgetFileReload def "home")
```

I checked the source of `defaultLayout` (https://hackage.haskell.org/package/yesod-core-1.6.26.0/docs/src/Yesod.Core.Class.Yesod.html#defaultLayout) and it indeed does not seem to include the `default-layout.hamlet` file. So I'm wondering, is the Yesod Book outdated here? And is there a different way I can have a default layout for all my pages? Or am I doing something wrong?

I'm using Yesod 1.6.2.1 and building it with Nix & Cabal.

**Comment by jezen** [comment]
It depends on your implementation of `defaultLayout`, and it also might depend on how you're compiling your project.

Do you have a minimal example in a repository somewhere?

**Comment by TheOddler** [comment]
I have no custom implementation of `defaultLayout`, simply using the one provided by `Yesod`. As linked above, it seems the default implementation indeed doesn't use the `default-layout.hamlet` file, and instead has a [hard-coded template](https://hackage.haskell.org/package/yesod-core-1.6.26.0/docs/src/Yesod.Core.Class.Yesod.html#defaultLayout). So I'm guessing the book is just outdated, but wanted to be sure.

I'll have to implement my own `defaultLayout` function then it seems.

Currently don't have a minimal example no, but I can make one if it helps.

**Comment by TheOddler** [comment]
Oh wait I see, the book has it's own template project it uses, which has an overwritten `defaultLayout` function!

I'm sorry, this was just me misunderstanding the book!

**Comment by jezen** [comment]
Ok, yes, you are reading the source correctly. If you don't write an implementation for `defaultLayout` in the `Yesod` instance for your application, then it will use that default one defined in the typeclass.

**Comment by TheOddler** [comment]
Thank you! That makes sense, and luckily I was reading the source correct, just didn't realise yet where my mistake was.
