### ISSUE TITLE
instance Default WidgetFileSettings vanished

### ISSUE THREAD

**Issue by thielema** [yesodweb/yesod#1850]
After a `cabal update` I get the following type error when compiling `hledger-web`:
~~~~
    • No instance for ‘Data.Default.Internal.Default
                         WidgetFileSettings’
        arising from a use of ‘def’
~~~~

Did something change in one of the `yesod` packages?

**Comment by jezen** [comment]
The [file where this instance is defined][0] hasn't changed in the best part of eight years. I don't see any changes to Yesod that would have caused this in the past half year either. Could the change be somewhere else, like in hledger?

[0]: https://github.com/nh2/yesod/blob/master/yesod/Yesod/Default/Util.hs

**Comment by thielema** [comment]
On Thu, 24 Oct 2024, Jezen Thomas wrote:

> The file where this instance is defined hasn't changed in the best part 
> of eight years. I don't see any changes to Yesod that would have caused 
> this in the past half year either. Could the change be somewhere else, 
> like in hledger?

I assumed it could be caused by Cabal choosing two different versions of 
the same yesod package at different places. But Cabal has not shown a 
warning about such a conflict. Hm.

**Comment by thielema** [comment]
On Thu, 24 Oct 2024, Jezen Thomas wrote:

> Could it perhaps be related to this?
> 
> #1848 (comment)

That one looks different.

I assumed my problem could have to do with an orphan instance, but 
"instance Default WidgetFileSettings" is defined right after 
"WidgetFileSettings" in Yesod.Default.Util.

**Comment by thielema** [comment]
On Thu, 24 Oct 2024, thielema wrote:

> I assumed my problem could have to do with an orphan instance, but 
> "instance Default WidgetFileSettings" is defined right after 
> "WidgetFileSettings" in Yesod.Default.Util.

I think I found the problem. yesod imports package data-default-class and 
defines instance Data.Default.Class.Default WidgetFileSettings, whereas 
hledger expects instance Data.Default.Default WidgetFileSettings from 
package data-default. Formerly, data-default just re-exported Default 
class from data-default-class, but in data-default-0.8.0.0 there seems to 
be a custom definition. data-default-0.8.0.0 was released yesterday.

I do not know whether this means that data-default-class becomes 
deprecated or what the relation between data-default and 
data-default-class is intended to be.

**Comment by thielema** [comment]
The author of `data-default-class` tells, that in future `data-default` should be preferred:
https://github.com/mauke/data-default/issues/29

**Comment by jezen** [comment]
Thank you for investigating. It seems (and correct me if I'm wrong) that there's nothing really to do here though, so I will close this issue.

**Comment by thielema** [comment]
On Sat, 26 Oct 2024, Jezen Thomas wrote:

> Thank you for investigating. It seems (and correct me if I'm wrong) that 
> there's nothing really to do here though, so I will close this issue.

I think you can replace data-default-class by data-default to become 
future-proof.
