### ISSUE TITLE
There should be a tutorial explaining how to use websockets with Yesod

### ISSUE THREAD

**Issue by derekchiang** [yesodweb/yesod#529]
Currently searching "Yesod websockets" on Google only results in this: http://stackoverflow.com/questions/10963175/websockets-in-yesod

According to the answer, however, it's possible to use websockets with Yesod.  Since websockets is a hot topic, I think there should be a tutorial explaining its usage in haskell.

**Comment by snoyberg** [comment]
Closing out old issues, if still relevant please open a new one.
