### ISSUE TITLE
GHC eats 13 GB of memory when compiling staticFiles TH splice

### ISSUE THREAD

**Issue by ygale** [yesodweb/yesod#585]
The static dir contains about 300 files - it includes an in-browser HTML editor. Running yesod 1.1.2 on ghc 7.6.3 64-bit, Ubuntu 12.10.

**Comment by snoyberg** [comment]
Closing out old issues, if still relevant please open a new one.

**Comment by ygale** [comment]
For the record, we are working around the problem by having front-end developers maintain {{StaticFilesList.hs}} manually. Even for someone who has never seen a line of Haskell code before, the format of this module is simple and predictable enough that it doesn't seem to cause them pain.
