### ISSUE TITLE
Dev server doesn't reload static files properly

### ISSUE THREAD

**Issue by chrisdotcode** [yesodweb/yesod#606]
So I"m testing out my new site with `yesod --dev devel`, and I'm editing stylesheets live. Unfortunately, every once in a while, the stylesheets either don't load (even after force refreshing cache), and/or the HTTP connection is hanging. I'm positive that these are both issues with the yesod server -and in particular the dev server.

I also put these two bugs in this same issue because I'm pretty sure that they're related.

My yesod bin version is: 1.2.2, and I'm 64bit Firefox Linux, if it matters.

I'm still a haskell newbie, but if there's any way I could help, I want to help!

**Comment by myShoggoth** [comment]
I'm still seeing this, and for some reason touching the StaticFiles.hs has no effect.

**Comment by snoyberg** [comment]
The new yesod devel for the GSoC project this year is designed to support this correctly.

**Comment by adarqui** [comment]
Hi. I'm using yesod 1.4.2. I've recently come across this behavior. Literally every single "refresh" from the browser causes it to hang. I then have to stop & refresh once more to get to a page. It seemed to just come out of nowhere, but I think it's related to the static assets I added to my project. As a test, I removed static/css/bootstrap.css. Once I did that, I can refresh no problem. When I add it back, I get this weird hanging behavior. If I don't actually refresh and instead click through the site, it doesn't seem to happen.

touching Settings/StaticFiles.hs doesn't fix it.

Should I update some dependencies perhaps?

Thanks!

**Comment by adarqui** [comment]
To anyone else struggling with this, I may have resolved it. I simply updated yesod-static, yesod-bin, and yesod-core. For now it seems to have resolved the issue. Here is a snippet from my cabal file & my yesod-bin command:

```
                , yesod                         >= 1.4.2      && < 1.5
                , yesod-core                    >= 1.4.19      && < 1.5
                , yesod-auth                    >= 1.4.0      && < 1.5
                , yesod-auth-account            >= 1.4.1      && < 1.5
                , yesod-auth-oauth2             >= 0.1.3
                , yesod-static                  == 1.5.0.3
                , yesod-form                    >= 1.4.0      && < 1.5
```


```
stack install yesod-bin-1.4.17.1
```

Thanks!
