### ISSUE TITLE
Contextualizing Session Messages

### ISSUE THREAD

**Issue by 2piix** [yesodweb/yesod#614]
I would like to add "context" to the messages I set and use, so that I can use a unified messaging framework with "style".  For example, Bootstrap 3 has alerts which can be styled as "warnings" or "information".

To that end, I propose we add a method to the Yesod type class:

    contextualMessage :: LogLevel -> msg -> HandlerT a m ()

and defining

    setMessage = contextualMessage LogInfo

**Comment by snoyberg** [comment]
Closing out old issues, if still relevant please open a new one.
