### ISSUE TITLE
yesod-bin: idle cpu usage should be reduced further

### ISSUE THREAD

**Issue by MetaMemoryT** [yesodweb/yesod#615]
On my computer yesod devel takes a solid 5-17% cpu even when idle.

I tried to remove the garbage collection with:

   let devArgs = pkgArgs ++ ["+RTS","-I0","-M150m","-RTS"

and compiled with -rtsopts so I could:
    +RTS -I0 -M350m -RTS

I don't think it is to do with garbage collection, it might have something to do with running yesod devel in a directory that is also being watched by dropbox.

some possibly related information:
  http://stackoverflow.com/questions/16469623/yesod-devel-cpu-overhead

**Comment by snoyberg** [comment]
Closing out old issues, if still relevant please open a new one.
