### ISSUE TITLE
Implement Compilation Errors into the Browser

### ISSUE THREAD

**Issue by lucassimon994** [yesodweb/yesod#616]
One of my favorite features of the Play framework in Java is the fact that is displays compilation errors in the browser in a page that looks like

![compileerror](https://f.cloud.github.com/assets/1832482/1386141/0a5905f6-3b6c-11e3-97ca-bdae86716cf0.png)

The reason that I want such a feature is because the following error I received while following the Yesod tutorial for noobies was

    Forcing recompile for ./Handler/Article.hs because of templates/article.hamlet
    Forcing recompile for ./Handler/Article.hs because of templates/article.hamlet
    Rebuilding application... (using cabal)

    Handler/Article.hs:10:11:
        Not in scope: data constructor `BlogB'
        Perhaps you meant `BlogR' (imported from Import)
        In the result of the splice:
          $(widgetFile "article")
        To see what the splice expanded to, use -ddump-splices
        In a stmt of a 'do' block: $(widgetFile "article")
        In the second argument of `($)', namely
          `do { setTitle $ toHtml $ articleTitle article;
                $(widgetFile "article") }'
    Build failure, pausing...

What the error ended up being was a typo in the article.hamlet file. The advantage of using such a compilation error reporting system is that new users will not have to get used to the types of compilation errors and what they mean.

**Comment by snoyberg** [comment]
Planned for the GSoC project.
