### ISSUE TITLE
Webserver hangs after model change (using MongoDB)

### ISSUE THREAD

**Issue by Timwi** [yesodweb/yesod#633]
I encountered this bug under Windows, though I doubt that it’s Windows-specific.

Steps to reproduce:

* Install Haskell Framework, Yesod and MongoDB

* Use the Yesod scaffolding to create a site called “Guestbook” with MongoDB

* Add the following entity to the `config\models` file:

        Entry
            name Text
            subject Text
            message Textarea

* Replace `Handler\Home.hs` with this file: http://pastebin.com/3t4kCSPj

* Replace `templates\homepage.hamlet` with this file: http://pastebin.com/J57Fch8H

* Now run the application. Go to `localhost:3000` and post a guestbook entry. The entry is posted to the MongoDB database with three fields: `name`, `subject` and `message`.

* Now add a field to the `Entry` record in `config\models`:

        created UTCTime

* Add this line at the bottom of `Handler\Home.hs` (with the right indentation):

        <*> lift (liftIO getCurrentTime)

* In `templates\homepage.hamlet`, change line 12 so that it reads:

        $forall Entry user subject message _ <- entries

    (i.e., just add an underscore)

* Wait for Yesod to recompile the application and then go to `localhost:3000` again. Reload the page.

Expected behaviour
-------------------------

**The page loads.** An error message or some garbled content might be expected.

Actual behaviour
-------------------------

**The page does not load.** Yesod just hangs and never responds to the HTTP request. The website is rendered completely inoperable.

**Comment by snoyberg** [comment]
Closing out old issues, if still relevant please open a new one.
