### ISSUE TITLE
"yesod devel" doesn't work nicely with other reverse proxies

### ISSUE THREAD

**Issue by pikajude** [yesodweb/yesod#677]
I tried to run nginx + yesod devel in development mode and a couple bugs came up:
1.  I found that the wai reverse proxy is throwing `IncompleteHeaders` when the first asset is loaded (but not the subsequent ones).
   
   As a workaround, I can add in an empty CSS file to the top of the file in development mode, which seems to clear that up.
   
   I have no idea where the bug is coming from. I poked around in the `http-client` source but couldn't make anything of it.
2. POST requests hang for awhile, then a "Something went wrong" page comes up. If I refresh the page, the request went through.

**Comment by chreekat** [comment]
As a followup, nginx has "safe" defaults for proxy_set_header and proxy_http_version:

    # http://nginx.org/en/docs/http/ngx_http_proxy_module.html#proxy_set_header
    proxy_set_header Host $proxy_host;
    proxy_set_header Connection close;

    # http://nginx.org/en/docs/http/ngx_http_proxy_module.html#proxy_http_version
    proxy_http_version 1.0;

These are all wrong for Keter, which handles persistent connections and
does further name-based proxying. What we want is:

    proxy_http_version 1.1;
    proxy_set_header Host $host;
    proxy_set_header Connection "";
