### ISSUE TITLE
Add i18n placeholder support to yesod-form

### ISSUE THREAD

**Issue by meteficha** [yesodweb/yesod#686]
Currently you may add a `placeholder` attribute using the `fsAttrs` field of `FieldSettings`.  However, that isn't a good solution since you either have to forego i18n for your placeholder or manually use `getMessageRender`.

An option is to make `placeholder` a first-class citizen by creating a `fsPlaceholder` attribute.  I'm not sure how much code would be broken by this change.

**Comment by snoyberg** [comment]
I think we'll want to rethink `FieldSettings` a bit for the next breaking change, may as well include this at that time.

**Comment by meteficha** [comment]
I agree.  And I think that promoting it to a separate field is the way to go.

**Comment by geraldus** [comment]
This will be very useful!

**Comment by StevenXL** [comment]
Please see #1597 and #1593. Both attempt to add i18n placeholder support, but were rejected. We are closing down this issue, but as always, we can re-open if need be.

**Comment by geraldus** [comment]
> I think we'll want to rethink `FieldSettings` a bit for the next breaking change, may as well include this at that time.

Sorry for off-topic, very interested in Yesod's future, is there any place where you discuss / inform about pending changes and etc.?  I'm interested in participation

**Comment by snoyberg** [comment]
The Yesod mailing list would be the best place for that. I've been avoiding
breaking changes for a few years now, which is why such discussions haven't
happened much. But please do feel free to bring up such discussions there.
