### ISSUE TITLE
keter scp port in copy-to

### ISSUE THREAD

**Issue by mrogalski** [yesodweb/yesod#724]
Could there be a copy-to-port: setting for keter?  As far as I see, simplest modifications (for example, breaking copy-to on spaces: run "scp" $ [fp] ++ T.words $ T.unpack s) to the current keter.hs won't work -- the port setting (for instance, -P1234) must be inserted before any filepaths.

This would allow sending project.keter to a virtual server that listens on ssh connections on a certain, non-22 port.

**Comment by wiz** [comment]
Can this be generalized to `scp-options` or something like that? I'm currently fighting a glitch causing transfer stalling (and `yesod keter` command lock-up). Passing arbitrary options will help a lot.

**Comment by snoyberg** [comment]
I'm not opposed. Would you like to take a crack at a pull request?

**Comment by wiz** [comment]
Sure.
