### ISSUE TITLE
yesod-static: perform hash calculations in a separate thread

### ISSUE THREAD

**Issue by andrewthad** [yesodweb/yesod#732]
I've noticed that on the site I've built that has around 30,000 files uploaded (they go in the static folder), it takes around 60 seconds to start warp. If I move these files elsewhere (so that they wouldn't be served in the static subsite), warp starts almost immidiately, just like it does locally. Does anyone know why this would be happening?

**Comment by snoyberg** [comment]
Lower priority, closing.
