### ISSUE TITLE
before/after actions for yesod-test

### ISSUE THREAD

**Issue by joelteon** [yesodweb/yesod#734]
Would like to be able to clean out the database after each test. There's already a [page for this](https://github.com/yesodweb/yesod/wiki/Flushing-database-between-tests) on the wiki, but the "flushing" there is just an IO action since he's deleting a sqlite3 database file. If you need an action to run before each test and you need access to your Yesod environment, currently you're SOL.

**Comment by MaxGabriel** [comment]
Just wanted to mention to the people here that I've implemented database wiping for each of the backends as part of the scaffolding https://github.com/yesodweb/yesod-scaffold/pull/54

HSpec2 is being used now, so before/after actions in general are now supported, as well.

**Comment by gregwebs** [comment]
Let me know if hspec2 does not do the trick.
