### ISSUE TITLE
yesod devel is really slow compared to :reload in ghci

### ISSUE THREAD

**Issue by darthdeus** [yesodweb/yesod#754]
I'm not sure if this is a bug, but I asked around on IRC and got told to file a bug.

It seems that `yesod devel` is really really really slow compared to doing `:reload` and `:main` in GHCi. In a scaffolded site it takes around 5-8 seconds for the app to recompile and server to start again after I save a file without making any changes to it.

I've tried using GHCi with manual `:reload` and `:main`, which is basically instant for source file changes, but unfortunately `:reload` doesn't detect changes in template files. I'm not really sure if there's a way around that?

I'm mostly curious if there's a way to make this faster, or any workaround or tips? :)

**Comment by creichert** [comment]
I workaround this by using DevelMain. https://github.com/yesodweb/yesod-scaffold/blob/postgres/app/DevelMain.hs and hook it into an editor shortcut and it's very quick.

You can also hook DevelMain into something like Chromix or Moz Repl to auto reload the browser window when templates change.

I also use https://github.com/sol/reserve on smaller non-scaffold project.

**Comment by mgsloan** [comment]
Another good trick is to use `forkProcess` in the ghci session that's running your `main`.  The reason this is necessary is that merely using `fork` and killing the main thread isn't sufficient to kill all the threads.  I believe that the solution `yesod devel` takes to this (and the TH dependencies stuff) is to kill the whole GHCI and start a new one.  However, that throws away a lot of incrementality.  If you use `pid <- forkProcess $ ...` instead, though, you can kill all the threads via `signalProcesss sigKILL pid`, and then start a new one.

**Comment by gregwebs** [comment]
@mgsloan I which I had known that!

**Comment by mgsloan** [comment]
@gregwebs It's a good one!  POSIX only, though!

**Comment by gregwebs** [comment]
@mgsloan are you interested in putting together a patch for this?

**Comment by darthdeus** [comment]
If I understand correctly, if `DevelMain` used `forkProcess` instead of `forkIO`, it would automatically cleanup all child threads from the process?

**Comment by mgsloan** [comment]
@gregwebs I am not sure if I will have the time to do that, sorry!  Also, I haven't been doing much development based on yesod recently, so I don't personally feel the need for it right now.

I do have a rough / thrown together internal tool I wrote that's similar to yesod devel, which uses this trick.  It's whimsically called "turbo-devel".  I can clean it up a little bit and put it up, if that sounds helpful.

**Comment by snoyberg** [comment]
There are enough projects in flight right now that I think we can safely close this. Either the GHCi options in the scaffold or the upcoming GSoC should address this.
