### ISSUE TITLE
Yesod eats 10-30% CPU when running idle in development

### ISSUE THREAD

**Issue by darthdeus** [yesodweb/yesod#767]
I've asked around on IRC and it seems I'm not the only one experiencing this. I just noticed today when I left my Yesod app running and left the room for about 5 minutes, only to come back and hear my cpu fan running, so I opened htop and there was yesod, eating half of my CPU :)

I've been also using [DevelMain.hs](https://github.com/chrisdone/ghci-reload-demo) from @chrisdone, which seems to eat even more CPU and hangs at around 25-50%, while `yesod devel` itself runs only at about 10-30%. I'm on OS X 10.9 and GHC 7.8.2 if that's of any relevance.

Is there some way that I can inspect what is using the CPU?

**Comment by jezen** [comment]
This issue is now ancient, and the PR that may have been an approach to addressing this was closed half a decade ago, unmerged. I think we can close this.
