### ISSUE TITLE
Websocket example error "One or more reserved bits are on: reserved1 = 1, reserved2 = 0, reserved3 = 0"

### ISSUE THREAD

**Issue by swamp-agr** [yesodweb/yesod#823]
Running websocket chat application on http://localhost:3000 in chromium browser.
After a one minute timeout client is failed to submit test message.

console.log: WebSocket connection to 'ws://localhost:3000/' failed: One or more reserved bits are on: reserved1 = 1, reserved2 = 0, reserved3 = 0
WebSocket is already in CLOSING or CLOSED state.

**Comment by reneklacan** [comment]
What's the status of this issue? I am experiencing this issue right now on Chrome.

**Comment by creichert** [comment]
@reneklacan The status is it's a dodgy issue and we're not certain exactly certain if the error is in yesod-websockets. What version of websockets and yesod-websockets are you using?

**Comment by reneklacan** [comment]
Thank you for your response

My versions:
```
websockets-0.9.2.2
yesod-websockets-0.2.1.1
```

**Comment by reneklacan** [comment]
So I have found out that it was issue with my code - I didn't do `newBroadcastTChan`. Sorry for false alert.

**Comment by geraldus** [comment]
Is this still relevant?

**Comment by snoyberg** [comment]
I don't think so @geraldus, closing.
