### ISSUE TITLE
incorrect credentials on login should redirect to /auth/login

### ISSUE THREAD

**Issue by krgn** [yesodweb/yesod#827]
I am using Yesod.Auth.Email to log users in. It works in general, however, when omitting, e.g. the email field, I get re-directed to `/auth/page/email/login` and shown a message. As far as I can tell it is not possible to override this behavior in the YesodAuth or YesodAuthEmail classes. From a users perspective, it should be changed to redirect to /auth/login, again showing a message.

**Comment by snoyberg** [comment]
Closing out old issues, please reopen if still relevant
