### ISSUE TITLE
Chat example requires extra modules.

### ISSUE THREAD

**Issue by dschalk** [yesodweb/yesod#838]
The Yesod websockets chat example wouldn't run in my GHC-7.8.3/Ubuntu 14.04.1 box until I installed stm-lifted and conduit-combinators. I am concerned that people searching for Haskell full-duplex, mult-user boilerplate code will be discouraged by this and continue Googling until they hit on some inferior technology that happens to work out of the box.  The following print-out shows what I did and the not-so-helpful error messages I received:
_____________________________________________________________
e@e:~/yesod$ cd yesod-webs*
e@e:~/yesod/yesod-websockets$ cabal install
Resolving dependencies...
In order, the following will be installed:
yesod-websockets-0.2.0 (reinstall)
Warning: Note that reinstalls are always dangerous. Continuing anyway...
Configuring yesod-websockets-0.2.0...
Building yesod-websockets-0.2.0...
Installed yesod-websockets-0.2.0
e@e:~/yesod/yesod-websockets$ runghc chat

chat.hs:9:8:
    Could not find module ‘Conduit’
    Use -v to see a list of the files searched for.

chat.hs:11:8:
    Could not find module ‘Control.Concurrent.STM.Lifted’
    Perhaps you meant
      Control.Concurrent.MVar.Lifted (from lifted-base-0.2.2.1)
      Control.Concurrent.Chan.Lifted (from lifted-base-0.2.2.1)
      Control.Concurrent.Lifted (from lifted-base-0.2.2.1)
    Use -v to see a list of the files searched for.
_________________________________________________________
Also, I added an every-twenty-second ping function in order to stop the premature timeouts. I suggest that the elapsed time before timeout be extended, and that a convenient way to adjust the time before timeout be provided. Wai websockets server.lhs' main function has a place for "Warp.runSettings Warp.defaultSettings { Warp.settingsTimeout = whatever . . . " but there is no clue in the commentary about doing this. Yesod-websockets has nothing comparable.
I am not having any problems with any of this. My main purpose in bringing this to your attention is to make sure you know that chat.hs doesn't compile in its current state. Maybe adding stm-lifted and conduit-combinators to build-depends in yesod-websockets.cabal would fix this. I also think that timeouts come way too soon, and that it would be nice to have a convenient way to adjust them.

**Comment by creichert** [comment]
I'm closing this issue as Fixed since this is now documented in the README. Don't hesitate to bring this back up if you have further issues.

Thanks!
