### ISSUE TITLE
Add configurable CORS support to yesod-static

### ISSUE THREAD

**Issue by maxcan** [yesodweb/yesod#850]
If you have a site which requires CORS, using yesod-static makes it difficult to add the `Access-Control-...` headers required for CORS support.  IE seems to have more stringent requirements than FF/Chrome which is why we didn't notice this earlier.  For example, IE requires CORS headers on font requests whereas FF/Chrome do not.

@snoyberg , if you're theoretically comfortable with adding this, I'll get a pull request ready for you.

CC: @gregwebs

**Comment by snoyberg** [comment]
Closing out old issues, please reopen if still relevant
