### ISSUE TITLE
Automatic redirect for "unclean" paths would have problems for POST/PUT requests

### ISSUE THREAD

**Issue by neocxi** [yesodweb/yesod#852]
https://github.com/yesodweb/yesod/blob/9ce4d49d0af41c818c94214c2c6ea5f3ab340f34/yesod-core/Yesod/Core/Dispatch.hs#L87 redirects all unclean paths regardless of the HTTP request types.

On the other hand, the cleanPath fuction is doesn't have any information to decide if it's an appropriate request to clean up. I suggest either disable automatic redirects for non-GET requests or adding one more parameter to cleanPath function

**Comment by snoyberg** [comment]
Closing, I don't think we should try significantly harder for some broken clients
