### ISSUE TITLE
MHelper listToMaybe

### ISSUE THREAD

**Issue by JeremyRubin** [yesodweb/yesod#856]
In MHelper from Yesod.Form.Functions

     Left (SomeMessage e) -> (FormFailure [renderMessage site langs e], maybe (Left "") Left (listToMaybe mvals))

I think that listToMaybe is not the correct function here because it only extracts `head mvals`.

Rather, I propose that the type should be changed to [Text] allowing the user to restore state on fails.

Otherwise when implementing custom form fields multiple values cannot be extracted in the error case so the users state cannot be renewed on error. I think this shouldn't break too much existing code.

**Comment by snoyberg** [comment]
Closing out old issues, please reopen if still relevant
