### ISSUE TITLE
Support for 'Access-Control-Allow-Origin' Headers

### ISSUE THREAD

**Issue by Normangorman** [yesodweb/yesod#859]
See here:
http://stackoverflow.com/questions/26824120/how-do-i-enable-access-control-allow-origin-headers-for-static-files-in-yesod

Michael Snoyman advised setting up a WAI middleware to take care of this, but it should probably be a feature which is more easily available in Yesod.

Looks like we need to get this on Stackage:
http://hackage.haskell.org/package/wai-cors-0.2/docs/Network-Wai-Middleware-Cors.html

**Comment by meteficha** [comment]
Although `wai-cors` works, ideally it would be better to have something more tightly integrated into Yesod.  By that I mean that it should report on OPTIONS only the methods that are accepted by the server.  But this is just a wish.

**Comment by gregwebs** [comment]
It looks like the [cors](http://hackage.haskell.org/package/wai-cors-0.2.2/docs/Network-Wai-Middleware-Cors.html#v:cors) function takes a parameter that allows for customization. One can traverse yesod's routing data type.

**Comment by snoyberg** [comment]
I don't think anyone has plans on jumping into this given that wai-cors solves most of the problem, closing.
