### ISSUE TITLE
Make yesod-bin add-handler accept a routes file as an argument, automatically generating all handlers therein

### ISSUE THREAD

**Issue by bitemyapp** [yesodweb/yesod#893]
Cf. https://github.com/yesodweb/yesod/issues/892

So I don't have to abuse `awk`.

**Comment by snoyberg** [comment]
@bitemyapp I'm still waiting for feedback on this issue.

**Comment by bitemyapp** [comment]
@snoyberg sorry!

So basically, the idea is that I defined a bunch of routes semi-mechanically in my routes file. I wanted to generate the handler files for each without manually copying and pasting to the yesod binary.

I couldn't find a way to make it purely argument passing at the time, so I had to use expect.

It seems to me (maybe this isn't reasonable?) that one should be able to point at a routes file with an action like "add-handlers" or some-such and have the Handlers all generated.

That's the gist of the request here.

**Comment by snoyberg** [comment]
That still doesn't answer my question above: how is this different from #892? Are these just two identical issues, or are you asking for two different things? I'm having trouble following what's going on here.

**Comment by bitemyapp** [comment]
@snoyberg Sorry, I'll try to make them more distinct:

#892 -> make the use of expect unnecessary by making argument passing work rather than using `getLine` to get user input, makes it more scriptable

#893 (this one) -> add new functionality (not just changing the command-line interface) that would generate all handlers from a routes file. Varying degrees of "smartness" are possible here.

**Comment by snoyberg** [comment]
I'd recommend changing the title on #892, it's incredibly unclear to the point of likely scaring off potential contributors. I'm personally *not* in favor of implementing this issue, but if someone sends a PR I'd accept it.

**Comment by bitemyapp** [comment]
@snoyberg not in favor this issue, the other one, or both?

**Comment by snoyberg** [comment]
This issue. I'm pretty neutral in the other one since it seems almost
trivial to script with the current interface, but I agree that command line
options are better. But I don't see a good reason to support an input file
syntax if we have a good CLI.

**Comment by bitemyapp** [comment]
I'm axing this issue then.
