### ISSUE TITLE
A CSRF protection error occurs without reason when using Firefox

### ISSUE THREAD

**Issue by YongJoonJoe** [yesodweb/yesod#905]
When I use `MForm Handler` to POST data, I encountered a CSRF protection error when using Firefox.

I've tested the program in two Linux servers those have almost same configurations.
The differences between those two servers are

1. Remote server is VPS(virtual private server), and the other server is placed in local network (not client machine).
1. Each `approot` are different. (of course)

I've usually tested the program with Google Chrome only. 
When I tested the program with Firefox(tested in OS X, Windows.vanilla option), the program returns a CSRF protection error from remote server side only. The other browsers (newest [Safari, Internet Explorer, Opera, etc.] with OS X and Windows) did not trouble with remote server.
However, with local network server, the problem does not occur.

1. With Firefox, the program returns a CSRF protection error from remote server only.
1. With the other browser, the problem does not occur.

I don't understand how `Yesod.Form` detect CSRF attack, but I don't think this case should be treated as a CSRF attack.

Questions:
* Is this `Yesod.Form` problem?
* Could this be Firefox issue?
* Do I need more informations to define this problem?

From the log, it shows nothing to remark
```
127.0.0.1 - - [10/Jan/2015:17:49:28 +0900] "GET /refer HTTP/1.1" 200 - "http://yongjoon.net/AHStudy01/refer" "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:34.0) Gecko/20100101 Firefox/34.0"
127.0.0.1 - - [10/Jan/2015:17:49:32 +0900] "POST /refer HTTP/1.1" 200 - "http://yongjoon.net/AHStudy01/refer" "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:34.0) Gecko/20100101 Firefox/34.0"
127.0.0.1 - - [10/Jan/2015:18:08:05 +0900] "GET /refer HTTP/1.1" 200 - "" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.10; rv:34.0) Gecko/20100101 Firefox/34.0"
127.0.0.1 - - [10/Jan/2015:18:08:08 +0900] "POST /refer HTTP/1.1" 200 - "http://yongjoon.net/AHStudy01/refer" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.10; rv:34.0) Gecko/20100101 Firefox/34.0"
```

Of course, 

1. those two programs are same, (I've also tested after copying a binary from local server to remote  server.) 
1. produced HTML codes are same without `approot`
1. and each server's configurations are same.

Here is the handler code.
```
getReferMessageR :: Handler Html
getReferMessageR = do
    (postSeparatedHashedMessageWidget, enctype) <- generateFormPost separatedHashedMessageForm
    defaultLayout $ do
        setTitle "getReferMessageR"
        $(widgetFile "header")
        $(widgetFile "getReferMessage")

postReferMessageR :: Handler Html
postReferMessageR = do
    ((result,postSeparatedHashedMessageWidget),enctype) <- runFormPost separatedHashedMessageForm
    case result of 
        FormSuccess referMessageSet -> do
            let postedMD5Base64 = shmMD5Base64 referMessageSet
            hsData <- runDB $ selectList [HashedSetHashMD5Base64 ==. postedMD5Base64] [Desc HashedSetTimeStamp]
            defaultLayout $ do
                setTitle "postReferMessageR"
                $(widgetFile "header")
                $(widgetFile "postReferMessage")
        FormFailure [e] -> defaultLayout $ do
                setTitle "Fail when refering message : FormFailure"
                let errorMessage = Just $ toHtml e
                $(widgetFile "header")
                $(widgetFile "hashedError")
        _ -> defaultLayout $ do
                setTitle "Fail when refering message : not FormSuccess anyway"
                let errorMessage = Just (T.pack "anyway, not FormSuccess")
                $(widgetFile "header")
                $(widgetFile "hashedError")
```

And here is the widget code
```
<form method=post action=@{ReferMessageR} enctype=#{enctype}>
  <table>
    ^{postSeparatedHashedMessageWidget}
  <button>Refer
```

The used libraries are
* wai 3.0.2.1
* wai-app-static 3.0.0.5
* wai-extra 3.0.3.2
* wai-logger 2.2.3
* warp 3.0.5
* yesod 1.4.1.3
* yesod-auth 1.4.1.2
* yesod-core 1.4.7.1
* yesod-form 1.4.3.1
* yesod-newsfeed 1.4.0.1
* yesod-persistent 1.4.0.2
* yesod-static 1.4.0.4

**Comment by paul-rouse** [comment]
Can you check that the session cookie is being set (in the case which doesn't work)?  In other words, in Firefox, do you see a cookie called _SESSION being set under the name of the remote server?  To be certain, if it is already there, I would delete it and check it is created again when you visit your site.

**Comment by YongJoonJoe** [comment]
I've checked it. The browser have cookie like `_SESSION` something like 
```
"Cookies: [(\"_SESSION\",\"VqguJ57TjHSepSg7cTdBJz1jf7HlaVJ7rZy4XJquDWtuyfXbh3/k2/CRcB2SiBddMzXkri8yg3MC5JqXkFABfc4JmcVf8jVlGZp0MOHW7wQml0DcG/KeGHsh0Yp9RCDxeN4II8FfWd4=\"),(\"__utma\",\"217168286.1791057447.1420888281.1420888281.1420888281.1\"),(\"__utmb\",\"217168286.1.10.1420888281\"),(\"__utmc\",\"217168286\"),(\"__utmz\",\"217168286.1420888281.1.1.utmcsr=(direct)|utmccn=(direct)|utmcmd=(none)\"),(\"__utmt\",\"1\")]"
```
from `getRequest` and browser's inspector.

**Comment by paul-rouse** [comment]
Hmm.  Just to check, can you see a hidden input field in the html of the form (using Firefox inspector), looking much like ```<input type="hidden" name="_token" value="170US6vz8P">```?  Do you see the *same* value in that hidden input field if you force-reload the page (as long as you don't wait too long)?

**Comment by YongJoonJoe** [comment]
Yes, your guess is right.
I get a different value in every refresh in very short time(<80ms) from the program running on the remote server.

I understand that this is the problem. 
But I don't understand why this happen in the remote server only.
Those two servers run the programs from the same code.

**Comment by paul-rouse** [comment]
I am not quite sure how you did it that quickly(!), but as long as you did it way which is supposed to send the session cookie back to the server, the test is still valid.

It looks as if something in the configuration of Firefox and/or the remote server is blocking the session cookie.  It is important that this cookie is returned to the Yesod server with the form submission, since a value encoded in it has to match the value in the hidden "_token" field.

**Comment by YongJoonJoe** [comment]
@paul-rouse  I'm sorry. I misunderstand your words. (<80ms) was response time.... Anyway I used shortcut, so I reload my page 5 times per seconds.

I tested this case, and I finally could reproduce this problem on any machine.

The reason was that refreshing token.

The server runs two Yesod program. 
* http://MAINSITE : Personal site (NOT target site. Have no `token` element in HTML code)
* http://MAINSITE/TESTSITE : Test site (TARGET site)
(`approot' setting also follows each)

These two programs runs independently. 
However, __when I request something to Personal site, the token of Test site is refreshed__. So `Yesod.Form` judge this __old__ token from `POST` as CSRF.


Of course, it usually does not happen. I reload the page in Test site for a times in very short time.
And it seems to be that there are no visitor in Personal site.
However, sometimes (I couldn't specify that situation), 
the favicon (or something other) is requested not to Test site, but to Personal site when I make a request to Test site. (But this is not occur always. I couldn't define this situation. But it seems to be that Firefox request a favicon not always.)
According to Personal site log, It shows that something like
```
127.0.0.1 - - [11/Jan/2015:13:42:01 +0900] "GET /favicon.ico HTTP/1.1" 200 1342 "" "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:34.0) Gecko/20100101 Firefox/34.0"
127.0.0.1 - - [11/Jan/2015:13:42:01 +0900] "GET /favicon.ico HTTP/1.1" 200 1342 "" "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:34.0) Gecko/20100101 Firefox/34.0"
127.0.0.1 - - [11/Jan/2015:13:42:01 +0900] "GET /favicon.ico HTTP/1.1" 200 1342 "" "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:34.0) Gecko/20100101 Firefox/34.0"
127.0.0.1 - - [11/Jan/2015:13:42:01 +0900] "GET /favicon.ico HTTP/1.1" 200 1342 "" "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:34.0) Gecko/20100101 Firefox/34.0"
127.0.0.1 - - [11/Jan/2015:13:42:01 +0900] "GET /favicon.ico HTTP/1.1" 200 1342 "" "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:34.0) Gecko/20100101 Firefox/34.0"
127.0.0.1 - - [11/Jan/2015:13:42:11 +0900] "GET /favicon.ico HTTP/1.1" 200 1342 "" "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:34.0) Gecko/20100101 Firefox/34.0"
127.0.0.1 - - [11/Jan/2015:13:42:11 +0900] "GET /favicon.ico HTTP/1.1" 200 1342 "" "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:34.0) Gecko/20100101 Firefox/34.0"
127.0.0.1 - - [11/Jan/2015:13:42:17 +0900] "GET /favicon.ico HTTP/1.1" 200 1342 "" "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:34.0) Gecko/20100101 Firefox/34.0"
127.0.0.1 - - [11/Jan/2015:13:42:17 +0900] "GET /favicon.ico HTTP/1.1" 200 1342 "" "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:34.0) Gecko/20100101 Firefox/34.0"
127.0.0.1 - - [11/Jan/2015:13:42:17 +0900] "GET /favicon.ico HTTP/1.1" 200 1342 "" "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:34.0) Gecko/20100101 Firefox/34.0"
127.0.0.1 - - [11/Jan/2015:13:42:34 +0900] "GET /favicon.ico HTTP/1.1" 200 1342 "" "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:34.0) Gecko/20100101 Firefox/34.0"
127.0.0.1 - - [11/Jan/2015:13:42:34 +0900] "GET /favicon.ico HTTP/1.1" 200 1342 "" "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:34.0) Gecko/20100101 Firefox/34.0"
127.0.0.1 - - [11/Jan/2015:13:42:35 +0900] "GET /favicon.ico HTTP/1.1" 200 1342 "" "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:34.0) Gecko/20100101 Firefox/34.0"
127.0.0.1 - - [11/Jan/2015:13:42:35 +0900] "GET /favicon.ico HTTP/1.1" 200 1342 "" "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:34.0) Gecko/20100101 Firefox/34.0"
```

My assumtion is as follow,

1. I `GET` a page which have input form ("_token" = A) from Test site.
1. Firefox request a favicon (or something other) from Personal site.
1. Because of a request to Personal site, the token of Test site is refreshed. (Why?)
1. I 'POST` data with 'old token', and Test site judge my data is not vaild one.

I assume that I encountered problem with Firefox only because browsers' the request order is different each other.

Question:

1. What happens with Personal site and Test site's token? (may Yesod side's problem?)

These two programs are independent. Thier working directory is different.
The `approot` have a intersection(MAINSITE part), but different. 
But why the token is refreshed when Personal site got request?
There could be something other reasons. However, when I make a request something(`GET`, `POST`, etc...) to Personal site, the token of Test site is refreshed when I reload the page of Test site.

Is there any problem with sharing prefix of `approot` even there are independent program?

2. Why Firefox request favicon to Personal sites?

The problem about Request something to other site may hard to solve.
I used scaffolding, so there are `favicon.ico` in Test site.
I'm not sure that how a browser find a favicon, but I can guess that Firefox find a favicon from .
However, sometimes, test with Google Chrome shows that there are new token when I reloaded. But it works with no problem.

It seems to be that Firefox has different request order or different request path about `favicon.ico`, so there is only one problem case.

**Comment by snoyberg** [comment]
This looks like an issue that's come up before:

http://comments.gmane.org/gmane.comp.lang.haskell.yesod/2580

If you change your implementation of [`makeSessionBackend`](http://www.stackage.org/haddock/lts-1.0/yesod-core-1.4.7.1/Yesod-Core.html#v:makeSessionBackend) you can control the name of the cookie that's used for storing the session.

**Comment by paul-rouse** [comment]
Or use a subdomain for one of the sites, if that is an option you have - for example use ```http://test.MAINSITE/...``` for the test site.

**Comment by YongJoonJoe** [comment]
I understand that this was known problem. Thanks for your advice.
