### ISSUE TITLE
Submit buttons does not works when using Internet Explorer 11 in some environment

### ISSUE THREAD

**Issue by YongJoonJoe** [yesodweb/yesod#906]
On the contrary to #905, a submit button does not work when using Internet Explorer 11 in some environment. I think this problem is different issue with #905.

I run the program in two Linux servers(remote server and local network server). When I tested in various browsers (Google Chrome, Firefox, Safari, Internet Explorer 11, etc. on OS X, Windows).
However, the page from local network server not react with Internet Explorer 11, 

Conditions
1. The produced HTML code are same. (except `approot`)
1. Two server's configurations are same.

Situation
1. With the other browsers does not have any problem (except #905)
1. With Internet Explorer 11, after pushing submit button reacts nothing with local network server.

According to log file, there are no POST request has sent to the server, GET request only when using IE 11.

Question
1. Is this `Yesod.Form` issue?
1. Or is this IE issue?

The codes below is same as #905.

Here is the handler code.
```
getReferMessageR :: Handler Html
getReferMessageR = do
    (postSeparatedHashedMessageWidget, enctype) <- generateFormPost separatedHashedMessageForm
    defaultLayout $ do
        setTitle "getReferMessageR"
        $(widgetFile "header")
        $(widgetFile "getReferMessage")

postReferMessageR :: Handler Html
postReferMessageR = do
    ((result,postSeparatedHashedMessageWidget),enctype) <- runFormPost separatedHashedMessageForm
    case result of 
        FormSuccess referMessageSet -> do
            let postedMD5Base64 = shmMD5Base64 referMessageSet
            hsData <- runDB $ selectList [HashedSetHashMD5Base64 ==. postedMD5Base64] [Desc HashedSetTimeStamp]
            defaultLayout $ do
                setTitle "postReferMessageR"
                $(widgetFile "header")
                $(widgetFile "postReferMessage")
        FormFailure [e] -> defaultLayout $ do
                setTitle "Fail when refering message : FormFailure"
                let errorMessage = Just $ toHtml e
                $(widgetFile "header")
                $(widgetFile "hashedError")
        _ -> defaultLayout $ do
                setTitle "Fail when refering message : not FormSuccess anyway"
                let errorMessage = Just (T.pack "anyway, not FormSuccess")
                $(widgetFile "header")
                $(widgetFile "hashedError")
```

And here is the widget code
```
<form method=post action=@{ReferMessageR} enctype=#{enctype}>
  <table>
    ^{postSeparatedHashedMessageWidget}
  <button>Refer
```

The used libraries are
* wai 3.0.2.1
* wai-app-static 3.0.0.5
* wai-extra 3.0.3.2
* wai-logger 2.2.3
* warp 3.0.5
* yesod 1.4.1.3
* yesod-auth 1.4.1.2
* yesod-core 1.4.7.1
* yesod-form 1.4.3.1
* yesod-newsfeed 1.4.0.1
* yesod-persistent 1.4.0.2
* yesod-static 1.4.0.4

**Comment by snoyberg** [comment]
I can't imagine how this could be a Yesod issue. Perhaps you have some Javascript libraries which prevent the submission from going through? Have you checked your JS console to see if there are any error messages?

**Comment by andrewthad** [comment]
@snoyberg Can this be closed? There's no way this could be caused by Yesod and it's half a year old at this point.
