### ISSUE TITLE
New scaffolding env-var config doesn't work for tests.

### ISSUE THREAD

**Issue by bitemyapp** [yesodweb/yesod#908]
http://www.yesodweb.com/blog/2014/12/yesods-new-scaffolding

https://github.com/yesodweb/yesod/wiki/Configuration

Whether I export or set the environment variables for a single run, whether I run my tests via `cabal test` or build the test binary and then run that with the environment variables, I cannot get the tests to respect the env-vars for my configuration.

I need this to work because I need to override what database the CI for my Yesod project uses.

I can make it connect to a different database if I change the hard-coded values in the config files, but I cannot via environment variables.

**Comment by bitemyapp** [comment]
if I run `PGDATABASE="BLAHBLAHBLAH" cabal test` and add:

```
print =<< getEnv "PGDATABASE"
```

to makeFoundation

I get the following in my test results:

```
robots.txt
"BLAHBLAHBLAH"
  gives a 200
"BLAHBLAHBLAH"
  has correct User-agent
favicon.ico
"BLAHBLAHBLAH"
  gives a 200
```

But the tests pass despite a spurious database name that the process can see in the environment variables. The config isn't loading the env vars for some reason.

**Comment by bitemyapp** [comment]
User error:

I was reusing code from somewhere or another, so my testSettings was:

```
testSettings :: FromJSON settings => IO settings
testSettings = loadAppSettings
               ["config/test-settings.yml", "config/settings.yml"]
               [] ignoreEnv
```

But should've been:

```
testSettings :: FromJSON settings => IO settings
testSettings = loadAppSettings
               ["config/test-settings.yml", "config/settings.yml"]
               [] useEnv
```

Blah. Works now.

**Comment by MaxGabriel** [comment]
I notice that the [test code in the scaffolding](https://github.com/yesodweb/yesod-scaffold/blob/4b736274405b04ff19742867db813ba7f032d8f8/test/TestImport.hs#L26) ignores environment variables by default, which may have been where you got that code from.

@snoyberg Is there a reason for that btw?

**Comment by bitemyapp** [comment]
@MaxGabriel yeah that was...unnecessarily painful. It'd be nice if we could change the scaffold for that.

**Comment by gregwebs** [comment]
closed in favor of #56

**Comment by bitemyapp** [comment]
@gregwebs what does this have to do with #56 ?

**Comment by snoyberg** [comment]
I've commented over on yesodweb/yesod-scaffold#56. tl;dr: I think we have the right decision right now.
