### ISSUE TITLE
Installation issues

### ISSUE THREAD

**Issue by amadeusxnet** [yesodweb/yesod#912]
Hi!

I have a problem while trying to install Yesod on my Ubuntu machine.
I've done "cabal update && cabal install yesod-platform".

After I hit the "yesod init" the logs tells me:
"""nemo@amx-pc:~/haskell$ cd tester && cabal install -j --enable-tests --max-backjumps=-1 --reorder-goals && yesod devel
Resolving dependencies...
In order, the following would be installed:
bytestring-builder-0.10.4.0.1 (new package)
clientsession-0.9.1.1 (new version)
hspec-core-2.1.2 (new package)
mwc-random-0.13.3.0 (new package)
streaming-commons-0.1.9.1 +use-bytestring-builder (new version)
conduit-extra-1.1.6.2 (new version)
cryptohash-conduit-0.1.1 (reinstall) changes: conduit-1.1.7 -> 1.2.3,
conduit-extra-1.1.3 -> 1.1.6.2
http-client-0.4.6.2 -network-uri (reinstall) changes: publicsuffixlist-0.1
added, streaming-commons-0.1.4.1 -> 0.1.9.1
http-client-tls-0.2.2 (reinstall) changes: http-client-0.3.7.1 -> 0.4.6.2
http-conduit-2.1.5 (reinstall) changes: http-client-tls-0.2.2 added
monad-logger-0.3.11.1 (new version)
persistent-2.1.1.4 (new version)
persistent-sqlite-2.1.1.2 (new package)
persistent-template-2.1.0.1 (new version)
wai-logger-2.2.3 (reinstall) changes: unix-time-0.3.4 added
wai-extra-3.0.4.1 (reinstall) changes: ansi-terminal-0.6.2.1 -> 0.6.1.1,
streaming-commons-0.1.4.1 -> 0.1.9.1
warp-3.0.5.2 (reinstall) changes: streaming-commons-0.1.4.1 -> 0.1.9.1
wai-app-static-3.0.0.6 (new version)
xml-conduit-1.2.3.1 (new version)
tagstream-conduit-0.5.5.3 (new version)
authenticate-1.3.2.11 (new version)
html-conduit-1.1.1.1 (new version)
yaml-0.8.10.1 (reinstall) changes: aeson-0.6.2.1 -> 0.7.0.4,
scientific-0.3.3.2 -> 0.2.0.2
yesod-core-1.4.7.2 (new version)
yesod-persistent-1.4.0.2 (new version)
yesod-form-1.4.3.1 (new version)
yesod-auth-1.4.1.3 (new version)
yesod-1.4.1.3 (new version)
yesod-static-1.4.0.4 (new version)
yesod-test-1.4.2.2 (new version)
tester-0.0.0 *test (new package)
cabal: The following packages are likely to be broken by the reinstalls:
yesod-static-1.2.4
yesod-platform-1.2.13.3
wai-app-static-3.0.0
http-conduit-2.1.4
yesod-auth-1.3.4.1
yesod-auth-hashdb-1.3.0.1
yesod-1.2.6.1
authenticate-1.3.2.10
Use --force-reinstalls if you want to install anyway.
nemo@amx-pc:~/haskell/tester$"""

I want this to work on all my machines. But this problem is giving the same result on every debian/ubuntu versions I got.

I wanted to learn Haskell from being a PHP developer. In the middle of the summer I got Yesod working on Windows 8.1
But I'm only running Linux from now on so.

If anyone can help me, please help me!

´Edit: I've Googled around, but nada´

**Comment by gregwebs** [comment]
Hi @amadeusxnet. AFAIK yesod-platform is dead. Can you try the [latest instructions](http://www.yesodweb.com/page/quickstart)?

**Comment by amadeusxnet** [comment]
Hi gregwebs! Thank you for the reply!
Thanks to that link I've managed to get it more working. But I'll wait till it's done :)
Thank you once again!

**Comment by amadeusxnet** [comment]
I get the following:
cabal: At least the following dependencies are missing:
aeson >=0.6 && <0.9,
fast-logger ==2.2.*,
hjsmin ==0.1.*,
http-conduit ==2.1.*,
monad-control ==0.3.*,
monad-logger ==0.3.*,
persistent >=2.0 && <2.2,
persistent-sqlite >=2.0 && <2.2,
persistent-template >=2.0 && <2.2,
shakespeare ==2.0.*,
wai-extra ==3.0.*,
wai-logger ==2.2.*,
warp ==3.0.*,
yaml ==0.8.*,
yesod >=1.4.0 && <1.5,
yesod-auth >=1.4.0 && <1.5,
yesod-core >=1.4.0 && <1.5,
yesod-form >=1.4.0 && <1.5,
yesod-static >=1.4.0 && <1.5

**Comment by snoyberg** [comment]
What command did you run? You probably need to run cabal install

**Comment by amadeusxnet** [comment]
Hi snoyberg! I ran "cabal update && cabal install alex happy yesod-bin yesod init --bare && cabal sandbox init && cabal install --run-tests && yesod devel" And still that error came up!

**Comment by snoyberg** [comment]
Can you try running

    cabal install

If that succeeds, then try running

    yesod devel

It's unclear where the error is coming from.

**Comment by amadeusxnet** [comment]
Cabal install:
nemo@amx-pc:~/haskell/tester/tester$ cabal install
Resolving dependencies...
cabal: Could not resolve dependencies:
trying: ReadArgs-1.2.2/installed-2c1... (user goal)
next goal: text (dependency of ReadArgs-1.2.2/installed-2c1...)
rejecting: text-0.11.3.1/installed-e38... (global constraint requires
==1.2.0.4)
rejecting: text-1.2.0.4 (conflict: ReadArgs =>
text==0.11.3.1/installed-e38...)
rejecting: text-1.2.0.3, 1.2.0.2, 1.2.0.0, 1.1.1.3, 1.1.1.2, 1.1.1.1, 1.1.1.0,
1.1.0.1, 1.1.0.0, 1.0.0.1, 1.0.0.0, 0.11.3.1, 0.11.3.0, 0.11.2.3, 0.11.2.2,
0.11.2.1, 0.11.2.0, 0.11.1.13, 0.11.1.12, 0.11.1.11, 0.11.1.10, 0.11.1.9,
0.11.1.8, 0.11.1.7, 0.11.1.6, 0.11.1.5, 0.11.1.3, 0.11.1.2, 0.11.1.1,
0.11.1.0, 0.11.0.8, 0.11.0.7, 0.11.0.6, 0.11.0.5, 0.11.0.4, 0.11.0.3,
0.11.0.2, 0.11.0.1, 0.11.0.0, 0.10.0.2, 0.10.0.1, 0.10.0.0, 0.9.1.0, 0.9.0.1,
0.9.0.0, 0.8.1.0, 0.8.0.0, 0.7.2.1, 0.7.1.0, 0.7.0.1, 0.7, 0.6, 0.5, 0.4, 0.3,
0.2, 0.1 (global constraint requires ==1.2.0.4)
Dependency tree exhaustively searched.

Note: when using a sandbox, all packages are required to have consistent
dependencies. Try reinstalling/unregistering the offending packages or
recreating the sandbox.
nemo@amx-pc:~/haskell/tester/tester$ 

And yesod devel:
nemo@amx-pc:~/haskell/tester/tester$ yesod devel
Yesod devel server. Press ENTER to quit
Resolving dependencies...
Configuring tester-0.0.0...
cabal: At least the following dependencies are missing:
aeson >=0.6 && <0.9,
fast-logger ==2.2.*,
hjsmin ==0.1.*,
http-conduit ==2.1.*,
monad-control ==0.3.*,
monad-logger ==0.3.*,
persistent >=2.0 && <2.2,
persistent-sqlite >=2.0 && <2.2,
persistent-template >=2.0 && <2.2,
shakespeare ==2.0.*,
wai-extra ==3.0.*,
wai-logger ==2.2.*,
warp ==3.0.*,
yaml ==0.8.*,
yesod >=1.4.0 && <1.5,
yesod-auth >=1.4.0 && <1.5,
yesod-core >=1.4.0 && <1.5,
yesod-form >=1.4.0 && <1.5,
yesod-static >=1.4.0 && <1.5

Can it have with the old yesod-platform and yesod-bin to do with?

**Comment by geraldus** [comment]
Your problem is `ReadArgs` package, your current version depends on very ourfated `text-0.11.3.1`, while yesod wants `1.2.0.4`

**Comment by amadeusxnet** [comment]
I'm still getting those "Could not resolve dependencies"

Can anyone list those package I need with cabal install?
like cabal install ReadArgs and so on.

**Comment by snoyberg** [comment]
You should delete the old sandbox, and then start over with a fresh sandbox. Try running

    cabal sandbox delete
    cabal sandbox init
    cabal install

**Comment by amadeusxnet** [comment]
I've tried re-running the install tutorial.
And the last thing it shouted about was the streaming-commons. And the newest package wont install so I Googled for a older one. So lets see what happens next :)
