### ISSUE TITLE
Yesod executable on Windows?

### ISSUE THREAD

**Issue by m-blazejczyk** [yesodweb/yesod#913]
Hi,

I know this is probably a very dumb question but I'm unable to find the yesod executable (the one used to create scaffolded sites) on Windows...  I searched my entire hard drive, and I cannot find anything.  My yesod installation was successful.

Thanks in advance,
Michal

**Comment by gregwebs** [comment]
what packages did you install? Do you have yesod-bin?

**Comment by m-blazejczyk** [comment]
I only installed yesod.  Let me try installing yesod-bin...

Yes, that was it!

Told you it was a dumb question  :)

Thank you so much!

Michal
