### ISSUE TITLE
yesod-test functions/documentation still use the term "nonce"

### ISSUE THREAD

**Issue by MaxGabriel** [yesodweb/yesod#914]
After discussion in #214, yesod-form started using the term "token" instead of "nonce" (implemented [in this commit](https://github.com/yesodweb/yesod/commit/5762272f8b6ab49e37e9cae73378047d35f563ea)). 

However, yesod-test still has [functions](https://github.com/yesodweb/yesod/blob/2fb7cccf15c04cef78158f792cf1a569bd87ceec/yesod-test/Yesod/Test.hs#L489-L501) and [documentation](https://github.com/yesodweb/yesod/blob/2fb7cccf15c04cef78158f792cf1a569bd87ceec/yesod-test/Yesod/Test.hs#L21) using that word. 

Proposal: 
* Deprecate `addNonce` and `addNonce_`; add new functions called something like `addToken` or `addCsrfToken`. Implemented in #917
* Change documentation/comments in yesod-test to use the term "token". Implemented in #917
* Update the scaffolding to use the new function names (they [currently use the `addNonce` function](https://github.com/yesodweb/yesod-scaffold/blob/e4b2fb01eec21c60ed07e3e2a84a0f823341d742/test/Handler/HomeSpec.hs)).
* Make a PR to remove the deprecated functions in a future major release of Yesod.

Full search for "nonce" in this repo: https://github.com/yesodweb/yesod/search?utf8=%E2%9C%93&q=nonce

**Comment by gregwebs** [comment]
sounds good to me. The scaffolding will need to require the newer version of yesod-test.
