### ISSUE TITLE
yesod-test README code doesn't compile

### ISSUE THREAD

**Issue by MaxGabriel** [yesodweb/yesod#920]
The [README example](https://github.com/yesodweb/yesod/blob/5d431fbdb542084d1a77f9c4df786d32cfe79721/yesod-test/README.md) in yesod-test, afaict, doesn't typecheck.

Based on testing it, the `post url $ do` style that's used several times doesn't work, perhaps it's meant to be `request $ do`?

```
post "url/to/post/to" $ do
    addToken -- Add the CSRF _token field with the currently shown value
```

Additionally, no `byName` function exists, that's probably meant to be `addPostParam`:

```
-- And of course you can add any field if you know it's name
byName "answer" "42"
```

**Comment by snoyberg** [comment]
Looks like that would be an improvement. Would you be able to send a PR?

**Comment by MaxGabriel** [comment]
Yeah I can work on that
