### ISSUE TITLE
Add handler should check the line it is writing to is empty

### ISSUE THREAD

**Issue by ianbamforth** [yesodweb/yesod#921]
With a routes file with no trailing newline at the end of the file, running add-handler appends the new route to the old one, resulting in invalid code.  Should be simple to insert the newline if required.

**Comment by MaxGabriel** [comment]
I can replicate this. For this to happen, there also has to be no newline at the end of the routes file.

**Comment by MaxGabriel** [comment]
Actually the "routes file with no trailing slash" I'm not sure about.

**Comment by ianbamforth** [comment]
I have no idea where the word slash came from, I meant to write "newline".  Sorry!
