### ISSUE TITLE
ClassyPrelude, Yesod Scaffolding, Semigroup

### ISSUE THREAD

**Issue by andrewthad** [yesodweb/yesod#924]
The variant of the `<>` operator that we get in the scaffolded yesod site has its constraint as `Semigroup`, not `Monoid`. I assume that this comes from ClassyPrelude. So, when I try to concatenate two `Widget`s like this `w1 <> w2`, I get this type error:

    No instance for (Semigroup Widget) arising from a use of ‘<>’

Since I'm sure that Yesod at least transitively depends on the semigroups package, could we make that explicit and then just add the instance? Alternatively (and I consider this a better option), classy prelude could just export the monoidal version of `<>` instead.

**Comment by MaxGabriel** [comment]
> Alternatively (and I consider this a better option), classy prelude could just export the monoidal version of `<>` instead.

Classy-prelude exports `++` as the monoidal append.

**Comment by MaxGabriel** [comment]
Pretty sure that a Semigroup instance is a reasonable request, though. The `yesod` package depends on semigroups directly, and yesod-core (where the monoid instance for Widget is defined) depends on it transitively.

**Comment by snoyberg** [comment]
I agree, we should definitely add such an instance. This is good low
hanging fruit for someone looking to make their first yesod contribution.

**Comment by gregwebs** [comment]
is #928 what you are looking for?

**Comment by snoyberg** [comment]
Lgtm.
