### ISSUE TITLE
SpecialResponse referenced in docs is outdated

### ISSUE THREAD

**Issue by MaxGabriel** [yesodweb/yesod#925]
[The haddocks for `ErrorResponse`](https://github.com/yesodweb/yesod/blob/df304d6393a419b308f3f9cde6eb791e6b4a5415/yesod-core/Yesod/Core/Types.hs#L294-L295) mention a type called `SpecialResponse`, but I can't find it anywhere in the source code or on fpcomplete's hoogle. I'm pretty sure its an outdated reference to something like this: http://hackage.haskell.org/package/yesod-core-0.8.3.2/docs/Yesod-Handler.html#g:4

**Comment by snoyberg** [comment]
Good catch, that's definitely out-of-date.
