### ISSUE TITLE
yesod-bin doesn't link on Windows 8.1

### ISSUE THREAD

**Issue by darthdeus** [yesodweb/yesod#926]
When installing `yesod-bin` on my Windows machine, I'll get the following error during the linking of `yesod-bin`.

```
C:\Program Files\Haskell Platform\2014.2.0.0\lib/rts-1.0/libHSrts_thr.a(PrimOps.thr_o):fake:(.text+0x70f): undefined reference to `EnterCriticalSection@8'
C:\Program Files\Haskell Platform\2014.2.0.0\lib/rts-1.0/libHSrts_thr.a(PrimOps.thr_o):fake:(.text+0x746): undefined reference to `LeaveCriticalSection@8'
```

Here's a gist of the whole log https://gist.github.com/darthdeus/16c18a73c5bed57ef168

At first I was getting build errors in `unix-compat` about missing `msvcrt` library, which probably isn't related, but I'm mentioning it just to be sure (I fixed this installing the vcredist C++ Redistributable package from Microsoft.)

I've tried googling the critical section error, but couldn't find anything at all. I'm using a fresh install of Haskell Platform 2014.2.0.0.

**Comment by gregwebs** [comment]
have you tried re-installing?

**Comment by snoyberg** [comment]
It would also be interesting to hear if this problem exists with minghc,
especially the 32 bit version.

**Comment by darthdeus** [comment]
@gregwebs I did this on a clean install of Haskell Platform, if you mean by reinstalling that.

@snoyberg I tried uninstalling Haskell Platform, removed AppData\Roaming\cabal, installed minghc 32bit, but now `cabal install` fails for any package with the same error message, for example

```
> cabal install happy
Resolving dependencies...
Downloading transformers-0.4.2.0...
Configuring transformers-0.4.2.0...
Failed to install transformers-0.4.2.0
Build log ( C:\Users\Jakub\AppData\Roaming\cabal\logs\transformers-0.4.2.0.log ):
Configuring transformers-0.4.2.0...
setup-Simple-Cabal-1.18.1.3-i386-windows-ghc-7.8.3.exe: does not exist
cabal.exe: Error: some packages failed to install:
happy-1.19.5 depends on transformers-0.4.2.0 which failed to install.
mtl-2.2.1 depends on transformers-0.4.2.0 which failed to install.
transformers-0.4.2.0 failed during the configure step. The exception was:
ExitFailure 1
```

I'm not sure if I did something wrong, though this probably belongs as an issue to minghc? I do see `ghc` in my PATH, and it is even the correct version.

**Comment by darthdeus** [comment]
Sorry for the confusion with the last post, the problem was that I had installed [Strawberry Perl](http://strawberryperl.com/), which as its own `ld`, and it was earlier in my `PATH`, so I only discovered this after invoking cabal with `-v3`.

But the good news is that I managed to successfully build `yesod-bin` with minghc 32 bit version :) So I guess this issue can be closed?

**Comment by snoyberg** [comment]
Thanks for checking. Is recommend opening up a GHC issue about this still, since it's problematic that 64 bit GHC can't compile yesod-bin.
