### ISSUE TITLE
Serving uploaded files from the static subsite

### ISSUE THREAD

**Issue by m-blazejczyk** [yesodweb/yesod#931]
Hi,

I want to use Yesod to build a web site that is partially a CMS, i.e. it allows for uploading media and content (images, documents).  How can I later return such content?  Can it be done via the static site?  Or will I have to set this up at the Apache / nginx level before the request ever gets to Yesod?

All the best,
Michal

**Comment by gregwebs** [comment]
You don't need Apache / nginx. You cannot have static route types for files that are dynamically uploaded but you can still serve the files. Can you ask this question on the yesodweb google group?
