### ISSUE TITLE
Better way to do PathMultiPiece instances

### ISSUE THREAD

**Issue by andrewthad** [yesodweb/yesod#932]
In the `path-pieces` package, we see three instances of `PathMultiPiece`:

    PathMultiPiece [String]	 
    PathMultiPiece [Text]	 
    PathMultiPiece [Text]

Why don't we just do this instead:

    instance PathPiece a => PathMultiPiece [a] where
        fromPathMultiPiece = mapM fromPathPiece  -- The monad here is Maybe
        toPathMultiPiece = map toPathPiece

Then we get the previous three for free, and we get several dozen more (like `[Int]`), and we don't need FlexibleContexts (or whatever that flexible something extension is, not that I really care about extension use). I'm using this in a project right now and it seems to work fine.

**Comment by snoyberg** [comment]
The downside would be that there wouldn't be utmost flexibility around list instances... but I'm having a hard time thinking of an example where this wouldn't be the instance that you'd want. Then the only other problem is breaking backwards compatibility, but I highly doubt this will cause anyone real trouble. Still, we should consult the mailing list first to see if anyone has custom instances that would be hurt by this. Would you be able to send such an email?

**Comment by andrewthad** [comment]
I have posted on the mailing list.

**Comment by snoyberg** [comment]
Thanks. Just to repeat what I said there: let's give this 1 week and, if we
don't hear anything negative, we'll move ahead.

**Comment by andrewthad** [comment]
Sounds good

**Comment by andrewthad** [comment]
Link to the mailing list post: https://groups.google.com/forum/#!topic/yesodweb/w9wnDdMv83k

**Comment by snoyberg** [comment]
Alright, looks like no one objects, so I've pushed a commit that makes this change:

https://github.com/yesodweb/path-pieces/commit/102e230e6441dfc35f22daaad59fff797cf6b66f

Can you look it over before I release?

**Comment by andrewthad** [comment]
Looks good to me.

**Comment by snoyberg** [comment]
Cool, this is now on Hackage as 0.2.0.
