### ISSUE TITLE
build fail

### ISSUE THREAD

**Issue by tancorko** [yesodweb/yesod#938]
Try to build empty project
yesod init
cabal install
Build failure:

Settings/StaticFiles.hs:1:1:
    Exception when trying to run compile-time code:
      when expecting a String, encountered Number instead
    Code: staticFiles (appStaticDir compileTimeAppSettings)

Do you have any idea?

**Comment by MaxGabriel** [comment]
`compileTimeAppSettings` is trying to create an [`AppSettings`](https://github.com/yesodweb/yesod-scaffold/blob/f41ee288073105ac8e5a5bbce5cceb5867888919/Settings.hs#L24). It sounds like its getting a number for a certain setting that expects a string. (All this code is from the Settings.hs file in the scaffolding, btw)

I can't replicate this using yesod-bin-1.4.3.7 with the SQLite scaffolding. Have you made any changes to a config file that might cause this? If not, can you specify which scaffolding you're using?

**Comment by MaxGabriel** [comment]
Another theory is that an environment variable is being used for a setting. It seems like that can cause this issue:

```
Max@maximilians-mbp ~/D/N/t/OneFourThreeSeven> yesod devel
Yesod devel server. Press ENTER to quit
Resolving dependencies...
Configuring OneFourThreeSeven-0.0.0...
Rebuilding application... (using cabal)
Starting development server...
Starting devel application
Devel application launched: http://localhost:3000
```

```
Max@maximilians-mbp ~/D/N/t/OneFourThreeSeven> env STATIC_DIR=4000 yesod devel
Yesod devel server. Press ENTER to quit
Resolving dependencies...
Configuring OneFourThreeSeven-0.0.0...
Rebuilding application... (using cabal)
Starting development server...
Starting devel application
devel.hs: Could not convert to AppSettings: when expecting a String, encountered Number instead
Exit code: ExitFailure 1
```

Could you do print your environment variables to and compare them to the ones in `config/settings.yml`? (Use `printenv` in bash to print your environment variables).

**Comment by MaxGabriel** [comment]
@snoyberg I haven't looked into this much because I just got to work, but is it a bug that when a string value like `STATIC_DIR` looks like a number, it gets parsed as a number? Since you could theoretically have a directory named e.g. "123".

**Comment by snoyberg** [comment]
It's a known issue, but we're unlikely to solve it here.

**Comment by tancorko** [comment]
yesod-bin-1.4.3.7
I used postgres scaffolding, and changed settings.yml only:
`static-dir:     "_env:STATIC_DIR:static"
host:           "_env:HOST:*4" # any IPv4 host
port:           "_env:PORT:3000"
approot:        "_env:APPROOT:http://localhost:3000"
ip-from-header: "_env:IP_FROM_HEADER:false"
database:
  user:     "_env:PGUSER:ys"
  password: "_env:PGPASS:123"
  host:     "_env:PGHOST:localhost"
  port:     "_env:PGPORT:5432"
  database: "_env:PGDATABASE:ys"
  poolsize: "_env:PGPOOLSIZE:10"`

printenv - there is no STATIC_DIR, and when I set it manually - result the same.

**Comment by MaxGabriel** [comment]
Ok, the issue is that the password "123" is being treated as a number instead of a string. I haven't looked into the settings related code enough to know the details on why, though. As a workaround, you could change your postgres password to something else.

**Comment by tancorko** [comment]
It works, lol. Thanks a lot.

**Comment by MaxGabriel** [comment]
If anyone else runs into this, you can also remove the `_env:ENVNAME:` part of the setting to workaround this (e.g. just do `password: "123"` in settings.yml).
