### ISSUE TITLE
Interested in slight styling improvements for "Welcome To Yesod!" page?

### ISSUE THREAD

**Issue by r00k** [yesodweb/yesod#943]
Hi there!

I'm not much of a designer, but there are a few things about the default "Welcome To Yesod!" page that seemed like they could be improved.

Would you be interested in a pull that made a few style tweaks?

For example...

Before:
![before](https://cloud.githubusercontent.com/assets/46677/6418500/88b4f8ec-be83-11e4-96fc-8b4bd05309a6.png)

After:
![after](https://cloud.githubusercontent.com/assets/46677/6418507/9380e218-be83-11e4-9efb-eaf6a1967e6b.png)

**Comment by MaxGabriel** [comment]
Your version is way better :+1:

**Comment by creichert** [comment]
I think it looks great. Looking forward to the PR.

**Comment by creichert** [comment]
Fixed in the scaffold now, thanks!
