### ISSUE TITLE
Is there a way how to do partial template in hamlet?

### ISSUE THREAD

**Issue by reneklacan** [yesodweb/yesod#946]
Hi, maybe this will be very stupid question but I was not able to find solution anywhere.

Is there any way how I can include one hamlet inside another hamlet.

For example how you modify this code

```haskell
footer = [hamlet|
<footer>
    Footer
|]

main = putStrLn $ renderHtml $ [hamlet|
<body>
    ^{footer}
|] render
```

to achieve that footer would be taken from `statis/footer.hamlet` file?

Thanks

**Comment by zudov** [comment]
http://stackoverflow.com/questions/10791591/how-can-i-include-an-hamletfile-inside-another-using-widgetfile

**Comment by zudov** [comment]
See, in your example you define hamlet template `footer` literally in the source, instead you could read it from the file:

```haskell
footer = $(hamletFile "statis/footer.hamlet")
```

**Comment by zudov** [comment]
Also, I think that stackoverflow is a better place for such questions, the core yesod developers usually provide good responses there.

**Comment by reneklacan** [comment]
Thank you for fast reply.

I have hoped for quicker answer here, that's why I tried it here

both of examples you provided are giving me same error:
```
    No instance for (ToWidget App (t0 -> m0 ()))
      arising from a use of ‘toWidget’
    The type variables ‘t0’, ‘m0’ are ambiguous
    Note: there is a potential instance available:
      instance render ~ Yesod.Core.Types.RY site =>
               ToWidget site (render -> Html)
        -- Defined in ‘Yesod.Core.Widget’
    In the second argument of ‘(GHC.Base..)’, namely ‘toWidget’
    In the expression: asWidgetT GHC.Base.. toWidget
    In a stmt of a 'do' block: (asWidgetT GHC.Base.. toWidget) hovno
```

Sorry, I am fairly new to Haskell

**Comment by reneklacan** [comment]
Ok, so type signature `footer :: (MonadThrow m, MonadBaseControl IO m, MonadIO m) => WidgetT site m ()` fixed that, I just not able to find prettier form of this signature.

**Comment by zudov** [comment]
Hmm. It seems that you've done something different from your very first example. The scary error message says that compiler can't figure out how to convert something to widget, but in the first example there was nothing about widgets.

Here is my code which is based on your first example but reads hamlet template from the file

```haskell
{-# LANGUAGE QuasiQuotes #-}
{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE TemplateHaskell #-}
import Text.Hamlet (HtmlUrl, hamlet, hamletFile)
import Text.Blaze.Html.Renderer.String (renderHtml)
import Text.Blaze (Markup)
import Data.Text (Text)

render = undefined

footer = $(hamletFile "footer.hamlet")

main :: IO ()
main = putStrLn $ renderHtml $ [hamlet|
<body>
    <p>This is my page.
    ^{footer}
|] render
```

**Comment by reneklacan** [comment]
I have isolated what caused mentioned error, it was fact that my `footer.hamlet` was empty file. I just did `touch templates/footer.hamlet` and started chasing solution without realizing that there needs to me some content.

After doing `echo "<h1> Test" > templates/footer.slim` error disappread, it just complained about missing signature.

**Comment by zudov** [comment]
If you want to simplify that type signature:
```haskell
footer :: (MonadThrow m, MonadBaseControl IO m, MonadIO m) => WidgetT site m ()
```
I guess the simplest thing to go is:
```haskell
footer :: WidgetT site IO ()
```

**Comment by zudov** [comment]
Weird, I certainly wouldn't expect a type error because of empty file. And in fact, the code above works with empty file.

**Comment by reneklacan** [comment]
Actually, this was the right type signature for me:

```haskell
footer :: WidgetT App IO ()
footer = $(widgetFile "navbar")
```

With `IO` I was getting
```
    Couldn't match type ‘site’ with ‘App’
      ‘site’ is a rigid type variable bound by
             the type signature for footer :: WidgetT site IO ()
```

Empty `footer.hamlet` is working with type signature otherwise it's throwing mentioned error.

Thank you very much for your time! I really appreciate that. You helped me a lot.

Have a nice rest of the evening
