### ISSUE TITLE
runFormPost has wrong behavior for empty forms

### ISSUE THREAD

**Issue by andrewthad** [yesodweb/yesod#950]
So, I just noticed an odd problem. If I have a form that collects no data, then `runFormPost` will always give a `FormSuccess` when run, even when I make a GET request. A code fragment to sort of illustrate this:

    acceptTheContractButton :: AForm m ()
    acceptTheContractButton = ...
    
    handleAcceptContractR :: Handler Html  -- Yesod dispatches to this function for GET and POST requests
    handleAcceptContractR = do
      ((res, widget), enctype) <- runFormPost $ someAFormRenderer acceptTheContractButton
      case res of
        FormSuccess () -> ... -- make some change in the database and redirect
        _ -> ... --show the form. A bug causes this path to never be taken

This is a super common (and super useful) pattern in Yesod where you can use the same form and the same handler for dealing with both the GET and POST response. Unfortunately, this particular use doesn't work. The problem is that `runFormPost` always gives us a `FormSuccess` if there are no named inputs (yes, this issue also occurs if everything in the form generated by `pure` instead of `areq`, `mopt`, etc.). The concerning thing is that the CSRF token must be getting ignored, since the GET request to the page doesn't even have that information. On the whole, I don't consider this a super pressing issue because empty forms are a sort of degenerate case, but I would appreciate this being fixed so that I can stop working around it by creating hidden fields.

**Comment by snoyberg** [comment]
That's strange. Minimal reproducing test case:

```haskell
{-# LANGUAGE OverloadedStrings, TemplateHaskell, QuasiQuotes, TypeFamilies, MultiParamTypeClasses #-}
import Yesod
import Yesod.Form
import Control.Applicative (pure)

data App = App

mkYesod "App" [parseRoutes|
/ HomeR GET POST
|]

instance Yesod App
instance RenderMessage App FormMessage where
    renderMessage _ _ = defaultFormMessage

getHomeR, postHomeR :: Handler Html
getHomeR = postHomeR
postHomeR = do
    ((res, widget), enctype) <- runFormPost $ renderDivs $ pure ()
    defaultLayout $ do
        setTitle "Test for issue #950"
        [whamlet|
            <p>Result: #{show res}
            <form method=post action=@{HomeR} enctype=#{enctype}>
                ^{widget}
                <button>Submit
        |]

main :: IO ()
main = warp 3000 App
```

I'll try to look into this tomorrow.

**Comment by andrewthad** [comment]
Thanks, I appreciate that.

**Comment by snoyberg** [comment]
OK, I believe the commit I just pushed should fix the issue, can you test it out?

**Comment by andrewthad** [comment]
I have tested it, and it's behavior is now correct. Thanks for taking care of this so quickly.

**Comment by snoyberg** [comment]
No problem, this is now on Hackage.
