### ISSUE TITLE
Lucius is compiled, right?

### ISSUE THREAD

**Issue by andrewthad** [yesodweb/yesod#954]
I just deployed an application and got this when I ran it:

    13/Mar/2015:12:02:00 -0400 [Error#yesod-core] Error handler errored out: InternalError "templates/styles.lucius: openFile: does not exist (No such file or directory)" @(yesod-core-1.4.7.2:Yesod.Core.Internal.Run ./Yesod/Core/Internal/Run.hs:163:21)

I have never needed to deploy any hamlet files, just my compiled binary. Why is lucius different? Isn't it just TH that becomes haskell code and is included in the binary?

**Comment by andrewthad** [comment]
Hold up. It may be something else.

**Comment by andrewthad** [comment]
No, it's definitely as I suspected. The lucius files are actually loaded at runtime. Can anyone explain why this is the behavior?

**Comment by gregwebs** [comment]
Are you using the default scaffold? It is likely you are using the debug mode for Lucius (this behavior is usually specified in Settings.hs).

**Comment by andrewthad** [comment]
I think that this is the line that causes it:

    widgetFile :: String -> Q Exp
    widgetFile = (if appReloadTemplates compileTimeAppSettings
                then widgetFileReload
                else widgetFileNoReload)
              widgetFileSettings

**Comment by snoyberg** [comment]
How are you compiling your executable for production?

**Comment by andrewthad** [comment]
For the library, this is in my cabal file:
    ghc-options: -Wall -Werror -fcontext-stack=40 -fwarn-tabs -O1
For the executable, this is:
    -threaded -O1 -rtsopts -with-rtsopts=-N
My setup is that I start with the yesod scaffold and immediately strip out everything dealing with `yesod devel` (I turn off the `CPP` extension as well). So, my production build is the same as my development build.

**Comment by snoyberg** [comment]
It's hard to guess at this without having a reproducing test case. What does your config file look like?

**Comment by andrewthad** [comment]
It was the code I pasted earlier. To fix this, I changed a line further up in the scaffold to be

    appReloadTemplates        <- o .:? "reload-templates" .!= False
