### ISSUE TITLE
getAuthId to return a more useful result

### ISSUE THREAD

**Issue by pbrisbin** [yesodweb/yesod#956]
When I'm unable to authenticate a user based on some `Creds`, the only information I really have is that `getAuthId` returned `Nothing` and the page shows "Invalid login". I frequently have to debug `getAuthId`, when a more informative return value could have told me directly what was going on.

The simplest thing would be to upgrade the `Maybe` to `Either`, but then we'd have to decide if that `Left` message is intended for a developer or the end-user. We could return something like:

```haskell
data AuthResult
    = Success UserId
    | UserError Message -- User's fault, show them message
    | ServerError Message -- Server's fault, log message, show user "Sorry" or something
```

Obviously this is a breaking change, but I wanted to put it out there and start the discussion. I could handle my own use case in a few other ways (exceptions, logging, etc), but this felt like a Good Idea in general.

**Comment by erikd** [comment]
I'm a bit ole +1 on this. I would be happy with an `Either` or your proposed `AuthResult`.

**Comment by MaxGabriel** [comment]
You could add new API to return the `AuthResult`, leaving the `getAuthId` API the same, right?

**Comment by pbrisbin** [comment]
Ah good idea. As long as `requireAuth{,Id}` will use the new API, though.

Let me outline what I think could work:

- Add a new function, something like:

```haskell
class Yesod m => YesodAuth m where
    getAuthResult :: Creds -> m AuthResult
    getAuthResult c = do
        muid <- getAuthId c
        return $ maybe (UserError "Invalid Login") Success muid
```

- Update `requireAuth{,Id}` to call this new function and log/render as I described above.

I think this keeps everything completely backwards compatible.

Users who want can define `getAuthResult` directly and take advantage of the logging and a better user-facing error page. These users wouldn't need to define `getAuthId`, so we could add a symmetrical default for `getAuthId`:

```haskell
class Yesod m => YesodAuth m where
    getAuthId :: Creds -> m (Maybe UserId)
    getAuthId c = do
        res <- getAuthResult c
        return $ case res of
            Success uid -> Just uid
            _ -> Nothing
```

Making the minimal complete definition `getAuthResult | getAuthId`.

Finally, deprecate then remove `getAuthId`.

**Comment by erikd** [comment]
I approve of @pbrisbin's idea.

**Comment by snoyberg** [comment]
I'm in favor of this move, +1. @pbrisbin you want to implement it?

**Comment by pbrisbin** [comment]
Sure. I should have some time on Friday to get started on a PR.
