### ISSUE TITLE
Uploading a file 

### ISSUE THREAD

**Issue by MonrealRyan** [yesodweb/yesod#961]
Hi, 
I was having a hard time on uploading a file to my ``static`` folder.

here is my code hope you help me.

```
{-# LANGUAGE MultiParamTypeClasses #-}
{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE QuasiQuotes #-}
{-# LANGUAGE TemplateHaskell #-}
{-# LANGUAGE TypeFamilies #-}

module FileServer where

import Yesod
import Yesod.Static
import Data.Time (UTCTime)
import System.FilePath
import System.Directory (removeFile, doesFileExist)
import Control.Applicative ((<$>), (<*>))
import Data.Conduit
import Data.Text (unpack)
import qualified Data.ByteString.Lazy as DBL
import Data.Conduit.List (consume)

--import some libraries
import Data.Default
import Text.Hamlet
import Yesod.Default.Util

import Control.Exception hiding (Handler)
import qualified Data.ByteString.Lazy as LB
import Data.Default
import Data.Text (Text)
import qualified Data.Text as Text
import qualified Data.Text.Lazy as LT
import qualified Data.Text.Lazy.Encoding as LT
import Text.Blaze



staticFiles "static"

data App = App
    {
        getStatic :: Static
    }

mkYesod "App" [parseRoutes|
/ HomeR GET POST
/static StaticR Static getStatic
|]

instance Yesod App where
  defaultLayout widget = do
    pc <- widgetToPageContent $ $(widgetFileNoReload def "default-layout")
    withUrlRenderer $(hamletFile "templates/default-layout-wrapper.hamlet")

instance RenderMessage App FormMessage where
    renderMessage _ _ = defaultFormMessage


uploadForm = renderDivs $ fileAFormReq "file"

uploadDirectory :: FilePath
uploadDirectory = "static"

getHomeR :: Handler Html
getHomeR = do
    (formWidget, formEncType) <- generateFormPost uploadForm
    mmsg <- getMessage
    defaultLayout $ do
        setTitle "File Processor"
        $(widgetFileNoReload def "home")

postHomeR :: Handler Html
postHomeR = do
    ((result, widget), enctype) <- runFormPost uploadForm
    case result of
        FormSuccess (file) -> do
            -- TODO: check if image already exists
            -- save to image directory
            filename <- writeToServer file
            setMessage $ toMarkup $ "Image saved = " `Text.append` "Image Name"
            redirect HomeR
        _ -> do
            setMessage "Something went wrong"
            redirect HomeR

writeToServer :: FileInfo -> Handler FilePath
writeToServer file = do
    let filename = unpack $ fileName file
        path = imageFilePath filename
    liftIO $ fileMove file path
    return filename

imageFilePath :: String -> FilePath
imageFilePath f = uploadDirectory </> f

main :: IO ()
main = do
    static@(Static settings) <- static "static"
    warpEnv $ App static
```
the file was not seen on the ``static`` folder also there's no error so i'm confuse where does my file goes.

hope you help me.

**Comment by geraldus** [comment]
Sorry, this is not actual answer. I guess the purpose of static folder is to provide static files with ability to use type safe urls when you need to point to some file in your code (e.g. url of background picture in cassius code). And if you want to store user uploaded files I assume that you should pick another folder, say `dynamic` or `upload`.

**Comment by MonrealRyan** [comment]
@geraldus  - thank you, i add uploaded folder then `` uploadDirectory = "uploaded" ``. But, still the file was not there any suggestion?

**Comment by geraldus** [comment]
Can you insert some debug messages to your code (e.g. `$(logDebug)`)and look at logs?

**Comment by MonrealRyan** [comment]
@geraldus - in what particular line should i put this ``$(logDebug)``?

**Comment by MonrealRyan** [comment]
@geraldus - i put it before this code `` filename <- writeToServer file`` but can't see the debug message i put.

anyway maybe i used Fpcomplete IDE for my development.
does my ide has an affect on it?

**Comment by geraldus** [comment]
I suppose that means your form never succeeds. Do you have `<form>` wrapper in your `home` template? If you expect form to be POSTed, you must have something like this is your template:

```html
<form method=post>
  ^{formWidget}
  <input type=submit>
```

**Comment by MonrealRyan** [comment]
@geraldus - yes i have, here's the code.

```
<form method=post action=@{HomeR} enctype=#{formEncType}>
  ^{formWidget}
  <input type="submit" value="Upload">
```

**Comment by geraldus** [comment]
Ok, can you try this one then:

```haskell
postHomeR :: Handler Html
postHomeR = do
    ((result, widget), enctype) <- runFormPost uploadForm
    $(logDebug) "Got POST data"
    case result of
        FormSuccess (file) -> do
            $(logDebug) "Form SUCCESS"
            filename <- writeToServer file
            $(logDebug) "File served"
            setMessage $ toMarkup $ "Image saved = " `Text.append` "Image Name"
            redirect HomeR
        FormFailure _ -> do
            $(logDebug) "Form FAILURE"
            redirect HomeR
        FormMissing -> do
            $(logDebug) "No DATA"
            redirect HomeR

writeToServer :: FileInfo -> Handler FilePath
writeToServer file = do
    let filename = unpack $ fileName file
        path = imageFilePath filename
    $(logDebug) "Moving file..."
    liftIO $ fileMove file path
    $(logDebug) "Done"
    return filename

```

**Comment by MonrealRyan** [comment]
@geraldus - thank you, but it the same nothing has change.

**Comment by geraldus** [comment]
@MonrealRyan OK! I've figured out that `$(logDebug)` does not produce logs, because it need some debugging setup (e.g. env variable), so I just replaced them all to `$(logInfo)` and now I see form failure messages.

Not sure can you visit my project, here it is: https://www.fpcomplete.com/user/Geraldus/fileserver
Anyway, you can replace debug with info manually.

**Comment by geraldus** [comment]
I can't be certain, it looks like FP Complete restrictions, can you check your code locally?

**Comment by MonrealRyan** [comment]
@geraldus - hi, i visit you project but it does not have a file.

**Comment by geraldus** [comment]
Yes, because form always **FAILS**. As I mentioned before this could be some restriction of FP Complete IDE, which prevents uploading files for obvious security reasons. Can you test it locally on your machine, not in FP Complete IDE? As for mine, I can do local test in about few hours, quite busy now, sorry.

**Comment by MonrealRyan** [comment]
@geraldus - i can't do it on my local machine. cause i having a hard time on intalling the yesod and its dependency..  i will try another solution and ask also the support for that matter. thank you again.. i will wait also for you if the code is running well in you local machine..

thank you.

**Comment by geraldus** [comment]
Can confirm now, that issue persists with local build too, code can be grabbed from here: https://www.fpcomplete.com/user/Geraldus/fileserver

CSRF token is generated, not sure what's going wrong. A bug?

Maybe, it's time to ping @snoyberg ?

**Comment by snoyberg** [comment]
I'm not seeing any files in that project. Did you remember to commit before
publishing?

**Comment by MonrealRyan** [comment]
@snoyberg - you try https://www.fpcomplete.com/user/MonrealRyan0208/yesdo-db sir, its the same on @geraldus. but sorry for dirty code :)

**Comment by snoyberg** [comment]
If the bug report is "the uploaded file is not reflected in the IDE," this
is a known behavior in the IDE. See:
https://www.fpcomplete.com/school/using-fphc/fp-haskell-center-tricks-and-tips/FileViewer

**Comment by MonrealRyan** [comment]
@snoyberg - hi sir. so once i deploy this code code it will run in natural way? I also run the code and I see all the files i upload but, for example i have an ``<img src="/uploaded/chosen-sprite.png">`` 
it always give me an broken ``img`` is it that IDE also or in my code? 
Thank you.

**Comment by snoyberg** [comment]
I am unable to debug this code for you, I recommend researching the issue
more thoroughly.

**Comment by geraldus** [comment]
@snoyberg, no, I see form failure logs with local build too (i.e. on my laptop).
Sorry, didn't know that I should commit changes to make code publicly available.

**Comment by geraldus** [comment]
> `24/Mar/2015:15:30:09 +0500 [Info#yesod-core] Application launched @(yesod-core-1.4.7.2:Yesod.Core.Dispatch ./Yesod/Core/Dispatch.hs:141:11)`

> `24/Mar/2015:15:30:38 +0500 [Info] Entered HOME @(main:Main FileServer.hs:65:7)
127.0.0.1 - - [24/Mar/2015:15:30:38 +0500] "GET / HTTP/1.1" 200 - "http://localhost:9999/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_2) AppleWebKit/600.4.10 (KHTML, like Gecko) Version/8.0.4 Safari/600.4.10"`


> `24/Mar/2015:15:30:49 +0500 [Info] Got POST data @(main:Main FileServer.hs:74:7)`

> `24/Mar/2015:15:30:49 +0500 [Info] Form FAILURE: Value is required @(main:Main FileServer.hs:83:15)`

> `127.0.0.1 - - [24/Mar/2015:15:30:49 +0500] "POST / HTTP/1.1" 303 - "http://localhost:9999/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_2) AppleWebKit/600.4.10 (KHTML, like Gecko) Version/8.0.4 Safari/600.4.10"`

> `24/Mar/2015:15:30:49 +0500 [Info] Entered HOME @(main:Main FileServer.hs:65:7)`

> `127.0.0.1 - - [24/Mar/2015:15:30:49 +0500] "GET / HTTP/1.1" 200 - "http://localhost:9999/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_2) AppleWebKit/600.4.10 (KHTML, like Gecko) Version/8.0.4 Safari/600.4.10"`

**Comment by geraldus** [comment]
Oh, sorry for so many stupid noise! There **must** be `enctype` attribute specified in form:

``` htmk
<form method=post enctype=#{formEncType}>
   ^{formWidget}
   <input type=submit>
```

And everything should work.

**Comment by snoyberg** [comment]
@geraldus Good catch, I hadn't figured that out yet, thank you for updating me :).

Looks like all is working as expected, closing.

**Comment by geraldus** [comment]
glad to be helpful :blush:

**Comment by MonrealRyan** [comment]
@geraldus - so our code is working?

**Comment by geraldus** [comment]
Yes, it does. Checked locally and on FPComplete: check it yourself https://www.fpcomplete.com/user/Geraldus/fileserver

**Comment by MonrealRyan** [comment]
@geraldus and @snoyberg - Thank you :)
