### ISSUE TITLE
Yesod hangs when serving JSON

### ISSUE THREAD

**Issue by andrewthad** [yesodweb/yesod#967]
This is a huge problem. The yesod packages that come with stackage lts 2.1 can't serve json. You can verify this by running `yesod init` and choosing the `mini` option for the type of scaffold. Now, go to the localhost:3000 and you'll see this:

    HTML addition
    JSON addition

If you click HTML addition, it works fine. Now go back and hit JSON addition and yesod will hang until killed with Ctrl+C.

**Comment by snoyberg** [comment]
I just tested with the version of Yesod I had installed locally, and did
not reproduce. Testing with LTS 2.1 to be certain. I suspect something else
it going on here.

**Comment by snoyberg** [comment]
Just checked again: no issues at all loading up the JSON response body. Are you running via `yesod devel` or some other way?

**Comment by snoyberg** [comment]
Oh, of course, the minimal scaffolding doesn't support `yesod devel`, so I have to assume you're running this with `cabal install && ./dist/build/...` or equivalent. I'm testing in that manner, and having no issues.

**Comment by andrewthad** [comment]
Thanks for looking into it. I'm not using `yesod devel`, just `cabal run`, and I'm getting this across multiple projects and across different browsers. I've turned optimization down to `-0O` but that had no effect. I'm using GHC 7.8.4. I assume you're on 7.10?

**Comment by snoyberg** [comment]
No, 7.8.4 as well, 7.10 doesn't have LTS support. What OS are you on? I
tested using Ubuntu 14.04

**Comment by andrewthad** [comment]
I'm also on Ubuntu 14.04

**Comment by snoyberg** [comment]
I don't know what to say then. Perhaps write to the mailing list and see if
others can repro?

**Comment by andrewthad** [comment]
Yeah, that's the only thing I can think of. I'll look into it more and then give that a try.

**Comment by andrewthad** [comment]
Oh, and my GHC is built with integer-simple instead of integer-gmp. Not that I expect that to matter.

**Comment by andrewthad** [comment]
@snoyberg Could you go into the `x86_64-linux-ghc-7.8.4-packages.conf.d` folder in your sandbox and run this:

    ls | awk 'BEGIN{FS="-";OFS="-"} {$NF=""; print $0}'

**Comment by andrewthad** [comment]
Nevermind. I just realized that all 132 of the packages I depend on had constraints set by stackage.
