### ISSUE TITLE
Curiosity - Transit handler support?

### ISSUE THREAD

**Issue by JulianLeviston** [yesodweb/yesod#971]
Hi, just wondering if it's planned to add transit as a format for data interchange, seeing as it's substantially better than standard JSON (more compact, better at transporting varying types across JSON, etc.) especially useful for sending large JSON payloads.

Currently considering Yesod as a replacement for the next step in our futuristic CMS's backend (currently needs to be rewritten in alien tech, because it's object tech right now).

http://blog.cognitect.com/blog/2014/7/22/transit
https://github.com/cognitect/transit-clj

I haven't seen a haskell implementation other than someone's alpha stab at it here:
https://github.com/jstepien/transit
And this comment thread:
https://groups.google.com/forum/#!topic/transit-format/AT_1yXZgFMc

**Comment by snoyberg** [comment]
I'm fully in favor of such support. Fortunately this wouldn't actually require any built-in functionality from Yesod itself. Yesod allows any instance of `ToTypedContent` to be returned from a handler, which essentially boils down to "has a content-type and can be serialized to a byte stream." For more information, see:

http://www.yesodweb.com/book/yesod-for-haskellers#yesod-for-haskellers_to_content_to_typedcontent

I'm not familiar with Transit myself, but it's worth bringing it up on the mailing list and seeing if others are interested in such a library.

**Comment by JulianLeviston** [comment]
Thanks. I'm slowly working my way through yesod. Good to keep in mind. I might take a crack at it when I get to that part, so long as I can address the other couple of things I'll need (such as a good front-end solution based on something similar to React, and the ability to use Datomic or something like it).
