### ISSUE TITLE
Supplement "yesod init" interactive mode with non-interactive mode

### ISSUE THREAD

**Issue by kairuku** [yesodweb/yesod#974]
I was wondering if it might be possible in the future that "yesod init" could accept the app name and database backend as inline arguments to the yesod init command itself. This would allow me to wrap yesod init inside a fish shell function that also did other repetitive things (like initializing a git repo, or generating a dash-haskell docset), by just passing the arguments to the fish function, which in turn would then be able to pass them to yesod init.  It would be nice to retain the --bare flag for both modes of yesod init too.

Thank you for any consideration of this enhancement request :)

**Comment by snoyberg** [comment]
No objection to such a change, It's pretty easy to implement, I'm going to mark it as Newcomer. PRs welcome!
