### ISSUE TITLE
`yesod devel` does start websever

### ISSUE THREAD

**Issue by raichoo** [yesodweb/yesod#976]
Hi,

I'm having the following issue with `yesod`. I created a simple scaffolding application using a `postgres` backend. When starting the application migration works just fine, however there is no webserver running on port 3000. I also get a mysterious `ExitFailure 1` message at startup. This happens with an out of the box scaffolding application created by `yesod init`.

Here is the output of `yesod devel`:

    Yesod devel server. Press ENTER to quit
    Application can be accessed at:

    http://127.0.0.1:3000
    https://127.0.0.1:3443
    If you wish to test https capabilities, you should set the following variable:
      export APPROOT=https://127.0.0.1:3443

    yesod: ExitFailure 1
    Resolving dependencies...
    Configuring exitfailtest-0.0.0...
    Rebuilding application... (using cabal)
    Starting development server...
    Starting devel application
    Devel application launched: http://localhost:3000

For now I can work around the issue by falling back to `cabal`.

Kind regards,
raichoo

**Comment by geraldus** [comment]
Sometimes I also have `ExitFailure 1` message when I'm using some external tools while `yesod devel` is running, e.g. `ghc-mod` background process which is used by Emacs. Usually I just hitting `Enter` and relaunching devel process again, though `touch Application.hs` (or whatever) also wakes up devel process and it relaunching server.

However, I can say nothing of possible reason why is `localhost:3000` is unreachable. How do you check that server is no actually running?

**Comment by raichoo** [comment]
I'm not using `ghc-mod` at the moment. I did check with `nmap` and `lsof`. There is nothing bound to port `3000`.

**Comment by raichoo** [comment]
Ok, it looks like this "bug" was be related to an operating system inconsistency. I checked everything with the `mysql` version of the `yesod` application which worked perfectly fine yesterday and it resulted in the same behavior. Rebooting the system fixed everything… looks like Linux is becoming more and more like Windows these days ^^.

I'll close this report since it seems to be a glitch on my side.

**Comment by geraldus** [comment]
BTW, I don't have `nmap` on OS X, but `lsof | grep 3000` shows me nothing when I have devel server running.
