### ISSUE TITLE
Newer Cabal breaks yesod devel

### ISSUE THREAD

**Issue by pikajude** [yesodweb/yesod#979]
It looks like Cabal configures all of the buildables in the cabal file even if they're not intended to be built, meaning that after configure, `yesod-devel/ghcargs.txt` will contain the necessary arguments for running the last test suite in the cabal file instead of the ones for the library.

One idea I had to mitigate this would be to have yesod-ghc-wrapper only save its arguments if they contain an arg that identifies that the library is being built (like "Application") but that's not very elegant and I'm sure there's a better solution.

**Comment by snoyberg** [comment]
Can you provide a repro for this? I'm not sure how you are triggering this bug.

**Comment by pikajude** [comment]
Well, now I can't reproduce it either. Fixed!

**Comment by pikajude** [comment]
@snoyberg You should be able to reproduce it on https://github.com/pikajude/jude-web

**Comment by pikajude** [comment]
@snoyberg Never mind! I was accidentally *manually* passing --enable-tests. That is NOT what needs to happen.

**Comment by erikd** [comment]
Just hit this problem myself, running cabal version 1.24.? and ghc-7.10. Switched to ghc-8.0 (as I always intended to use anyway) and that fixed it.
