### ISSUE TITLE
Scaffolded PostgreSQL configuration

### ISSUE THREAD

**Issue by noijd** [yesodweb/yesod#982]
The scaffolded `settings.yml` has capitalized user and database names (at least with a project name like "Example").
As PG converts them to lower case, it fails to start with `yesod devel`.

I have check that it works creating the db and user with lower case, and adapting the `settings.yml` to that, and I have also verified that it is possible to use capitalized or upper case names inside quotes on both places.

Source: http://stackoverflow.com/questions/9538668/postgresql-forces-lowercase-names

So I think that Yesod should generate lower case names or wrap them with quotes.

**Comment by snoyberg** [comment]
Interesting, we [just discussed this elsewhere](https://github.com/snoyberg/keter/pull/88). @tolysz @MaxGabriel @rvion Thoughts?

**Comment by MaxGabriel** [comment]
Making the database name/username all lowercase seems like a good default; it doesn't seem to have much downside to me.

I think having a database name that requires quoting in psql will throw people off (google around for `ERROR:  syntax error at or near "user"` or `user reserved word postgresql` for examples of the trouble that causes).

**Comment by noijd** [comment]
I second the lower case because It is a usual practice, but I'm just a Yesod newbie, so I don't know if it incurs on the project conventions.

**Comment by snoyberg** [comment]
I've pushed some commits which should address this. Can you test before I release to Hackage?

**Comment by snoyberg** [comment]
I've released to Hackage. Please reopen if there are still problems.
