### ISSUE TITLE
Defaults for `PathPiece`

### ISSUE THREAD

**Issue by andrewthad** [yesodweb/yesod#983]
If we have a `Show` and a `Read` instance for a type, we can trivially get a `PathPiece` instance. I recommend adding default signatures like this:

    class PathPiece s where 
        fromPathPiece :: S.Text -> Maybe s
        default fromPathPiece :: (Read s) => S.Text -> Maybe s
        fromPathPiece = readMaybe . Text.unpack

        toPathPiece :: s -> S.Text
        default toPathPiece :: (Show s) => s -> S.Text -> s
        toPathPiece = Text.pack . show

This let's use more easily define `PathPiece` instances (even if they're just a throwaway implementation):

    data Detail = Low | Medium | High | VeryHigh
      deriving (Show, Eq)
    instance PathPiece Detail

Note: I have not type checked the example code.

**Comment by snoyberg** [comment]
I'm OK with adding this, though there's some concern about mismatched `Show`/`Read` instances. Want to send a PR?

**Comment by gregwebs** [comment]
I disagree with this change because read/show has a different purpose. Better would be just to document and provide helper functions for this case.

**Comment by creichert** [comment]
In it's current state, I would disagree with the proposed patch as
well. It will make life easier for only a small subset of types which
have Show instances (especially auto derived instances).

**Comment by andrewthad** [comment]
I'm alright with just having the helper functions instead (with documentation of course). In fact, that's how I've already got this implemented in several projects. I think that would be more understandable for people, and this is a somewhat small use case I'm trying to satisfy. What are everyone's thoughts on providing these:

    defReadFromPathPiece :: Read s => Text -> Maybe s
    defShowToPathPiece :: Show s => s -> Text

Also, @creichert you are right that the intent here is really just to take advantage of the derived `Show` and `Read` instances for simple enumeration types. This is a behavior that I've copied between enough of my projects that I do feel like `path-piece` should provide it out of the box.

**Comment by gregwebs** [comment]
I think you can drop the `def` prefix for the functions.

**Comment by creichert** [comment]
Looks good to me and I agree with the naming advice. This will be a
good addition.

**Comment by andrewthad** [comment]
I've got a PR up for this now.

**Comment by snoyberg** [comment]
Let's track in the PR, closing issue.
