### ISSUE TITLE
Add support for a graph database

### ISSUE THREAD

**Issue by marcusmonteiro** [yesodweb/yesod#984]
I think it would be nice to have support for a graph database, such as [Cayley] (https://github.com/google/cayley). Is this part of the plan for Yesod? If I wanted to try adding such support, how could I start? What are some things that I would have to keep in mind?

**Comment by gregwebs** [comment]
To use a database you initialize it the main functions and then access it in runDB.
yesod-persistent has some integrations with persistent (I think mostly with forms) that you would be missing out on.

In general the goal is for Yesod not to care about what databases you are using, but to make sure it is easy out of the box with persistent. If someone is willing to maintain a scaffold for a different database then it could work out of the box for that one also.

**Comment by andrewthad** [comment]
Yeah, in general, the approach of `persistent` seems to be to treat the database as a key-value store (sort of the least common denominator in datastore technologies) and then uses other tools to get more specific querying capabilities (like esqueleto). So, a good start would be figuring out how to just use it as a key-value store.

**Comment by snoyberg** [comment]
I think the resolution here is: persistent supports different backends, the backend for a graph database just needs to be written.
