### ISSUE TITLE
`mkYesodData` generates type synonyms

### ISSUE THREAD

**Issue by andrewthad** [yesodweb/yesod#985]
I've known this for a long time, and even when I very first learned about it, it seemed like a misfeature. To my knowledge, the main purpose of `mkYesodData` is to build a giant ADT with all your routes in it. However, it also generates the type synonyms `Handler` and `Widget`. My belief is that generating these type synonyms is a bad idea. If we take a look at the scaffold, we see this:

    -- Note that this is really half the story; in Application.hs, mkYesodDispatch                    
    -- generates the rest of the code. Please see the linked documentation for an                     
    -- explanation for this split.                                                                    
    mkYesodData "App" $(parseRoutesFile "config/routes")                                              

    -- | A convenient synonym for creating forms.                                                     
    type Form x = Html -> MForm (HandlerT App IO) (FormResult x, Widget)   

So, `mkYesodData` gives us two magic type synonyms (which was confusing when I was new to Yesod), but the scaffold goes ahead and provides another for helping with forms. Why don't we just add

    type Handler x = HandlerT App IO x
    type Widget x = WidgetT App IO x

to the scaffold instead. I realize that this would be a breaking change (really easy to fix though). I just wanted to hear if anyone else had feelings about this.

**Comment by MaxGabriel** [comment]
Is it a really easy to fix breaking change? I think many Yesod code snippets would break without the Handler type synonym, so even if you added these type signatures to the scaffolding it would necessitate many book/docs updates.

I also found this confusing when learning Yesod, though. Maybe adding a comment to the scaffolding or something would be helpful?

**Comment by andrewthad** [comment]
Yeah, I guess I forgot about all the online examples breaking. That would be pretty lame (like how I still come across snippets that reference `GHandler`). What I meant was more along the lines of it would be easy to fix all of my existing code. I would only need to add two lines to each project.

**Comment by snoyberg** [comment]
How about this: add another function that doesn't include the type
signatures, use that from the scaffolding, and then explicitly add the type
signatures. We can even add a note in the scaffolding about the presence of
the mkYesodData function that does this for you automatically.

**Comment by mgsloan** [comment]
One approach would be to have "mkYesodData" lookup the names `Handler` and `Widget` and not generate the declarations if they already exist.  Then these type synonyms could then be added to the scaffold, before the splice.  I'm in favor of this change, because I have vague memories of being confused by the docs not existing for these back when I was getting started with Yesod.

**Comment by meteficha** [comment]
That may work.  The `Handler` and `Widget` synonyms do not depend on anything created by `mkYesodData`.  However, this would replace magic with more magic, so I'm not sure if it's worth it in the end.

**Comment by snoyberg** [comment]
It seems like all that does is let us avoid adding an extra function, and instead and magic which will be non obvious and will silently break things for older versions of the library in very confusing ways. I'm -1

**Comment by MaxGabriel** [comment]
Made a PR related to this in the yesod-scaffold repo; wanted to mention it here because I didn't think that people would get pinged otherwise https://github.com/yesodweb/yesod-scaffold/issues/77

**Comment by andrewthad** [comment]
Excellent. I'm pretty happy with that as far as making things more understandable for new people goes.
