### ISSUE TITLE
Failed to build yesod-static 1.4.0.4

### ISSUE THREAD

**Issue by snakamura** [yesodweb/yesod#989]
I found that it failed to build yesod-static 1.4.0.4 because cabal tried to build it with wai-app-static 3.1.0. It would be nice if you set the upper bound (wai-app-static < 3.1.0) and release yesod-static 1.4.0.5.

**Comment by snoyberg** [comment]
Good call, I just revised the cabal files for the 1.4.* series to have an upper bound. Does that help?

**Comment by snakamura** [comment]
Yes, it builds fine now. Thank you.
