### ISSUE TITLE
RAML style route definitions for yesod-routes

### ISSUE THREAD

**Issue by junjihashimoto** [yesodweb/yesod#990]
Hi,

I want to develop RAML style route definition parser like https://github.com/scalableminds/sbt-play-raml/ for yesod-route.
How do you think? (I should develop this or use alternative one.)

I develop rest-api service with yesod.
The specification is written by [raml](http://raml.org/spec.html).
At first write spec. Next update route fo yesod.
This causes below.
(I just pick up these things from http://forums.raml.org/t/playframework-raml-resource-definition/159/2)

+ Defining http routes in two different places will lead to inconsistencies
+ Separating the documentation from the actual routing will lead to outdated documentations

So I want to develop https://github.com/scalableminds/sbt-play-raml/ for yesod-route.

example / behavior is blow.

1, Write following raml file in config/routes.raml
```
#%RAML 0.8
/user:
  /{userid}
    get:
      description: |
        Get user information
        Handler is below.
        default:  UserR
```
2, Write ``` parseRoutesRamlFile "default" "config/routes.raml"``` in Foundation.hs.
    I will make ```parseRoutesRamlFile``` to parse raml file.
     ```parseRoutesRamlFile```  parses raml file and generates routes-file for yesod.
    Genarated route-file is below.
```
/users/#userid UserR GET
```

**Comment by snoyberg** [comment]
It's (unfortunately) not well documented, but the data types that the current route parser generate are at:

https://www.stackage.org/haddock/nightly-2015-05-11/yesod-core-1.4.9.1/Yesod-Routes-TH-Types.html

Instead of converting to the current format, you should be able to just write a parser that generates those data types, and then pass that to `mkYesod` as usual.

**Comment by junjihashimoto** [comment]
Thank you for your comment.
I will try.

**Comment by junjihashimoto** [comment]
I was able to make following package.
https://github.com/junjihashimoto/yesod-raml

thx.
