### ISSUE TITLE
ExitFailure 1 for `yesod devel` on FreeBSD 10

### ISSUE THREAD

**Issue by obscaenvs** [yesodweb/yesod#992]
I get ExitFailure 1 for `yesod devel` on FreeBSD, but it goes on happily to produce the following output:
```
Yesod devel server. Press ENTER to quit
Application can be accessed at:

http://127.0.0.1:3000
https://127.0.0.1:3443
If you wish to test https capabilities, you should set the following variable:
  export APPROOT=https://127.0.0.1:3443

yesod: ExitFailure 1
Resolving dependencies...
Configuring JunkApp-0.0.0...
Rebuilding application... (using cabal)
Starting development server...
Starting devel application
Devel application launched: http://localhost:3000
```

However, the app is not reverse proxied in this instance.

`dist/dist-sandbox-843b94a5/build/JunkApp/JunkApp config/settings.yml` works fine.

The error seems to be produced by `race_ httpProxy  httpsProxy` in `Devel.hs`, line 194.
I built a custom binary in a noobish way just to isolate the problem further, which works. 
Here's `$ diff -U2 yesod-bin-1.4.7.2/Devel.hs yesod-bin-1.4.7.2-my/Devel.hs`, with the first one being the ordinary Hackage one and the other my custom:
```
--- yesod-bin-1.4.7.2/Devel.hs	2015-05-15 19:12:03.000000000 +0200
+++ yesod-bin-1.4.7.2-my/Devel.hs	2015-05-15 19:00:34.000000000 +0200
@@ -185,5 +185,5 @@
           runTLS tlsSettings (setPort port defaultSettings) app
         httpProxy = run (develPort opts) proxyApp
-        httpsProxy = runProxyTls (develTlsPort opts) proxyApp
+        httpsProxy = httpProxy -- just for testing purposes
     putStrLn "Application can be accessed at:\n"
     putStrLn $ "http://127.0.0.1:" ++ show (develPort opts)
@@ -192,5 +192,5 @@
     putStrLn $ "  export APPROOT=https://127.0.0.1:" ++ show (develTlsPort opts)
     putStrLn ""
-    loop (race_ httpProxy httpsProxy) `Ex.onException` exitFailure
+    loop (race_ httpProxy httpsProxy) `Ex.onException` (putStrLn "Something went south." >> exitFailure)
   where
     loop proxies = forever $ do
```

**Comment by obscaenvs** [comment]
Further down the call line in the original file, `runTLS` throws a fit:
```
runTLS tlsSettings (setPort port defaultSettings) app `Ex.onException` (do putStrLn "runTLS failed")
```
gives the expected result, namely `runTLS failed` when `yesod devel`'ing the app as usual.

**Comment by snoyberg** [comment]
It sounds like there are two different bugs going on here:

1. The warp-tls server crashing isn't taking down the entirety of `yesod devel` like it should
2. warp-tls itself is not working on FreeBSD

I'm more interested in solving the second one, but I don't have access to a FreeBSD machine. Are you able to reproduce it in a standalone test?

**Comment by snoyberg** [comment]
I also just pushed a commit which will be a bit more verbose in this situation, can you tell me the result of running `yesod devel` with the current master?

**Comment by obscaenvs** [comment]
Yep, I can, hopefully some time during the day.

**Comment by obscaenvs** [comment]
OK, I am actually glad to be able to say I am facepalming myself to sleep tonight. For some queer reason, `runghc` had *bound to port 3443 at the beginning of April*, and not let go. One SIGTERM later, there is no problem, at least not when running without a certificate. 

The extra output was nice, though, as was looking into some of the code for `yesod-bin`. I'll be more thorough in the future.
