### ISSUE TITLE
Enter to stop yesod devel seems incomplete

### ISSUE THREAD

**Issue by wolftune** [yesodweb/yesod#995]
I often hit Enter only to not be back at a real prompt. I might start typing but the result is odd, like it has some strange extra buffering or something from before. I have to hit Enter several times and sometimes I then later also Ctrl-C before I'm *certain* that I'm back to a regular prompt and everything is stopped.

**Comment by snoyberg** [comment]
I think this is the same as #777. I did not follow the discussions on that and then #801. The short answer here is: we all agree that the behavior should change, and I don't know what's blocking it from happening. If someone just pushes ahead and makes a solid PR, I'll be happy to merge it.

**Comment by wolftune** [comment]
Ok, this is basically duplicate then, sorry. Hope someone figures this out.
