### ISSUE TITLE
`yesod keter` gives broken tar archive

### ISSUE THREAD

**Issue by geraldus** [yesodweb/yesod#996]
I'm not sure what's going on, but I'm not able to successfully pack keter bundle: `keter`reports error
> 2015-05-25 10:30:03.19: Error occured when launching bundle Project: Invalid file name in tar archive: "config/../dist/build/Project/Project"

I believe it comes from `checkEntrySecurity` of `Codec.Archive.Tar.Check` from `tar` package<sup>[1]</sup>.

If I unpack keter bundle manually by **tar** (1.26) if succeeds but with warning:
> tar: Removing leading `config/../' from member names
> config/../dist/build/Project/Project

Is it my fault?

[1]:https://hackage.haskell.org/package/tar-0.3.1.0/docs/src/Codec-Archive-Tar-Check.html

**Comment by snoyberg** [comment]
Should be fixed with 1.4.9.2, please see: https://github.com/yesodweb/yesod/commit/848b1ab3e5e4a787a23ca5d444f7722dde5e2740

**Comment by geraldus** [comment]
Great! I'll update `yesod-bin`. Thanks for instant response!
