### ISSUE TITLE
yesod-bin: Fails to build on GHC 7.8.3 (Filepath type error in HsFile.hs)

### ISSUE THREAD

**Issue by rzetterberg** [yesodweb/yesod#999]
Hello!

I have a project that uses GHC 7.8.3 and cabal 1.20.0.4 with a set of dependencies with exact version constraints ([cabal.config here](http://lpaste.net/1913659185954816000)).

When I execute:

```bash
cd path_to_src_dir
cabal sandbox init --sandbox /var/cabal_env 
cabal install -j yesod-bin
```

I recieve the following error:

```
HsFile.hs:32:12:
    Couldn't match type `[Char]' with `FilePath'
    Expected type: conduit-1.2.1:Data.Conduit.Internal.Conduit.Conduit
                     (FilePath, ResourceT IO BS.ByteString) (ResourceT IO) BS.ByteString
      Actual type: conduit-1.2.1:Data.Conduit.Internal.Conduit.Conduit
                     (GHC.IO.FilePath, ResourceT IO BS.ByteString)
                     (ResourceT IO)
                     BS.ByteString
    In the first argument of `(=$)', namely `createTemplate'
    In the second argument of `(=$)', namely
      `createTemplate =$ awaitForever (liftIO . BS.putStr)'
cabal: Error: some packages failed to install:
yesod-bin-1.4.0 failed during the building phase. The exception was:
ExitFailure 1
```

I have tried a couple of earlier versions until I get a constraint mismatch with `resourcet` or `conduit`.

I can provide a full Docker example if needed!

**Comment by snoyberg** [comment]
Try forcing project-template-0.1.4.2. By the way, this is exactly why I recommend people use LTS Haskell or Stackage Nightly snapshots.

**Comment by rzetterberg** [comment]
Thank you, I will try that tomorrow!

Yes. I'm using LTS Haskell on my newer projects! This is a old and large project that I just maintain :(

**Comment by rzetterberg** [comment]
Addedd `project-template ==0.1.4.2` to my `cabal.config` and that solved the problem!

Thanks for the invaluable help!

**Comment by snoyberg** [comment]
Sure, no problem!
